Repository gip-inclusion/les-emplois, pull requests merged in 2023-06, with the labels that each got.

#2588 users: Add a migration to create the missing JobSeekerProfile
  itou/users/migrations/0018_data_create_jobseeker_profiles.py
Labels: no-changelog

#2590 Controle a posteriori: simplification de code
  itou/templates/siae_evaluations/siae_job_applications_list.html
  itou/www/siae_evaluations_views/tests/tests_siaes_views.py
  itou/www/siae_evaluations_views/views.py
Labels: no-changelog

#2601 Candidature: nettoyage du NIR en session
  itou/www/apply/tests/tests_submit.py
  itou/www/apply/views/submit_views.py
Labels: no-changelog

#2603 prescriber_join_org: Elargir le bloc atomic()
  itou/www/signup/views.py
Labels: no-changelog

#2608 Inclusion connect: Retrait d’une instruction return inutilisée
  itou/openid_connect/inclusion_connect/tests.py
  itou/openid_connect/inclusion_connect/views.py
Labels: no-changelog

#2602 Harmonisation des icones
  itou/templates/apply/list_for_job_seeker.html
  itou/templates/approvals/includes/job_description_list.html
  itou/templates/dashboard/includes/dora_card.html
  itou/templates/dashboard/includes/job_seeker_job_applications_card.html
  itou/templates/dashboard/includes/siae_card.html
  itou/templates/dashboard/includes/siae_employees_card.html
  itou/templates/dashboard/includes/siae_job_applications_card.html
  itou/templates/dashboard/includes/stats.html
  itou/templates/search/siaes_search_results.html
Labels: recette-jetable, no-changelog

#2584 Modification de la déconnexion sur Inclusion Connect
  itou/openid_connect/inclusion_connect/tests.py
  itou/openid_connect/inclusion_connect/views.py
  itou/www/invitations_views/tests/tests_prescriber_organization.py
  itou/www/invitations_views/tests/tests_siae_accept.py
  itou/www/signup/tests/test_prescriber.py
Labels: recette-jetable

#2607 Inclusion connect: Retrait d’un assignement inutile
  itou/openid_connect/inclusion_connect/views.py
Labels: no-changelog

#2632 Contrôle a posteriori: simplification d'un template
  itou/templates/siae_evaluations/includes/siae_infos.html
Labels: no-changelog

#2622 Supprimer la possibilité d'un jobseeker_profile vide, même dans les tests.
  itou/employee_record/admin.py
  itou/employee_record/management/commands/sanitize_employee_records.py
  itou/employee_record/models.py
  itou/employee_record/tests/test_admin.py
  itou/employee_record/tests/test_sanitize_employee_records.py
  itou/employee_record/tests/tests_models.py
  itou/job_applications/factories.py
  itou/users/factories.py
  itou/users/tests/test_models.py
  itou/www/apply/tests/tests_submit.py
  itou/www/employee_record_views/tests/test_create.py
  itou/www/employee_record_views/views.py
Labels: no-changelog

#2642 Parcours de candidature: suppression de l'action du formulaire
  itou/templates/apply/submit_step_check_job_seeker_nir.html
  itou/www/apply/views/submit_views.py
Labels: no-changelog

#2637 Contrôle a posteriori: suppression de l'état NOTIFICATION_PENDING
  itou/metabase/tables/evaluated_siaes.py
  itou/siae_evaluations/enums.py
  itou/siae_evaluations/models.py
  itou/siae_evaluations/tests/tests_models.py
  itou/templates/siae_evaluations/includes/siae_infos.html
  itou/templates/siae_evaluations/institution_evaluated_siae_list.html
  itou/www/siae_evaluations_views/tests/__snapshots__/tests_institutions_views.ambr
Labels: no-changelog

#2639 PASS IAE : Mentionner dans l'admin de faire attention aux dates de Prolongation/Suspension
  itou/approvals/admin_forms.py
  itou/approvals/tests/__snapshots__/test_admin.ambr
  itou/approvals/tests/test_admin.py
Labels: recette-jetable

#2654 approvals.admin_forms: Corriger une exception dueà certains droits manquants
  itou/approvals/admin_forms.py
Labels: no-changelog

#2643 En tant qu’employeur je souhaite pouvoir clôturer un PASS IAE après 12 mois consécutifs de suspension
  itou/templates/approvals/detail.html
  itou/www/approvals_views/tests/__snapshots__/test_detail.ambr
  itou/www/approvals_views/tests/test_detail.py
  itou/www/approvals_views/views.py
Labels: recette-jetable

#2648 Changelog: sprint 65
  CHANGELOG.md
Labels: no-changelog

#2657 Contrôle a posteriori: suppression d'une rétro-compatiblité inutile dans l'export metabase
  itou/metabase/tables/evaluated_siaes.py
Labels: no-changelog

#2676 Boost stats
  itou/templates/dashboard/includes/stats.html
Labels: no-changelog

#2677 User.has_data_changed() : être plus clair sur les cas positifs
  itou/users/factories.py
  itou/users/models.py
  itou/users/tests/test_models.py
  pytest.ini
Labels: no-changelog

#2696 Réutiliser make populate_db pour déployer les fixtures
  clevercloud/review-app-after-success.sh
Labels: recette-jetable

#2697 matomo: Suivre plus de tableaux de bord
  itou/metabase/management/__snapshots__/test_populate_metabase_matomo.ambr
  itou/metabase/management/commands/populate_metabase_matomo.py
  itou/metabase/management/test_populate_metabase_matomo.py
Labels: no-changelog

#2691 pytest: Monter le timeout à 30 secondes
  pytest.ini
Labels: no-changelog

#2695 Mettre SIAE.kind en lecture seule pour les changements
  itou/siaes/admin.py
Labels: no-changelog
