Repository gip-inclusion/les-emplois, pull requests merged in 2023-08, with the labels that each got.

#2826 PASS IAE : modification de la période ou les prolongations sont possibles
  itou/approvals/models.py
  itou/employee_record/management/commands/sanitize_employee_records.py
  itou/employee_record/models.py
  tests/approvals/tests.py
  tests/employee_record/test_models.py
Labels: recette-jetable

#2847 Retirer uWSGI des requirements Python
  requirements/base.in
  requirements/base.txt
  requirements/dev.txt
  requirements/test.txt
Labels: recette-jetable, no-changelog

#2846 BOOST : retrait d'une mention obsolète sur le formulaire de suspension
  itou/www/approvals_views/forms.py
Labels: no-changelog

#2849 Éligibilité GEIQ: utilisation des paramètres d'URL plutôt que la session
  itou/templates/apply/process_geiq_eligibility.html
  itou/www/apply/views/process_views.py
Labels: no-changelog

#2851 Découper EligibilityDiagnosisManagerTest
  tests/eligibility/test_iae.py
Labels: no-changelog

#2852 Augmentation de la couverture de tests pour EligibilityDiagnosisManagerTest
  tests/eligibility/test_iae.py
Labels: no-changelog

#2844 BOOST - Retirer le texte qui parle d’IAE dans l’écran d’inscription des candidats
  itou/templates/signup/job_seeker_situation.html
Labels: no-changelog

#2850 BOOST : le label du champ "reason" apparait en anglais dans le formulaire
  itou/www/approvals_views/forms.py
Labels: no-changelog

#2866 Nettoyage: suppression d'un appel de fonction inutile
  itou/users/models.py
Labels: no-changelog

#2868 Test: correction d'un test instable
  tests/www/dashboard/tests.py
Labels: no-changelog

#2841 Retirer du code non testé de EligibilityDiagnosis
  itou/eligibility/models/iae.py
Labels: no-changelog

#2872 Amélioration de l'affichage des templates apply/process_
  itou/templates/apply/process_accept.html
  itou/templates/apply/process_base.html
  itou/templates/apply/process_cancel.html
  itou/templates/apply/process_details_prescriber.html
  itou/templates/apply/process_details_siae.html
  itou/templates/apply/process_eligibility.html
  itou/templates/apply/process_postpone.html
  itou/templates/apply/process_refuse.html
  itou/templates/eligibility/includes/form.html
Labels: recette-jetable

#2876 Tableau de bord: vérification des sanctions au niveau de la vue
  itou/templates/dashboard/includes/siae_employees_card.html
  itou/www/dashboard/views.py
Labels: no-changelog

#2877 Parcours de vérification de profil : correction du titre sur la dernière étape
  itou/templates/apply/submit/create_or_update_job_seeker/step_end.html
  tests/www/apply/test_submit.py
Labels: no-changelog

#2879 Suppression d'un bloc htmx inutile
  itou/templates/approvals/declare_prolongation.html
Labels: no-changelog

#2870 Metabase : Ajout de l'ID de PASS IAE
  itou/metabase/tables/approvals.py
  tests/metabase/management/test_populate_metabase_emplois.py
Labels: no-changelog

#2827 Makefile : Réparation des commandes `make django_admin`
  Makefile
  itou/siaes/management/commands/move_siae_data.py
  scripts/import-latest-db-backup.sh
Labels: no-changelog

#2889 Update menu "besoin d'aide"
  itou/templates/layout/_footer.html
  itou/templates/layout/_header_nav_primary_items.html
Labels: recette-jetable

#2893 Ressucitation du debugging interactif en local dev dans le cas de Docker
  docker-compose.yml
Labels: no-changelog

#2845 BOOST - retirer des mentions spécifique à l'IAE dans le formulaire d'embauche
  itou/www/apply/forms.py
  tests/www/apply/test_forms.py
Labels: no-changelog

#2880 Amélioration de l'affichage des templates apply/submit_
  itou/templates/apply/submit/application/base.html
  itou/templates/apply/submit/application/end.html
  itou/templates/apply/submit/create_or_update_job_seeker/step_base.html
  itou/templates/apply/submit/create_or_update_job_seeker/step_end.html
  itou/templates/apply/submit_base.html
  itou/templates/apply/submit_base_two_columns.html
  itou/templates/apply/submit_step_check_job_seeker_nir.html
  itou/templates/apply/submit_step_check_prev_applications.html
  itou/templates/apply/submit_step_job_seeker.html
  itou/templates/apply/submit_step_job_seeker_check_info.html
  itou/templates/apply/submit_step_pending_authorization.html
  itou/templates/approvals/includes/card.html
Labels: recette-jetable

#2882 CAP: Améliorer les fixtures
  itou/siae_evaluations/fixtures.py
Labels: no-changelog

#2900 tests: update register_assert_rewrite
  tests/conftest.py
Labels: no-changelog

#2899 Limiter le nombre de destinataire pour l'email de relance pour la demande de prolongation
  itou/approvals/notifications.py
  tests/approvals/test_notifications.py
Labels: no-changelog

#2902 Ajout d'un test vérifiant la cohérence htmx du formulaire d'acceptation de candidature
  tests/www/apply/test_process.py
Labels: no-changelog

#2901 Retirer la mention qui fait référence à l’acceptation automatique dans l’email de notif des prolongations
  itou/approvals/notifications.py
  itou/templates/approvals/email/prolongation_request/created_reminder_body.txt
  tests/approvals/__snapshots__/test_notifications.ambr
Labels: no-changelog

#2905 Retrait d’expire-elastic-indices
  clevercloud/cron.json
  clevercloud/expire-elastic-indices.sh
  scripts/expire-elastic-indices
Labels: no-changelog

#2903 Ajout d’un commentaire à propos d’Approval.suspended_until
  itou/approvals/models.py
Labels: no-changelog, performance

#2894 Stats : Ajout de deux nouveaux TB pour les CD sur liste blanche de quelques départements
  config/settings/base.py
  itou/templates/dashboard/includes/stats.html
  itou/users/models.py
  itou/utils/apis/metabase.py
  itou/www/stats/urls.py
  itou/www/stats/views.py
  tests/users/test_models.py
Labels: no-changelog

#2907 Retrait d’un garde inutile de CreateProlongationForm
  itou/www/approvals_views/forms.py
Labels: no-changelog

#2913 Demandes de prolongation : Correction d'une N+1
  itou/www/approvals_views/views.py
  tests/www/approvals_views/test_prolongation_requests.py
Labels: no-changelog

#2918 Fusionner ResumeLinkMixin avec sa seule classe utilisatrice
  itou/common_apps/resume/forms.py
  itou/www/apply/forms.py
  tests/utils/tests.py
  tests/www/apply/test_submit.py
Labels: no-changelog

#2923 Parcours de candidature GEIQ: sauvegarde du niveau de qualification
  itou/www/apply/forms.py
  tests/www/apply/test_forms.py
Labels: no-changelog

#2928 Validation d'éligibilité: wording
  itou/templates/eligibility/includes/form.html
Labels: no-changelog

#2931 test_prolongation: Geler la date pour les tests et snapshots
  tests/www/approvals_views/test_prolongation.py
Labels: no-changelog

#2925 Utiliser le formatage des f-strings plutôt que `strftime()`
  itou/approvals/models.py
  itou/scripts/management/commands/deduplicate_asp_approvals.py
  itou/siae_evaluations/models.py
  itou/siaes/admin.py
  itou/www/approvals_views/forms.py
  tests/www/apply/test_edit.py
  tests/www/apply/test_process.py
Labels: no-changelog

#2929 Ajout du plugin `pytest-subtests`
  requirements/base.txt
  requirements/dev.txt
  requirements/test.in
  requirements/test.txt
Labels: no-changelog

#2950 Publication de notre nouvelle page stats
  itou/utils/apis/metabase.py
Labels: recette-jetable

#2930 Sécurité : améliorer la détection du domaine S3
  itou/www/apply/forms.py
  tests/www/apply/test_submit.py
Labels: no-changelog

#2924 job_applications: Add the job seeker title in exports
  itou/job_applications/export.py
  tests/job_applications/tests.py
Labels: recette-jetable

#2960 BOOST - Modification des labels des champs concernant la qualification pour les GEIQ
  itou/job_applications/migrations/0011_added_geiq_qualification_and_training_fields.py
  itou/job_applications/models.py
  tests/www/apply/__snapshots__/test_process.ambr
Labels: no-changelog
