Repository gip-inclusion/les-emplois, pull requests merged in 2023-12, with the labels that each got.

#3415 dashboard: adaptation du HTML du formulaire d'édition de profil
  itou/templates/dashboard/edit_user_info.html
Labels: recette-jetable

#3423 Maj du theme itou vers la v1.1.3
  itou/utils/staticfiles.py
Labels: recette-jetable, no-changelog

#3403 Déclaration d'embauche: gestion des demandeurs d'emploi ayant eu un PASS dans les 2 dernières années
  itou/www/apply/views/submit_views.py
  tests/www/apply/test_submit.py
Labels: recette-jetable

#3427 Maj du theme itou vers la v1.1.4
  itou/utils/staticfiles.py
Labels: recette-jetable

#3434 Retirer des boutons inutile qui risque de faire sortir l’utilisateur du parcours
  itou/templates/apply/submit/application/end.html
  itou/templates/apply/submit/check_job_seeker_info_for_hire.html
Labels: html

#3435 [FIX #3327] approvals : annuler une suspension
  itou/templates/approvals/suspension_action_choice.html
  tests/www/approvals_views/test_suspend.py
Labels: html

#3438 templates.stats: Remove some "Nouveau" badges
  itou/templates/dashboard/includes/stats.html
Labels: no-changelog

#3439 Tests : Correction de la _flakyness_ pour `EmployeeRecordModelTest.test_archivable`
  tests/employee_record/test_models.py
Labels: no-changelog

#3440 tests: correction de l'incompatibilité entre pytest-django & pytest-randomly
  tests/conftest.py
Labels: no-changelog

#3436 Mise à jour des titres de l'écran de recherche des emplois
  itou/templates/includes/pagination_for_title.html
  itou/templates/search/siaes_search_results.html
  tests/www/search/tests.py
Labels: html

#3445 Modification UI des boutons "Supprimer" dans les modales
  itou/templates/apply/includes/job_application_prior_action.html
  itou/templates/companies/job_description_list.html
Labels: recette-jetable

#3446 Candidatures : message en l'absence de telephone renseigné lors de la confirmation [GEN-5256]
  itou/templates/apply/submit/application/end.html
  tests/www/apply/test_submit.py
Labels: html

#3458 approvals: ajout dans l'admin d'une page de stats concernant la synchronisation des PASS IAE avec PE
  itou/approvals/admin.py
  itou/approvals/admin_views.py
  itou/templates/admin/approvals/change_list_with_stats.html
  itou/templates/admin/approvals/send_approvals_to_pe_stats.html
  tests/approvals/test_admin.py
Labels: recette-jetable

#3462 [GEN-7294] Modifier la règle d’affichage de la liste des organisations conventionnées pour les admin d’un CD
  itou/prescribers/models.py
  tests/www/prescribers_views/test_list.py
Labels: recette-jetable

#3463 PASS: ajout d'une contrainte en base de données sur la cohérence des dates de début/fin
  itou/approvals/migrations/0023_cancelledapproval_approvals_cancelledapproval_start_before_end.py
  itou/approvals/migrations/0024_approval_approvals_approval_start_before_end.py
  itou/approvals/models.py
Labels: no-changelog

#3465 Ajout d'une bannière temporaire sur la homepage
  itou/templates/search/siaes_search_home.html
Labels: no-changelog

#3470 tests: renommage du fichier de tests pour que le test soit lancé
  tests/www/test_security.py
Labels: no-changelog

#3480 tests: clairement spécifier quand un test nécessite que le demandeur d'emploi ait un identifiant pole emploi
  tests/approvals/tests.py
  tests/eligibility/test_iae.py
  tests/job_applications/tests.py
  tests/metabase/management/test_populate_metabase_emplois.py
  tests/users/factories.py
  tests/users/test_models.py
  tests/www/apply/test_process.py
  tests/www/apply/test_submit.py
  tests/www/employee_record_views/test_create.py
Labels: no-changelog

#3425 [GEN-2761] En tant que candidat / prescripteur / employeur, je veux être accompagné a créer mon CV par le service partenaire Diagoriente
  itou/static/css/itou.css
  itou/static/img/dashboard/card-header-bg-diagoriente.png
  itou/templates/apply/submit/application/resume.html
  itou/templates/dashboard/dashboard.html
  itou/templates/dashboard/includes/diagoriente_card.html
  itou/templates/dashboard/includes/job_seeker_job_applications_card.html
  tests/www/apply/test_submit.py
  tests/www/dashboard/tests.py
Labels: recette-jetable

#3460 [GEN-6341] En tant qu’employeur, je veux inviter un prescripteur/candidat a créer un CV via le service partenaire Diagoriente
  itou/job_applications/migrations/0022_jobapplication_diagoriente_invite_sent_at.py
  itou/job_applications/models.py
  itou/templates/apply/email/diagoriente_job_seeker_invite_body.txt
  itou/templates/apply/email/diagoriente_job_seeker_invite_subject.txt
  itou/templates/apply/email/diagoriente_prescriber_invite_body.txt
  itou/templates/apply/email/diagoriente_prescriber_invite_subject.txt
  itou/templates/apply/includes/job_application_diagoriente_invite.html
  itou/templates/apply/includes/job_seeker_info.html
  itou/templates/apply/process_details_company.html
  itou/www/apply/urls.py
  itou/www/apply/views/process_views.py
  tests/www/apply/test_process.py
Labels: recette-jetable

#3400 [GEN-5180] En tant que prescripteur qui reçoit un refus pour motif autre je suis invité à contacter l’employeur si je souhaite en savoir +
  itou/job_applications/models.py
  itou/templates/apply/includes/job_application_answers.html
  itou/templates/approvals/prolongation_requests/show.html
  itou/templates/companies/job_description_card.html
  itou/templates/dashboard/api_token.html
  itou/templates/includes/copy_to_clipboard.html
  itou/templates/invitations_views/includes/pending_invitations.html
  itou/www/apply/views/process_views.py
  tests/job_applications/tests.py
  tests/www/apply/test_process.py
Labels: recette-jetable, python, html

#3472 tests: Forcer le paramètre de configuration `METABASE_HASH_SALT`
  tests/metabase/conftest.py
Labels: no-changelog

#3501 scripts : Proposer la suppression du remote git dans `create-fast-machine.sh`
  scripts/create-fast-machine.sh
Labels: no-changelog

#3502 [Boost] Correction des 2 types de badges [GEN-7822]
  itou/templates/companies/includes/_card_jobdescription.html
  itou/templates/companies/includes/_card_siae.html
Labels: no-changelog

#3499 Fiches Salarié : Archiver plutôt que désactiver les “FS Orphelines” [GEN-7836]
  itou/employee_record/management/commands/sanitize_employee_records.py
  tests/employee_record/test_sanitize_employee_records.py
Labels: no-changelog

#3498 Stats : Ajout de stats IAE pour les CD (déploiement national)
  itou/templates/dashboard/includes/stats.html
  itou/utils/apis/metabase.py
  itou/www/dashboard/views.py
  itou/www/stats/urls.py
  itou/www/stats/views.py
Labels: no-changelog
