Repository gip-inclusion/les-emplois, pull requests merged in 2023-05, with the labels that each got.

#2483 Retrait de JS pour désactiver les boutons de formulaires
  itou/static/js/utils.js
  itou/templates/apply/submit/application/end.html
  itou/templates/apply/submit/create_or_update_job_seeker/step_base.html
Labels: no-changelog

#2487 scripts: lancement d'import_ea_eatt par le script imports-asp
  scripts/imports-asp.sh
Labels: no-changelog

#2488 changelog: Sprint 62
  CHANGELOG.md
Labels: no-changelog

#2498 Import SIAE : Résolution d'un souci technique mineur
  itou/siaes/management/commands/_import_siae/convention.py
Labels: no-changelog

#2508 Airflow : Résolution d'un souci technique avec les vues
  itou/metabase/db.py
Labels: no-changelog

#2511 Contrôle a posteriori: possibilité de créer des campagnes pour certaines DDETS uniquement
  itou/siae_evaluations/models.py
  itou/siae_evaluations/tests/tests_models.py
Labels: no-changelog

#2514 Affichage de la date de fin estimée du PASS IAE aux prescripteurs et employeurs
  itou/templates/approvals/includes/status.html
  itou/www/approvals_views/tests/test_detail.py
Labels: recette-jetable

#2509 Candidature: ajout des informations de NIR dans les parcours de création/mise à jour des profils de demandeur d'emploi
  itou/common_apps/nir/forms.py
  itou/templates/apply/submit/create_or_update_job_seeker/step_1.html
  itou/templates/apply/submit/create_or_update_job_seeker/step_base.html
  itou/templates/apply/submit/create_or_update_job_seeker/step_end.html
  itou/www/apply/forms.py
  itou/www/apply/tests/tests_submit.py
  itou/www/apply/views/submit_views.py
Labels: recette-jetable

#2512 Pilotage : Airflow : suppression des vues obsolètes à chaque mise à jour de données
  itou/metabase/db.py
Labels: no-changelog

#2510 Pilotage : Ajout d'un nouveau type d'institution "Réseau IAE"
  itou/institutions/enums.py
  itou/institutions/migrations/0003_alter_institution_kind.py
Labels: no-changelog

#2465 Metabase : ajout d'une table utilisateurs avec *uniquement* les utilisateurs pros et leur email, pas les candidats
  clevercloud/crons/populate_metabase_emplois.sh
  itou/metabase/management/commands/populate_metabase_emplois.py
  itou/metabase/management/test_populate_metabase_emplois.py
  itou/metabase/tables/users.py
Labels: no-changelog

#2515 Candidature: suppression des anciens chemins sans PK de candidat & de récupération de la PK dans la session
  itou/www/apply/tests/tests_submit.py
  itou/www/apply/urls.py
  itou/www/apply/views/submit_views.py
Labels: no-changelog

#2513 BOOST: les GEIQ peuvent embaucher rétroactivement
  itou/www/apply/forms.py
  itou/www/apply/tests/tests_forms.py
Labels: no-changelog

#2526 inclusion_connect: Autoriser les prescripteurs de se connecter depuis la page des employeurs (et reciproquement)
  itou/openid_connect/inclusion_connect/tests.py
  itou/openid_connect/inclusion_connect/views.py
  itou/openid_connect/models.py
Labels: recette-jetable

#2532 Correction du script merge-organizations
  itou/prescribers/management/commands/merge_organizations.py
Labels: no-changelog

#2534 Correction HTML
  itou/templates/apply/submit/application/eligibility.html
Labels: no-changelog, html

#2550 Tentative de correction d'un test échouant aléatoirement
  itou/www/signup/tests/test_siae.py
Labels: no-changelog

#2529 Utilisation des `messages` de Django afin d'afficher des toasts Bootstrap
  itou/templates/bootstrap4/messages.html
  itou/templates/layout/base.html
  itou/templates/utils/toasts.html
  itou/utils/templatetags/theme_inclusion.py
Labels: no-changelog

#2541 Fiches salarié : Suppression de la désactivation automatique des fiches avec un `JobSeekerProfile()` incorrect
  itou/employee_record/management/commands/sanitize_employee_records.py
  itou/employee_record/tests/test_sanitize_employee_records.py
Labels: no-changelog

#2537 Fiches Salarié : Suppression du champs `notification_type` 1/2
  itou/employee_record/admin.py
  itou/employee_record/enums.py
  itou/employee_record/factories.py
  itou/employee_record/management/commands/sanitize_employee_records.py
  itou/employee_record/management/commands/transfer_employee_records.py
  itou/employee_record/migrations/0005_stop_using_notification_type_field.py
  itou/employee_record/models.py
  itou/employee_record/tests/test_admin.py
  itou/employee_record/tests/tests_management_commands.py
Labels: no-changelog

#2551 Mise a jour de l'ui des cards du dashboard
  itou/static/css/itou.css
  itou/static/img/dashboard/card-header-bg-dora.png
  itou/static/img/dashboard/card-header-bg-pilotage.png
  itou/templates/approvals/includes/status.html
  itou/templates/dashboard/dashboard.html
  itou/templates/dashboard/includes/admin_card.html
  itou/templates/dashboard/includes/dora_card.html
  itou/templates/dashboard/includes/job_seeker_approval_card.html
  itou/templates/dashboard/includes/job_seeker_job_applications_card.html
  itou/templates/dashboard/includes/labor_inspector_evaluation_campains_card.html
  itou/templates/dashboard/includes/labor_inspector_organization_card.html
  itou/templates/dashboard/includes/prescriber_job_applications_card.html
  itou/templates/dashboard/includes/prescriber_organisation_card.html
  itou/templates/dashboard/includes/siae_card.html
  itou/templates/dashboard/includes/siae_employees_card.html
  itou/templates/dashboard/includes/siae_evaluation_campains_card.html
  itou/templates/dashboard/includes/siae_job_applications_card.html
  itou/templates/dashboard/includes/stats.html
Labels: recette-jetable

#2573 Parcours de candidature: suppression de la vue dépréciée CheckEmailForSenderView
  itou/www/apply/tests/tests_submit.py
  itou/www/apply/urls.py
  itou/www/apply/views/submit_views.py
Labels: no-changelog

#2571 Suppression des mentions de l'API Entreprise de `api.gouv.fr`
  config/settings/base.py
  itou/prescribers/tests.py
  itou/status/probes.py
  itou/utils/apis/api_entreprise.py
  itou/utils/apis/test_entreprise_api.py
  itou/utils/mocks/pole_emploi.py
  itou/www/signup/tests/test_prescriber.py
  itou/www/signup/tests/test_siae.py
Labels: no-changelog

#2579 boost: La date de fin prévisionnelle du PASS IAE n’est pas visible pour le CANDIDAT
  itou/templates/approvals/includes/status.html
  itou/www/dashboard/tests.py
Labels: no-changelog
