Repository gip-inclusion/les-emplois, pull requests merged in 2023-07, with the labels that each got.

#2670 Ajouter DJANGO_SETTINGS_MODULE et définir PYTHONPATH aux siae_evaluations.fixtures
  Makefile
  itou/siae_evaluations/fixtures.py
Labels: recette-jetable, no-changelog

#2707 Correction d'une erreur sur l'affichage d'un profil de demandeur d'emploi dans l'admin
  itou/templates/admin/users/change_user_form.html
  itou/users/admin.py
  itou/users/tests/test_admin_views.py
Labels: no-changelog

#2692 PASS IAE : Modifier légèrement la règle de gestion de l'affichage du bouton de suppression
  itou/www/approvals_views/tests/test_detail.py
  itou/www/approvals_views/views.py
Labels: no-changelog

#2698 CHANGELOG Sprint 66
  CHANGELOG.md
Labels: no-changelog

#2701 Gérer les identifiants dans la recherche admin et les pages de changement
  itou/static/js/admin.js
  itou/templates/admin/base_site.html
Labels: no-changelog

#2712 Correction d'un test instable
  itou/www/approvals_views/tests/test_pe_approval.py
Labels: no-changelog

#2715 populate_matomo: Cesser de récupérer les données des TB privés par API
  itou/metabase/management/commands/populate_metabase_matomo.py
  tests/metabase/management/__snapshots__/test_populate_metabase_matomo.ambr
  tests/metabase/management/test_populate_metabase_matomo.py
Labels: no-changelog

#2710 Ne pas recompter les candidatures dans l’admin
  itou/job_applications/admin.py
Labels: no-changelog

#2713 Définir un mot de passe inutilisable pour les utilisateurs créés par des tiers
  itou/users/models.py
Labels: no-changelog

#2718 Parcours de candidature: la session est maintenant optionelle
  itou/www/apply/views/submit_views.py
  tests/www/apply/test_submit.py
Labels: no-changelog

#2720 Parcours de candidature: divers réusinages
  itou/www/apply/views/submit_views.py
  tests/www/apply/test_submit.py
Labels: no-changelog

#2721 Parcours de candidature: faciliter la réutilisation d'un formulaire sans candidature
  itou/www/apply/forms.py
  itou/www/apply/views/process_views.py
Labels: no-changelog

#2724 populate_metabase_matomo: Retirer un argument inutilisé
  clevercloud/crons/populate_metabase_matomo.sh
Labels: no-changelog

#2723 Indexer PoleEmploiApproval.nir
  itou/approvals/migrations/0008_poleemploiapproval_nir_idx.py
  itou/approvals/models.py
Labels: no-changelog

#2731 Utilisation de `pluralizefr` partout
  itou/templates/approvals/includes/status.html
  itou/templates/employee_record/list.html
  itou/templates/siae_evaluations/email/to_siae_sanctioned_subject.txt
  itou/templates/siae_evaluations/evaluated_siae_sanction.html
  itou/templates/siaes/card.html
  itou/templates/siaes/includes/_job_description_details.html
  itou/templates/siaes/includes/_list_siae_actives_jobs.html
  itou/templates/siaes/job_description_card.html
  tests/www/siae_evaluations_views/test_views.py
  tests/www/siaes_views/test_views.py
Labels: no-changelog

#2728 Retrait d’un cas impossible de ApprovalModelTest.test_remainder
  tests/approvals/tests.py
Labels: no-changelog

#2732 Corriger le détail des requêtes dans test_approval_status_includes
  tests/www/approvals_views/test_detail.py
Labels: no-changelog

#2730 Retrait d’une condition impossible de PoleEmploiApproval.find_for
  itou/approvals/models.py
Labels: no-changelog, performance

#2738 Réutiliser Siae.can_upload_prolongation_report
  itou/www/approvals_views/views.py
Labels: no-changelog

#2733 Réécrire Approval.can_be_deleted
  itou/approvals/models.py
  itou/job_applications/models.py
  tests/approvals/tests.py
Labels: no-changelog

#2736 Correction de ApprovalModelTest.test_remainder
  tests/approvals/tests.py
Labels: no-changelog

#2729 CheckConstraint que les Suspensions ne démarrent pas dans le futur
  itou/approvals/migrations/0009_suspension_cannot_start_in_the_future.py
  itou/approvals/models.py
Labels: no-changelog

#2741 Fix typo in name Contrôle a posteriori
  itou/approvals/models.py
  tests/approvals/tests.py
Labels: no-changelog

#2747 Retrait de itou.metabase.utils.chunks
  itou/metabase/utils.py
Labels: no-changelog

#2743 Retire un doublon de vérification de contraintes des Prolongations et Suspensions
  itou/approvals/migrations/0001_initial.py
  itou/approvals/models.py
  tests/approvals/tests.py
Labels: no-changelog

#2740 Correction d’un warning de test à propos de django.utils.timezone.utc
  tests/approvals/test_notify_pole_emploi.py
  tests/users/test_models.py
Labels: no-changelog

#2742 Retrait de Suspension.start_in_future
  tests/approvals/test_notify_pole_emploi.py
  tests/users/test_models.py
Labels: no-changelog

#2745 Retire une vieille logique de CommonApprovalMixin.is_valid()
  itou/approvals/models.py
Labels: no-changelog

#2749 Amélioration des performances de l’admin candidatures
  itou/job_applications/admin.py
Labels: no-changelog, performance

#2737 metabase crons: Ajout de moniteurs sentry
  itou/metabase/management/commands/populate_metabase_emplois.py
  itou/metabase/management/commands/populate_metabase_matomo.py
Labels: no-changelog

#2751 Correction d’assertions dans test_pec_display
  tests/www/search/tests.py
Labels: no-changelog

#2739 Mettre à jour les requêtes de TestApprovalDetailView.test_approval_status_includes
  tests/www/approvals_views/test_detail.py
Labels: no-changelog

#2758 Retirer les espaces de fin de ligne
  .editorconfig
  itou/static/js/commune_autocomplete_field.js
  itou/static/js/job_autocomplete.js
  itou/static/js/s3_upload.js
  itou/templates/apply/includes/geiq/geiq_administrative_criteria_form.html
  itou/templates/apply/includes/geiq/geiq_diagnosis_details.html
  itou/templates/approvals/includes/declaration_contact_details.html
  itou/templates/approvals/includes/declaration_upload_panel.html
  itou/templates/layout/_footer.html
Labels: no-changelog

#2752 Accélération de EvaluationCampaignMiscMethodsTest::test_select_min_max_job_applications
  tests/siae_evaluations/test_models.py
Labels: no-changelog

#2768 Envoi des e-mails de prolongation avec l'adresse adéquate
  itou/approvals/notifications.py
  itou/templates/approvals/email/new_prolongation_for_prescriber_body.txt
  itou/utils/emails.py
  itou/utils/settings_context_processors.py
  tests/approvals/tests.py
Labels: recette-jetable

#2778 cron: Garder les lignes dans leur ordre d'exécution
  clevercloud/cron.json
Labels: no-changelog

#2501 Ajout d'une contrainte pour vérifier la présence d'un diag si le PASS a été délivré par Itou
  itou/approvals/migrations/0010_add_eligibility_diagnosis_constraint.py
  itou/approvals/models.py
  tests/approvals/factories.py
  tests/approvals/tests.py
  tests/eligibility/test_iae.py
  tests/job_applications/tests.py
  tests/metabase/management/test_populate_metabase_emplois.py
  tests/metabase/test_approvals.py
  tests/siae_evaluations/test_models.py
  tests/users/test_models.py
  tests/www/apply/test_process.py
  tests/www/apply/test_submit.py
  tests/www/approvals_views/__snapshots__/test_detail.ambr
  tests/www/approvals_views/test_detail.py
  tests/www/approvals_views/test_display.py
  tests/www/approvals_views/test_pe_approval.py
Labels: no-changelog

#2773 tests: Échouer s’il y a des warnings
  itou/metabase/dataframes.py
  pytest.ini
Labels: no-changelog

#2784 Use djlint to format CSS and JS
  itou/settings_viewer/templates/settings/list.html
  itou/templates/admin/base_site.html
  itou/templates/admin/prescribers/change_form.html
  itou/templates/apply/process_accept.html
  itou/templates/apply/submit/create_or_update_job_seeker/step_base.html
  itou/templates/approvals/declare_prolongation.html
  itou/templates/approvals/printable_approval.html
  itou/templates/dashboard/api_token.html
  itou/templates/employee_record/list.html
  itou/templates/invitations_views/create.html
  itou/templates/invitations_views/includes/pending_invitations.html
  itou/templates/layout/base.html
  itou/templates/layout/base_printable.html
  itou/templates/search/prescribers_search_results.html
  itou/templates/search/siaes_search_results.html
  itou/templates/siaes/job_description_card.html
  itou/templates/siaes/job_description_list.html
  itou/templates/stats/stats.html
  itou/templates/stats/stats_pilotage.html
  itou/templates/utils/widgets/csp_proof_openlayers-osm.html
  pyproject.toml
  tests/utils/__snapshots__/tests.ambr
Labels: no-changelog

#2803 Préciser le JS qui cache le champchamp password de l’admin
  itou/static/js/admin.js
Labels: no-changelog

#2804 tests: Retrait d’instructions invalides de ProcessListTest
  tests/www/apply/test_list.py
Labels: no-changelog

#2783 DeclareProlongationForm: vérifier le paramètre “reason”
  itou/www/approvals_views/forms.py
  tests/www/approvals_views/test_prolongation.py
Labels: no-changelog

#2815 Correctement lié la prolongation à sa demande lors de sa création
  itou/approvals/models.py
  tests/approvals/tests.py
Labels: no-changelog

#2810 FS : Ajout de `employee_records_status` pour extraire le statut de fiche salarié en masse
  itou/employee_record/management/commands/employee_records_status.py
Labels: no-changelog

#2813 Forcer les settings S3 à None en test
  config/settings/test.py
Labels: no-changelog

#2814 Ne pas lire les variables d’environnement MAILJET_* en tests
  config/settings/test.py
Labels: no-changelog

#2821 admin: change display name of some apps
  itou/prescribers/apps.py
  itou/users/apps.py
Labels: no-changelog

#2819 BOOST : modification (en passant) de quelques descriptions dans l'admin des candidatures
  itou/job_applications/admin.py
Labels: no-changelog

#2825 [Fix] Cron - transfer_employee_records : Utiliser `--wet-run` pour la PROD
  clevercloud/download_employee_records.sh
Labels: no-changelog

#2820 Metabase : Injections des prolongations et de leurs demandes
  clevercloud/crons/populate_metabase_emplois.sh
  itou/metabase/management/commands/populate_metabase_emplois.py
  itou/metabase/tables/prolongation_requests.py
  itou/metabase/tables/prolongations.py
  itou/metabase/tables/utils.py
  tests/approvals/factories.py
  tests/metabase/management/test_populate_metabase_emplois.py
Labels: no-changelog

#2817 Correction d'une typo
  itou/users/models.py
Labels: no-changelog

#2829 Mise a jour de l'ui de la page fiche SIAE
  itou/static/vendor/theme-inclusion/stylesheets/app.css
  itou/templates/siaes/card.html
Labels: recette-jetable, no-changelog

#2828 Fix ux/ui badge "action requise"
  itou/templates/dashboard/includes/siae_card.html
Labels: no-changelog
