Repository gip-inclusion/les-emplois, pull requests merged in 2023-09, with the labels that each got.

#2966 Ajout d'un test comptant les requêtes sur l'applicants_api
  tests/api/applicants_api/tests.py
Labels: no-changelog

#2917 Réordonner les déclarations des ModelForm
  itou/www/apply/forms.py
  itou/www/approvals_views/forms.py
  itou/www/dashboard/forms.py
  itou/www/employee_record_views/forms.py
  itou/www/prescribers_views/forms.py
  itou/www/siaes_views/forms.py
Labels: no-changelog

#2961 Ajout de la bannière livestorm au tableau de bord des prescripteurs et employeurs
  itou/templates/dashboard/dashboard.html
Labels: recette-jetable

#2962 Mettre à dispo le lien du calendrier de la campagne de contrôle côté SIAE
  itou/templates/dashboard/includes/labor_inspector_evaluation_campains_card.html
  itou/templates/dashboard/includes/siae_evaluation_campains_card.html
  itou/www/dashboard/views.py
  itou/www/siae_evaluations_views/views.py
  tests/www/siae_evaluations_views/test_siaes_views.py
Labels: recette-jetable

#2981 Clarifier la signature de Prolongation.has_reached_max_cumulative_duration
  itou/approvals/models.py
  tests/approvals/tests.py
Labels: no-changelog

#2915 Metabase : Ajouter une colonne candidatures.parcours_de_création (reprise de stock AI)
  clevercloud/crons/populate_metabase_emplois.sh
  itou/metabase/management/commands/populate_metabase_emplois.py
  itou/metabase/tables/job_applications.py
  tests/metabase/management/test_populate_metabase_emplois.py
Labels: no-changelog

#2988 Ajouter un rappel de préciser les étapes pour une recette jetable
  .github/workflows/review-app-creation.yml
Labels: recette-jetable

#2991 API - FS : Correction d'une N+1
  itou/employee_record/models.py
  tests/api/employee_record_api/tests.py
Labels: no-changelog

#2989 Maj du theme itou vers la v0.7.5
  itou/static/vendor/theme-inclusion/stylesheets/app.css
Labels: recette-jetable

#2995 tests: uncomment assertion
  tests/utils/tests.py
Labels: no-changelog

#2996 Users : déplacer ville & pays de naissance vers JobSeekerProfile - partie 1
  itou/users/migrations/0021_jobseekerprofile_birth_country_and_more.py
  itou/users/models.py
Labels: no-changelog

#2965 Ne plus afficher le PASS IAE dans le parcours d'embauche GEIQ
  itou/templates/apply/submit_base.html
  tests/www/apply/test_submit.py
Labels: recette-jetable

#2970 Modification du nom de la table organisations
  itou/metabase/tables/organizations.py
Labels: no-changelog

#2999 Users : déplacer ville & pays de naissance vers JobSeekerProfile - dernière partie
  itou/users/migrations/0023_remove_user_birth_country_remove_user_birth_place.py
  itou/users/models.py
Labels: no-changelog

#3000 jobs: utilisation du SearchQuery de Django plutôt qu'un extra
  itou/jobs/models.py
Labels: no-changelog

#3012 fixtures: Correction après migration de champs vers jobseeker_profile
  itou/fixtures/django/05_test_users.json
  itou/fixtures/django/07_jobseeker_profile.json
Labels: no-changelog

#3023 Candidatures - Éligibilité aux fiches salariés : Sortir plus rapidement et simplement si la SIAE n'utilise pas les FS
  itou/job_applications/models.py
Labels: no-changelog

#3024 fix: ensure local `master_clever` branch is up-to-date before creating a fast-machine
  scripts/create-fast-machine.sh
Labels: no-changelog

#3026 Intergiciel ItouCurrentOrganizationMiddleware: on enrichit maintenant toujours l'objet request
  itou/utils/perms/middleware.py
Labels: no-changelog

#3019 docker-compose: limiter la visibilité de postgres
  docker-compose.yml
Labels: no-changelog

#3032 [Hotfix] Les candidats ne peuvent plus voir les fiches de poste
  itou/www/siaes_views/views.py
  tests/www/siaes_views/test_job_description_views.py
Labels: no-changelog

#3039 Suppression de prefetch_job_description_through
  itou/api/siae_api/viewsets.py
  itou/siaes/models.py
  tests/siaes/test_models.py
Labels: no-changelog

#3041 Retirer la règle graph_models_itou
  Makefile
Labels: no-changelog

#3029 Invitations : Correction mineure de l'interface sur le fait que la durée des invitations n'est pas toujours de 15 jours
  itou/templates/invitations_views/includes/pending_invitations.html
Labels: no-changelog

#3025 Ne plus avoir de champs combinant `auto_now=True` et `null=True`
  itou/approvals/migrations/0015_alter_suspension_updated_at.py
  itou/approvals/models.py
  itou/job_applications/migrations/0015_alter_jobapplication_updated_at.py
  itou/job_applications/models.py
Labels: no-changelog

#3059 Admin : Préchargement des objets liés lors de l'édition d'un objet et pour les _Inline_
  itou/analytics/admin.py
  itou/antivirus/admin.py
  itou/api/admin.py
  itou/approvals/admin.py
  itou/asp/admin.py
  itou/cities/admin.py
  itou/common_apps/organizations/admin.py
  itou/eligibility/admin.py
  itou/employee_record/admin.py
  itou/external_data/admin.py
  itou/files/admin.py
  itou/geo/admin.py
  itou/invitations/admin.py
  itou/job_applications/admin.py
  itou/jobs/admin.py
  itou/settings_viewer/admin.py
  itou/siae_evaluations/admin.py
  itou/siaes/admin.py
  itou/users/admin.py
  itou/utils/admin.py
Labels: no-changelog

#3061 CSP: ajout de base-uri et suppression de redoc
  config/settings/base.py
  itou/api/redoc_views.py
  itou/api/urls.py
Labels: recette-jetable

#3028 Réécriture du README pour encourager les virtualenv
  .github/workflows/ci.yml
  Makefile
  README.md
  clevercloud/review-app-after-success.sh
  docs/Docker.md
Labels: no-changelog

#3065 Retrait de fichiers en doublon bootstrap*.css.map
  itou/static/rest_framework/css/bootstrap-theme.min.css.map
  itou/static/rest_framework/css/bootstrap.min.css.map
Labels: recette-jetable, no-changelog

#3070 Retirer fonts.googleapis.com de CSP_STYLE_SRC
  config/settings/base.py
Labels: no-changelog

#3068 Retrait de la cible PHONY run au profit de runserver
  Makefile
Labels: no-changelog

#3091 Retirer une condition de la règle venv du Makefile
  Makefile
Labels: no-changelog

#3072 Simplifier la construction du virtualenv
  Makefile
  docker/dev/django/Dockerfile
  docker/dev/django/entrypoint.sh
  docs/Docker.md
Labels: no-changelog

#3093 tests: ajout d'un test pour la page d'accueil de l'API
  tests/www/api/__init__.py
  tests/www/api/tests.py
Labels: no-changelog

#3096 Réusinage de SubmitJobApplicationForm
  itou/www/apply/forms.py
  itou/www/apply/views/submit_views.py
Labels: no-changelog

#3033 fix: workaround for email sending crash
  itou/job_applications/models.py
  itou/www/apply/views/submit_views.py
  tests/job_applications/test_transfer.py
  tests/job_applications/tests.py
Labels: no-changelog

#3094 Définir EvaluatedSiae.verbose_name comme “entreprise contrôlée”
  itou/siae_evaluations/migrations/0001_initial.py
  itou/siae_evaluations/models.py
Labels: no-changelog

#3087 github: add check to detect fixup commits
  .github/workflows/git.yml
Labels: no-changelog

#3106 Gestion d’un TODO dans allauth_adapters.migrations
  itou/allauth_adapters/migrations/0001_initial.py
Labels: no-changelog
