Repository gip-inclusion/les-emplois, pull requests merged in 2023-11, with the labels that each got.

#3264 (vscode settings): debug django app
  .vscode/launch.json
Labels: no-changelog, discussion

#3281 environment : Add a dotenv
  .envrc
  .gitignore
Labels: no-changelog

#3291 vscode settings : Add vim compatibility workaround
  .vscode/settings.json
Labels: no-changelog

#3305 conftest: suppression de la solution de contournement
  tests/conftest.py
Labels: no-changelog

#3309 Settings : Pourvoir lancer les tests (aussi) depuis le docker
  config/settings/dev.py
  config/settings/test.py
Labels: no-changelog

#3316 Création d'une table structures_v0
  itou/metabase/tables/siaes.py
  itou/metabase/tables/utils.py
  tests/metabase/management/test_populate_metabase_emplois.py
Labels: no-changelog

#3312 Stats : Ajout du département 18 à la liste blanche des CD (Conseils Départementaux)
  config/settings/base.py
Labels: no-changelog

#3276 Stats : Ajout de stats sur les demandes de prolongations pour la DGEFP
  itou/templates/dashboard/includes/stats.html
  itou/utils/apis/metabase.py
  itou/www/stats/urls.py
  itou/www/stats/views.py
  tests/www/stats/test_views.py
Labels: no-changelog

#3326 UX: Harmonisation de l'affichage des 0 résultat sur les fiches salarié (ASP)
  itou/templates/employee_record/list.html
  itou/www/employee_record_views/views.py
  tests/www/employee_record_views/test_list.py
Labels: recette-jetable, no-changelog

#3341 Modification d'un ancien DAG + nouveau DAG pilotage
  clevercloud/crons/populate_metabase_emplois.sh
  clevercloud/crons/populate_metabase_matomo.sh
  itou/metabase/db.py
  itou/metabase/management/commands/populate_metabase_emplois.py
  itou/metabase/management/commands/populate_metabase_fluxiae.py
Labels: no-changelog

#3335 Ajout d'un journal des changements techniques majeurs
  .github/pull_request_template.md
  CHANGELOG_breaking_changes.md
Labels: no-changelog

#3266 Fiches salarié : Amélioration de performance pour le nettoyage des FS orphelines
  itou/employee_record/management/commands/sanitize_employee_records.py
Labels: no-changelog

#3358 Nettoyage d'une référence inutile à une variable inexistante
  itou/templates/signup/prescriber_check_already_exists.html
  tests/www/signup/test_prescriber.py
Labels: no-changelog

#3359 Metabase : Ajout du référentiel du type prescripteur (`c1_ref_type_prescripteur`)
  itou/metabase/management/commands/populate_metabase_emplois.py
  tests/metabase/management/test_populate_metabase_emplois.py
Labels: no-changelog

#3365 Mise a jour du contenu de la déclaration d'accessibilité
  itou/templates/static/accessibility.html
Labels: recette-jetable, no-changelog

#3373 Correctif du contenu de la déclaration d'accessibilité
  itou/templates/static/accessibility.html
Labels: no-changelog

#3372 Tests : Faire en sorte qu'ils passent depuis environnement docker
  itou/job_applications/models.py
  tests/conftest.py
  tests/www/apply/test_submit.py
Labels: no-changelog

#3376 Makefile: ajout d'un message pour clarifier l'absence d'une migration
  Makefile
Labels: no-changelog

#3371 [gitignore] repertoire backups
  .gitignore
Labels: no-changelog, discussion

#3379 Correction de la valeur PE_PRESCRIBER_FILTER_VALUE
  itou/utils/apis/metabase.py
Labels: no-changelog

#3366 Institutions : Ajout du type DRIHL (direction régionale et interdépartementale de l'Hébergement et du Logement) pour un futur accès à des stats Pilotage
  itou/institutions/enums.py
  itou/institutions/migrations/0008_alter_institution_kind.py
Labels: no-changelog

#3377 [PASS IAE AI] message pour les pass arrivant à expiration dans moins de 30 jours
  itou/templates/approvals/declare_prolongation.html
  itou/www/approvals_views/views.py
  tests/www/approvals_views/test_prolongation.py
Labels: python, html

#3370 [dashboard] retrait du sondage maze
  itou/static/css/itou.css
  itou/templates/layout/base.html
  tests/www/dashboard/__snapshots__/tests.ambr
  tests/www/dashboard/tests.py
Labels: html

#3378 Makefile: correction de la vérification des migrations
  Makefile
Labels: no-changelog

#3381 [PASS IAE AI] filtrer les demandes refusées par date pour les AI
  itou/approvals/admin.py
Labels: python

#3384 [PASS IAE AI] CORRECTION MESSAGE pour les pass arrivant à expiration dans moins de 30 jours
  itou/templates/approvals/declare_prolongation.html
  tests/www/approvals_views/test_prolongation.py
Labels: html

#3323 Ajout d’information dans le PASS IAE pour une Prolongation en cours
  itou/templates/approvals/includes/status.html
  itou/www/approvals_views/views.py
  tests/www/approvals_views/__snapshots__/test_detail.ambr
  tests/www/approvals_views/test_detail.py
Labels: recette-jetable

#3390 [PASS IAE AI] filtrer les demandes refusées par date pour les AI (part2)
  itou/approvals/admin.py
Labels: python

#3393 Ajout de l'ID 325 de dashboard metabase
  config/settings/base.py
Labels: no-changelog

#3389 PASS IAE: ajout d'un script pour repasser les PASS modifées en PENDING
  itou/approvals/management/commands/reset_pe_notification_status_for_date_updates.py
Labels: no-changelog

#3394 PASS IAE: augmentation de la taille des batchs des envois à pole emploi
  itou/approvals/management/commands/send_approvals_to_pe.py
  tests/approvals/test_notify_pole_emploi.py
Labels: no-changelog

#3395 Certification PE: suppression de données personnelles des logs
  itou/users/management/commands/pe_certify_users.py
  tests/users/__snapshots__/test_management_commands.ambr
Labels: no-changelog

#3396 PASS IAE: renommage des champs du PASS annulés pour coller à ceux des PASS
  itou/approvals/admin.py
  itou/approvals/migrations/0022_rename_prescriber_kind_cancelledapproval_origin_prescriber_organization_kind_and_more.py
  itou/approvals/models.py
  tests/approvals/factories.py
  tests/approvals/test_notify_pole_emploi.py
  tests/approvals/tests.py
Labels: no-changelog

#3397 Envoi PASS à pole emploi: simplification
  itou/utils/apis/pole_emploi.py
Labels: no-changelog

#3398 PASS IAE: suppression du script reset_pe_notification_status_for_date_updates
  itou/approvals/management/commands/reset_pe_notification_status_for_date_updates.py
Labels: no-changelog

#3404 PASS IAE: nouvelle augmentation de la taille des batchs des envois à pole emploi
  itou/approvals/management/commands/send_approvals_to_pe.py
Labels: no-changelog

#3409 Tableau de bord: modification du titre de la page de modification du profil
  itou/templates/dashboard/edit_user_email.html
  itou/templates/dashboard/edit_user_info.html
Labels: no-changelog

#3408 Utilisateurs: suppression de la property inutilisée is_orienter
  itou/users/models.py
  tests/users/test_models.py
Labels: no-changelog

#3406 Candidature : Correction des attributs Matomo ajoutés dans le `href`
  itou/templates/apply/submit_step_check_job_seeker_nir.html
Labels: no-changelog

#3402 admin: mieux gérer les entrées invalides lors de la création de candidature
  itou/job_applications/admin_forms.py
  tests/job_applications/test_admin.py
Labels: no-changelog
