Repository gip-inclusion/les-emplois, pull requests merged in 2023-10, with the labels that each got.

#3108 Run git fixup check in merge queue only
  .github/workflows/git.yml
Labels: no-changelog

#3117 Revert "Run git fixup check in merge queue only"
  .github/workflows/git.yml
Labels: no-changelog

#3090 Admin - FS : Autoriser la modification de l'annexe financière
  itou/employee_record/admin.py
Labels: no-changelog

#3119 tests: amélioration de la cohérence de EvaluatedJobApplicationFactory
  tests/siae_evaluations/factories.py
Labels: no-changelog

#3120 populate_db: Charger les fixtures petit à petit
  Makefile
Labels: no-changelog

#3042 Changer URL de l’espace connecté
  itou/openid_connect/france_connect/views.py
  itou/openid_connect/inclusion_connect/views.py
  itou/templates/account/login_generic.html
  itou/templates/account/login_job_seeker.html
  itou/templates/api/index.html
  itou/templates/apply/list_for_job_seeker.html
  itou/templates/apply/list_for_prescriber.html
  itou/templates/apply/submit/application/end.html
  itou/templates/apply/submit_step_check_prev_applications.html
  itou/templates/apply/submit_step_pending_authorization.html
  itou/templates/dashboard/includes/job_seeker_job_applications_card.html
  itou/templates/dashboard/includes/prescriber_job_applications_card.html
  itou/templates/layout/_footer.html
  itou/templates/layout/_header_nav_secondary_items.html
  itou/templates/layout/breadcrumbs_from_dashboard.html
  itou/templates/search/siaes_search_home.html
  itou/templates/siaes/edit_siae_breadcrumb.html
  itou/templates/signup/choose_user_kind.html
  itou/templates/static/accessibility.html
  itou/users/adapter.py
  itou/utils/settings_context_processors.py
  itou/www/apply/views/list_views.py
  itou/www/apply/views/process_views.py
  itou/www/home/views.py
  itou/www/search/urls.py
  itou/www/search/views.py
  itou/www/signup/views.py
  tests/openid_connect/france_connect/tests.py
  tests/openid_connect/inclusion_connect/tests.py
  tests/utils/htmx/tests.py
  tests/utils/perms/tests.py
  tests/utils/tests.py
  tests/www/approvals_views/test_prolongation.py
  tests/www/approvals_views/test_suspend.py
  tests/www/dashboard/tests.py
  tests/www/home/tests.py
  tests/www/signup/test_prescriber.py
  tests/www/signup/test_siae.py
Labels: recette-jetable

#3114 approvals: Add prolongation request recipient
  itou/templates/approvals/prolongation_requests/list.html
  itou/templates/approvals/prolongation_requests/show.html
  itou/www/approvals_views/views.py
  tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
Labels: recette-jetable

#3122 Admin - FS : Correction suite à #3090
  itou/employee_record/admin.py
Labels: no-changelog

#3086 Ne pas définir de mot de passe pour les utilisateurs créés via l’admin
  itou/users/admin.py
  itou/users/admin_forms.py
  itou/users/migrations/0001_initial.py
  itou/users/models.py
  tests/users/test_admin_views.py
Labels: recette-jetable

#3128 metabase : Corriger les exports de demande de prolongation
  itou/metabase/tables/prolongation_requests.py
  tests/metabase/management/test_populate_metabase_emplois.py
Labels: no-changelog

#3129 Retrait de geiq_author_structure
  itou/www/apply/views/submit_views.py
Labels: no-changelog

#3121 Ne pas toucher aux EvaluatedSiae lors d’un move_siae_data
  itou/siaes/management/commands/move_siae_data.py
  tests/siaes/test_management_commands.py
Labels: no-changelog

#3110 [Metabase] Ajout du suivi matomo du TB 336
  itou/metabase/management/commands/populate_metabase_matomo.py
  tests/metabase/management/__snapshots__/test_populate_metabase_matomo.ambr
  tests/metabase/management/test_populate_metabase_matomo.py
Labels: no-changelog

#3132 Passage à PostgreSQL 15
  .github/workflows/ci.yml
  .github/workflows/review-app-creation.yml
  docker-compose.yml
Labels: recette-jetable, no-changelog

#3113 Activation de l'option FAIL_INVALID_TEMPLATE_VARS de pytest-django
  pytest.ini
  requirements/dev.txt
  requirements/test.in
  requirements/test.txt
  tests/allauth_adapters/peamu/tests.py
  tests/approvals/tests.py
  tests/conftest.py
  tests/job_applications/tests.py
  tests/openid_connect/inclusion_connect/tests.py
  tests/settings_viewer/tests.py
  tests/status/tests.py
  tests/users/test_admin_views.py
  tests/utils/htmx/tests.py
  tests/utils/tests.py
  tests/www/api/tests.py
  tests/www/apply/test_geiq.py
  tests/www/apply/test_submit.py
  tests/www/dashboard/tests.py
  tests/www/employee_record_views/test_create.py
  tests/www/employee_record_views/test_disable.py
  tests/www/employee_record_views/test_list.py
  tests/www/employee_record_views/test_reactivate.py
  tests/www/employee_record_views/test_summary.py
  tests/www/home/tests.py
  tests/www/invitations_views/test_new_user.py
  tests/www/invitations_views/test_prescriber_organization.py
  tests/www/invitations_views/test_siae_accept.py
  tests/www/invitations_views/test_siae_send.py
  tests/www/login/tests.py
  tests/www/prescribers_views/test_edit.py
  tests/www/prescribers_views/test_members.py
  tests/www/releases/tests.py
  tests/www/search/tests.py
  tests/www/siae_evaluations_views/test_siaes_views.py
  tests/www/siae_evaluations_views/test_views.py
  tests/www/siaes_views/test_job_description_views.py
  tests/www/siaes_views/test_views.py
  tests/www/signup/test_job_seeker.py
  tests/www/signup/test_password.py
  tests/www/signup/test_prescriber.py
  tests/www/signup/test_siae.py
  tests/www/stats/test_views.py
  tests/www/welcoming_tour/tests.py
Labels: no-changelog

#3089 Inscription : adapter le message aux GEIQ
  itou/templates/signup/siae_select.html
Labels: no-changelog, html

#3144 Intergiciel: limitation du hasard
  itou/utils/perms/middleware.py
Labels: no-changelog

#3143 settings : Nettoyer des settings inutilisés
  config/settings/base.py
Labels: no-changelog

#3145 Intergiciel: nettoyage de clefs de sessions inutilisées
  itou/utils/constants.py
  itou/utils/perms/middleware.py
  tests/utils/tests.py
Labels: no-changelog

#3141 tests: Ordre aléatoire pour les requêtes qui n'en spécifie pas
  itou/siae_evaluations/admin.py
  itou/users/management/commands/sync_group_and_perms.py
  itou/utils/perms/middleware.py
  tests/conftest.py
  tests/siae_evaluations/test_emails.py
  tests/siaes/test_import_siae_command.py
  tests/status/tests.py
  tests/users/test_admin.py
  tests/users/test_management_commands.py
Labels: no-changelog

#3151 Fichiers static: réduction de la verbosité du collectstatic
  itou/utils/staticfiles.py
Labels: no-changelog

#3155 Détail d'une organisation de prescripteur: correction du titre
  itou/templates/prescribers/card.html
Labels: no-changelog

#3154 tests: ajout des tests pour la vue list_accredited_organizations
  tests/www/prescribers_views/test_list.py
Labels: no-changelog

#3162 tests: nettoyage de marques inutiles
  tests/www/employee_record_views/test_summary.py
  tests/www/prescribers_views/test_list.py
Labels: no-changelog

#3156 Configurer le bucket S3 au déploiement
  .github/workflows/review-app-creation.yml
  .github/workflows/review-app-removal.yml
  itou/files/management/commands/configure_bucket.py
  scripts/delete-bucket
Labels: no-changelog

#3182 static: simplification JS
  itou/static/js/job_autocomplete.js
Labels: no-changelog

#3185 Remplacer `true` par `True` dans prolongation_requests/list.html
  itou/templates/approvals/prolongation_requests/list.html
Labels: no-changelog

#3183 Retrait de la variable intermédiaire allowed_headers de configure_bucket
  itou/files/management/commands/configure_bucket.py
Labels: no-changelog

#3186 Définir l’attribut accept sur les ItouFileInput à partir du content_type
  itou/files/forms.py
  itou/www/apply/forms.py
Labels: no-changelog

#3181 Fusionner test_prolongation_{report_file_saved,notification_contains_report_link}
  tests/www/approvals_views/test_prolongation.py
Labels: no-changelog

#3180 Nettoyage de www.approval_views.test_prolongation
  tests/www/approvals_views/test_prolongation.py
Labels: no-changelog

#3184 Éviter de construire une politique CORS pour MinIO
  itou/files/management/commands/configure_bucket.py
Labels: no-changelog

#3179 Déplacer les settings de DEV pour S3 dans config.settings.dev
  config/settings/dev.py
  config/settings/test.py
  tests/approvals/__snapshots__/test_notifications.ambr
  tests/conftest.py
  tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
Labels: no-changelog

#3190 Restreindre la politique S3 pour empêcher PutObject
  itou/files/management/commands/configure_bucket.py
  tests/files/tests.py
Labels: no-changelog

#3197 Candidature annulée: amélioration de l'email envoyée
  itou/templates/apply/email/cancel_body.txt
  tests/job_applications/tests.py
Labels: no-changelog

#3170 Fichier de variables d'environnement minimaliste
  .env.template
Labels: no-changelog

#3163 Importer et MAJ le style de programmation de itou-private
  docs/coding-style.md
Labels: no-changelog

#3202 Utiliser FileExtensionValidator au lieu de la vérif maison
  itou/files/forms.py
  tests/www/apply/test_submit.py
Labels: no-changelog

#3194 Ajouter un champ EvaluatedAdministrativeCriteria.proof
  itou/siae_evaluations/admin.py
  itou/siae_evaluations/migrations/0011_evaluatedadministrativecriteria_proof.py
  itou/siae_evaluations/models.py
  itou/www/siae_evaluations_views/views.py
  tests/siae_evaluations/factories.py
  tests/siae_evaluations/test_models.py
  tests/www/siae_evaluations_views/test_institutions_views.py
  tests/www/siae_evaluations_views/test_siaes_views.py
Labels: no-changelog

#3188 Retirer js-display-if-javascript-enabled
  itou/static/css/itou.css
  itou/static/js/utils.js
  itou/templates/apply/submit/application/eligibility.html
  itou/templates/apply/submit/application/end.html
  itou/templates/apply/submit/application/geiq_eligibility.html
Labels: no-changelog

#3193 Valider les accès aux bilans des demandes de prolongation
  config/settings/base.py
  itou/approvals/admin.py
  itou/approvals/notifications.py
  itou/files/models.py
  itou/templates/approvals/email/prolongation_request/created_body.txt
  itou/templates/approvals/prolongation_requests/show.html
  itou/utils/storage/s3.py
  itou/www/apply/views/submit_views.py
  itou/www/approvals_views/urls.py
  itou/www/approvals_views/views.py
  tests/approvals/__snapshots__/test_notifications.ambr
  tests/conftest.py
  tests/files/tests.py
  tests/www/apply/test_submit.py
  tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
  tests/www/approvals_views/test_prolongation.py
  tests/www/approvals_views/test_prolongation_requests.py
Labels: no-changelog

#3212 Amélioration de la commande `loaddata_bulk`
  itou/utils/management/commands/loaddata_bulk.py
Labels: no-changelog

#3195 Migrer EvaluatedAdministrativeCriteria.proof_url vers proof
  itou/siae_evaluations/admin.py
  itou/siae_evaluations/migrations/0012_evaluatedadministrativecriteria_proof_url_to_proof.py
  itou/siae_evaluations/models.py
  itou/templates/siae_evaluations/includes/criterion_validation.html
  itou/templates/siae_evaluations/includes/list_item.html
  itou/templates/siae_evaluations/institution_evaluated_job_application.html
  itou/templates/siae_evaluations/siae_upload_doc.html
  itou/www/siae_evaluations_views/urls.py
  itou/www/siae_evaluations_views/views.py
  tests/siae_evaluations/factories.py
  tests/siae_evaluations/test_models.py
  tests/www/siae_evaluations_views/test_institutions_views.py
  tests/www/siae_evaluations_views/test_siaes_views.py
  tests/www/siae_evaluations_views/test_views.py
Labels: no-changelog

#3203 Retirer le champ EvaluatedAdministrativeCriteria.proof_url
  itou/siae_evaluations/migrations/0013_remove_evaluatedadministrativecriteria_proof_url.py
Labels: no-changelog

#3213 Nettoyage de la migration EvaluatedAdministrativeCriteria.proof_url
  itou/siae_evaluations/migrations/0012_evaluatedadministrativecriteria_proof_url_to_proof.py
  itou/siae_evaluations/migrations/0013_remove_evaluatedadministrativecriteria_proof_url.py
Labels: no-changelog

#3216 Contrôle a posteriori: autoriser les admins à vérifier la vue du calendrier de la campagne
  itou/www/siae_evaluations_views/views.py
  tests/www/siae_evaluations_views/test_views.py
Labels: no-changelog

#3232 settings: suppression de l'intergiciel ErrorLoggingMiddleware
  config/settings/base.py
Labels: no-changelog

#3255 Suppression de siaes/models.py qui est resté là après un rebase
  itou/siaes/models.py
Labels: no-changelog

#3256 Correction du script import asp après le renommage de l'app siaes
  scripts/imports-asp.sh
Labels: no-changelog

#3262 Correctif de la fixture `_template_string_if_invalid_marker`
  tests/conftest.py
  tests/www/approvals_views/test_detail.py
  tests/www/approvals_views/test_display.py
  tests/www/invitations_views/test_prescriber_organization.py
  tests/www/invitations_views/test_siae_accept.py
Labels: no-changelog

#3260 metabase - Structures : Ajout des champs adresses renseignées par l'utilisateur
  itou/metabase/tables/siaes.py
  tests/metabase/management/test_populate_metabase_emplois.py
  tests/metabase/test_siaes.py
Labels: no-changelog

#3261 stats : Mettre en place le suivi Matomo du TB306 ESAT
  itou/metabase/management/commands/populate_metabase_matomo.py
  tests/metabase/management/__snapshots__/test_populate_metabase_matomo.ambr
  tests/metabase/management/test_populate_metabase_matomo.py
Labels: no-changelog

#3268 Utilisation de connections persistantes
  config/settings/base.py
Labels: no-changelog

#3270 JS: Ajout d'un guillemet manquant
  itou/templates/apply/submit/create_or_update_job_seeker/step_1.html
Labels: no-changelog

#3275 Metabase : Ajout de trois nouveaux champs (code NAF, email public et email d'authentication) à la table `structures`
  itou/metabase/tables/siaes.py
  tests/metabase/management/test_populate_metabase_emplois.py
Labels: no-changelog

#3274 Fiches Salarié : Ne plus casser au moment de la sérialisation pour le pays de naissance et la commune
  itou/employee_record/serializers.py
  tests/employee_record/__snapshots__/test_transfer_employee_records.ambr
  tests/employee_record/__snapshots__/test_transfer_employee_records_updates.ambr
  tests/employee_record/test_serializers.py
  tests/employee_record/test_transfer_employee_records.py
  tests/employee_record/test_transfer_employee_records_updates.py
Labels: no-changelog

#3263 Ajout des dates du PASS IAE sur les cartes « profil salariés »
  itou/templates/approvals/includes/list_card.html
  tests/www/approvals_views/test_list.py
Labels: recette-jetable

#3272 tests : Corriger les factories ZRR
  tests/geo/factories.py
Labels: no-changelog
