Repository gip-inclusion/les-emplois, pull requests merged in 2023-03, with the labels that each got.

#2205 Utiliser la même version python de prod dans les review-apps
  .github/workflows/review-app-creation.yml
Labels: recette-jetable, no-changelog

#2178 Ne plus considérer les super-utilisateurs comme des membres des organisations
  itou/common_apps/organizations/models.py
  itou/job_applications/models.py
Labels: no-changelog

#2149 Amélioration UI du parcours de gestion de candidatures
  itou/static/css/itou.css
  itou/templates/apply/edit_contract_start_date.html
  itou/templates/apply/includes/buttons/accept.html
  itou/templates/apply/includes/buttons/new_diagnosis.html
  itou/templates/apply/includes/buttons/postpone.html
  itou/templates/apply/includes/buttons/refuse.html
  itou/templates/apply/includes/job_application_answers.html
  itou/templates/apply/includes/job_application_sender_info.html
  itou/templates/apply/includes/job_applications_export_button.html
  itou/templates/apply/includes/job_applications_filters/criteria.html
  itou/templates/apply/includes/job_applications_filters/dates.html
  itou/templates/apply/includes/job_applications_filters/departments.html
  itou/templates/apply/includes/job_applications_filters/eligibility_validated.html
  itou/templates/apply/includes/job_applications_filters/job_seekers.html
  itou/templates/apply/includes/job_applications_filters/pass.html
  itou/templates/apply/includes/job_applications_filters/selected_jobs.html
  itou/templates/apply/includes/job_applications_filters/sender.html
  itou/templates/apply/includes/job_applications_filters/statut.html
  itou/templates/apply/includes/list_card_body.html
  itou/templates/apply/includes/list_card_header.html
  itou/templates/apply/includes/rdv_insertion_promo_card.html
  itou/templates/apply/includes/state_badge.html
  itou/templates/apply/includes/state_transition_siae.html
  itou/templates/apply/includes/transfer_job_application.html
  itou/templates/apply/list_for_siae.html
  itou/templates/apply/process_accept.html
  itou/templates/apply/process_base.html
  itou/templates/apply/process_cancel.html
  itou/templates/apply/process_details_prescriber.html
  itou/templates/apply/process_details_siae.html
  itou/templates/apply/process_eligibility.html
  itou/templates/apply/process_postpone.html
  itou/templates/apply/process_refuse.html
  itou/templates/approvals/includes/card.html
  itou/templates/dashboard/edit_job_seeker_info.html
  itou/templates/dashboard/edit_user_email.html
  itou/templates/dashboard/edit_user_info.html
  itou/templates/dashboard/edit_user_notifications.html
  itou/templates/dashboard/includes/edit_job_seeker_info_form.html
  itou/templates/layout/content_small.html
Labels: recette-jetable

#2213 Nettoyage journalier des sessions expirées
  clevercloud/cron.json
Labels: no-changelog

#2222 [Metabase] Ajout de l'année d'autoprescription
  itou/metabase/sql/031_suivi_auto_prescription.sql
  itou/metabase/sql/034_candidats_auto_prescription.sql
Labels: no-changelog

#2217 Mise à jour de l'UI des cards dans le dashboard
  itou/static/css/itou.css
  itou/static/vendor/theme-inclusion/javascripts/app.js
  itou/static/vendor/theme-inclusion/stylesheets/app.css
  itou/templates/dashboard/dashboard.html
  itou/templates/dashboard/includes/admin_card.html
  itou/templates/dashboard/includes/dora_card.html
  itou/templates/dashboard/includes/job_seeker_approval_card.html
  itou/templates/dashboard/includes/job_seeker_job_applications_card.html
  itou/templates/dashboard/includes/labor_inspector_evaluation_campains_card.html
  itou/templates/dashboard/includes/labor_inspector_organization_card.html
  itou/templates/dashboard/includes/prescriber_job_applications_card.html
  itou/templates/dashboard/includes/prescriber_organisation_card.html
  itou/templates/dashboard/includes/siae_card.html
  itou/templates/dashboard/includes/siae_employees_card.html
  itou/templates/dashboard/includes/siae_evaluation_campains_card.html
  itou/templates/dashboard/includes/siae_job_applications_card.html
  itou/templates/dashboard/includes/stats.html
  itou/templates/layout/_footer.html
  itou/www/dashboard/tests.py
  itou/www/dashboard/views.py
Labels: recette-jetable

#2225 github: add ref_name to concurrency group
  .github/workflows/ci.yml
Labels: no-changelog

#2206 metabase : CAP : creation d'une table avec le détail des critères d'eligibilité par campagne
  itou/metabase/sql/038_suivi_cap_criteres.sql
Labels: no-changelog

#2201 Correction de balises matomo dans le parcours d'activation de compte Inclusion Connect
  itou/templates/account/activate_inclusion_connect_account.html
  itou/templates/account/login_generic.html
  itou/templates/dashboard/dashboard.html
  itou/utils/perms/context_processors.py
  itou/utils/tests.py
  itou/www/login/views.py
Labels: recette-jetable, no-changelog

#2208 feat: ajout d'un tooltip d'explication pour le refus `prevent_objectives`
  itou/templates/apply/process_refuse.html
  itou/utils/enums_context_processors.py
Labels: recette-jetable

#2211 Rendre obligatoire la civilité du candidat lors de la création
  itou/templates/signup/job_seeker_signup.html
  itou/www/signup/forms.py
  itou/www/signup/tests/test_job_seeker.py
  itou/www/welcoming_tour/tests.py
Labels: recette-jetable

#2230 deploy_prod: suppression de l'option --no-ff
  scripts/deploy_prod.sh
Labels: no-changelog

#2239 deploy_prod: resynchronisation de la branche master_clever
  scripts/deploy_prod.sh
Labels: no-changelog

#2245 Metabase : ajout d'une colonne métier
  itou/metabase/sql/032_metier_candidatures.sql
Labels: no-changelog

#2243 matomo: Correction d'un bug qui annule certaines écritures + autres correctifs
  itou/metabase/management/commands/populate_metabase_matomo.py
  itou/metabase/management/test_populate_metabase_matomo.py
  itou/metabase/sql/025_suivi_visiteurs_tous_tb.sql
  itou/metabase/sql/030_taux_penetration_tb_prives.sql
Labels: no-changelog

#2257 [Metabase] : retrait d'une condition inutile
  itou/metabase/sql/034_candidats_auto_prescription.sql
Labels: no-changelog

#2260 Metabase : prise en compte de la table V1 pour les visiteurs publics
  itou/metabase/sql/025_suivi_visiteurs_tous_tb.sql
Labels: no-changelog

#2235 fix: ajout du next_url pour la redirection Inclusion Connect
  itou/templates/account/activate_inclusion_connect_account.html
  itou/utils/tests.py
  itou/utils/urls.py
  itou/www/invitations_views/tests/tests_prescriber_organization.py
  itou/www/invitations_views/tests/tests_siae_accept.py
  itou/www/login/tests.py
  itou/www/login/views.py
Labels: recette-jetable

#2266 test_populate_matomo: Accélération des tests
  itou/metabase/management/test_populate_metabase_matomo.py
Labels: no-changelog

#2259 Retirer le tag "nouveau" de certains fonctionnalités
  itou/templates/dashboard/includes/dora_card.html
  itou/templates/dashboard/includes/labor_inspector_evaluation_campains_card.html
  itou/templates/dashboard/includes/prescriber_organisation_card.html
  itou/templates/dashboard/includes/siae_employees_card.html
  itou/templates/dashboard/includes/siae_evaluation_campains_card.html
  itou/www/dashboard/tests.py
  itou/www/dashboard/views.py
Labels: no-changelog

#2276 Stats : Tentative de résolution d'une erreur CSP sur l'iframe utilisée par le site Pilotage
  config/settings/base.py
Labels: no-changelog

#2277 Stats : Fix d'une erreur 500 qui se produisait quand un utilisateur authentifié sur le C1 tentait d'accéder à un tableau de bord public sur https://pilotage.inclusion.beta.gouv.fr/
  itou/www/stats/tests/tests_views.py
  itou/www/stats/views.py
Labels: no-changelog

#2273 Nettoyage d'avertissements de dépréciation de django
  itou/users/tests/test_management_commands.py
Labels: no-changelog

#2292 Correction d'un test
  itou/approvals/tests/tests.py
Labels: no-changelog

#2290 Admin PASS IAE : Ré-autoriser la modification quand la FS existe pour certain statuts
  itou/approvals/admin.py
  itou/approvals/tests/tests.py
Labels: recette-jetable, no-changelog

#2301 Petite amélioration UI de la fiche SIAE
  itou/templates/siaes/card.html
Labels: no-changelog

#2296 Admin - Utilisateur : Forcer l'affichage de certaines informations liées que si le type correspond
  itou/users/admin.py
Labels: recette-jetable, no-changelog

#2302 Correction de l'admin des PASS IAE lors d'une tentative d'ajout avec un numéro commençant par 99999
  itou/approvals/admin_forms.py
  itou/approvals/tests/tests.py
Labels: no-changelog

#2293 Correction de la génération du code postal de SIaeFactory
  itou/siaes/factories.py
Labels: no-changelog

#2303 requirements: upgrade boto3 & botocore
  requirements/base.txt
  requirements/dev.txt
Labels: recette-jetable

#2300 Simplification de show_geiq_eligibility_modal V2
  itou/templates/apply/includes/buttons/accept.html
  itou/www/apply/tests/tests_process.py
  itou/www/apply/views/process_views.py
Labels: no-changelog

#2313 Simplification de code
  itou/metabase/tables/utils.py
  itou/users/migrations/0004_fill_user_last_checked_at.py
  itou/www/apply/tests/tests_process.py
  itou/www/apply/views/process_views.py
  itou/www/search/tests.py
Labels: no-changelog

#2317 Ajout du support responsif pour le bouton inclusion connect
  itou/static/img/inclusion_connect/logo-inclusion-connect-one-line.svg
  itou/static/img/inclusion_connect/logo-inclusion-connect.svg
  itou/templates/account/activate_inclusion_connect_account.html
  itou/templates/account/login_generic.html
  itou/templates/inclusion_connect/includes/description.html
Labels: no-changelog

#2319 [Metabase] Ajout du type de structure pour l'auto prescription des candidats
  itou/metabase/sql/034_candidats_auto_prescription.sql
Labels: no-changelog

#2330 Harmonsiation des templates de job list
  itou/templates/apply/includes/job_applications_filters/to_siaes.html
  itou/templates/apply/includes/state_badge.html
  itou/templates/apply/list_for_job_seeker.html
  itou/templates/apply/list_for_prescriber.html
  itou/templates/apply/list_for_siae.html
Labels: recette-jetable

#2089 Ajout d'une page pour créer / accéder à son token d'API
  itou/api/applicants_api/views.py
  itou/api/employee_record_api/viewsets.py
  itou/api/token_auth/__init__.py
  itou/api/token_auth/tests.py
  itou/api/token_auth/views.py
  itou/api/urls.py
  itou/templates/dashboard/api_token.html
  itou/templates/layout/_nav_btn_items.html
  itou/www/dashboard/tests.py
  itou/www/dashboard/urls.py
  itou/www/dashboard/views.py
Labels: recette-jetable
