Repository gip-inclusion/les-emplois, pull requests merged in 2024-01, with the labels that each got.

#3507 Nettoyage de migrations
  itou/users/migrations/0028_remove_user_lack_of_pole_emploi_id_reason_and_more.py
  itou/users/migrations/0029_really_remove_user_pole_emploi_fields.py
Labels: no-changelog

#3504 Mise à jour des settings `vscode` avec le passage à la version `1.85.1`
  .vscode/settings.json
Labels: no-changelog

#3509 Fiches salarié : Nettoyage des FS orphelines faisant doublon
  itou/employee_record/management/commands/clean_orphans.py
Labels: no-changelog

#3521 [GEN-7877] Suppression du lien en double "Mot de passe oublié ?"
  itou/templates/account/includes/login_form.html
  itou/www/login/forms.py
Labels: recette-jetable

#3520 [GEN-7876] Suppression du lien voxusagers
  itou/templates/layout/base.html
Labels: no-changelog

#3522 [GEN-7556] Modification du widget des départements et fiches de poste dans la recherche de candidatures
  itou/templates/apply/includes/job_applications_filters/departments.html
  itou/templates/apply/includes/job_applications_filters/selected_jobs.html
  itou/www/apply/forms.py
  tests/www/apply/__snapshots__/test_list.ambr
Labels: recette-jetable

#3526 Correction d'une migration
  itou/employee_record/migrations/0011_clean_orphans_duplicate.py
Labels: no-changelog

#3523 admin: amélioration des performances sur la page de l'utilisateur
  itou/users/admin.py
  tests/users/test_admin_views.py
Labels: no-changelog

#3459 Embauche : masquer l'alerte sur le Pass expiré lors du dépot de candidature [GEN-7451]
  itou/templates/approvals/includes/status.html
  tests/www/approvals_views/__snapshots__/test_includes.ambr
  tests/www/approvals_views/test_includes.py
Labels: html

#3529 analytics: ajout du nombre d'utilisateur par type
  itou/analytics/management/commands/collect_analytics_data.py
  itou/analytics/migrations/0001_initial.py
  itou/analytics/models.py
  itou/analytics/users.py
  tests/analytics/test_users.py
Labels: no-changelog

#3533 prescribers: suppression de commande inutilisée avec leurs données vieilles de 4/5 ans
  itou/prescribers/management/commands/data/authorized_prescribers.csv
  itou/prescribers/management/commands/data/pole_emploi_agencies.csv
  itou/prescribers/management/commands/import_pole_emploi_agencies.py
  itou/prescribers/management/commands/import_prescribers.py
Labels: no-changelog

#3531 [GEN-7865] Changer le logo PE en logo France Travail
  itou/static/img/logo-france-travail.svg
  itou/static/img/logo-pole-emploi.svg
  itou/templates/companies/includes/_card_jobdescription.html
  tests/www/search/tests.py
Labels: recette-jetable

#3043 [ADRESSES] Ajout d'une FK vers cities.City à l'AddressMixin + cron de résolution
  clevercloud/cron.json
  itou/cities/management/commands/resolve_insee_cities.py
  itou/common_apps/address/models.py
  itou/companies/migrations/0012_company_insee_city.py
  itou/institutions/migrations/0009_institution_insee_city.py
  itou/prescribers/migrations/0004_prescriberorganization_insee_city.py
  itou/users/migrations/0030_user_insee_city.py
  tests/cities/__snapshots__/tests.ambr
  tests/cities/tests.py
Labels: no-changelog

#3537 Maj du theme itou vers la v1.1.7 et de l'a11y du bouton burger
  itou/templates/layout/_header.html
  itou/utils/staticfiles.py
Labels: recette-jetable

#3543 Permettre aux développeurs de gérer un .envrc local
  .envrc
  .gitignore
Labels: no-changelog

#3540 Stats : Ajout de stats sur les fdp en tension pour les DDETS IAE et DREETS IAE
  itou/templates/dashboard/includes/stats.html
  itou/utils/apis/metabase.py
  itou/www/stats/urls.py
  itou/www/stats/views.py
  tests/www/stats/test_views.py
Labels: no-changelog

#3508 Améliorer la hiérarchisation des données dans la page de détail de candidature
  itou/templates/apply/includes/eligibility_diagnosis.html
  itou/templates/apply/includes/geiq/geiq_diagnosis_details.html
  itou/templates/apply/includes/job_application_answers.html
  itou/templates/apply/includes/job_application_diagoriente_invite.html
  itou/templates/apply/includes/job_application_info.html
  itou/templates/apply/includes/job_application_sender_info.html
  itou/templates/apply/includes/job_seeker_info.html
  itou/templates/apply/includes/out_of_band_changes_on_job_application_state_update_siae.html
  itou/templates/apply/includes/siae_hiring_details.html
  itou/templates/apply/includes/transition_logs.html
  itou/templates/apply/process_base.html
  itou/templates/apply/process_details.html
  itou/templates/apply/process_details_company.html
  itou/templates/approvals/detail.html
  itou/templates/approvals/includes/status.html
  itou/templates/companies/includes/_list_siae_actives_jobs_row.html
  itou/templates/companies/includes/_siae_jobdescription.html
  itou/utils/templatetags/job_applications.py
  tests/utils/__snapshots__/tests.ambr
  tests/www/apply/__snapshots__/test_list.ambr
  tests/www/apply/test_edit.py
  tests/www/apply/test_process.py
  tests/www/approvals_views/__snapshots__/test_includes.ambr
  tests/www/companies_views/__snapshots__/test_views.ambr
  tests/www/dashboard/__snapshots__/tests.ambr
Labels: recette-jetable, html

#3535 [GEN-7531] Amélioration de la disposition des champs concernant l'origine d'une candidature
  itou/job_applications/admin.py
  itou/job_applications/admin_forms.py
  itou/job_applications/migrations/0001_initial.py
  itou/job_applications/models.py
Labels: recette-jetable

#3554 Correction de JobSeekerProfileFactory
  tests/users/factories.py
Labels: no-changelog

#3553 settings.dev: Allow customizing Metabase configuration variables
  config/settings/dev.py
Labels: no-changelog

#3555 Refonte UX/UI - Cartes dashboard
  itou/templates/dashboard/dashboard.html
  itou/templates/dashboard/includes/prescriber_job_applications_card.html
  itou/templates/dashboard/includes/siae_card.html
  itou/templates/dashboard/includes/siae_employees_card.html
  itou/templates/dashboard/includes/siae_job_applications_card.html
  itou/templates/layout/_header_nav_primary_items.html
  itou/utils/staticfiles.py
  tests/www/__snapshots__/test_layout.ambr
Labels: recette-jetable, html

#3557 Fiches salarié : Ajout d'un script pour sortir en masse des FS pour une SIAE
  itou/employee_record/management/commands/unarchive_employee_records.py
Labels: no-changelog

#3551 Refonte UX/UI - Modification de la box des infos structure
  itou/templates/apply/includes/siae_card.html
  itou/templates/apply/process_details.html
  itou/templates/apply/submit/application/base.html
  itou/templates/apply/submit_base_two_columns.html
  itou/templates/approvals/prolongation_requests/show.html
  itou/templates/companies/edit_siae.html
  itou/templates/companies/edit_siae_preview.html
  itou/templates/companies/includes/_siae_details.html
  itou/templates/companies/includes/_siae_info.html
  itou/templates/companies/job_description_card.html
Labels: recette-jetable, html

#3556 Changelog Sprint 79
  CHANGELOG.md
Labels: no-changelog
