Repository gip-inclusion/les-emplois, pull requests merged in 2024-07, with the labels that each got.

#4324 UX/UI : Corriger une typo sur le filtre par statut de la liste des candidatures
  itou/templates/apply/includes/job_applications_filters/status.html
Labels: no-changelog

#4276 UX/UI: Refonte de la page de recherche prescripteur habilité
  itou/templates/search/includes/prescribers_search_filters.html
  itou/templates/search/includes/prescribers_search_summary.html
  itou/templates/search/prescribers_search_results.html
  tests/www/search/tests.py
Labels: 1-recette-jetable, modifié

#4277 UX/UI: Correction d’un petit bug sur la recherche employeur
  itou/static/js/utils.js
  itou/templates/search/includes/siaes_search_top.html
  itou/templates/search/siaes_search_results.html
  tests/www/search/tests.py
Labels: 1-recette-jetable, modifié

#4323 changelog: From 2024-06-24 to 2024-06-30
  CHANGELOG.md
Labels: no-changelog

#4336 Admin: Correction de la page des transition d'état de candidature
  itou/job_applications/admin.py
  itou/templates/admin/job_applications/jobapplication_change_form.html
Labels: no-changelog

#4349 Admin : Limiter les champs des `inline` d’appartenance à une entreprise ou organisation aux champs en lecture seule
  itou/users/admin.py
Labels: modifié

#4343 UX/UI : Rajouter le champ « Structure destinataire » à la liste des candidatures pour les prescripteurs
  itou/templates/apply/includes/job_applications_filters/offcanvas_body.html
  tests/www/apply/__snapshots__/test_list_for_siae.ambr
  tests/www/apply/__snapshots__/test_list_prescriptions.ambr
Labels: modifié

#4347 UX/UI : Afficher le nom du candidat en majuscule dans le filtre des PASS IAE et salariés
  itou/www/approvals_views/forms.py
  tests/www/approvals_views/test_list.py
Labels: modifié

#4320 Candidats : limitation du nom à 70 caractères et correctif et sécurité
  itou/static/js/gps.js
  itou/users/models.py
  itou/www/autocomplete/views.py
  tests/users/test_models.py
Labels: modifié

#4350 Préferer request.path pour la target du form de la recherche SIAE/fiche de poste
  itou/templates/search/siaes_search_results.html
Labels: no-changelog

#4345 UX/UI : Limiter la sélection rapide à un candidat dans la liste des PASS IAE et salariés [GEN-1687]
  itou/templates/approvals/list.html
  itou/www/approvals_views/forms.py
  tests/www/approvals_views/test_list.py
Labels: modifié

#4352 UX/UI : remplacer Status par Statut
  itou/templates/apply/submit_step_pending_authorization.html
  itou/templates/status/index.html
  tests/www/apply/test_submit.py
Labels: modifié

#4353 UX/UI : Mise en cohérence de l'aspect de la carte "Orientation" sur le Tableau de bord des Employeurs
  itou/templates/dashboard/includes/employer_prescription_card.html
Labels: 1-recette-jetable, modifié

#4354 Autoriser Matomo dans l’environnement de dev
  config/settings/dev.py
Labels: no-changelog

#4344 UX/UI : Limiter la sélection rapide à un candidat dans la liste des fiches salarié [GEN-1687]
  itou/templates/employee_record/list.html
  itou/www/employee_record_views/forms.py
  itou/www/employee_record_views/views.py
  tests/www/employee_record_views/test_list.py
Labels: modifié

#4015 [GEN-186] Ajout d'un rappel périodique par email pour inviter les administrateurs d'organisations à s'assurer que leurs membres sont bien actifs et autorisés
  clevercloud/cron.json
  itou/common_apps/organizations/models.py
  itou/communications/dispatch/__init__.py
  itou/communications/dispatch/utils.py
  itou/companies/migrations/0003_company_active_members_email_reminder_last_sent_at.py
  itou/companies/migrations/0004_set_companies_active_members_email_reminder_last_sent_at.py
  itou/institutions/migrations/0004_institution_active_members_email_reminder_last_sent_at.py
  itou/institutions/migrations/0005_set_institutions_active_members_email_reminder_last_sent_at.py
  itou/prescribers/migrations/0002_prescriberorganization_active_members_email_reminder_last_sent_at.py
  itou/prescribers/migrations/0003_set_prescriber_organizations_active_members_email_reminder_last_sent_at.py
  itou/templates/users/emails/check_authorized_members_email_body.txt
  itou/templates/users/emails/check_authorized_members_email_subject.txt
  itou/users/management/commands/send_check_authorized_members_email.py
  itou/users/notifications.py
  tests/users/__snapshots__/test_management_commands.ambr
  tests/users/test_management_commands.py
Labels: ajouté

#4315 Statistiques: Export de données anonymes pour analyses d'impact
  clevercloud/cron.json
  clevercloud/crons/populate_c1_analyses.sh
  config/settings/base.py
  config/settings/dev.py
  itou/metabase/dataframes.py
  itou/metabase/db.py
  itou/metabase/management/commands/metabase_to_csv.py
  itou/metabase/management/commands/populate_c1_analyses.py
  itou/metabase/management/commands/populate_metabase_matomo.py
  itou/metabase/tables/c1_analyses.py
  tests/metabase/conftest.py
  tests/metabase/management/test_populate_c1_analyses.py
Labels: ajouté

#4359 UX/UI : bandeau « chercher un bénéficiaire » sur GPS
  itou/templates/gps/my_groups.html
Labels: modifié

#4363 Statistiques: Correction de la connexion à la base de donnée
  itou/metabase/db.py
Labels: no-changelog

#4364 Ajout des départements 984 et 989
  itou/analytics/migrations/0001_initial.py
  itou/api/migrations/0004_departmenttoken.py
  itou/cities/migrations/0001_initial.py
  itou/common_apps/address/departments.py
  itou/companies/migrations/0001_initial.py
  itou/institutions/migrations/0001_initial.py
  itou/prescribers/migrations/0001_initial.py
  itou/users/migrations/0001_initial.py
  tests/www/prescribers_views/__snapshots__/test_edit.ambr
Labels: modifié

#4360 Contrôle a posteriori : Correction de l’algorithme de sélection des auto-prescriptions
  itou/siae_evaluations/models.py
  tests/siae_evaluations/test_models.py
Labels: modifié

#4365 Flaky TestViewProof.test_access_other_institution
  tests/www/siae_evaluations_views/test_views.py
Labels: no-changelog

#4368 templates: suppression de l'indirection `approvals/includes/card.html`
  itou/templates/apply/process_base.html
  itou/templates/apply/submit_base.html
  itou/templates/approvals/declare_prolongation.html
  itou/templates/approvals/includes/card.html
  itou/templates/approvals/suspend.html
  tests/www/apply/test_submit.py
Labels: no-changelog

#4367 GEIQ: utilisation d'un OneToOneField pour éviter un warning
  itou/geiq/migrations/0001_initial.py
  itou/geiq/models.py
Labels: no-changelog

#4370 Ajouter les départements 984 et 989 aux TOM
  itou/common_apps/address/departments.py
Labels: no-changelog

#4371 Analytics : Suivi des champs prénom et nom pour les candidats
  itou/templates/apply/submit/create_or_update_job_seeker/step_base.html
  itou/templates/dashboard/includes/edit_job_seeker_info_form.html
  itou/templates/employee_record/includes/create_step_1.html
  itou/templates/signup/job_seeker_signup.html
  itou/www/apply/views/submit_views.py
  tests/www/signup/__snapshots__/test_job_seeker.ambr
Labels: no-changelog

#4374 Employeur: toujours afficher le nom de famille du candidat en majuscule [GEN-1786]
  itou/templates/apply/includes/job_seeker_info.html
  tests/www/apply/test_process.py
Labels: modifié

#4377 Admin: le statut d'une demande de prolongation est maintenant en lecture seule
  itou/approvals/admin.py
Labels: modifié

#4378 tests: division de dashboard/tests.py en plusieurs petits fichiers
  tests/www/dashboard/__snapshots__/test_dashboard.ambr
  tests/www/dashboard/__snapshots__/test_edit_user_info.ambr
  tests/www/dashboard/test_activate_ic_account.py
  tests/www/dashboard/test_api_token.py
  tests/www/dashboard/test_dashboard.py
  tests/www/dashboard/test_edit_job_seeker_info.py
  tests/www/dashboard/test_edit_user_email.py
  tests/www/dashboard/test_edit_user_info.py
  tests/www/dashboard/test_edit_user_notifications.py
  tests/www/dashboard/test_switch_organization.py
  tests/www/dashboard/tests.py
Labels: no-changelog

#4376 Journal des changements: ajouter une section Tech [GEN-1706]
  .github/workflows/require-labels.yml
  scripts/mkchangelog
Labels: tech

#4385 tests: correction test instable
  tests/job_applications/tests.py
Labels: no-changelog

#4381 tests: suppression de deux variables inconnues
  itou/templates/dashboard/includes/job_seeker_approval_card.html
  tests/www/dashboard/test_dashboard.py
Labels: no-changelog

#4358 Doc (README): infos sur l'activation de venv
  README.md
  docs/developing.md
Labels: no-changelog

#4366 Changement du backend de cache en faveur de django-redis
  config/settings/base.py
  config/settings/test.py
  itou/utils/cache.py
  requirements/base.in
  requirements/base.txt
  requirements/dev.txt
  requirements/test.txt
  tests/utils/apis/test_pole_emploi_api.py
  tests/utils/test_cache.py
Labels: dependencies

#4384 changelog: From 2024-07-01 to 2024-07-07
  CHANGELOG.md
Labels: no-changelog

#4361 GPS : pagination et filtre par nom de bénéficiaire
  itou/templates/gps/includes/memberships_results.html
  itou/templates/gps/my_groups.html
  itou/www/gps/forms.py
  itou/www/gps/views.py
  tests/gps/__snapshots__/test_views.ambr
  tests/gps/test_views.py
Labels: 1-recette-jetable, ajouté

#4394 Admin: facilite l'ajout automatique de remarque de support
  itou/users/admin.py
  itou/utils/admin.py
Labels: no-changelog

#4396 tests: division du fichier www/companies_views/test_views.py en plusieurs
  tests/www/companies_views/__snapshots__/test_card_views.ambr
  tests/www/companies_views/__snapshots__/test_dora_views.ambr
  tests/www/companies_views/test_card_views.py
  tests/www/companies_views/test_create_company_views.py
  tests/www/companies_views/test_dora_views.py
  tests/www/companies_views/test_edit_company_views.py
  tests/www/companies_views/test_financial_annex_views.py
  tests/www/companies_views/test_members_views.py
  tests/www/companies_views/test_views.py
Labels: no-changelog

#4401 Candidature: Double fermeture de form sur les filtres candidats
  itou/templates/apply/includes/job_applications_filters/offcanvas.html
Labels: modifié

#4397 style(models/User.public_id): add help_text
  itou/users/migrations/0008_fix_user_public_id.py
  itou/users/models.py
Labels: python, no-changelog

#4406 Candidature: suppression des enquêtes Tally auprès des SIAE et des prescripteurs pour connaître leur pratiques concernant les candidatures faites par des candidats en autonomie
  itou/templates/apply/list_for_siae.html
  itou/templates/apply/list_prescriptions.html
Labels: supprimé

#4387 Candidature: ajout d'une notification au candidat et au prescripteur/orienteur éventuel lors d'une mise en attente [GEN-1759]
  itou/job_applications/models.py
  itou/job_applications/notifications.py
  itou/templates/apply/email/postpone_for_job_seeker_body.txt
  itou/templates/apply/email/postpone_for_job_seeker_subject.txt
  itou/templates/apply/email/postpone_for_proxy_body.txt
  itou/templates/apply/email/postpone_for_proxy_subject.txt
  tests/www/apply/__snapshots__/test_process.ambr
  tests/www/apply/test_process.py
Labels: 1-recette-jetable, ajouté

#4403 GPS: Corriger les dates de création des groupes de suivi créés par script
  itou/gps/management/commands/init_follow_up_groups.py
  itou/gps/management/commands/update_follow_up_groups_member_created_at.py
  tests/gps/test_management_commands.py
Labels: modifié

#4410 Tableau de bord: suppression de la bannière annonçant une enquête Tally aux employeurs SIAE [GEN-1846]
  itou/www/dashboard/views.py
Labels: supprimé

#4382 Changement du titre d'un TB
  itou/templates/dashboard/includes/stats.html
Labels: no-changelog

#4412 Correction d'un test
  tests/gps/__snapshots__/test_views.ambr
  tests/gps/test_views.py
Labels: no-changelog

#4395 Vie privée: utilisation du ID public en place de PK dans les URLs
  itou/templates/apply/includes/job_seeker_info.html
  itou/templates/apply/submit/application/base.html
  itou/templates/apply/submit/check_job_seeker_info_for_hire.html
  itou/www/apply/urls.py
  itou/www/apply/views/common.py
  itou/www/apply/views/submit_views.py
  itou/www/apply/views/utils.py
  itou/www/dashboard/urls.py
  itou/www/dashboard/views.py
  tests/www/apply/test_geiq.py
  tests/www/apply/test_submit.py
  tests/www/approvals_views/test_detail.py
  tests/www/dashboard/test_edit_job_seeker_info.py
Labels: ajouté

#4407 Support: simplification de move_company_data
  itou/companies/management/commands/move_company_data.py
Labels: no-changelog

#4415 fix(apply/submit_views.py): TypeError on functional views
  itou/www/apply/views/submit_views.py
Labels: no-changelog

#4419 Statistiques: Mise à jour des noms sur le tableau de bord
  itou/templates/dashboard/includes/stats.html
  tests/www/dashboard/test_dashboard.py
Labels: no-changelog

#4421 changelog: From 2024-07-08 to 2024-07-14
  CHANGELOG.md
Labels: no-changelog

#4418 tests: suppression d'une variable inconnue
  itou/templates/includes/copy_to_clipboard.html
  tests/utils/test_redirect_legacy_views.py
  tests/utils/tests.py
  tests/www/approvals_views/test_prolongation_requests.py
  tests/www/companies_views/test_card_views.py
  tests/www/companies_views/test_job_description_views.py
  tests/www/dashboard/test_api_token.py
  tests/www/dashboard/test_switch_organization.py
  tests/www/invitations_views/test_company_send.py
Labels: no-changelog

#4399 UX/UI : Ajout d'une alerte Maze
  itou/templates/apply/list_prescriptions.html
Labels: 1-recette-jetable, ajouté

#4423 Ajout des pop up tally sur les TBs privés du pilotage
  itou/utils/apis/metabase.py
Labels: no-changelog

#4422 admin: Remonter l’annexe financière valide en haut de liste
  itou/companies/admin.py
Labels: modifié

#4435 GPS: Ajouter un filtre par département dans l’admin [GEN-1851]
  itou/gps/admin.py
Labels: ajouté

#4436 GPS: Ajouter le département des bénéficiaires dans l’admin [GEN-1850]
  itou/gps/admin.py
Labels: ajouté

#4438 Statistiques: Ajout des données des groupes de suivi
  clevercloud/crons/populate_metabase_emplois.sh
  itou/metabase/management/commands/populate_metabase_emplois.py
  itou/metabase/tables/gps.py
  tests/metabase/management/test_populate_metabase_emplois.py
Labels: ajouté

#4400 [Metabase] Whitelist SIAE
  config/settings/base.py
  itou/templates/dashboard/includes/stats.html
  itou/utils/apis/metabase.py
  itou/www/dashboard/views.py
  itou/www/stats/urls.py
  itou/www/stats/utils.py
  itou/www/stats/views.py
  tests/www/stats/test_views.py
Labels: no-changelog

#4437 Candidature: Bloquer l'embauche trop loin dans le futur [GEN-1867]
  itou/job_applications/models.py
  itou/www/apply/forms.py
  tests/www/apply/test_process.py
Labels: 1-recette-jetable, modifié

#4417 Contrôle a posteriori: envoi de la notification aux DDETS au moment du blocage des soumissions [GEN-1860]
  itou/siae_evaluations/management/commands/evaluation_campaign_notify.py
  itou/siae_evaluations/models.py
  tests/siae_evaluations/test_admin.py
  tests/siae_evaluations/test_management_commands.py
  tests/siae_evaluations/test_models.py
Labels: 1-recette-jetable, modifié

#4441 PASS IAE: Amélioration de l'affichage de temps restant
  itou/approvals/models.py
  tests/approvals/tests.py
  tests/www/approvals_views/__snapshots__/test_includes.ambr
  tests/www/approvals_views/test_list.py
Labels: modifié

#4444 Autocompletion: suppression de code déprécié
  itou/www/autocomplete/views.py
  tests/www/autocomplete/tests.py
Labels: 1-recette-jetable, no-changelog

#4445 Autocompletion: suppression de code déprécié - partie 2
  itou/www/companies_views/forms.py
  itou/www/employee_record_views/forms.py
  itou/www/gps/forms.py
  itou/www/search/forms.py
  tests/www/dashboard/__snapshots__/test_dashboard.ambr
  tests/www/employee_record_views/__snapshots__/test_create.ambr
Labels: no-changelog

#4447 changelog: From 2024-07-15 to 2024-07-21
  CHANGELOG.md
Labels: no-changelog

#4442 Pilotage : Augmenter la durée de vie des tableaux de bord à 1 heure
  itou/utils/apis/metabase.py
Labels: no-changelog

#4443 Pilotage : Suppression des bannières pour les webinaires du mois de juin
  itou/templates/dashboard/dashboard.html
  itou/www/dashboard/views.py
Labels: no-changelog

#4449 Vie privée : enlève le support temporaire de job_seeker_pk aux URLs apply
  itou/www/apply/urls.py
  itou/www/apply/views/submit_views.py
  itou/www/apply/views/utils.py
  itou/www/dashboard/urls.py
  itou/www/dashboard/views.py
  tests/www/apply/test_submit.py
Labels: no-changelog

#4448 Candidature: Faciliter la mise à jour du NIR à l'aide d'un texte d'aide [GEN-265]
  itou/common_apps/nir/forms.py
  tests/www/apply/test_process.py
  tests/www/dashboard/test_edit_job_seeker_info.py
  tests/www/dashboard/test_edit_user_info.py
Labels: 1-recette-jetable, modifié

#4462 Retirer le hack pour faire apparaître `.has-selected-item` en gras dans htmx_dropdown_filter
  itou/static/js/htmx_dropdown_filter.js
Labels: no-changelog

#4453 UX/UI : Retirer l'alerte du test Maze sur la liste des candidatures côté prescripteur
  itou/templates/apply/list_prescriptions.html
Labels: supprimé

#4455 Tests: Migration de certains tests à pytest
  tests/api/applicants_api/tests.py
  tests/api/data_inclusion_api/tests.py
  tests/api/employee_record_api/test_throttling.py
  tests/api/employee_record_api/tests.py
  tests/api/test_c4_api.py
  tests/approvals/test_notify_pole_emploi.py
  tests/common_apps/address/tests.py
  tests/companies/test_models.py
  tests/conftest.py
  tests/www/institutions_views/test_views.py
  tests/www/invitations_views/test_company_send.py
  tests/www/prescribers_views/test_admins.py
  tests/www/prescribers_views/test_edit.py
  tests/www/prescribers_views/test_members.py
  tests/www/releases/tests.py
  tests/www/search/tests.py
  tests/www/siae_evaluations_views/test_forms.py
  tests/www/siae_evaluations_views/test_institutions_views.py
  tests/www/siae_evaluations_views/test_siaes_views.py
  tests/www/signup/__snapshots__/test_job_seeker.ambr
  tests/www/signup/test_allauth.py
  tests/www/signup/test_job_seeker.py
  tests/www/signup/test_password.py
  tests/www/stats/test_views.py
  tests/www/welcoming_tour/tests.py
Labels: no-changelog

#4463 Correction d'un test instable
  tests/utils/test.py
  tests/utils/tests.py
Labels: no-changelog

#4459 Processus de candidature : réusinage des tests du processus d'acceptation
  tests/users/factories.py
  tests/www/apply/test_process.py
Labels: no-changelog

#4355 Permettre de stocker l’ID RDV-S d’un SIAE dans les emplois [GEN-1762]
  itou/companies/admin.py
  itou/companies/migrations/0005_company_rdv_insertion_id.py
  itou/companies/models.py
Labels: ajouté

#4356 Système permettant de renouveler token d’API RDV-S [GEN-1763]
  config/settings/base.py
  itou/rdv_insertion/__init__.py
  itou/rdv_insertion/api.py
  itou/rdv_insertion/migrations/__init__.py
  itou/utils/mocks/rdv_insertion.py
  tests/rdv_insertion/__init__.py
  tests/rdv_insertion/tests.py
Labels: ajouté

#4471 changelog: From 2024-07-22 to 2024-07-28
  CHANGELOG.md
Labels: no-changelog

#4465 Améliorer test_auto_prescription_xlsx_export
  tests/job_applications/tests.py
Labels: no-changelog

#4464 Sécurité : Déléguer le security.txt au GIP de l’inclusion
  .github/SECURITY.md
  itou/templates/static/security/security.txt
  itou/www/security/views.py
  tests/www/test_security.py
Labels: modifié

#4467 Retirer le préfixe inutile des `test_list_prescriptions`
  tests/www/apply/__snapshots__/test_list_prescriptions.ambr
  tests/www/apply/test_list_prescriptions.py
Labels: no-changelog

#4470 Mise à jour de Pandas
  itou/companies/management/commands/_import_siae/utils.py
  pytest.ini
  requirements/base.in
  requirements/base.txt
  requirements/dev.txt
  requirements/test.txt
Labels: no-changelog

#4408 UX/UI - Wording : Clarification du help text + Ajout d'une majuscule à "Pays"
  itou/www/employee_record_views/forms.py
Labels: modifié

#4482 Admin : Permettre l’édition du champ `website` pour les organisations prescriptrices
  itou/prescribers/admin.py
Labels: modifié

#4475 GPS : Amélioration des performances de la recherche de bénéficiaires
  itou/users/models.py
Labels: modifié

#4473 Clarifier que l’envoi de fichier ne permet d’envoyer qu’un seul fichier [GEN-1889]
  itou/templates/utils/widgets/file_input.html
  tests/www/geiq_views/__snapshots__/tests.ambr
Labels: no-changelog

#4472 Utiliser la fixture settings dans les tests au lieu de modifier les settings django
  tests/conftest.py
Labels: no-changelog

#4468 Verifier que les prescripteurs habilités voient leurs candidatures comme éligibles à l’IAE
  tests/www/apply/test_list_prescriptions.py
Labels: no-changelog

#4485 Fiches salarié : Supprimer la voiture balai pour les erreurs 3436
  itou/employee_record/management/commands/sanitize_employee_records.py
  itou/employee_record/models.py
  tests/employee_record/test_models.py
  tests/employee_record/test_sanitize_employee_records.py
Labels: no-changelog

#4484 France Travail : Migrer les informations des organisations prescriptrices Pôle emploi vers France Travail
  itou/prescribers/migrations/0004_poleemploi_to_francetravail.py
Labels: modifié

#4486 Fiches salarié : Afficher la PK plutôt que le `__str__()` du candidat pour le modèle `EmployeeRecord()`
  itou/employee_record/models.py
  tests/employee_record/__snapshots__/test_transfer_employee_records.ambr
  tests/employee_record/test_transfer_employee_records.py
Labels: no-changelog

#3682 requirements: Remplacer `pip-tools` par `uv`
  Makefile
  requirements/base.txt
  requirements/dev.txt
  requirements/test.in
  requirements/test.txt
Labels: no-changelog

#4491 Pilotage : Ajout d'un champ pour identifier les entreprises dîtes "Convergence"
  itou/metabase/tables/companies.py
  tests/metabase/management/test_populate_metabase_emplois.py
Labels: ajouté

#4489 UX/UI: Mise a jour des liens nos reseaux sociaux
  itou/templates/layout/_footer.html
Labels: modifié
