Repository gip-inclusion/les-emplois, pull requests merged in 2024-12, with the labels that each got.

#5134 Tableau de bord : Utilisation de _snapshots_ pour tester le contenu de l'onglet "Statistiques"
  tests/www/dashboard/__snapshots__/test_dashboard_stats.ambr
  tests/www/dashboard/test_dashboard.py
  tests/www/dashboard/test_dashboard_stats.py
Labels: no-changelog

#5176 API: simplification de la vue index
  itou/www/api/urls.py
  itou/www/api/views.py
Labels: no-changelog

#5138 UX/UI: Ajout de la page "Présentation" de ma structure
  itou/static/img/illustration-siae-card-no-result.png
  itou/static/img/illustration-siae-card-no-result.svg
  itou/templates/apply/includes/accept_section.html
  itou/templates/apply/includes/list_job_applications.html
  itou/templates/apply/includes/siae_card.html
  itou/templates/apply/process_details_company.html
  itou/templates/apply/process_internal_transfer.html
  itou/templates/apply/submit/application/base.html
  itou/templates/apply/submit_base_two_columns.html
  itou/templates/approvals/prolongation_requests/list.html
  itou/templates/approvals/prolongation_requests/show.html
  itou/templates/companies/card.html
  itou/templates/companies/edit_siae.html
  itou/templates/companies/edit_siae_preview.html
  itou/templates/companies/includes/_company_info.html
  itou/templates/companies/job_description_card.html
  itou/templates/companies/job_description_list.html
  itou/templates/companies/members.html
  itou/templates/companies/overview.html
  itou/templates/companies/show_financial_annexes.html
  itou/templates/geiq/assessment_info_for_labor_inspector.html
  itou/templates/geiq/assessment_review.html
  itou/templates/job_seekers_views/includes/list_results.html
  itou/utils/templatetags/nav.py
  itou/www/companies_views/urls.py
  itou/www/companies_views/views.py
  tests/www/__snapshots__/test_layout.ambr
  tests/www/apply/__snapshots__/test_list_for_job_seeker.ambr
  tests/www/apply/__snapshots__/test_list_for_siae.ambr
  tests/www/apply/__snapshots__/test_list_prescriptions.ambr
  tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
  tests/www/companies_views/__snapshots__/test_card_views.ambr
  tests/www/companies_views/test_overview.py
  tests/www/geiq_views/__snapshots__/tests.ambr
  tests/www/job_seekers_views/__snapshots__/test_list.ambr
Labels: 1-recette-jetable, modifié

#5162 [Analytics] Suivi de l'Apdex et des requêtes non abouties (Sentry)
  config/settings/base.py
  config/settings/test.py
  itou/analytics/management/commands/collect_analytics_data.py
  itou/analytics/migrations/0001_initial.py
  itou/analytics/models.py
  itou/analytics/tech.py
  itou/utils/apis/sentry.py
  tests/analytics/test_collect_analytics_data_management_command.py
  tests/analytics/test_tech_metrics.py
  tests/conftest.py
  tests/utils/apis/test_sentry_api.py
Labels: no-changelog

#5198 Suppression d'une mixin inutilisée
  itou/www/job_seekers_views/views.py
Labels: no-changelog

#5203 Correction de la gestion des tokens lors de la fusion d'utilisateurs
  itou/www/itou_staff_views/merge_utils.py
  itou/www/itou_staff_views/views.py
  tests/www/itou_staff_views/tests.py
Labels: no-changelog

#5173 Corriger le message d’erreur de validate_birth_location [GEN-2265]
  itou/utils/validators.py
  tests/www/apply/test_process.py
  tests/www/employee_record_views/test_create.py
  tests/www/job_seekers_views/test_create.py
  tests/www/job_seekers_views/test_create_or_update.py
Labels: modifié, bug

#5207 Tech: nettoyage de code de rétrocompatibilité sur le parcours de création/mise à jour de candidat
  itou/www/job_seekers_views/views.py
Labels: no-changelog

#5208 Tech: nettoyage de code inutile
  itou/static/js/utils.js
Labels: no-changelog

#5206 Ajouter un lien vers la politique de confidentialité pour les utilisateurs connectés
  itou/templates/layout/_header_authenticated.html
  tests/www/__snapshots__/test_layout.ambr
Labels: modifié, bug

#5209 Tech: amélioration du code JS pour les swaps htmx
  itou/static/js/utils.js
Labels: no-changelog

#5233 MàJ l’emplacement du security.txt
  itou/www/security/views.py
Labels: no-changelog

#5211 Retirer du code mort des eligibility factories
  tests/eligibility/factories.py
Labels: no-changelog

#5212 Retirer du code mort de TestExportJobApplications.test_export
  tests/www/itou_staff_views/tests.py
Labels: no-changelog

#5214 changelog: From 2024-12-02 to 2024-12-08
  CHANGELOG.md
Labels: no-changelog

#5089 UX/UI: Traitement par lot - Vue tableau des candidatures
  itou/static/css/itou.css
  itou/static/js/utils.js
  itou/templates/apply/includes/job_applications_filters/offcanvas.html
  itou/templates/apply/includes/job_applications_filters/offcanvas_body.html
  itou/templates/apply/includes/list_job_applications.html
  itou/templates/apply/includes/list_tr.html
  itou/templates/apply/includes/list_view_switcher.html
  itou/templates/apply/list_for_job_seeker.html
  itou/templates/apply/list_for_siae.html
  itou/templates/apply/list_prescriptions.html
  itou/www/apply/views/list_views.py
  tests/www/apply/__snapshots__/test_list.ambr
  tests/www/apply/__snapshots__/test_list_for_job_seeker.ambr
  tests/www/apply/__snapshots__/test_list_for_siae.ambr
  tests/www/apply/__snapshots__/test_list_prescriptions.ambr
  tests/www/apply/test_list_for_job_seeker.py
  tests/www/apply/test_list_for_siae.py
  tests/www/apply/test_list_prescriptions.py
  tests/www/apply/test_templates.py
Labels: 1-recette-jetable, modifié

#5238 Tech : Stabilitation du test bagottant `test_is_searchable()`
  tests/www/search/tests.py
Labels: no-changelog

#5236 UX/UI: Suppression du bouton retour sur la page présentation des structures
  itou/templates/companies/overview.html
  itou/www/companies_views/views.py
Labels: no-changelog

#5247 [Employeur] Affichage du bouton de blocage des candidature pour les structures sans fiches de poste
  itou/templates/companies/job_description_list.html
  tests/www/companies_views/test_job_description_views.py
Labels: 1-recette-jetable, modifié

#5246 Tech: nettoyage HTML
  itou/templates/companies/job_description_list.html
Labels: no-changelog

#5244 UX/UI: Demande de retours prescripteurs habilités sur une refonte de leur espace [GEN-2297]
  itou/templates/dashboard/dashboard.html
Labels: ajouté

#5251 Fiches salarié : Fin de la maintenance pour "Récolter et transmettre les informations spécifiques aux EITI"
  itou/templates/includes/employee_records_disabled.html
  itou/templates/layout/base.html
Labels: no-changelog

#5250 Correction de l'envoi à brevo des listes d'utilisateur
  itou/users/management/commands/new_users_to_brevo.py
  tests/users/test_management_commands.py
Labels: no-changelog

#5253 Tech: restriction des URLs exposés par anymail
  config/urls.py
  tests/www/test_anymail.py
Labels: no-changelog

#5252 Correction du JS pour désactiver un champ
  itou/static/js/utils.js
Labels: no-changelog

#5241 UX/UI: Mise a jour du theme en version 2.5.0
  itou/utils/staticfiles.py
Labels: 1-recette-jetable, no-changelog

#5232 Simplifier AbstractEligibilityDiagnosisModel.is_valid
  itou/eligibility/models/common.py
Labels: no-changelog

#5126 Candidats: Ajout des champs commune et pays de naissance dans « Mon profil »
  itou/templates/dashboard/includes/edit_job_seeker_info_form.html
  itou/www/dashboard/forms.py
  tests/conftest.py
  tests/www/dashboard/__snapshots__/test_edit_job_seeker_info.ambr
  tests/www/dashboard/__snapshots__/test_edit_user_info.ambr
  tests/www/dashboard/test_edit_job_seeker_info.py
  tests/www/dashboard/test_edit_user_info.py
Labels: 1-recette-jetable, modifié

#5257 Définir la configuration de l’éditeur pour les JSON
  .editorconfig
Labels: no-changelog

#5256 UX/UI: Mise a jour du theme en version 2.5.3
  itou/templates/layout/base.html
  itou/utils/staticfiles.py
Labels: 1-recette-jetable, no-changelog

#5234 Retirer l’affichage du NIR pour les orienteurs qui n’ont pas créé le compte du candidat [GEN-2254]
  itou/templates/apply/includes/job_seeker_info.html
  tests/www/apply/test_process.py
  tests/www/job_seekers_views/__snapshots__/test_details.ambr
Labels: modifié

#5258 [matomo] Ajout du tracking matomo d'un nouveau tableau de bord du pilotage
  itou/metabase/management/commands/populate_metabase_matomo.py
  tests/metabase/management/__snapshots__/test_populate_metabase_matomo.ambr
  tests/metabase/management/test_populate_metabase_matomo.py
Labels: no-changelog

#5261 Tech: réduction du niveau de log des erreurs `GeocodingDataError`
  itou/common_apps/address/models.py
  itou/users/admin_forms.py
Labels: no-changelog

#5265 GPS: correction de la page de détail des bénéficiaire pour les orienteurs sans organisation.
  itou/www/gps/views.py
  tests/gps/test_views.py
Labels: modifié, bug

#5266 changelog: From 2024-12-09 to 2024-12-15
  CHANGELOG.md
Labels: no-changelog

#5262 Tech : Correction d'un test bagottant
  tests/users/factories.py
  tests/www/employee_record_views/test_create.py
Labels: no-changelog

#5267 Tech: correction du comportement de `member_required`
  itou/common_apps/organizations/models.py
  tests/companies/test_models.py
  tests/institutions/tests.py
  tests/prescribers/tests.py
  tests/www/apply/__snapshots__/test_submit.ambr
Labels: no-changelog

#5243 [Profil salarié] Diminution de la taille du badge Certifié
  itou/templates/apply/includes/selected_administrative_criteria_display.html
Labels: modifié

#5175 [Analytics] Récupération du taux de disponibilité de notre applicatif et de l'apdex (Updown)
  config/settings/base.py
  config/settings/test.py
  itou/analytics/migrations/0001_initial.py
  itou/analytics/models.py
  itou/analytics/tech.py
  itou/utils/apis/updown.py
  tests/analytics/test_collect_analytics_data_management_command.py
  tests/analytics/test_tech_metrics.py
  tests/conftest.py
  tests/utils/apis/test_updown.py
Labels: no-changelog

#4991 Inscription: Refonte de parcours pour les candidats [GEN-1569]
  itou/openid_connect/errors.py
  itou/openid_connect/france_connect/views.py
  itou/openid_connect/pe_connect/views.py
  itou/openid_connect/utils.py
  itou/static/css/itou.css
  itou/static/img/job_seeker_signup.png
  itou/static/img/job_seeker_signup.svg
  itou/static/img/job_seeker_signup_situation.svg
  itou/templates/signup/includes/france_connect_button.html
  itou/templates/signup/includes/login_reminder.html
  itou/templates/signup/includes/no_email_link.html
  itou/templates/signup/includes/submit_rgpd.html
  itou/templates/signup/job_seeker_nir.html
  itou/templates/signup/job_seeker_signup.html
  itou/templates/signup/job_seeker_signup_base.html
  itou/templates/signup/job_seeker_signup_credentials.html
  itou/templates/signup/job_seeker_situation.html
  itou/templates/utils/modal_includes/registration_failure.html
  itou/templates/utils/modal_includes/sso_email_conflict_registration_failure.html
  itou/templates/utils/modals.html
  itou/utils/constants.py
  itou/www/signup/errors.py
  itou/www/signup/forms.py
  itou/www/signup/urls.py
  itou/www/signup/views.py
  tests/openid_connect/pe_connect/tests.py
  tests/www/login/__snapshots__/tests.ambr
  tests/www/signup/__snapshots__/test_job_seeker.ambr
  tests/www/signup/test_job_seeker.py
  tests/www/welcoming_tour/tests.py
Labels: 1-recette-jetable, modifié

#5284 UX/UI: Corrections interface GEIQ
  itou/templates/dashboard/includes/employer_geiq_card.html
  itou/templates/dashboard/includes/labor_inspector_geiq_assessment_card.html
  itou/templates/geiq/assessment_info_for_employer.html
  itou/templates/geiq/assessment_info_for_labor_inspector.html
  itou/templates/geiq/assessment_review.html
  itou/templates/geiq/geiq_list.html
  itou/templates/geiq/includes/labor_inspector_assessment_state_badge.html
  itou/templates/geiq/includes/labor_inspector_assessment_state_badge_for_list.html
  itou/templates/geiq/includes/last_synced_at.html
  itou/templates/geiq/list_base.html
  tests/www/geiq_views/__snapshots__/tests.ambr
  tests/www/geiq_views/tests.py
Labels: modifié

#5283 Tests : Correction du bagotement de `TestCreateEmployeeRecordStep4()`
  tests/www/employee_record_views/test_create.py
Labels: no-changelog

#5292 Tech: ajout de décorateurs `check_user`
  itou/www/apply/views/edit_views.py
  itou/www/apply/views/process_views.py
  tests/www/apply/__snapshots__/test_process.ambr
  tests/www/apply/test_detail_rdv_insertion.py
  tests/www/apply/test_edit.py
  tests/www/apply/test_geiq.py
  tests/www/apply/test_list_rdv_insertion.py
  tests/www/apply/test_process.py
Labels: no-changelog

#5293 Tests: suppression du trait `job_seeker_with_address`
  tests/job_applications/factories.py
  tests/www/apply/test_list_prescriptions.py
  tests/www/apply/test_process.py
  tests/www/apply/test_submit.py
  tests/www/job_seekers_views/test_details.py
  tests/www/job_seekers_views/test_list.py
Labels: no-changelog

#5286 Connexion: Donner plus d'informations sur le choix du mot de passe pour un nouveau candidat
  config/settings/base.py
  itou/templates/signup/job_seeker_signup_credentials.html
  itou/utils/password_validation.py
  itou/www/signup/forms.py
  tests/users/factories.py
  tests/users/test_models.py
  tests/www/signup/__snapshots__/test_job_seeker.ambr
  tests/www/signup/__snapshots__/test_password.ambr
  tests/www/signup/test_job_seeker.py
  tests/www/signup/test_password.py
Labels: 1-recette-jetable, modifié

#5290 Inscription: Supprimer code temporaire pour le deploiement de la refonte du parcours d'inscription
  itou/openid_connect/utils.py
  itou/utils/constants.py
  itou/www/signup/urls.py
  itou/www/signup/views.py
  tests/www/signup/test_job_seeker.py
Labels: no-changelog

#5296 Nettoyage des valeurs initiales dans `CreateOrUpdateJobSeekerStep3Form`
  itou/www/job_seekers_views/views.py
Labels: no-changelog

#5294 UX/UI: Quelques améliorations pour faire plaisir a PageSpeed
  itou/static/img/home/bg-communaute-mobile.png
  itou/static/img/home/bg-communaute.png
  itou/static/img/home/illustration-01.png
  itou/static/img/home/illustration-02.png
  itou/templates/search/siaes_search_home.html
  itou/utils/staticfiles.py
Labels: 1-recette-jetable, modifié

#5291 Candidature: vérifier que l'utilisateur est toujours un membre actif de l'entreprise
  itou/job_applications/models.py
  tests/job_applications/tests.py
  tests/www/apply/__snapshots__/test_process.ambr
Labels: modifié

#5295 Pilotage : Récupérer la validité des diagnostic directement dans les emplois
  itou/metabase/tables/job_seekers.py
  tests/metabase/management/test_populate_metabase_emplois.py
Labels: no-changelog, pilotage

#5298 changelog: From 2024-12-16 to 2024-12-22
  CHANGELOG.md
Labels: no-changelog
