Repository gip-inclusion/les-emplois, pull requests merged in 2024-11, with the labels that each got.

#5026 changelog: From 2024-10-28 to 2024-11-03
  CHANGELOG.md
Labels: no-changelog

#5009 Candidature : Remplacer le bouton pour passer la recherche de NIR par un <a>
  itou/templates/apply/submit_step_check_job_seeker_nir.html
  itou/www/apply/views/submit_views.py
  tests/www/apply/test_submit.py
Labels: no-changelog

#5041 Connexion: AJout de remontée d'erreur en cas de problème de connexion avec ProConnect
  itou/openid_connect/models.py
  tests/openid_connect/pro_connect/tests.py
Labels: modifié

#5039 Retirer les campagnes de contrôle a posteriori de 2021 [GEN-2210]
  itou/siae_evaluations/migrations/0003_delete_2021_test_campaigns.py
Labels: supprimé

#5010 Inscription : Remplacer le bouton pour passer la recherche de NIR par un <a>
  itou/templates/signup/job_seeker_nir.html
  itou/www/signup/views.py
  tests/www/signup/test_job_seeker.py
Labels: no-changelog

#5040 UX/UI : Retrait de la banière d’expérimentation Maze sur la page des candidatures [GEN-2213]
  itou/templates/apply/list_for_siae.html
Labels: supprimé

#5042 GPS : Cacher les informations de l’entreprise fictive France Travail lors de la création d’un bénéficiaire [GEN-1925]
  itou/templates/apply/submit_base_two_columns.html
  tests/gps/test_create_beneficiary.py
Labels: modifié

#4983 API particulier : Respecter la fréquence d’appels et les workers web
  itou/eligibility/models/common.py
  itou/eligibility/tasks.py
  itou/utils/apis/api_particulier.py
  itou/utils/mocks/api_particulier.py
  tests/eligibility/test_iae.py
  tests/eligibility/test_tasks.py
  tests/utils/apis/test_api_particulier.py
  tests/www/apply/test_templates.py
Labels: modifié

#5019 Déplacer les vues, formulaires et URLs de vérification du NIR à `job_seekers_views`
  itou/templates/apply/submit_step_pending_authorization.html
  itou/templates/dashboard/includes/dashboard_title_content.html
  itou/templates/job_seekers_views/step_check_job_seeker_nir.html
  itou/www/apply/forms.py
  itou/www/apply/urls.py
  itou/www/apply/views/submit_views.py
  itou/www/job_seekers_views/forms.py
  itou/www/job_seekers_views/urls.py
  itou/www/job_seekers_views/views.py
  tests/gps/test_create_beneficiary.py
  tests/www/apply/test_forms.py
  tests/www/apply/test_submit.py
  tests/www/dashboard/test_dashboard.py
  tests/www/job_seekers_views/test_forms.py
Labels: no-changelog

#5047 Déplacer les vues, formulaires et URLs de recherche par email à `job_seekers_views`
  itou/www/apply/forms.py
  itou/www/apply/urls.py
  itou/www/apply/views/submit_views.py
  itou/www/job_seekers_views/forms.py
  itou/www/job_seekers_views/urls.py
  itou/www/job_seekers_views/views.py
  tests/gps/test_create_beneficiary.py
  tests/www/apply/test_submit.py
Labels: no-changelog

#5053 tests: détection d'erreur de rendu dans les templates Django
  tests/utils/test.py
Labels: no-changelog

#5050 Déplacer les vues, formulaires et URLs de création/MàJ de candidat vers `job_seekers_views`
  itou/templates/apply/submit/application/base.html
  itou/templates/job_seekers_views/check_job_seeker_info_for_hire.html
  itou/www/apply/forms.py
  itou/www/apply/urls.py
  itou/www/apply/views/submit_views.py
  itou/www/job_seekers_views/forms.py
  itou/www/job_seekers_views/urls.py
  itou/www/job_seekers_views/views.py
  tests/gps/test_create_beneficiary.py
  tests/www/apply/__snapshots__/test_submit.ambr
  tests/www/apply/test_forms.py
  tests/www/apply/test_submit.py
  tests/www/job_seekers_views/test_forms.py
Labels: no-changelog

#4912 UX/UI: Remplacer role=button par des <button>
  itou/templates/apply/includes/job_application_answers.html
  itou/templates/apply/list_of_available_exports.html
  itou/templates/approvals/includes/job_description_list.html
  itou/templates/approvals/suspend.html
  itou/templates/companies/includes/_company_info.html
  itou/templates/dashboard/edit_user_notifications.html
  itou/templates/employee_record/includes/create_step_3.html
  itou/templates/includes/demo_accounts.html
  itou/templates/prescribers/list_accredited_organizations.html
  itou/templates/siae_evaluations/evaluated_job_application.html
  itou/templates/siae_evaluations/includes/list_item.html
  itou/templates/users/details.html
  itou/templates/welcoming_tour/employer.html
  itou/templates/welcoming_tour/job_seeker.html
  itou/templates/welcoming_tour/prescriber.html
  itou/utils/templatetags/theme_inclusion.py
  tests/gps/__snapshots__/test_views.ambr
  tests/utils/__snapshots__/test_templatetags.ambr
  tests/utils/test_templatetags.py
  tests/www/apply/__snapshots__/test_list_for_siae.ambr
  tests/www/apply/__snapshots__/test_list_prescriptions.ambr
  tests/www/apply/test_templates.py
  tests/www/geiq_views/__snapshots__/tests.ambr
Labels: modifié

#5057 UX/UI: Suppression de la redirection de repli sur page nouveautés
  itou/templates/announcements/news.html
  itou/www/announcements/views.py
  tests/www/announcements/__snapshots__/test_views.ambr
  tests/www/announcements/test_views.py
Labels: no-changelog

#5059 Imports IAE: Empêcher la suppression d’entreprises dans plus de cas
  itou/companies/management/commands/_import_siae/utils.py
  tests/companies/test_import_siae_command.py
Labels: no-changelog

#5058 PASS IAE: utilisation du nouvel encart dans les vues de traitement des demandes de prolongation [GEN-2196]
  itou/templates/approvals/prolongation_requests/_status_box.html
  itou/templates/approvals/prolongation_requests/show.html
  tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
  tests/www/approvals_views/test_prolongation_requests.py
Labels: 1-recette-jetable, modifié

#5051 Déplacer les vues, formulaires et URLs de vérification des infos à `job_seekers_views`
  itou/www/apply/forms.py
  itou/www/apply/urls.py
  itou/www/apply/views/common.py
  itou/www/apply/views/submit_views.py
  itou/www/job_seekers_views/forms.py
  itou/www/job_seekers_views/urls.py
  itou/www/job_seekers_views/views.py
  tests/www/apply/test_submit.py
  tests/www/apply/test_submit_from_job_seekers_list.py
  tests/www/welcoming_tour/tests.py
Labels: no-changelog

#5021 UX/UI: Passer le bouton “Modifier” de la fiche de poste à droite
  itou/templates/companies/job_description_card.html
  tests/www/companies_views/__snapshots__/test_card_views.ambr
Labels: modifié

#5062 Ajouter Python 3.12 au CHANGELOG_breaking_changes.md
  CHANGELOG_breaking_changes.md
Labels: tech

#4985 Employeur : Correction pour l'entreprise utilisée pour les offres PEC
  itou/companies/migrations/0012_fix_ft_company.py
  itou/companies/models.py
Labels: no-changelog

#5063 Robustesse de TestJobDescriptionCardView::test_card_tally_url_with_user
  tests/www/companies_views/test_card_views.py
Labels: no-changelog

#5052 ProConnect: écraser les comptes avec le même email.
  itou/openid_connect/france_connect/views.py
  itou/openid_connect/inclusion_connect/views.py
  itou/openid_connect/models.py
  itou/openid_connect/pe_connect/views.py
  itou/openid_connect/pro_connect/models.py
  itou/openid_connect/pro_connect/views.py
  tests/openid_connect/france_connect/__snapshots__/tests.ambr
  tests/openid_connect/inclusion_connect/__snapshots__/tests.ambr
  tests/openid_connect/pe_connect/__snapshots__/tests.ambr
  tests/openid_connect/pro_connect/__snapshots__/tests.ambr
  tests/openid_connect/pro_connect/tests.py
Labels: tech

#5007 Statistiques: Indicateurs à suivre accessible aux membres de l'équipe des emplois [GEN-2190]
  itou/templates/dashboard/dashboard.html
  itou/templates/dashboard/includes/staff_stats_card.html
  itou/utils/apis/metabase.py
  itou/www/stats/urls.py
  itou/www/stats/utils.py
  itou/www/stats/views.py
  tests/www/stats/test_utils.py
  tests/www/stats/test_views.py
Labels: ajouté

#5023 UX/UI: Problème de rechargement des sliding-tabs apres reload htmx
  itou/static/js/sliding_tabs.js
  itou/templates/approvals/list.html
  itou/templates/companies/job_description_list.html
  itou/templates/companies/members.html
  itou/templates/companies/show_financial_annexes.html
  itou/templates/employee_record/list.html
Labels: modifié

#5086 requirements: add required setuptools
  requirements/base.txt
  requirements/dev.txt
  requirements/test.txt
Labels: no-changelog

#5070 changelog: From 2024-11-04 to 2024-11-10
  CHANGELOG.md
Labels: no-changelog

#5084 Supprimer les URLs de `apply` qui ont été déplacées à `job_seekers_views`
  itou/www/apply/urls.py
Labels: no-changelog

#5087 UX/UI: Améliorer les messages de déconnexion
  itou/templates/logout/warning.html
  tests/logout/__snapshots__/tests.ambr
Labels: no-changelog

#5068 Nettoyage des modèles d'invitations
  itou/invitations/admin.py
  itou/invitations/migrations/0002_fix_data.py
  itou/invitations/migrations/0003_remove_employerinvitation_accepted_and_more.py
  itou/invitations/models.py
  itou/templates/invitations_views/invitation_errors.html
  tests/invitations/factories.py
  tests/invitations/tests.py
  tests/www/invitations_views/test_company_accept.py
  tests/www/invitations_views/test_company_send.py
  tests/www/invitations_views/test_helpers.py
  tests/www/invitations_views/test_prescriber_organization.py
Labels: tech

#5090 Vie privée: modification de l'adresse mail contact pour demandes RGPD
  itou/templates/static/legal/privacy.html
Labels: modifié

#4676 Admin: ajout d'un bouton pour transférer des données entre entreprises [GEN-1527]
  itou/companies/admin.py
  itou/companies/admin_forms.py
  itou/companies/management/commands/move_company_data.py
  itou/companies/transfer.py
  itou/templates/admin/companies/change_company_form.html
  itou/templates/admin/companies/transfer_company.html
  itou/users/admin.py
  itou/users/admin_forms.py
  itou/utils/admin.py
  tests/companies/test_admin.py
  tests/companies/test_management_commands.py
Labels: 1-recette-jetable, ajouté

#4910 Admin: Recalculer automatiquement le geocoding des organisations, sauf cas particuliers [GEN-2023]
  itou/common_apps/organizations/models.py
  itou/companies/admin.py
  itou/companies/admin_forms.py
  itou/companies/migrations/0013_company_automatic_geocoding_update.py
  itou/institutions/admin.py
  itou/institutions/admin_forms.py
  itou/institutions/migrations/0008_institution_automatic_geocoding_update.py
  itou/prescribers/admin.py
  itou/prescribers/admin_forms.py
  itou/prescribers/migrations/0007_prescriberorganization_automatic_geocoding_update.py
  tests/api/__snapshots__/test_geiq.ambr
  tests/api/employee_record_api/__snapshots__/tests.ambr
  tests/api/siae_api/__snapshots__/tests.ambr
  tests/siae_evaluations/__snapshots__/test_models.ambr
  tests/users/__snapshots__/test_admin_views.ambr
  tests/www/apply/__snapshots__/test_list_for_siae.ambr
  tests/www/apply/__snapshots__/test_list_prescriptions.ambr
  tests/www/apply/__snapshots__/test_process.ambr
  tests/www/apply/__snapshots__/test_submit.ambr
  tests/www/approvals_views/__snapshots__/test_detail.ambr
  tests/www/approvals_views/__snapshots__/test_list.ambr
  tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
  tests/www/approvals_views/__snapshots__/test_suspend.ambr
  tests/www/companies_views/__snapshots__/test_card_views.ambr
  tests/www/companies_views/__snapshots__/test_job_description_views.ambr
  tests/www/dashboard/__snapshots__/test_dashboard.ambr
  tests/www/dashboard/__snapshots__/test_edit_job_seeker_info.ambr
  tests/www/dashboard/__snapshots__/test_edit_user_notifications.ambr
  tests/www/employee_record_views/__snapshots__/test_list.ambr
  tests/www/employees_views/__snapshots__/test_detail.ambr
  tests/www/itou_staff_views/__snapshots__/tests.ambr
  tests/www/job_seekers_views/__snapshots__/test_details.ambr
  tests/www/job_seekers_views/__snapshots__/test_list.ambr
  tests/www/search/__snapshots__/tests.ambr
  tests/www/siae_evaluations_views/__snapshots__/test_institutions_views.ambr
  tests/www/siae_evaluations_views/__snapshots__/test_siaes_views.ambr
  tests/www/signup/__snapshots__/test_siae.ambr
Labels: modifié

#5091 UX/UI: Mise à jour d'icônes dans la liste de prolongation
  itou/templates/approvals/prolongation_requests/list.html
  tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
Labels: modifié

#5098 Correction d'un test instable
  tests/www/search/tests.py
Labels: no-changelog

#5099 tests: ignorer les fichier `.DS_Store` dans le test `test_unused_templates`
  tests/test_consistency.py
Labels: no-changelog

#5069 GPS: Mise en page de la liste des bénéficiaires
  itou/templates/gps/includes/memberships_results.html
  itou/templates/gps/my_groups.html
  itou/templates/users/details.html
  tests/gps/__snapshots__/test_views.ambr
Labels: no-changelog

#5101 changelog: From 2024-11-11 to 2024-11-17
  CHANGELOG.md
Labels: no-changelog

#5102 Mini correctifs sur le journal des modifications
  CHANGELOG.md
Labels: no-changelog

#5092 Pilotage : Rajouter l'export de la table marché financier du flux IAE
  itou/metabase/management/commands/populate_metabase_fluxiae.py
Labels: no-changelog, pilotage

#5093 sentry : Configuration des moniteurs Cron depuis le code
  itou/employee_record/management/commands/transfer_employee_records.py
  itou/employee_record/management/commands/transfer_employee_records_updates.py
  itou/metabase/management/commands/populate_metabase_matomo.py
  itou/status/management/commands/run_status_probes.py
Labels: no-changelog

#5060 Retirer un import pytest non utilisé de tests.www.approvals_views.test_includes
  tests/www/approvals_views/test_includes.py
Labels: no-changelog

#5064 PASS IAE: utilisation du nouvel encart dans les candidatures [GEN-2120]
  itou/templates/apply/process_base.html
  itou/templates/apply/process_details_company.html
  itou/templates/apply/submit_base.html
  itou/templates/approvals/includes/prolongations_list.html
  itou/templates/approvals/includes/status.html
  tests/www/apply/__snapshots__/test_process.ambr
  tests/www/apply/test_process.py
  tests/www/apply/test_submit.py
  tests/www/approvals_views/test_includes.py
Labels: 1-recette-jetable, modifié

#5100 GPS: Permettre aux orienteurs d’accéder à GPS sur leur dashboard [GEN-2226]
  itou/templates/dashboard/includes/gps_card.html
  itou/templates/gps/my_groups.html
  itou/www/autocomplete/views.py
  itou/www/dashboard/views.py
  itou/www/gps/views.py
  tests/gps/__snapshots__/test_views.ambr
  tests/gps/test_views.py
  tests/www/dashboard/__snapshots__/test_dashboard.ambr
  tests/www/dashboard/test_dashboard.py
Labels: 1-recette-jetable, modifié

#5103 EA/EATT : Ajout d'un moniteur sentry pour l'import
  itou/companies/management/commands/import_ea_eatt.py
Labels: no-changelog

#5115 requirement: Fix bump setuptools from 75.4.0 to 75.5.0
  requirements/base.txt
  requirements/dev.txt
  requirements/test.txt
Labels: dependencies, python

#5116 PASS IAE: correction de la vue de détail pour d'anciens PASS liés à des candidatures acceptées sans date de début d'embauche
  itou/www/approvals_views/views.py
  tests/www/approvals_views/test_detail.py
Labels: modifié

#5117 Admin: Corriger le log de fusion de compte dans l'admin
  itou/www/itou_staff_views/merge_utils.py
  tests/www/itou_staff_views/tests.py
Labels: no-changelog

#5118 Envelopper async_certify_criteria dans une transaction
  itou/eligibility/tasks.py
Labels: no-changelog, bug

#5119 Stabilisation de TestListEmployeeRecords::test_employee_record_to_disable
  tests/www/employee_record_views/test_list.py
Labels: no-changelog

#5048 UX/UI : Amélioration de la navigation pour la gestion des annexes financières [GEN-2191]
  itou/templates/companies/select_financial_annex.html
  itou/templates/utils/templatetags/buttons_form.html
  itou/www/companies_views/views.py
  tests/utils/__snapshots__/test_templatetags.ambr
  tests/www/approvals_views/__snapshots__/test_suspend.ambr
  tests/www/employee_record_views/__snapshots__/test_add.ambr
  tests/www/employee_record_views/__snapshots__/test_create.ambr
Labels: modifié

#5095 Versionner les fichiers du stockage S3
  itou/files/management/commands/configure_bucket.py
  tests/conftest.py
  tests/files/tests.py
Labels: tech

#5094 UX/UI: Ajouter la date d'émission de la candidature dans l'onglet d'infos générales
  itou/templates/apply/includes/job_application_sender_info.html
Labels: modifié

#5061 Candidature: correction des règles d'affichage de l'onglet pour voir les rendez-vous d'une candidature
  itou/templates/apply/process_details_company.html
Labels: no-changelog

#5127 github : Correction des notifications de mise en prod
  .github/workflows/notify-slack.yml
Labels: modifié

#4945 Employeur : Historique des SIRET
  itou/companies/admin.py
  itou/companies/migrations/0014_company_fields_history_and_more.py
  itou/companies/models.py
  itou/utils/admin.py
  itou/utils/triggers.py
  tests/api/__snapshots__/test_geiq.ambr
  tests/api/employee_record_api/__snapshots__/tests.ambr
  tests/companies/test_models.py
  tests/siae_evaluations/__snapshots__/test_models.ambr
  tests/users/__snapshots__/test_admin_views.ambr
  tests/www/apply/__snapshots__/test_list_for_siae.ambr
  tests/www/apply/__snapshots__/test_list_prescriptions.ambr
  tests/www/apply/__snapshots__/test_process.ambr
  tests/www/apply/__snapshots__/test_submit.ambr
  tests/www/approvals_views/__snapshots__/test_detail.ambr
  tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
  tests/www/companies_views/__snapshots__/test_card_views.ambr
  tests/www/companies_views/__snapshots__/test_job_description_views.ambr
  tests/www/employee_record_views/__snapshots__/test_list.ambr
  tests/www/employees_views/__snapshots__/test_detail.ambr
  tests/www/itou_staff_views/__snapshots__/tests.ambr
  tests/www/job_seekers_views/__snapshots__/test_details.ambr
  tests/www/search/__snapshots__/tests.ambr
  tests/www/siae_evaluations_views/__snapshots__/test_institutions_views.ambr
  tests/www/siae_evaluations_views/__snapshots__/test_siaes_views.ambr
Labels: ajouté

#5131 Candidature: ajout d'un lien vers la fiche structure pour les utilisateurs n'appartenant pas à la structure [GEN-2234]
  itou/templates/apply/includes/job_application_info.html
  tests/www/apply/test_process.py
Labels: 1-recette-jetable, ajouté

#5132 Candidature: suppression de liens vers la fiche candidat ou entreprise dans la vue liste des candidatures [GEN-2257]
  itou/templates/apply/includes/list_card_body_company.html
  itou/templates/apply/includes/list_card_body_jobseeker.html
  tests/www/apply/__snapshots__/test_list.ambr
  tests/www/apply/test_list_prescriptions.py
Labels: modifié

#5137 Corriger la date logguée par notify_pole_emploi autour de minuit
  itou/approvals/models.py
Labels: no-changelog, bug

#5144 Candidature: suppression de code inutile
  itou/templates/apply/includes/list_card_body_jobseeker.html
  tests/www/apply/__snapshots__/test_list.ambr
Labels: no-changelog

#5128 Amélioration de l'interface de fusion de comptes
  itou/templates/itou_staff_views/merge_users.html
  itou/templates/itou_staff_views/merge_users_confirm.html
  itou/www/itou_staff_views/forms.py
  itou/www/itou_staff_views/merge_utils.py
  itou/www/itou_staff_views/urls.py
  itou/www/itou_staff_views/views.py
  tests/www/itou_staff_views/__snapshots__/tests.ambr
  tests/www/itou_staff_views/tests.py
Labels: no-changelog

#5140 Pagination : Passer de 50 à 20 résultats par page sur 6 listes dont les listes de candidatures
  itou/www/apply/views/list_views.py
  itou/www/approvals_views/views.py
  itou/www/companies_views/views.py
  itou/www/geiq_views/views.py
Labels: no-changelog

#5139 Statistiques : Mise à jour de la bannière utilisée par défaut
  itou/www/stats/views.py
Labels: no-changelog

#5147 changelog: From 2024-11-18 to 2024-11-24
  CHANGELOG.md
Labels: no-changelog

#5146 Création de compte candidat : déconnecter la recherche par email du parcours `apply`
  itou/www/job_seekers_views/urls.py
  itou/www/job_seekers_views/views.py
  tests/gps/test_create_beneficiary.py
  tests/www/apply/test_submit.py
  tests/www/job_seekers_views/test_create.py
Labels: no-changelog

#5161 Création de compte candidat : déconnecter la création du parcours `apply`
  itou/www/job_seekers_views/urls.py
  itou/www/job_seekers_views/views.py
  tests/gps/test_create_beneficiary.py
  tests/www/apply/test_submit.py
  tests/www/job_seekers_views/test_create.py
Labels: no-changelog

#5135 Ajout de RDV-Insertion à l'admin Django [GEN-2178]
  itou/rdv_insertion/admin.py
  itou/rdv_insertion/apps.py
Labels: ajouté

#5136 Mesurer l’usage de la fonctionnalité RDV-Insertion (Matomo) [GEN-2177]
  itou/templates/apply/includes/appointments.html
  tests/www/apply/__snapshots__/test_detail_rdv_insertion.ambr
Labels: ajouté

#5166 Ajout d'une bannière temporaire pour avertir de l'indisponibilité
  itou/templates/layout/base.html
Labels: modifié

#5168 Retrait de la bannière temporaire
  itou/templates/layout/base.html
Labels: no-changelog

#5164 UX/UI: ajustement de l'UI de copy to clipboard
  itou/templates/includes/copy_to_clipboard.html
  tests/gps/__snapshots__/test_views.ambr
  tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
  tests/www/companies_views/__snapshots__/test_card_views.ambr
  tests/www/geiq_views/__snapshots__/tests.ambr
  tests/www/job_seekers_views/__snapshots__/test_details.ambr
Labels: modifié

#5165 templates: déplacement de template vers `apply`
  itou/templates/apply/includes/job_application_box_for_user.html
  itou/templates/apply/includes/list_card_body.html
  itou/templates/apply/includes/selected_jobs_list.html
Labels: no-changelog

#5120 parse_response_to_soup: Retirer la forme courte de replace_in_attr
  tests/utils/test.py
  tests/utils/tests.py
  tests/www/apply/test_process.py
  tests/www/dashboard/test_dashboard.py
Labels: no-changelog

#5170 Correction de copy-pasta TestCreateForSender.test_check_nir_with_session
  tests/www/job_seekers_views/test_create.py
Labels: no-changelog

#5122 parse_response_to_soup: Amélioration de replace_in_attr
  tests/utils/test.py
  tests/utils/tests.py
Labels: no-changelog

#5096 UX/UI: Mise en avant du bouton "Postuler pour ce candidat"
  itou/templates/job_seekers_views/includes/list_results.html
  itou/templates/job_seekers_views/list.html
  itou/templates/layout/base.html
  itou/utils/staticfiles.py
  tests/www/apply/test_submit_from_job_seekers_list.py
  tests/www/job_seekers_views/__snapshots__/test_list.ambr
  tests/www/job_seekers_views/test_list.py
Labels: 1-recette-jetable, ajouté

#5171 Toujours définir update_job_seeker dans les templates job_seekers_views
  itou/www/job_seekers_views/views.py
  tests/gps/test_create_beneficiary.py
  tests/www/apply/test_submit.py
  tests/www/job_seekers_views/test_create.py
Labels: no-changelog

#5172 Toujours définir readonly_form dans job_seekers_views
  itou/www/job_seekers_views/views.py
  tests/gps/test_create_beneficiary.py
  tests/www/apply/test_submit.py
  tests/www/job_seekers_views/test_create.py
Labels: no-changelog

#5141 UX/UI: Ajustements des templates GPS
  itou/templates/gps/includes/memberships_results.html
  itou/templates/gps/join_group.html
  itou/templates/gps/my_groups.html
  tests/gps/__snapshots__/test_views.ambr
Labels: modifié
