Repository gip-inclusion/les-emplois, pull requests merged in 2024-09, with the labels that each got.

#4621 changelog: From 2024-08-26 to 2024-09-01
  CHANGELOG.md
Labels: no-changelog

#4626 Stabiliser tests/www/job_seekers_views/test_details.py::test_job_application_tab
  tests/www/job_seekers_views/test_details.py
Labels: no-changelog

#4616 Demandeur d’emploi: tri des agréments en DB
  itou/users/models.py
  tests/www/job_seekers_views/__snapshots__/test_details.ambr
Labels: no-changelog

#4627 tests: Définir la variable boost pour la pagination
  itou/templates/includes/pagination.html
  tests/www/approvals_views/test_list.py
Labels: no-changelog

#4645 pytest: Déplacer la config dans pyproject.toml
  pyproject.toml
  pytest.ini
Labels: no-changelog

#4650 Stabiliser tests/gps/test_views.py::test_beneficiary_details
  tests/gps/test_views.py
Labels: no-changelog

#4625 Admin : Clarifier le message de confirmation du passage en phase contradictoire du contrôle a posteriori des auto-prescriptions
  itou/siae_evaluations/admin.py
Labels: modifié

#4648 tests: Retirer des assertions dupliquées de test_populate_metabase_emplois
  tests/metabase/management/test_populate_metabase_emplois.py
Labels: no-changelog

#4651 tests: correction de JobSeekerFactory
  tests/users/factories.py
Labels: no-changelog

#4652 tests: correction de la date de naissance dans JobSeekerWithAddressFactory
  tests/api/__snapshots__/test_geiq.ambr
  tests/employee_record/__snapshots__/test_serializers.ambr
  tests/users/factories.py
Labels: no-changelog

#4622 Statistiques: Correction du nombre de members dans les exports
  itou/metabase/management/commands/populate_metabase_emplois.py
  itou/metabase/tables/companies.py
  itou/metabase/tables/organizations.py
  itou/metabase/tables/utils.py
  tests/metabase/management/test_populate_metabase_emplois.py
Labels: modifié

#4653 tests: fusion de JobSeekerWithAddressFactory dans JobSeekerFactory
  tests/api/__snapshots__/test_geiq.ambr
  tests/api/test_geiq.py
  tests/asp/test_models.py
  tests/common_apps/address/test_qpv_zrr_fields.py
  tests/employee_record/__snapshots__/test_serializers.ambr
  tests/gps/test_create_beneficiary.py
  tests/gps/test_views.py
  tests/job_applications/factories.py
  tests/scripts/test_users_geolocation.py
  tests/users/factories.py
  tests/users/test_management_commands.py
  tests/users/test_models.py
  tests/utils/test_immersion_facile.py
  tests/utils/tests.py
  tests/www/apply/test_forms.py
  tests/www/apply/test_geiq.py
  tests/www/apply/test_process.py
  tests/www/apply/test_submit.py
  tests/www/apply/test_templates.py
  tests/www/dashboard/test_dashboard.py
  tests/www/dashboard/test_edit_user_info.py
  tests/www/employee_record_views/test_create.py
  tests/www/signup/test_password.py
Labels: no-changelog

#4618 Prescripteur: ajout de la liste des candidats [GEN-1806]
  itou/templates/dashboard/includes/prescriber_job_seekers_card.html
  itou/templates/job_seekers_views/includes/list_counter.html
  itou/templates/job_seekers_views/includes/list_results.html
  itou/templates/job_seekers_views/list.html
  itou/utils/templatetags/nav.py
  itou/www/job_seekers_views/forms.py
  itou/www/job_seekers_views/urls.py
  itou/www/job_seekers_views/views.py
  tests/job_applications/factories.py
  tests/www/dashboard/test_dashboard.py
  tests/www/job_seekers_views/__snapshots__/test_list.ambr
  tests/www/job_seekers_views/test_list.py
Labels: 1-recette-jetable, ajouté

#4612 Prescripteur : Synchronisation des informations pour les agences France Travail depuis leur API
  itou/common_apps/address/models.py
  itou/prescribers/management/commands/sync_ft_organizations.py
  tests/common_apps/address/tests.py
Labels: ajouté

#4623 Admin : Permettre la modification des champs des e-mails
  itou/emails/migrations/0001_initial.py
  itou/emails/models.py
Labels: modifié

#4624 tests: Compter les requêtes SQL avec assertSnapshotQueries
  tests/utils/test.py
  tests/www/apply/__snapshots__/test_process.ambr
  tests/www/approvals_views/__snapshots__/test_detail.ambr
  tests/www/job_seekers_views/__snapshots__/test_details.ambr
  tests/www/job_seekers_views/__snapshots__/test_list.ambr
Labels: no-changelog

#4628 Demandeur d’emploi: Mettre à jour le conseiller FT toutes les 15 minutes
  clevercloud/cron.json
Labels: 1-recette-jetable, no-changelog

#4646 Corriger pytest --help
  Makefile
  tests/conftest.py
Labels: no-changelog

#4663 Stabiliser gps test_beneficiaries pour de vrai
  tests/gps/test_views.py
Labels: no-changelog

#4659 Utiliser des valeurs par défaut pour boost_{indicator,target} dans la pagination
  itou/templates/includes/pagination.html
Labels: no-changelog

#4655 doc: mentionner les identifiants du superutilisateur local
  README.md
  docs/developing.md
Labels: no-changelog

#4664 Prescripteur : Amélioration pour la synchro des organisations FT
  itou/prescribers/management/commands/sync_ft_organizations.py
Labels: no-changelog

#4669 Mise à jour des fixtures après le déplacement de la date de naissance
  itou/fixtures/django/05_test_users.json
  itou/fixtures/django/07_jobseeker_profile.json
Labels: no-changelog

#4671 Admin: retour du champ date de naissance dans la liste des utilisateurs
  itou/users/admin.py
Labels: no-changelog

#4666 users: suppression du champs date de naissance de la table des utilisateurs
  itou/users/migrations/0013_drop_users_user_birthdate_for_real.py
Labels: no-changelog

#4540 Diagnostic d'éligibilité : ajouter un type et supprimer `certifiable`
  itou/eligibility/admin.py
  itou/eligibility/data/administrative_criteria.json
  itou/eligibility/data/administrative_criteria_geiq.json
  itou/eligibility/enums.py
  itou/eligibility/migrations/0006_remove_administrativecriteria_certifiable_and_add_kind.py
  itou/eligibility/models/common.py
  tests/eligibility/test_iae.py
  tests/www/apply/__snapshots__/test_process.ambr
  tests/www/approvals_views/__snapshots__/test_detail.ambr
  tests/www/job_seekers_views/__snapshots__/test_details.ambr
Labels: modifié

#4673 Tech: simplification des migrations de suppression du champ date de naissance
  itou/users/migrations/0012_remove_user_birthdate.py
  itou/users/migrations/0013_drop_users_user_birthdate_for_real.py
Labels: no-changelog

#4654 Prescripteur: Permettre aux agents France Travail de rejoindre une agence même si l'agence indiquée par NEPTUNE n'existe pas sur les emplois. [GEN-1991]
  itou/openid_connect/inclusion_connect/views.py
  itou/utils/perms/middleware.py
  tests/openid_connect/inclusion_connect/tests.py
  tests/www/job_seekers_views/__snapshots__/test_details.ambr
  tests/www/job_seekers_views/__snapshots__/test_list.ambr
  tests/www/signup/test_prescriber.py
Labels: modifié

#4680 changelog: From 2024-09-02 to 2024-09-08
  CHANGELOG.md
Labels: no-changelog

#4677 Tech: suppression de code maintenant inutile
  itou/users/admin_forms.py
Labels: no-changelog

#4562 [GEN-129] UX/UI: page nouveautés
  config/settings/base.py
  config/settings/dev.py
  config/urls.py
  itou/communications/admin.py
  itou/communications/forms.py
  itou/communications/migrations/0003_alter_announcementitem_options_and_more.py
  itou/communications/models.py
  itou/files/forms.py
  itou/files/management/commands/configure_bucket.py
  itou/static/css/itou-admin.css
  itou/static/css/itou.css
  itou/templates/announcements/news.html
  itou/templates/layout/_header_help_dropdown_content.html
  itou/templates/layout/_news_modal.html
  itou/templates/utils/widgets/news_image_input.html
  itou/utils/constants.py
  itou/www/announcements/__init__.py
  itou/www/announcements/urls.py
  itou/www/announcements/views.py
  requirements/base.in
  requirements/base.txt
  requirements/dev.txt
  requirements/test.txt
  tests/communications/__snapshots__/test_campaigns.ambr
  tests/communications/factories.py
  tests/communications/test_cache.py
  tests/communications/test_campaigns.py
  tests/communications/test_models.py
  tests/conftest.py
  tests/files/tests.py
  tests/utils/tests.py
  tests/www/__snapshots__/test_layout.ambr
  tests/www/announcements/__init__.py
  tests/www/announcements/__snapshots__/test_views.ambr
  tests/www/announcements/test_views.py
Labels: 1-recette-jetable, ajouté

#4672 Admin : Lecture seule pour les `EmployeeRecordUpdateNotification()`
  itou/employee_record/admin.py
  itou/geiq/admin.py
  itou/utils/admin.py
Labels: modifié

#4647 UX/UI: Ajout du bouton "Imprimer” sur la page de détail Candidat
  itou/templates/apply/process_base.html
  itou/templates/approvals/printable_approval.html
  itou/templates/layout/_header.html
  itou/templates/layout/_header_authenticated.html
  itou/templates/layout/_header_print.html
  itou/templates/layout/base_printable.html
  itou/utils/staticfiles.py
Labels: 1-recette-jetable, ajouté

#4658 Amélioration de `TestWelcomingTour`
  tests/www/welcoming_tour/tests.py
Labels: no-changelog

#4667 UX/UI: Retirer l’item “tableau de bord” du menu “mon espace”
  itou/templates/layout/_header_user_dropdown_menu.html
  tests/www/__snapshots__/test_layout.ambr
Labels: modifié

#4699 UX/UI : Amélioration des performances d’accès au tableau de bord depuis le menu
  itou/utils/templatetags/nav.py
Labels: modifié

#4700 Statistiques: Correction d'un nom d'événement Matomo [GEN-1630]
  itou/templates/approvals/includes/job_applications.html
Labels: modifié

#4656 UX/UI : Relooker du composant alerte immersion facile [GEN-1835]
  itou/static/css/itou.css
  itou/static/img/dashboard/card-header-bg-immersion-facile.png
  itou/static/img/dashboard/card-header-bg-pilotage.png
  itou/templates/approvals/detail.html
  tests/www/approvals_views/__snapshots__/test_detail.ambr
Labels: 1-recette-jetable, no-changelog

#4682 Candidat: correction du paramètre fictif pour le filtre du nom de candidat dans la vue liste
  itou/www/job_seekers_views/forms.py
  tests/www/job_seekers_views/__snapshots__/test_list.ambr
Labels: modifié

#4674 Tech: correction de l'HTML généré dans la barre de navigation en anonyme
  itou/templates/utils/templatetags/nav_anonymous.html
Labels: no-changelog

#4704 Employeur: : Modification du message d'erreur sur le SIRET lors de la création d'antenne
  itou/www/companies_views/forms.py
  tests/www/companies_views/test_create_company_views.py
Labels: modifié

#4701 Tech: simplifications & optimisation de la page détail salarié/PASS IAE
  itou/approvals/models.py
  itou/www/approvals_views/views.py
  tests/www/approvals_views/__snapshots__/test_detail.ambr
Labels: no-changelog

#4707 tests: correction d'un test instable
  tests/communications/test_models.py
Labels: no-changelog

#4683 UX/UI: Déplacer le texte d'intro dans les 3 onglets “organisation”
  itou/templates/companies/members.html
  itou/templates/companies/show_financial_annexes.html
Labels: 1-recette-jetable, modifié

#4703 Simplifier un parametrize dans tests.job_applications
  tests/job_applications/tests.py
Labels: no-changelog

#4670 UX/UI: Toast à la d'Alert lorsque j’enregistre mes préférences de notifications
  itou/templates/dashboard/edit_user_notifications.html
  itou/www/dashboard/views.py
Labels: modifié

#4706 dependabot: Utiliser les versions mineures de Python au lieu des patchs
  runtime.txt
Labels: no-changelog

#4709 Mettre en CasseDeChameau JobApplication de la ForeignKey du modèle EmployeeRecord
  itou/employee_record/models.py
Labels: no-changelog

#4708 Tableau de bord : déplacer "déclarer une embauche" pour les GEIQ
  itou/templates/dashboard/dashboard.html
  itou/templates/dashboard/includes/employer_job_applications_card.html
  tests/www/dashboard/test_dashboard.py
Labels: modifié

#4711 UX/UI: renommer “organisation” en “structure” pour les employeurs
  itou/templates/companies/job_description_list.html
  itou/templates/companies/members.html
  itou/templates/companies/show_financial_annexes.html
  itou/templates/dashboard/includes/employer_company_card.html
  itou/utils/templatetags/nav.py
Labels: 1-recette-jetable, modifié

#4710 Connexion: Suppression d'un paramètre inutilisé
  itou/openid_connect/inclusion_connect/enums.py
  itou/www/signup/views.py
  tests/www/signup/test_prescriber.py
Labels: modifié

#4660 Vérifier que le fichier `cron.json` est correctement trié
  clevercloud/cron.json
  requirements/dev.txt
  requirements/test.in
  requirements/test.txt
  tests/test_consistency.py
Labels: no-changelog

#4718 Correctif d’export des candidatures sans diagnostic d’éligibilité
  itou/job_applications/export.py
  tests/www/apply/__snapshots__/test_list_for_siae.ambr
  tests/www/apply/test_list_for_siae.py
Labels: no-changelog

#4717 Simplifier Announcement test_start_date_conflict_constraint
  tests/communications/test_models.py
Labels: no-changelog

#4714 Fiches salarié : Création d'une commande d'utilitaires
  itou/employee_record/management/commands/employee_record.py
Labels: no-changelog

#4720 Simplifier le template tag nav en mode connecté
  itou/utils/templatetags/nav.py
Labels: no-changelog

#4649 Candidatures : Archiver les candidatures inactives depuis 180+ jours
  clevercloud/cron.json
  itou/fixtures/django/24_job_applications.json
  itou/job_applications/admin.py
  itou/job_applications/enums.py
  itou/job_applications/management/commands/archive_job_applications.py
  itou/job_applications/migrations/0009_jobapplication_archived_at.py
  itou/job_applications/migrations/0010_set_jobapplication_archived_at.py
  itou/job_applications/models.py
  itou/metabase/management/commands/populate_metabase_emplois.py
  itou/metabase/tables/job_applications.py
  itou/templates/apply/includes/buttons/archive.html
  itou/templates/apply/includes/job_applications_filters/offcanvas_body.html
  itou/templates/apply/includes/list_for_siae_title.html
  itou/templates/apply/includes/list_job_applications.html
  itou/templates/apply/includes/list_job_applications_title.html
  itou/templates/apply/includes/siae_hiring_actions.html
  itou/templates/apply/list_for_siae.html
  itou/templates/apply/list_prescriptions.html
  itou/templates/apply/process_base.html
  itou/utils/templatetags/job_applications.py
  itou/www/apply/forms.py
  itou/www/apply/urls.py
  itou/www/apply/views/edit_views.py
  itou/www/apply/views/list_views.py
  itou/www/apply/views/process_views.py
  itou/www/dashboard/views.py
  tests/job_applications/test_archive_job_applications.py
  tests/job_applications/tests.py
  tests/metabase/management/test_populate_metabase_emplois.py
  tests/www/apply/__snapshots__/test_list_for_siae.ambr
  tests/www/apply/__snapshots__/test_list_prescriptions.ambr
  tests/www/apply/__snapshots__/test_process.ambr
  tests/www/apply/test_edit.py
  tests/www/apply/test_list_for_siae.py
  tests/www/apply/test_list_prescriptions.py
  tests/www/apply/test_process.py
  tests/www/dashboard/test_dashboard.py
  tests/www/employees_views/__snapshots__/test_detail.ambr
  tests/www/job_seekers_views/__snapshots__/test_details.ambr
Labels: modifié

#4721 Corriger l’import de JobApplicationState dans des tests
  tests/job_applications/factories.py
  tests/job_applications/test_admin.py
Labels: no-changelog

#4722 Capturer les exceptions lors du rendu du template tag nav
  itou/utils/templatetags/nav.py
  tests/www/test_error.py
Labels: no-changelog

#4726 Candidatures : Désarchiver lors de l’acceptation
  itou/job_applications/models.py
  tests/job_applications/tests.py
Labels: modifié

#4731 Profil salarié: affichage du dernier PASS
  itou/www/employees_views/views.py
  tests/www/employees_views/__snapshots__/test_detail.ambr
  tests/www/employees_views/test_detail.py
Labels: no-changelog

#4702 Admin: PASS IAE cliquable dans la fiche salarié
  itou/employee_record/admin.py
  tests/employee_record/test_admin.py
Labels: ajouté

#4725 Pilotage : Ouverture des TB 346 et 330 à tout les conseils départementaux
  config/settings/base.py
  itou/templates/dashboard/includes/stats.html
  itou/www/dashboard/views.py
  itou/www/stats/utils.py
  itou/www/stats/views.py
  tests/www/stats/test_utils.py
  tests/www/stats/test_views.py
Labels: modifié

#4734 Tableau de bord : le bouton Postuler pour un candidat envoie directement dans la page des résultats de recherche
  itou/templates/apply/includes/list_job_applications.html
  itou/templates/apply/list_prescriptions.html
  itou/templates/dashboard/includes/employer_prescription_card.html
  itou/templates/dashboard/includes/prescriber_job_applications_card.html
Labels: modifié

#4724 Retirer la variable inutilisée VENV_REQUIREMENT du Makefile
  Makefile
Labels: no-changelog

#4737 Profil salarié: gérer l'absence de PASS IAE
  itou/templates/employees/detail.html
  itou/www/employees_views/views.py
  tests/www/employees_views/__snapshots__/test_detail.ambr
  tests/www/employees_views/test_detail.py
Labels: no-changelog

#4727 Ajout de l'ID RDV-Solidarités aux entreprises
  itou/companies/admin.py
  itou/companies/migrations/0007_company_rdv_solidarites_id.py
  itou/companies/migrations/0008_migrate_company_rdv_insertion_id_to_rdv_solidarites_id.py
  itou/companies/migrations/0009_remove_company_rdv_insertion_id.py
  itou/companies/models.py
  tests/www/apply/__snapshots__/test_process.ambr
  tests/www/approvals_views/__snapshots__/test_list.ambr
  tests/www/companies_views/__snapshots__/test_job_description_views.ambr
  tests/www/employee_record_views/__snapshots__/test_list.ambr
  tests/www/employees_views/__snapshots__/test_detail.ambr
  tests/www/job_seekers_views/__snapshots__/test_details.ambr
Labels: no-changelog

#4738 Suppression de l'ancienne colonne rdv_insertion_id pour de vrai
  itou/companies/migrations/0010_remove_company_rdv_insertion_id_for_real.py
Labels: no-changelog

#4739 Simplification des migrations companies relatives au renommage de rdv_insertion_id
  itou/companies/migrations/0009_remove_company_rdv_insertion_id.py
  itou/companies/migrations/0010_remove_company_rdv_insertion_id_for_real.py
Labels: no-changelog

#4563 Gestion des événements remontés par RDV-I via un webhook [GEN-1765]
  config/settings/base.py
  config/urls.py
  itou/rdv_insertion/migrations/0001_initial.py
  itou/rdv_insertion/models.py
  itou/utils/mocks/rdv_insertion.py
  itou/www/rdv_insertion/__init__.py
  itou/www/rdv_insertion/urls.py
  itou/www/rdv_insertion/views.py
  tests/rdv_insertion/factories.py
  tests/rdv_insertion/tests.py
  tests/www/apply/test_detail_rdv_insertion.py
  tests/www/rdv_insertion/__init__.py
  tests/www/rdv_insertion/tests.py
Labels: ajouté

#4762 Permettre à RDV-I d'envoyer une invitation pour les structures ayant plusieurs catégories de motif
  itou/www/apply/views/process_views.py
Labels: no-changelog

#4765 UX/UI: mise a jour du theme vers v2.1.9
  itou/utils/staticfiles.py
Labels: no-changelog

#4743 Correction du test test_apply_as_job_seeker_from_job_description
  tests/www/apply/test_submit.py
Labels: no-changelog

#4741 Retirer le champ SubmitJobApplicationForm.selected_jobs
  itou/templates/apply/submit/application/resume.html
  itou/www/apply/forms.py
  itou/www/apply/views/process_views.py
  itou/www/apply/views/submit_views.py
  tests/www/apply/test_submit.py
Labels: no-changelog

#4736 UX/UI : largeur réponsive pour les composants `.select2`
  itou/static/css/itou.css
Labels: no-changelog

#4768 Admin : Correction de l’affichage de l’état des candidatures contrôlée a posteriori
  itou/siae_evaluations/admin.py
  tests/siae_evaluations/test_admin.py
Labels: modifié

#4748 changelog: From 2024-09-09 to 2024-09-15
  CHANGELOG.md
Labels: no-changelog

#4661 Supprimer la colonne `JobApplication.hidden_for_company`
  itou/job_applications/migrations/0011_drop_hidden_for_company.py
Labels: no-changelog

#4740 Tableau de bord : Déplacer le contenu de l'onglet "Statistique" dans sa propre vue
  itou/templates/dashboard/dashboard.html
  itou/templates/dashboard/dashboard_stats.html
  itou/templates/dashboard/includes/dashboard_title_content.html
  itou/utils/templatetags/nav.py
  itou/www/dashboard/urls.py
  itou/www/dashboard/views.py
  tests/www/dashboard/test_dashboard.py
Labels: no-changelog, pilotage

#4771 Candidatures : Nettoyage des migrations après archivage
  itou/job_applications/migrations/0010_set_jobapplication_archived_at.py
  itou/job_applications/migrations/0011_drop_hidden_for_company.py
Labels: no-changelog

#4773 Statistiques : Correction de la page `/stats` pour les prescripteurs sans organisation
  itou/www/stats/views.py
Labels: no-changelog

#4735 Profil salarié: redonner l'accès aux anciens PASS IAE
  itou/templates/approvals/includes/list_card.html
  itou/www/employees_views/views.py
  tests/www/approvals_views/test_list.py
  tests/www/employees_views/test_detail.py
Labels: no-changelog

#4619 [GEN-1937] Connexion: Empêcher l'écrasement des comptes France Travail (courriels dupliqués)
  itou/openid_connect/models.py
  itou/openid_connect/pe_connect/views.py
  itou/templates/django_bootstrap5/messages.html
  itou/templates/layout/base.html
  itou/templates/utils/modal_includes/france_travail_registration_failure.html
  itou/templates/utils/modals.html
  itou/users/models.py
  itou/utils/templatetags/str_filters.py
  tests/openid_connect/pe_connect/tests.py
  tests/users/test_models.py
  tests/www/invitations_views/test_company_accept.py
  tests/www/invitations_views/test_prescriber_organization.py
  tests/www/signup/test_prescriber.py
  tests/www/signup/test_siae.py
Labels: modifié

#4744 Valider le métier sélectionné dans apply:start
  itou/www/apply/views/submit_views.py
  tests/www/apply/test_submit.py
Labels: no-changelog

#4774 tests: Préchauffer le cache de ContentType de manière globale
  tests/companies/test_admin.py
  tests/conftest.py
  tests/job_applications/test_transfer.py
  tests/users/test_admin_views.py
  tests/www/dashboard/test_edit_user_notifications.py
Labels: no-changelog

#4778 Réutiliser GEIQEligibilityDiagnosis.valid_diagnosis_for()
  itou/eligibility/models/geiq.py
Labels: no-changelog

#4733 Ajouter une règle resetdb au Makefile
  Makefile
  README.md
Labels: no-changelog

#4772 Statistiques : Correction du filtre des structures pour le TB 440
  itou/www/stats/views.py
Labels: no-changelog, pilotage

#4712 Employeur: conserver les filtres de la page de candidature après une action sur une candidature
  itou/www/apply/views/process_views.py
  tests/www/apply/__snapshots__/test_process.ambr
  tests/www/apply/test_process.py
Labels: 1-recette-jetable, modifié

#4779 UX/UI : Étendre la zone cliquable du bouton déconnexion
  itou/templates/layout/_header_user_dropdown_menu.html
  tests/www/__snapshots__/test_layout.ambr
Labels: no-changelog

#4781 Admin : Lecture seule pour le référentiel ASP des pays
  itou/asp/admin.py
Labels: no-changelog

#4790 admin: ajout du champ "archivé le" dans le détail des candidatures
  itou/job_applications/admin.py
Labels: no-changelog

#4789 changelog: From 2024-09-16 to 2024-09-22
  CHANGELOG.md
Labels: no-changelog

#4791 UX/UI : Fix la zone cliquable du bouton déconnexion
  itou/templates/layout/_header_user_dropdown_menu.html
  tests/www/__snapshots__/test_layout.ambr
Labels: no-changelog

#4792 Admin: Correction du refus d'habilitations
  itou/prescribers/admin.py
  tests/prescribers/tests.py
Labels: modifié

#4785 UX/UI : réparer la modale de confirmation d'embauche GEIQ sans aide
  itou/templates/apply/includes/buttons/accept.html
  itou/templates/apply/process_details_company.html
  tests/www/apply/test_geiq.py
Labels: no-changelog

#4808 Corriger la hauteur minimale de l'iframe livestorm
  itou/templates/layout/base.html
Labels: no-changelog

#4809 UX/UI: Corriger le titre du dashboard pour les "Candidat" et les "Orienteur seul"
  itou/templates/dashboard/includes/dashboard_title_content.html
Labels: 1-recette-jetable, modifié

#4810 Connexion : Empêcher les utilisateurs de se connecter à un autre compte du SSO partageant un courriel existant
  itou/openid_connect/france_connect/views.py
  itou/openid_connect/inclusion_connect/views.py
  itou/openid_connect/models.py
  itou/openid_connect/pe_connect/views.py
  itou/templates/utils/modal_includes/sso_email_conflict_registration_failure.html
  itou/templates/utils/modals.html
  tests/openid_connect/france_connect/tests.py
  tests/openid_connect/inclusion_connect/tests.py
Labels: no-changelog

#4812 UX/UI: Redondance du menu “mon espace”
  itou/templates/layout/_header_authenticated.html
  tests/www/__snapshots__/test_layout.ambr
Labels: no-changelog

#4815 tests: correction de test non lancés
  tests/www/approvals_views/test_detail.py
Labels: no-changelog

#4819 UX/UI: Harmoniser l'UI des pages “collaborateurs”
  itou/templates/institutions/members.html
  itou/templates/prescribers/members.html
Labels: modifié

#4732 Demandeur d’emploi : Ajout lieu de naissance dans le formulaire de création par un tiers [GEN-1944]
  itou/asp/forms.py
  itou/asp/models.py
  itou/templates/apply/includes/profile_infos.html
  itou/templates/apply/submit/create_or_update_job_seeker/step_1.html
  itou/users/forms.py
  itou/users/models.py
  itou/utils/validators.py
  itou/www/apply/forms.py
  itou/www/apply/views/submit_views.py
  itou/www/employee_record_views/forms.py
  tests/gps/test_create_beneficiary.py
  tests/www/apply/__snapshots__/test_submit.ambr
  tests/www/apply/test_submit.py
Labels: 1-recette-jetable, modifié

#4817 Pilotage : Éviter une erreur sentry
  itou/www/stats/views.py
  tests/www/stats/test_views.py
Labels: no-changelog, pilotage

#4820 Admin : Lecture seule pour les champs `siret`, `convention` et `auth_email` quand l'entreprise vient du flux IAE
  itou/companies/admin.py
Labels: modifié

#4821 assertSnapshotQueries: gestion d'une origine manquante
  tests/utils/test.py
Labels: no-changelog

#4825 PASS IAE: retour sur la page d'origine lors de l'annulation d'une modification de suspension
  itou/templates/approvals/suspension_update.html
  tests/www/approvals_views/test_suspend.py
Labels: modifié

#4829 UX/UI: l'input de recherche dépasse du viewport en mobile
  itou/templates/search/includes/prescribers_search_form.html
  itou/templates/search/includes/siaes_search_form.html
  tests/www/dashboard/__snapshots__/test_dashboard.ambr
Labels: no-changelog

#4746 Candidature : vérifier la cohérence du NIR avec la date de naissance et la civilité
  itou/users/models.py
  itou/www/apply/forms.py
  itou/www/dashboard/forms.py
  tests/users/factories.py
  tests/www/apply/test_submit.py
  tests/www/dashboard/test_edit_job_seeker_info.py
  tests/www/dashboard/test_edit_user_info.py
Labels: ajouté

#4823 Pilotage : Ouvrir le TB 440 à toutes les SIAE
  config/settings/base.py
  itou/templates/dashboard/includes/stats.html
  itou/www/dashboard/views.py
  itou/www/stats/utils.py
  itou/www/stats/views.py
  tests/www/stats/test_views.py
Labels: modifié, pilotage

#4826 Employeur : le champ `email` est facultatif dans les formulaires d'édition et de création de SIAE
  itou/www/companies_views/forms.py
  tests/www/companies_views/test_edit_company_views.py
Labels: modifié

#4831 Statistiques: Amélioration des mesures de conversion des actions sur les candidatures
  itou/templates/apply/process_postpone.html
Labels: modifié

#4835 PASS IAE: correction des boutons d'annulation/retour dans le processus de suppression d'une suspension
  itou/templates/approvals/suspension_delete.html
  itou/templates/approvals/suspension_update_enddate.html
  itou/www/approvals_views/views.py
  tests/www/approvals_views/__snapshots__/test_suspend.ambr
  tests/www/approvals_views/test_suspend.py
Labels: modifié

#4838 Performances: Correction de la durée de cache des campagnes de nouveautés
  itou/communications/cache.py
  tests/communications/test_cache.py
Labels: no-changelog

#4818 Admin : Empêcher la validation d’une habilitation avec le type autre [GEN-2114]
  itou/fixtures/django/14_prescribers.json
  itou/prescribers/admin.py
  itou/prescribers/admin_forms.py
  itou/prescribers/migrations/0006_prescriberorganization_prevent_validated_authorization_if_other.py
  itou/prescribers/models.py
  tests/prescribers/tests.py
  tests/www/prescribers_views/test_list.py
Labels: 1-recette-jetable, modifié

#4837 changelog: From 2024-09-23 to 2024-09-29
  CHANGELOG.md
Labels: no-changelog

#4839 Employeur: Les EA, EATT, OCPS ne peuvent pas candidater GEN-2118
  itou/templates/apply/list_for_siae.html
  itou/www/apply/views/list_views.py
  tests/www/apply/test_list_for_siae.py
Labels: modifié

#4840 UX/UI: Modifier les positionnement responsifs des boutons de la .c-box--action
  itou/templates/apply/includes/siae_hiring_actions.html
  itou/templates/companies/card.html
  itou/templates/companies/job_description_card.html
  itou/utils/staticfiles.py
  tests/www/companies_views/__snapshots__/test_card_views.ambr
Labels: no-changelog
