Repository gip-inclusion/les-emplois, pull requests merged in 2024-06, with the labels that each got.

#4140 Gérer l’attribut manquant `anymail_status` sur les emails envoyés en dev
  itou/utils/tasks.py
Labels: no-changelog

#4155 Correction de la durée du sprint
  CHANGELOG.md
  scripts/mkchangelog
Labels: no-changelog

#4159 Suppression du message d'alerte pour inviter à remplir en enquête sur la réattribution des candidatures d’un collaborateur
  itou/templates/prescribers/members.html
Labels: supprimé

#4142 Utiliser dbshell pour charger les fixtures SQL
  Makefile
Labels: no-changelog

#4166 Ajout d'un commentaire sur User.first_login
  itou/users/models.py
  tests/users/test_models.py
Labels: no-changelog

#4147 Admin : Ajout du reliquat pour les PASS IAE et de la durée pour les suspensions et prolongations
  itou/approvals/admin.py
Labels: ajouté

#4167 Pilotage : Encart de promotion du webinaire pour les ML / Cap emploi & les acteurs AHI pour 3 régions spécifiques
  itou/templates/dashboard/dashboard.html
  itou/www/dashboard/views.py
Labels: ajouté

#4168 Demandes de prolongation: Gérer le cas où l'entreprise déclarante n'existe plus
  itou/templates/approvals/prolongation_requests/list.html
  itou/templates/approvals/prolongation_requests/show.html
  tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
  tests/www/approvals_views/test_prolongation_requests.py
Labels: modifié

#4171 Statistiques: Correction d'un code de dénormalisation
  itou/users/apps.py
Labels: modifié

#4172 Ajout de select_related
  itou/www/approvals_views/views.py
  tests/www/approvals_views/test_suspend.py
Labels: no-changelog

#4096 UX/UI : Ajout de cta dans la zone de titre des liste de candidatures
  itou/templates/apply/includes/job_applications_export_button.html
  itou/templates/apply/includes/list_job_applications.html
  itou/templates/apply/list_for_prescriber.html
  itou/templates/apply/list_for_siae.html
  itou/templates/apply/list_of_available_exports.html
  tests/www/apply/__snapshots__/test_list.ambr
  tests/www/apply/__snapshots__/test_list_for_prescriber.ambr
  tests/www/apply/__snapshots__/test_list_for_siae.ambr
Labels: 1-recette-jetable, modifié

#4144 Documenter les variables d’environnement principales
  docs/environment.md
Labels: no-changelog

#4143 Définir des valeurs par défaut au lieu d’un .env
  .env.template
  .envrc
  CHANGELOG_breaking_changes.md
  README.md
  config/settings/dev.py
  config/settings/test.py
  docs/Docker.md
Labels: no-changelog

#4170 Admin: Améliorer les filtres de la section contrôle à posteriori
  itou/siae_evaluations/admin.py
Labels: ajouté

#4151 Limiter la suppression des SIAE inactives dans l’import ASP
  itou/companies/management/commands/_import_siae/utils.py
  tests/companies/test_import_siae_command.py
Labels: modifié

#4121 Demandeur d’emploi: empêcher la saisie d'un identifiant France Travail invalide
  itou/users/forms.py
  tests/www/dashboard/tests.py
Labels: 1-recette-jetable, modifié

#4146 UX/UI : Correction des cartes postes ouverts au recrutement sur mobile
  itou/templates/companies/includes/_card_jobdescription.html
  itou/templates/companies/includes/_list_siae_actives_jobs_row.html
  itou/utils/staticfiles.py
Labels: 1-recette-jetable, modifié

#4169 UX/UI: Ajout du lien "nouveautés" dans le menu du header
  itou/templates/layout/_header_nav_primary_items.html
  tests/www/__snapshots__/test_layout.ambr
Labels: modifié

#4175 tests: Définir des fixtures pour les réponses Mailjet
  tests/utils/test_emails.py
Labels: no-changelog

#4176 Corriger le REDIS_URL dans l’environnement docker
  config/settings/test.py
Labels: no-changelog

#4177 Corriger l’avertissement de docker-compose sur la version
  docker-compose.yml
Labels: no-changelog

#4156 Admin : Commenter l’utilisation de import_export pour les entreprises
  itou/companies/admin.py
Labels: no-changelog

#4126 Ajouter un utilitaire or_queries
  itou/approvals/models.py
  itou/utils/db.py
  itou/www/approvals_views/forms.py
Labels: no-changelog

#4179 Statistiques: Correction d'un code de dénormalisation
  itou/users/apps.py
  itou/users/models.py
Labels: no-changelog

#4182 Retirer le paramètre city de Matomo
  itou/utils/context_processors.py
  tests/utils/__snapshots__/tests.ambr
  tests/utils/tests.py
Labels: no-changelog

#4184 UI : Correction du texte du placeholder de recherche salarié dans la liste des salariés
  itou/www/approvals_views/forms.py
Labels: modifié

#4186 Tableau de bord: Retrait d'un section vide pour les institutions [GEN-1714]
  itou/templates/dashboard/dashboard.html
Labels: supprimé

#4189 changelog: From 2024-06-03 to 2024-06-09
  CHANGELOG.md
Labels: no-changelog

#4185 UX/UI: correction du lien d'aide à la conversion d'un pdf sur le widget d'upload de fichier
  itou/files/forms.py
Labels: modifié

#4174 Demandeur d’emploi : Mise à jour du label adresse e-mail candidat pour préciser qu’elle doit être personnelle
  itou/www/apply/forms.py
  itou/www/dashboard/forms.py
Labels: modifié

#4145 Recommander d’utiliser direnv pour le dev local
  .gitignore
  CHANGELOG_breaking_changes.md
  docs/developing.md
  docs/environment.md
Labels: no-changelog

#4196 Local: ignorer temporairement le .envrc.local pour éviter les erreurs d'inattention
  .gitignore
Labels: no-changelog

#4190 GEIQ: Ajout de nouveaux types d'institutions partenaires [GEN-1623]
  itou/fixtures/django/16_institutions.json
  itou/fixtures/django/17_institution_memberships.json
  itou/institutions/enums.py
  itou/institutions/migrations/0002_alter_institution_kind.py
  itou/www/stats/utils.py
  tests/www/stats/test_utils.py
  tests/www/stats/test_views.py
Labels: ajouté

#4203 django-hijack: correction du CSS
  itou/templates/hijack/notification.html
Labels: 1-recette-jetable, no-changelog

#4198 Ajout de GDAL dans le README
  README.md
Labels: no-changelog

#4058 GPS : création d'un bénéficiaire
  itou/gps/models.py
  itou/static/js/gps.js
  itou/templates/apply/includes/_submit_title.html
  itou/templates/apply/submit/create_or_update_job_seeker/step_1.html
  itou/templates/apply/submit/create_or_update_job_seeker/step_2.html
  itou/templates/apply/submit/create_or_update_job_seeker/step_3.html
  itou/templates/apply/submit/create_or_update_job_seeker/step_base.html
  itou/templates/apply/submit/create_or_update_job_seeker/step_end.html
  itou/templates/apply/submit_step_check_job_seeker_nir.html
  itou/templates/apply/submit_step_job_seeker.html
  itou/templates/dashboard/includes/gps_card.html
  itou/templates/gps/includes/confirm_modal.html
  itou/templates/gps/join_group.html
  itou/templates/gps/my_groups.html
  itou/www/apply/forms.py
  itou/www/apply/views/submit_views.py
  itou/www/gps/forms.py
  itou/www/gps/views.py
  tests/gps/__snapshots__/tests.ambr
  tests/gps/test_create_beneficiary.py
  tests/gps/tests.py
Labels: 1-recette-jetable, ajouté

#4208 Définir la valeur par défaut de REDIS_URL dans base.py
  config/settings/base.py
  config/settings/test.py
Labels: no-changelog

#4205 Lancement de GPS !
  config/settings/base.py
  itou/templates/dashboard/dashboard.html
  itou/utils/settings_context_processors.py
  itou/www/autocomplete/views.py
  itou/www/gps/views.py
  tests/gps/tests.py
Labels: modifié

#4209 Ajouter un espace entre deux mots dans l'encart info bleu du NIR [GEN-1750]
  itou/templates/apply/submit_step_check_job_seeker_nir.html
Labels: no-changelog

#4219 Modèle `User` : Rendre `public_id` vraiment unique
  itou/users/migrations/0008_fix_user_public_id.py
  itou/users/models.py
Labels: no-changelog

#4216 UX/UI : Retirer le bandeau d’information pour le passage aux fiches salarié des EITI
  itou/templates/dashboard/dashboard.html
  itou/www/dashboard/views.py
Labels: modifié

#4215 UX/UI : Remplacer l’alerte nouveauté du parcours déclarer une embauche/candidature par un texte explicatif
  itou/templates/apply/submit_step_check_job_seeker_nir.html
Labels: modifié

#4211 UX/UI : Transformer l’alerte d’information à la demande d’invitation prescripteur en du texte simple
  itou/templates/signup/prescriber_request_invitation.html
Labels: modifié

#4212 UX/UI : Déplacer l’alerte de prescriber_check_already_exists dans le bloc messages
  itou/templates/signup/prescriber_check_already_exists.html
Labels: no-changelog

#4220 Admin : Échanger les labels pour le filtre “Envoyé au fournisseur d’e-mail”
  itou/emails/admin.py
Labels: no-changelog

#4206 Pilotage: Donner accès au CD-31 de la Haute-Garonne l’accès à 2 TB privés
  config/settings/base.py
Labels: ajouté

#4183 Nettoyage des anciennes tâches d’envoi d’e-mail
  itou/utils/tasks.py
  tests/utils/test_emails.py
Labels: no-changelog, pending

#4210 UX/UI : Utiliser un bandeau d’alerte globale pour la refonte
  itou/templates/dashboard/dashboard.html
  itou/templates/layout/base.html
Labels: modifié

#4213 UX/UI : Remplacer l’alerte de la liste des organisations accréditées par le conseil départemental par un bloc d’information
  itou/templates/prescribers/list_accredited_organizations.html
Labels: modifié

#4214 UX/UI : Remplacer le bandeau promotionnel « Besoin d’un chiffre » par un bloc d’information
  itou/templates/apply/list_of_available_exports.html
  tests/www/apply/__snapshots__/test_list_for_prescriber.ambr
  tests/www/apply/__snapshots__/test_list_for_siae.ambr
Labels: modifié

#4217 Inscription : Retirer la page de confirmation d’email pour les candidats
  config/settings/base.py
  tests/www/signup/test_job_seeker.py
Labels: modifié

#4222 Correction d'une 500 sur la page de migration IC
  itou/www/dashboard/views.py
  tests/www/dashboard/tests.py
Labels: no-changelog

#4224 emails: Vérifier l’exception logguée en cas de JSONDecodeError
  tests/emails/test_tasks.py
Labels: no-changelog

#4226 Correction de la page de migration vers IC pour les utilisateurs non connectés
  itou/www/dashboard/views.py
  tests/www/dashboard/tests.py
Labels: no-changelog

#4227 Correction de create_fake_postcode
  tests/utils/test.py
Labels: no-changelog

#4187 Contrôle a posteriori: Ajout d'un lien contacter le support si un prescripteur souhaite retirer des justificatifs attendus lors du contrôle [GEN-8]
  itou/templates/siae_evaluations/evaluated_job_application.html
Labels: ajouté

#4230 Admin: Ajout de la date des candidatures dans certaines pages [GEN-1598]
  itou/approvals/admin.py
  itou/users/admin.py
Labels: ajouté

#4231 tests: correction d'un test instable
  tests/siae_evaluations/test_models.py
Labels: no-changelog

#4232 changelog: From 2024-06-10 to 2024-06-16
  CHANGELOG.md
Labels: no-changelog

#4221 Retirer un doublon de logging.setLevel dans emails.tasks
  itou/emails/tasks.py
Labels: no-changelog

#4228 GEIQ: correction d'une contrainte en base de données sur la cohérence Annexe/Niveau
  itou/eligibility/migrations/0002_remove_geiqadministrativecriteria_ac_level_annex_coherence_and_more.py
  itou/eligibility/models/geiq.py
  tests/eligibility/test_geiq.py
Labels: no-changelog

#4204 Retirer le fichier .envrc
  .envrc
Labels: no-changelog

#4243 Ajouter API_BAN_BASE_URL au CONNECT_SRC de la CSP dans les settings de dev
  config/settings/dev.py
Labels: no-changelog

#4245 GEIQ: renommage du rapport d'activité en document de synthèse
  itou/templates/geiq/assessment_info_for_employer.html
  itou/templates/geiq/assessment_info_for_labor_inspector.html
  tests/www/geiq_views/__snapshots__/tests.ambr
Labels: no-changelog

#4247 GEIQ: ajout d'un formulaire Tally pour recueillir le retour des employeurs GEIQ [GEN-1757]
  itou/templates/geiq/assessment_info_for_employer.html
Labels: 1-recette-jetable, no-changelog

#4241 tests: correction d'un test instable
  tests/institutions/tests.py
  tests/utils/tests.py
  tests/www/siae_evaluations_views/test_institutions_views.py
Labels: no-changelog

#4223 Utiliser le greffon django citext
  config/settings/base.py
  itou/emails/migrations/0001_initial.py
  itou/emails/models.py
  itou/external_data/migrations/0001_initial.py
  itou/external_data/models.py
  itou/users/migrations/0001_initial.py
  itou/users/models.py
  requirements/base.in
  requirements/base.txt
  requirements/dev.txt
  requirements/test.txt
Labels: no-changelog

#4252 tests: correction d'un test instable
  tests/www/geiq_views/tests.py
Labels: no-changelog

#4253 tests: correction d'un autre test instable
  tests/metabase/management/test_populate_metabase_emplois.py
Labels: no-changelog

#4250 GEIQ: renommage du champ "Rapport d'activité" en "Document de synthèse" dans l'admin également
  itou/geiq/migrations/0001_initial.py
  itou/geiq/models.py
Labels: no-changelog

#4242 Employeur: Ajout de marqueurs Matomo sur certains onglets
  itou/templates/dashboard/dashboard.html
Labels: ajouté

#4254 UX/UI : Fusionner les dropdown-item et dropdown-divider avec leur li
  itou/templates/approvals/includes/approvals_filters/expiry.html
  itou/templates/employee_record/includes/employee_record_filters/status.html
  itou/templates/layout/_header_nav_primary_items.html
  tests/www/__snapshots__/test_layout.ambr
Labels: modifié

#4258 tests: correction d'un autre test instable
  tests/siae_evaluations/test_models.py
Labels: no-changelog

#4260 API: amélioration de la génération des token des entreprises
  itou/api/migrations/0001_initial.py
  itou/api/models.py
Labels: no-changelog

#4257 GEIQ: ajout d'une notification aux DDETS/DREETS lors de la transmission d'un bilan d'exécution [GEN-1739]
  itou/communications/__init__.py
  itou/geiq/notifications.py
  itou/templates/geiq/email/to_institution_assessment_submitted_body.txt
  itou/templates/geiq/email/to_institution_assessment_submitted_subject.txt
  itou/www/geiq_views/views.py
  tests/www/geiq_views/tests.py
Labels: 1-recette-jetable, ajouté

#4264 tests: correction d'un test instable (oui, encore)
  tests/siae_evaluations/test_models.py
Labels: no-changelog

#4266 tests: Ajouter un commentaire à test_list_for_siae_filter_for_different_kind
  tests/www/apply/test_list_for_siae.py
Labels: no-changelog

#4267 Renommer le gabarit des filtres candidatures statut -> status
  itou/templates/apply/includes/job_applications_filters/status.html
  itou/templates/apply/list_for_job_seeker.html
  itou/templates/apply/list_for_siae.html
  itou/templates/apply/list_prescriptions.html
Labels: no-changelog

#4251 Demandes de prolongation: Gestion des chevauchements de date
  itou/www/approvals_views/views.py
  tests/www/approvals_views/test_prolongation_requests.py
Labels: modifié

#4268 Test: correction d'un test
  tests/www/geiq_views/tests.py
Labels: no-changelog

#4265 GPS : correctif pour les prescripteurs sans organisation
  itou/www/apply/views/submit_views.py
  itou/www/gps/forms.py
  itou/www/gps/views.py
  tests/gps/test_create_beneficiary.py
  tests/gps/tests.py
Labels: modifié

#4269 Fix test_employer_organizations flakiness
  tests/users/test_models.py
Labels: no-changelog

#4271 tests: màj de JobDescriptionSearchViewTest assertNumQueries
  tests/www/search/tests.py
Labels: no-changelog

#4274 API: utilisation d'un nouveau modèle pour nos tokens
  itou/api/admin.py
  itou/api/geiq/views.py
  itou/api/migrations/0002_alter_companyapitoken_companies_companytoken.py
  itou/api/models.py
  tests/api/test_geiq.py
Labels: no-changelog

#4256 Stats : Ouverture des stats CD à 4 nouveaux départements
  config/settings/base.py
Labels: no-changelog

#4261 GPS : dans la liste des membres d'un groupe, affichage du type de membre
  itou/gps/models.py
  itou/templates/users/includes/gps_group.html
  itou/users/models.py
  itou/www/users_views/views.py
  tests/gps/__snapshots__/tests.ambr
  tests/gps/tests.py
  tests/users/test_models.py
Labels: ajouté

#4259 Stats : Augmentation de la durée de vie de l'iframe de 10 à 30 minutes pour réduire la frustration utilisateur au niveau des filtres qui cessent de fonctionner après ce délai
  itou/utils/apis/metabase.py
Labels: no-changelog

#4283 Correction d'un test avec snapshot
  tests/gps/tests.py
Labels: no-changelog

#4275 API: suppression du modèle inutilisé CompanyApiToken
  itou/api/migrations/0003_delete_companyapitoken.py
  itou/api/models.py
Labels: no-changelog

#4244 Admin: Robustifier le changement d'état des candidatures
  itou/job_applications/admin.py
  itou/job_applications/admin_forms.py
  itou/job_applications/models.py
  itou/templates/admin/job_applications/change_form.html
  tests/job_applications/__snapshots__/test_admin.ambr
  tests/job_applications/test_admin.py
Labels: 1-recette-jetable, modifié

#4278 GPS: envoi d'événements à Matomo
  itou/static/js/gps.js
  itou/templates/gps/join_group.html
  itou/templates/gps/my_groups.html
Labels: ajouté

#4284 API: changement de nom du modèle CompanyToken
  itou/api/migrations/0002_alter_companyapitoken_companies_companytoken.py
  itou/api/models.py
Labels: no-changelog

#4281 changelog: From 2024-06-17 to 2024-06-23
  CHANGELOG.md
Labels: no-changelog

#4272 UX/UI : Simplifier la création des filtres de départements pour la recherche employeur / postes
  itou/common_apps/address/departments.py
  itou/templates/search/includes/siaes_search_filters_departments.html
  itou/templates/search/includes/siaes_search_results.html
  itou/templates/search/siaes_search_results.html
  itou/www/search/forms.py
  itou/www/search/views.py
  tests/www/search/tests.py
Labels: modifié

#4290 Recherche employeur: Correction d’un bug lors de la recherche de département adjacent
  itou/www/search/forms.py
  tests/www/search/tests.py
Labels: modifié

#4291 Utiliser une enum.StrEnum pour les ItouEnvironment
  config/settings/base.py
  config/settings/dev.py
  config/settings/test.py
  itou/files/management/commands/configure_bucket.py
  itou/utils/enums.py
Labels: no-changelog

#4255 Import IAE : Limiter la période de grâce pour le déconventionnement au premier semestre
  itou/companies/management/commands/_import_siae/convention.py
Labels: modifié

#4295 Utiliser un factory.Iterator() pour les départements des institutions
  tests/institutions/factories.py
Labels: no-changelog

#4294 github: ajout de la version de la CLI Clever
  .github/workflows/review-app-creation.yml
  .github/workflows/review-app-removal.yml
Labels: no-changelog

#4296 Recherche employeur: Correction d’un bug lors de la recherche en Corse
  itou/common_apps/address/departments.py
Labels: modifié

#4297 Mettre en cache les fichiers statiques pour la CI
  .github/workflows/ci.yml
Labels: no-changelog

#4292 Utiliser le mode async de Huey dans la plupart des environnements
  config/settings/base.py
  config/settings/test.py
Labels: 1-recette-jetable, no-changelog

#4270 API: ajout des filtres `departement` et `departement_postes` sur la route `/api/v1/siaes/`
  itou/api/siae_api/viewsets.py
  tests/api/siae_api/tests.py
Labels: ajouté

#4299 Correction d’une typo pour l’activation du mode immédiat de Huey
  config/settings/base.py
Labels: no-changelog

#4246 Statistiques: Ajout d'une contrainte en base de donnée sur le champ `processed_at` des candidatures
  itou/job_applications/migrations/0005_fill_jobapplication_processed_at.py
  itou/job_applications/migrations/0006_jobapplication_processed_coherence.py
  itou/job_applications/models.py
  tests/job_applications/test_transfer.py
Labels: ajouté

#4262 Réordonner pull_request_template.md
  .github/pull_request_template.md
Labels: no-changelog

#4285 Candidature: ajout d'une enquête Tally auprès des prescripteurs habilités sur l'expérience candidat [GEN-1681]
  itou/templates/apply/list_prescriptions.html
Labels: 1-recette-jetable, ajouté

#4288 Candidature: ajout d'une enquête Tally auprès des employeurs pour connaître leurs pratiques quant aux candidatures faites par des candidats en autonomie [GEN-1680]
  itou/templates/apply/list_for_siae.html
Labels: 1-recette-jetable, ajouté

#4298 GEIQ: ajout de fixture pour les bilans d'exécution
  itou/fixtures/django/28_implementation_assessment_campaigns.json
  itou/fixtures/django/29_implementation_assessment.json
  itou/fixtures/django/dumpdata.sh
Labels: no-changelog

#4301 Sécurité : Toujours préfixer le sujet des emails par l’environnement depuis lequel ils sont envoyés
  itou/utils/emails.py
  tests/approvals/__snapshots__/test_notifications.ambr
  tests/common_apps/organizations/tests.py
  tests/companies/test_import_siae_command.py
  tests/job_applications/test_transfer.py
  tests/job_applications/tests.py
  tests/siae_evaluations/test_emails.py
  tests/siae_evaluations/test_management_commands.py
  tests/siae_evaluations/test_models.py
  tests/www/approvals_views/test_prolongation.py
  tests/www/companies_views/test_views.py
  tests/www/prescribers_views/test_members.py
  tests/www/siae_evaluations_views/test_institutions_views.py
  tests/www/siae_evaluations_views/test_siaes_views.py
Labels: modifié

#4282 Sécurité : Créer un environnement pour le programme de bug bounty
  config/settings/base.py
  itou/templates/includes/demo_accounts.html
  itou/templates/layout/base.html
  itou/utils/enums.py
Labels: no-changelog

#4304 API: utilisation de clefs plus longues pour nos tokens
  itou/api/migrations/0001_initial.py
  itou/api/migrations/0002_alter_companyapitoken_companies_companytoken.py
  itou/api/models.py
Labels: no-changelog

#4302 Supprimer le contrôle des auto-prescriptions sélectionnées par erreur
  delete-2023-evaluation-invalid-job-apps
  itou/templates/siae_evaluations/email/to_siae_canceled_evaluation_body.txt
  itou/templates/siae_evaluations/email/to_siae_canceled_evaluation_subject.txt
  itou/templates/siae_evaluations/email/to_siae_removed_auto_prescriptions_body.txt
  itou/templates/siae_evaluations/email/to_siae_removed_auto_prescriptions_subject.txt
Labels: no-changelog

#4305 Revert "Delete invalid job applications from 2023 siae evaluations"
  delete-2023-evaluation-invalid-job-apps
  itou/templates/siae_evaluations/email/to_siae_canceled_evaluation_body.txt
  itou/templates/siae_evaluations/email/to_siae_canceled_evaluation_subject.txt
  itou/templates/siae_evaluations/email/to_siae_removed_auto_prescriptions_body.txt
  itou/templates/siae_evaluations/email/to_siae_removed_auto_prescriptions_subject.txt
Labels: no-changelog

#4300 logs: ajout de l'identifiant du token dans nos logs Datadog
  itou/api/models.py
  itou/utils/logging.py
  tests/api/test_geiq.py
Labels: no-changelog

#4303 Admin : Ajouter une icône à la partie administration du site
  itou/templates/admin/base_site.html
Labels: modifié

#4312 Empêcher les déploiements concurrent de recettes jetables
  .github/workflows/review-app-creation.yml
Labels: no-changelog

#4316 Sécurité : Empêcher une injection HTML (et éventuellement XSS) sur la page de login
  itou/utils/templatetags/redirection_fields.py
  tests/utils/tests.py
Labels: modifié

#4313 UX/UI : Partager le template de btn-dropdown-filter pour les checkboxes
  itou/templates/apply/includes/job_applications_filters/departments.html
  itou/templates/apply/includes/job_applications_filters/selected_jobs.html
  itou/templates/apply/includes/job_applications_filters/status.html
  itou/templates/includes/btn_dropdown_filter/checkboxes.html
Labels: no-changelog

#4307 API: ajout de token de département avec leur authentification [GEN-223]
  itou/api/admin.py
  itou/api/auth.py
  itou/api/migrations/0004_departmenttoken.py
  itou/api/models.py
  itou/api/siae_api/viewsets.py
  tests/api/siae_api/tests.py
Labels: ajouté

#4273 Modification de la colonne motif_de_refus : recuperer la clé au lieu du label
  itou/metabase/management/commands/populate_metabase_emplois.py
  itou/metabase/tables/job_applications.py
  tests/metabase/management/test_populate_metabase_emplois.py
  tests/metabase/test_job_applications.py
Labels: no-changelog

#4314 UX/UI: Partager le gabarit des champs réductibles offcanvas
  itou/templates/apply/includes/job_applications_filters/criteria.html
  itou/templates/apply/includes/job_applications_filters/departments.html
  itou/templates/apply/includes/job_applications_filters/eligibility_validated.html
  itou/templates/apply/includes/job_applications_filters/field_collapse.html
  itou/templates/apply/includes/job_applications_filters/field_collapse_checkbox.html
  itou/templates/apply/includes/job_applications_filters/offcanvas_body.html
  itou/templates/apply/includes/job_applications_filters/selected_jobs.html
  tests/www/apply/__snapshots__/test_list_for_siae.ambr
  tests/www/apply/__snapshots__/test_list_prescriptions.ambr
Labels: no-changelog

#4317 API: amélioration de l'admin des jetons d'entreprise
  itou/api/admin.py
  itou/api/migrations/0002_alter_companyapitoken_companies_companytoken.py
  itou/api/models.py
Labels: no-changelog

#4318 Tableau de bord : ne pas afficher GPS aux orienteurs
  itou/templates/dashboard/dashboard.html
  itou/www/autocomplete/views.py
  itou/www/dashboard/views.py
  itou/www/gps/views.py
  itou/www/users_views/views.py
  tests/gps/__snapshots__/test_views.ambr
  tests/gps/test_create_beneficiary.py
  tests/gps/test_views.py
  tests/prescribers/factories.py
  tests/www/dashboard/tests.py
Labels: 1-recette-jetable, modifié

#4321 Statistiques: Correction de l'export des comptes de collaborateurs
  itou/metabase/management/commands/populate_metabase_emplois.py
  tests/metabase/management/test_populate_metabase_emplois.py
Labels: modifié

#4322 Admin: Correction de permissions
  itou/templates/admin/job_applications/change_form.html
  tests/job_applications/__snapshots__/test_admin.ambr
  tests/job_applications/test_admin.py
Labels: modifié
