Repository gip-inclusion/les-emplois, pull requests merged in 2024-05, with the labels that each got.

#3999 docker: Utiliser `unless-stopped` plutôt que `always`
  docker-compose.yml
Labels: no-changelog

#4000 pilotage : Supprimer les rubriques communautés des pages TB privés
  itou/templates/stats/stats.html
Labels: supprimé

#4002 Lire l’ID Matomo du site depuis les variables d’environnement
  .env.template
  config/settings/base.py
  itou/utils/constants.py
  itou/utils/settings_context_processors.py
Labels: no-changelog

#4005 [DataInclusion] Ne pas appeler l'API quand l'URL n'est pas définie
  itou/www/companies_views/views.py
Labels: modifié

#3974 Réduction de nombre de permutations des subtest apply
  tests/www/apply/test_process.py
Labels: no-changelog

#4017 Ajout du siret à l'export des rejet d'api PE [GEN-1585]
  itou/approvals/management/commands/export_pe_api_rejections.py
  tests/approvals/test_management_commands.py
Labels: modifié

#3729 Nettoyer des restes de PE Connect dans allauth
  itou/templates/socialaccount/authentication_error.html
  itou/templates/socialaccount/login_cancelled.html
  itou/users/migrations/0005_clean_pe_connect_users_from_allauth.py
Labels: no-changelog

#4001 Recherche employeur : amélioration de l’affichage lorsque le formulaire de recherche est invalide
  itou/www/search/views.py
  tests/www/search/tests.py
Labels: modifié

#4012 Simplifier les vérifications de application_geiq_eligibility
  itou/www/apply/views/submit_views.py
  itou/www/geiq_eligibility_views/forms.py
  tests/www/apply/test_submit.py
  tests/www/geiq_eligibility_views/test_forms.py
Labels: no-changelog

#4021 Correction d’une typo dans les analytics du bouton copier de job_seeker_info
  itou/templates/apply/includes/job_seeker_info.html
Labels: no-changelog

#3997 UX/UI : Filtrer les salariés et PASS IAE de manière plus dynamique
  itou/static/js/approvals_filters.js
  itou/templates/approvals/includes/list_results.html
  itou/templates/approvals/list.html
  itou/www/approvals_views/views.py
  tests/www/approvals_views/test_list.py
Labels: 1-recette-jetable, modifié

#4011 Renommer des siae en company dans le contexte de GEIQ
  itou/www/apply/views/common.py
  itou/www/apply/views/process_views.py
Labels: no-changelog

#3998 Gérer les variables matomo manquantes dans les tests
  itou/templates/layout/base.html
  itou/utils/context_processors.py
  itou/www/error.py
  tests/approvals/tests.py
  tests/users/test_admin_views.py
  tests/utils/__snapshots__/tests.ambr
  tests/utils/tests.py
  tests/www/test_error.py
Labels: no-changelog

#4009 Recherche prescripteur : amélioration de la page lorsque le formulaire est invalide
  itou/templates/search/prescribers_search_results.html
  itou/www/search/views.py
  tests/www/search/tests.py
Labels: modifié

#4018 github: Also (re)run `require-labels` on labels changes
  .github/workflows/require-labels.yml
Labels: no-changelog

#4016 [GEN-274] Ajout d’une explication de l’algorithme de tri dans la liste des entreprises et postes recherchés
  itou/templates/search/includes/siaes_search_top.html
Labels: 1-recette-jetable, ajouté

#4020 Formatage d'adresse : Gérer le cas où la BAN ne connais pas le code postal de la commune (ie. Saint-Martin)
  itou/asp/fixtures/test_asp_INSEE_communes_factory.json
  itou/common_apps/address/format.py
  tests/asp/__snapshots__/test_sync_communes.ambr
  tests/asp/test_communes.py
  tests/users/test_models.py
  tests/www/autocomplete/tests.py
Labels: modifié

#4027 changelog: From 2024-04-29 to 2024-05-05
  CHANGELOG.md
Labels: no-changelog

#4024 Désactiver GPS en démo
  config/settings/base.py
Labels: modifié

#4028 Résolution d'un problème entraînant une erreur 500 en admin
  itou/users/admin.py
Labels: no-changelog

#4014 UX/UI : Filtrer les prescripteurs habilités de manière plus dynamique
  itou/templates/search/includes/prescribers_search_results.html
  itou/templates/search/includes/prescribers_search_summary.html
  itou/templates/search/includes/prescribers_search_title.html
  itou/templates/search/prescribers_search_results.html
  itou/www/search/views.py
  tests/www/search/tests.py
Labels: 1-recette-jetable, modifié

#4022 Statistiques : La Direction Territoriale Alpes de Haute Provence et Hautes Alpes supervise 2 départements (04, 05)
  itou/prescribers/enums.py
Labels: modifié

#4007 Mettre à jour le changelog lorsque l’action est lancée à nouveau
  scripts/mkchangelog
Labels: no-changelog

#4038 App `address` : Renommer `format_address()`
  itou/common_apps/address/format.py
  itou/users/models.py
  tests/asp/test_models.py
  tests/users/test_models.py
Labels: no-changelog

#4040 Import ASP : Nom plus explicite pour le point de montage contenant les fichiers de la DGEFP
  scripts/imports-asp.sh
Labels: no-changelog

#4030 Configurer `ruff` pour qu'il corrige les erreurs automatiquement
  .pre-commit-config.yaml
Labels: no-changelog

#4043 Contrôle a posteriori : Modification du champ preuve dans l'admin en RO
  itou/siae_evaluations/admin.py
Labels: no-changelog

#4041 Import ASP : Séparer EA/EATT et IAE
  scripts/import-ea-eatt.sh
  scripts/import-iae.sh
  scripts/imports-asp.sh
Labels: no-changelog

#4045 Analytics: Ajouter le type d’utilisateur et le type d’organisation à Matomo [GEN-249]
  itou/templates/layout/base.html
  tests/utils/__snapshots__/tests.ambr
Labels: no-changelog

#4042 API : Indiquer de filtrer par SIRET sur l’API `employee-records` et non `candidats_list`
  itou/templates/dashboard/api_token.html
Labels: modifié

#4033 Éviter les recoupements entre les semaines du journal des modifications
  scripts/mkchangelog
Labels: no-changelog

#4053 Candidatures : Utiliser un autre domaine pour le lien vers le CV [GEN-1628]
  itou/job_applications/migrations/0003_workaround_clever_dangerous_domain_ms.py
Labels: modifié

#4054 Tests - Listes des candidatures : Réorganisation et nettoyage
  tests/www/apply/__snapshots__/test_list.ambr
  tests/www/apply/__snapshots__/test_list_for_prescriber.ambr
  tests/www/apply/__snapshots__/test_list_for_siae.ambr
  tests/www/apply/test_list.py
  tests/www/apply/test_list_for_job_seeker.py
  tests/www/apply/test_list_for_prescriber.py
  tests/www/apply/test_list_for_siae.py
Labels: no-changelog

#4051 MàJ les instructions pour lancer les imports IAE / EA-EATT
  scripts/create-fast-machine.sh
Labels: no-changelog

#4047 Admin : Éviter les doublons lorsqu’on liste les PASS IAE d’une entreprise
  itou/approvals/models.py
  tests/approvals/test_admin.py
Labels: modifié

#4052 Correction d’une typo dans latest_common_approval
  itou/users/models.py
  tests/users/test_models.py
Labels: no-changelog

#4061 [GPS] L'autocomplete des utilisateurs ne devrait pas être accessible à tout le monde
  itou/www/autocomplete/views.py
Labels: 1-recette-jetable, no-changelog

#4049 Trier les entrées du changelog en ignorant la casse de caractère
  scripts/mkchangelog
Labels: no-changelog

#4046 Documenter que matomoMore s’exécute après trackPageView
  itou/templates/layout/base.html
Labels: no-changelog

#4064 Inscription: correction du chemin d'accès à l'API SIRENE de l'INSEE
  config/settings/base.py
Labels: modifié

#4062 Suppression de code dupliqué pour l'affichage des toasts
  itou/templates/layout/base.html
Labels: no-changelog

#4074 Pilotage : Afficher les stats de la campagne de contrôle a posteriori 2024 pour la DGEFP
  itou/templates/dashboard/includes/stats.html
Labels: modifié

#4063 Passer à `ruff format`
  .pre-commit-config.yaml
  .vscode/extensions.json
  .vscode/settings.json
  Makefile
  docs/coding-style.md
  itou/analytics/migrations/0001_initial.py
  itou/antivirus/migrations/0001_initial.py
  itou/api/migrations/0001_initial.py
  itou/approvals/management/commands/send_approvals_to_pe.py
  itou/approvals/migrations/0001_initial.py
  itou/approvals/migrations/0003_alter_approval_updated_at.py
  itou/approvals/models.py
  itou/cities/migrations/0001_initial.py
  itou/companies/management/commands/update_companies_job_app_score.py
  itou/companies/migrations/0001_initial.py
  itou/eligibility/migrations/0001_initial.py
  itou/employee_record/migrations/0001_initial.py
  itou/external_data/migrations/0001_initial.py
  itou/geo/migrations/0001_initial.py
  itou/gps/migrations/0001_initial.py
  itou/gps/models.py
  itou/institutions/migrations/0001_initial.py
  itou/invitations/migrations/0001_initial.py
  itou/job_applications/migrations/0001_initial.py
  itou/job_applications/migrations/0002_jobapplication_refusal_reason_shared_with_job_seeker.py
  itou/job_applications/models.py
  itou/jobs/migrations/0001_initial.py
  itou/openid_connect/france_connect/migrations/0001_initial.py
  itou/openid_connect/inclusion_connect/migrations/0001_initial.py
  itou/prescribers/migrations/0001_initial.py
  itou/siae_evaluations/migrations/0001_initial.py
  itou/users/migrations/0001_initial.py
  itou/users/migrations/0002_remove_jobseekerprofile_previous_employer_kind.py
  itou/users/migrations/0003_remove_jobseekerprofile_previous_employer_kind_from_db.py
  itou/users/migrations/0005_clean_pe_connect_users_from_allauth.py
  itou/users/models.py
  itou/utils/apis/esd.py
  itou/utils/faker_providers.py
  itou/utils/tokens.py
  itou/www/apply/forms.py
  itou/www/approvals_views/forms.py
  itou/www/companies_views/forms.py
  itou/www/gps/views.py
  manage.py
  pyproject.toml
  requirements/dev.txt
  requirements/test.in
  requirements/test.txt
  tests/companies/test_import_siae_command.py
  tests/conftest.py
  tests/gps/tests.py
  tests/jobs/management/test_sync_romes_and_appellations.py
  tests/siae_evaluations/test_models.py
  tests/www/apply/test_process.py
  tests/www/apply/test_submit.py
  tests/www/employee_record_views/test_create.py
  tests/www/login/tests.py
Labels: no-changelog

#4029 Ajouter les catégories fréquentes au gabarit de PR
  .github/pull_request_template.md
Labels: no-changelog

#4039 Cosmétique sur le changelog
  CHANGELOG.md
Labels: no-changelog

#4073 Correction d’un échec de test_details_for_unauthorized_prescriber
  tests/www/apply/test_process.py
Labels: no-changelog

#4081 Ajout du numéro de PASS dans les représentations techniques des Supension & Prolongation
  itou/approvals/models.py
Labels: no-changelog

#4084 tests: correction d'un appel à create_test_romes_and_appellations call
  tests/www/companies_views/test_views.py
Labels: no-changelog

#4077 Ajouter des context processors à www/error.py
  itou/www/error.py
  tests/www/test_error.py
Labels: no-changelog

#4078 UX/UI : Postuler pour une entreprise directement depuis les résultats de recherche employeur [GEN-1645]
  itou/templates/companies/includes/_card_siae.html
  itou/templates/search/siaes_search_results.html
Labels: modifié

#4085 API : Correction d’une typo dans les URLs d’exemple de l’API candidats
  itou/api/applicants_api/views.py
Labels: modifié

#4079 Demandeur d’emploi : les champs prénom, nom et adresse sont requis [GEN-1620]
  itou/www/dashboard/views.py
  tests/gps/tests.py
  tests/www/dashboard/tests.py
  tests/www/signup/test_password.py
Labels: modifié

#4092 tests: association de quelques `assertNotContains` de plus à leur `assertContains`
  tests/www/apply/test_geiq.py
  tests/www/approvals_views/test_pe_approval.py
Labels: no-changelog

#4095 Admin : Ignorer les accents lors de la recherche par prénom ou nom [GEN-1627]
  itou/approvals/admin.py
  itou/users/admin.py
Labels: modifié

#4060 changelog: From 2024-05-06 to 2024-05-12
  CHANGELOG.md
Labels: no-changelog

#4091 ruff: activation des règles de pyupgrade
  itou/api/geiq/serializers.py
  itou/asp/management/commands/sync_communes.py
  itou/users/models.py
  itou/utils/staticfiles.py
  itou/utils/widgets.py
  itou/www/invitations_views/views.py
  pyproject.toml
  tests/approvals/test_notify_pole_emploi.py
  tests/conftest.py
  tests/job_applications/factories.py
  tests/users/test_models.py
  tests/utils/test_templatetags.py
  tests/www/apply/test_process.py
  tests/www/dashboard/tests.py
  tests/www/stats/test_views.py
  tests/www/test_security.py
Labels: no-changelog

#4098 logging: ajout de l'organisation courante de l'utilisateur dans les logs JSON
  itou/utils/logging.py
  tests/utils/tests.py
Labels: no-changelog

#4056 Rendre EligibilityDiagnosis.for_job_seeker_and_siae plus joli
  itou/eligibility/models/iae.py
  itou/job_applications/models.py
Labels: no-changelog

#4090 Vie privée : retrait de la mention des publicités Google, qui n’ont jamais été servies par le site
  .github/pull_request_template.md
  itou/templates/static/legal/privacy.html
Labels: no-changelog

#4101 Envoyer les emails lors que la transaction en cours `commit`
  itou/common_apps/organizations/admin.py
  itou/common_apps/organizations/views.py
  itou/companies/management/commands/_import_siae/siae.py
  itou/siae_evaluations/management/commands/evaluation_campaign_notify.py
  itou/utils/tasks.py
  tests/approvals/test_prolongation_requests.py
  tests/common_apps/notifications/tests.py
  tests/communications/test_dispatch.py
  tests/companies/test_admin.py
  tests/companies/test_import_siae_command.py
  tests/companies/test_models.py
  tests/conftest.py
  tests/geo/test_zrr.py
  tests/institutions/tests.py
  tests/job_applications/test_transfer.py
  tests/job_applications/tests.py
  tests/metabase/management/test_populate_metabase_emplois.py
  tests/prescribers/tests.py
  tests/siae_evaluations/test_emails.py
  tests/siae_evaluations/test_management_commands.py
  tests/siae_evaluations/test_models.py
  tests/utils/htmx/test.py
  tests/utils/test.py
  tests/utils/test_emails.py
  tests/www/apply/test_geiq.py
  tests/www/approvals_views/test_prolongation.py
  tests/www/companies_views/test_views.py
  tests/www/institutions_views/test_views.py
  tests/www/invitations_views/test_company_accept.py
  tests/www/invitations_views/test_prescriber_organization.py
  tests/www/prescribers_views/test_admins.py
  tests/www/prescribers_views/test_members.py
  tests/www/signup/test_prescriber.py
  tests/www/signup/test_siae.py
Labels: no-changelog

#4112 Correction de l’URL MinIO dans `configure_bucket`
  itou/files/management/commands/configure_bucket.py
Labels: no-changelog

#4023 Prescripteur : Création de nouveaux types de prescripteurs habilités dans l'interface d'administration [GEN-267]
  itou/approvals/migrations/0001_initial.py
  itou/prescribers/enums.py
  itou/prescribers/migrations/0001_initial.py
  itou/www/signup/forms.py
  tests/prescribers/tests.py
  tests/www/signup/test_prescriber.py
Labels: no-changelog

#4114 Utiliser une transaction pour prolongation_requests_chores
  itou/approvals/management/commands/prolongation_requests_chores.py
Labels: no-changelog

#4113 UX/UI: Améliorer le titre de section de connexion avec France Travail
  itou/templates/account/login_job_seeker.html
Labels: no-changelog

#4109 Tableau de bord: Afficher le type de structure/organisation dans le tableau de bord [GEN-156]
  itou/templates/dashboard/dashboard.html
Labels: modifié

#4116 Adresse: utilisation du dictionnaire inversé `DEPARTMENT_TO_REGION` pour trouver la région d'un département
  itou/common_apps/address/models.py
Labels: no-changelog

#4115 Notifications : Réessayer d’envoyer les emails lorsque Mailjet indique un problème
  itou/utils/tasks.py
  requirements/dev.txt
  requirements/test.in
  requirements/test.txt
  tests/utils/test_emails.py
Labels: modifié

#4117 Tableau de bord: renommage des `includes` spécifiques aux employeurs
  itou/templates/dashboard/dashboard.html
  itou/templates/dashboard/includes/employer_company_card.html
  itou/templates/dashboard/includes/employer_employees_card.html
  itou/templates/dashboard/includes/employer_evaluation_campaigns_card.html
  itou/templates/dashboard/includes/employer_job_applications_card.html
Labels: no-changelog

#4097 UX/UI : Améliorer la navigation dans le parcours de modification d’une suspension de PASS IAE
  itou/templates/approvals/suspension_action_choice.html
  itou/templates/approvals/suspension_update.html
Labels: 1-recette-jetable, modifié

#4119 Inscription: Nettoyage d'un code de rétro-compatibiité
  itou/www/invitations_views/views.py
  tests/www/invitations_views/test_company_accept.py
  tests/www/invitations_views/test_new_user.py
Labels: no-changelog

#4076 Renommer approval_{can_be_renewed_by,needs_new_eligibility_diagnosis}
  itou/job_applications/models.py
  itou/users/models.py
  itou/www/apply/views/process_views.py
  itou/www/apply/views/submit_views.py
  tests/users/test_models.py
Labels: no-changelog

#4122 Factories: Utiliser le diag d’éligibilité du pass sur la candidature
  tests/approvals/factories.py
Labels: no-changelog

#4125 Connexion: Améliorer un logger d'erreur avec France Travail Connect
  itou/openid_connect/pe_connect/views.py
Labels: modifié

#4124 Connexion: Amélioration des levée d'erreur en se connectant avec France Connect ou France Travail Connect
  itou/openid_connect/models.py
  tests/openid_connect/france_connect/tests.py
  tests/openid_connect/pe_connect/tests.py
Labels: modifié

#4128 Prescripteur: Correction de la géolocalsation sans adresse
  itou/utils/apis/geocoding.py
  tests/common_apps/address/tests.py
Labels: no-changelog

#4111 Suppression du bandeau promotionnelle RDV-I [GEN-1662]
  itou/templates/apply/includes/list_job_applications.html
  itou/templates/apply/includes/rdv_insertion_promo_card.html
  tests/www/apply/__snapshots__/test_list.ambr
  tests/www/apply/test_list_for_siae.py
Labels: 1-recette-jetable, supprimé

#4137 UX/UI : Mise a jour du theme et adaptation du DOM du menu #burgerNav
  itou/templates/layout/_header.html
  itou/utils/staticfiles.py
  tests/www/__snapshots__/test_layout.ambr
Labels: 1-recette-jetable, modifié

#4150 Notifications: Remise en place d'une banière Mobil’Emploi
  itou/templates/dashboard/dashboard.html
  itou/www/dashboard/views.py
Labels: ajouté

#4149 Statistiques: Nombre de candidats qui prennent le contrôle de leur compte [GEN-1642]
  itou/users/apps.py
  itou/users/migrations/0006_user_first_login.py
  itou/users/migrations/0007_fill_user_first_login.py
  itou/users/models.py
  tests/users/test_models.py
Labels: ajouté
