Repository gip-inclusion/les-emplois, pull requests merged in 2024-02, with the labels that each got.

#3571 scripts: Amaigrissement de `deploy_prod.sh`
  Makefile
  scripts/deploy_prod.sh
Labels: no-changelog

#3577 [GEN-7933] Afficher le lien d’une enquête tally pour les employeurs
  itou/templates/dashboard/dashboard.html
Labels: recette-jetable

#3584 Suppression définitive de la colonne User.resume_link en base de données
  itou/users/migrations/0032_drop_user_resume_link_in_db.py
Labels: no-changelog

#3588 Nettoyage de migration
  itou/users/migrations/0031_remove_user_resume_link.py
  itou/users/migrations/0032_drop_user_resume_link_in_db.py
Labels: no-changelog

#3587 Modification d'un test instable
  tests/www/employee_record_views/__snapshots__/test_add.ambr
  tests/www/employee_record_views/test_add.py
Labels: no-changelog

#3566 configuration : Suppression de `CLEVER_TOKEN` et `CLEVER_SECRET`
  .env.template
  CHANGELOG_breaking_changes.md
  scripts/create-fast-machine.sh
Labels: no-changelog

#3599 Correction d'un test d'une ancienne PR (#3018)
  tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
  tests/www/approvals_views/test_prolongation_requests.py
Labels: no-changelog

#3604 API: ajout d'un log en cas de token invalide
  itou/api/token_auth/views.py
Labels: no-changelog

#3607 Import EA : Correction d'une erreur mineure dans un commentaire
  itou/companies/management/commands/_import_siae/utils.py
Labels: no-changelog

#3606 API: correction du log en cas de mot de passe manquant
  itou/api/token_auth/views.py
  tests/api/token_auth/tests.py
Labels: no-changelog

#3600 Mise a jour de l'UI de la recherche principale
  itou/static/css/itou.css
  itou/templates/dashboard/includes/labor_inspector_evaluation_campains_card.html
  itou/templates/dashboard/includes/siae_evaluation_campains_card.html
  itou/templates/search/includes/generic_search_home.html
  itou/templates/search/includes/prescribers_search_form.html
  itou/templates/search/includes/siaes_search_form.html
  itou/templates/search/prescribers_search_results.html
  itou/templates/search/siaes_search_results.html
  itou/utils/staticfiles.py
  itou/www/search/forms.py
Labels: recette-jetable

#3567 [GEN-3994] Affichage de services Dora dans la description d'un employeur ou d'une fiche de poste
  config/settings/base.py
  itou/templates/companies/card.html
  itou/templates/companies/hx_dora_services.html
  itou/templates/companies/job_description_card.html
  itou/utils/apis/data_inclusion.py
  itou/www/companies_views/urls.py
  itou/www/companies_views/views.py
  tests/utils/apis/test_data_inclusion_api.py
  tests/www/companies_views/__snapshots__/test_views.ambr
  tests/www/companies_views/test_views.py
Labels: recette-jetable

#3573 Surveiller les erreurs JS avec Sentry
  config/settings/base.py
  itou/templates/layout/base.html
Labels: no-changelog

#3608 C2 : Mise en place du tracking Matomo du TB 337 "Bilan de la phase de candidatures en IAE" [GEN-8007]
  itou/metabase/management/commands/populate_metabase_matomo.py
  tests/metabase/management/__snapshots__/test_populate_metabase_matomo.ambr
  tests/metabase/management/test_populate_metabase_matomo.py
Labels: no-changelog

#3609 Suppression du paramètre d'URL back_url des liens vers les fiches entreprises
  itou/templates/apply/includes/list_card_header.html
  itou/templates/companies/includes/_card_jobdescription.html
  itou/templates/companies/includes/_card_siae.html
  itou/templates/dashboard/includes/siae_card.html
  itou/www/companies_views/views.py
Labels: no-changelog

#3610 Admin: ajout de la date de création de la candidature dans le listing de la vue Utilisateur
  itou/users/admin.py
Labels: no-changelog

#3611 Utilisation de la fonctionnalité "Copier dans le presse-papier" du thème
  itou/static/js/utils.js
  itou/templates/includes/copy_to_clipboard.html
  tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
Labels: recette-jetable, no-changelog

#3612 tests: amélioration de nos tests techniques
  tests/approvals/test_admin.py
  tests/settings_viewer/tests.py
  tests/www/apply/test_forms.py
  tests/www/companies_views/test_job_description_views.py
  tests/www/employee_record_views/test_create.py
  tests/www/login/tests.py
Labels: no-changelog

#3618 Tableau de bord : correction des URLs et trackers Dora
  itou/templates/dashboard/dashboard.html
  itou/templates/dashboard/includes/dora_card.html
  itou/utils/settings_context_processors.py
Labels: no-changelog

#3621 layout/base : Use matomoMore to track visible content
  itou/templates/layout/base.html
  tests/utils/__snapshots__/tests.ambr
Labels: no-changelog

#3616 Ajouter un test pour la limite de fréquence de l’API
  tests/api/applicants_api/tests.py
Labels: no-changelog

#3622 Services Dora : correction du cas où l'adresse structure est manquante
  itou/templates/companies/hx_dora_services.html
  tests/www/companies_views/__snapshots__/test_views.ambr
  tests/www/companies_views/test_views.py
Labels: no-changelog

#3614 Refonte UX/UI - Dropdown "structure"
  itou/static/css/itou.css
  itou/templates/apply/includes/siae_card.html
  itou/templates/apply/includes/transfer_job_application.html
  itou/templates/apply/submit/application/base.html
  itou/templates/apply/submit_base_two_columns.html
  itou/templates/approvals/prolongation_requests/show.html
  itou/templates/companies/edit_siae.html
  itou/templates/companies/edit_siae_preview.html
  itou/templates/companies/includes/_siae_info.html
  itou/templates/companies/job_description_card.html
  itou/templates/layout/_header_nav_primary_items.html
  itou/utils/staticfiles.py
Labels: recette-jetable

#3629 Confirmation d'embauche: réduction du nombre de requêtes
  itou/www/apply/views/submit_views.py
  tests/www/apply/test_submit.py
Labels: no-changelog

#3627 tests: ajout d'un test pour le cas difficile de la commande deduplicate_job_seekers
  tests/users/test_management_commands.py
Labels: no-changelog

#3628 changelog: sprint 80
  CHANGELOG.md
Labels: no-changelog

#3640 Requête en moins pour la mise à jour d'un candidat
  itou/www/apply/views/submit_views.py
  tests/www/apply/test_submit.py
Labels: no-changelog

#3646 tests: correction d'un test
  tests/approvals/test_management_commands.py
Labels: no-changelog

#3645 [GEN-8064] Gérer les membres ITOU se connectant avec FT connect
  itou/openid_connect/pe_connect/views.py
Labels: no-changelog

#3667 Retirer text/css des link stylesheet et style
  itou/templates/hijack/notification.html
  itou/templates/layout/base.html
  itou/templates/layout/base_printable.html
  itou/templates/utils/widgets/csp_proof_openlayers-osm.html
Labels: no-changelog

#3666 Convertir TestPEOrganizationInvitation à pytest
  tests/www/invitations_views/test_prescriber_organization.py
Labels: no-changelog

#3651 Grouper les scripts dans le template de base
  itou/templates/layout/base.html
Labels: no-changelog

#3671 tests: remove duplicate tests
  tests/www/geiq_eligibility_views/test_geiq.py
Labels: no-changelog

#3670 Profile candidat: empêcher les valeurs NULL pour le champs asp_uid
  itou/users/migrations/0041_alter_jobseekerprofile_asp_uid.py
  itou/users/models.py
  tests/users/test_models.py
Labels: no-changelog

#3673 tests: correction d'un test flaky
  tests/www/apply/test_geiq.py
Labels: no-changelog

#3675 tests: correction de certains appels à assertTemplate(Not)Used
  tests/www/apply/test_submit.py
Labels: no-changelog

#3677 Suppression définitive du champ asp_uid du modèle Utilisateur
  itou/users/migrations/0042_drop_user_asp_uid_in_db.py
Labels: no-changelog

#3681 Augmenter le délai avant la suppression automatique d’une entreprise (EA / GEIQ) non référencée [GEN-8073]
  itou/companies/management/commands/_import_siae/utils.py
Labels: no-changelog

#3692 Utiliser Redis pour les review apps
  .github/workflows/review-app-creation.yml
Labels: no-changelog

#3694 Largueur minimum du dropdown-structure
  itou/utils/staticfiles.py
Labels: recette-jetable

#3696 Scripts : Augmentation du temps de rétention du flux IAE
  scripts/imports-asp.sh
Labels: no-changelog

#3701 Appairer assert{Not,}Contains in tests.www.employee_record_views
  tests/www/employee_record_views/test_summary.py
Labels: no-changelog

#3698 Appairer des assert{Not,}Contains dans tests.www.companies_views
  tests/www/companies_views/test_views.py
Labels: no-changelog

#3700 Appairer des assert{Not,}Contains dans tests.www.search
  tests/www/search/tests.py
Labels: no-changelog

#3685 Add a check-health endpoint
  config/settings/base.py
  itou/www/middleware.py
  tests/www/test_check_health.py
Labels: recette-jetable

#3710 scripts.imports-asp: Use the correct environment variable name
  scripts/imports-asp.sh
Labels: no-changelog

#3714 Makefile: Afficher la liste des PR déployées pour `deploy_prod`
  Makefile
Labels: no-changelog

#3704 Utiliser un tri déterministe pour PoleEmploiApproval.find_for()
  itou/approvals/models.py
  tests/approvals/tests.py
Labels: no-changelog

#3720 Refonte UX/UI: Maj UI des cartes prescripteurs
  itou/templates/search/prescribers_search_results.html
  itou/utils/staticfiles.py
Labels: recette-jetable

#3715 Fiches salarié : La clé étrangère vers la candidature est obligatoire
  itou/employee_record/migrations/0010_add_asp_measure_to_unique_constraint.py
  itou/employee_record/migrations/0014_alter_employeerecord_job_application.py
  itou/employee_record/models.py
  tests/employee_record/factories.py
Labels: no-changelog

#3730 Correctif pour l’environnement de dév
  itou/utils/urls.py
Labels: no-changelog

#3718 Journal des modifications : sprint 81
  CHANGELOG.md
Labels: no-changelog

#3734 Préferer des timedelta aux relativedelta dans les tests de PASS
  tests/approvals/tests.py
  tests/www/approvals_views/test_list.py
Labels: no-changelog

#3732 Ajout d'un message pour prévenir les utilisateurs des changements d'interface
  itou/templates/dashboard/dashboard.html
Labels: recette-jetable
