Repository gip-inclusion/les-emplois, pull requests merged in 2024-04, with the labels that each got.

#3862 Makefile: Suppression d'une verrue pour le lancement de `shellcheck`
  Makefile
Labels: no-changelog

#3825 Inviter les développeurs à nous contacter à propos des API
  itou/templates/api/index.html
Labels: no-changelog

#3830 Simplifier PasswordChangeTest::test_password_change_flow
  tests/www/signup/test_password.py
Labels: no-changelog

#3837 Déplacer la commande migrate plus haut dans le README
  README.md
Labels: no-changelog

#3839 Retirer du code non utilisé pour js-job-applications-filters-button
  itou/static/js/job_applications_filters.js
Labels: no-changelog

#3773 [GEN-8082] Autocomplétion de l'adresse pour la création d'un candidat
  itou/common_apps/address/forms.py
  itou/static/js/address_autocomplete_fields.js
  itou/templates/apply/includes/job_application_accept_form.html
  itou/templates/apply/submit/application/end.html
  itou/templates/apply/submit/create_or_update_job_seeker/step_2.html
  itou/templates/apply/submit/hire_confirmation.html
  itou/templates/dashboard/includes/edit_job_seeker_info_form.html
  itou/utils/mocks/address_format.py
  itou/utils/widgets.py
  itou/www/apply/forms.py
  itou/www/apply/views/submit_views.py
  itou/www/dashboard/forms.py
  tests/users/factories.py
  tests/www/apply/test_process.py
  tests/www/apply/test_submit.py
  tests/www/dashboard/__snapshots__/tests.ambr
  tests/www/dashboard/tests.py
Labels: 1-recette-jetable

#3871 Fiches salarié : Ne plus les désactiver quand `hexa_commune` est manquant
  itou/employee_record/management/commands/sanitize_employee_records.py
  tests/employee_record/test_sanitize_employee_records.py
Labels: no-changelog

#3864 Liste fiches salariés: correction de l'affichage de la ville du candidat [GEN-277]
  itou/templates/employee_record/includes/list_item.html
  itou/utils/templatetags/job_seekers.py
  tests/utils/tests.py
  tests/www/employee_record_views/test_list.py
Labels: 1-recette-jetable

#3875 Fiches salarié : Correction d'oublis pour les données statiques des notifications
  itou/employee_record/serializers.py
  tests/employee_record/__snapshots__/test_serializers.ambr
  tests/employee_record/test_serializers.py
Labels: no-changelog

#3878 Mise a jour du theme itou vers la v1.5.1
  itou/templates/companies/job_description_list.html
  itou/utils/staticfiles.py
Labels: 1-recette-jetable

#3880 Ré-ordonnancement des méthodes de JobApplication
  itou/job_applications/models.py
Labels: no-changelog

#3881 Amélioration du test du cache Redis avec Docker sous macOS
  tests/utils/test_cache.py
Labels: no-changelog

#3877 Retirer du JS inutilisé pour #siae-number-results
  itou/templates/search/siaes_search_results.html
Labels: no-changelog

#3882 changelog: Sprint 84
  CHANGELOG.md
Labels: no-changelog

#3869 Filtrer les candidatures des candidats avec HTMX
  itou/static/js/job_applications_filters.js
  itou/templates/apply/includes/list_job_applications.html
  itou/templates/apply/list_for_job_seeker.html
  itou/www/apply/views/list_views.py
  tests/www/apply/__snapshots__/test_list.ambr
  tests/www/apply/test_list.py
Labels: 1-recette-jetable

#3865 Empêcher l’accès anonyme en lecture aux préfixes autres que resume/
  itou/files/management/commands/configure_bucket.py
  tests/files/tests.py
Labels: no-changelog

#3861 Dépendances : Suppression de `appnope` (et du fichier spécifique Mac) car non-utilisé dans le projet
  Makefile
  requirements/dev-mac.txt
Labels: no-changelog

#3892 Retirer make deploy_prod
  CHANGELOG_breaking_changes.md
  Makefile
Labels: no-changelog

#3654 [NOTIFICATIONS] Ajout des interfaces (configuration + admin)
  itou/approvals/notifications.py
  itou/communications/dispatch/__init__.py
  itou/communications/dispatch/base.py
  itou/communications/dispatch/utils.py
  itou/communications/models.py
  itou/invitations/notifications.py
  itou/job_applications/notifications.py
  itou/static/css/itou-admin.css
  itou/static/js/notifications_center.js
  itou/templates/dashboard/edit_user_notifications.html
  itou/templates/layout/_header_nav_primary_items.html
  itou/users/admin.py
  itou/utils/templatetags/theme_inclusion.py
  itou/www/dashboard/forms.py
  itou/www/dashboard/views.py
  tests/communications/test_dispatch.py
  tests/job_applications/tests.py
  tests/users/test_admin_views.py
  tests/www/__snapshots__/test_layout.ambr
  tests/www/dashboard/tests.py
Labels: 1-recette-jetable, no-changelog

#3903 Gérer les fichiers 7-zip dans import_siae
  itou/companies/management/commands/_import_siae/__init__.py
  itou/companies/management/commands/_import_siae/utils.py
  requirements/base.in
  requirements/base.txt
  requirements/dev.txt
  requirements/test.txt
Labels: no-changelog

#3908 Retirer des références restantes à master_clever
  .github/workflows/ci.yml
  scripts/create-fast-machine.sh
Labels: no-changelog

#3911 Mise à jour du 1er paragraphe de l'accueil
  itou/templates/search/siaes_search_home.html
Labels: no-changelog

#3905 Retirer JobSeekerProfile.previous_employer_kind
  itou/fixtures/django/07_jobseeker_profile.json
  itou/users/migrations/0002_remove_jobseekerprofile_previous_employer_kind.py
  itou/users/models.py
  tests/users/test_models.py
Labels: no-changelog

#3912 Mise à jour du 2e paragraphe de l'accueil
  itou/templates/search/siaes_search_home.html
Labels: no-changelog

#3906 Retirer JobSeekerProfile.previous_employer_kind de la base de données
  itou/users/migrations/0003_remove_jobseekerprofile_previous_employer_kind_from_db.py
Labels: no-changelog

#3883 Factories : Mixin pour permettre la surcharge des champs `auto_now=True`
  tests/employee_record/factories.py
  tests/utils/factory_boy.py
Labels: no-changelog

#3916 Correction saut de ligne
  itou/static/js/sliding_tabs.js
  itou/templates/apply/submit_step_check_job_seeker_nir.html
  itou/templates/signup/job_seeker_nir.html
  itou/utils/staticfiles.py
Labels: 1-recette-jetable

#3918 requirements: mise à jour d'ipython
  requirements/dev.txt
Labels: no-changelog

#3914 Pack de motifs de refus
  itou/job_applications/enums.py
  itou/job_applications/migrations/0001_initial.py
  itou/job_applications/models.py
  itou/templates/apply/includes/buttons/refuse.html
  itou/templates/apply/process_refuse.html
  itou/templates/apply/refusal_messages/did_not_come.txt
  itou/templates/apply/refusal_messages/did_not_come_to_interview.txt
  itou/templates/apply/refusal_messages/duplicate.txt
  itou/templates/apply/refusal_messages/hired_elsewhere.txt
  itou/templates/apply/refusal_messages/incompatible.txt
  itou/templates/apply/refusal_messages/lacking_skills.txt
  itou/templates/apply/refusal_messages/no_position.txt
  itou/templates/apply/refusal_messages/non_eligible.txt
  itou/templates/apply/refusal_messages/not_interested.txt
  itou/templates/apply/refusal_messages/not_mobile.txt
  itou/templates/apply/refusal_messages/other.txt
  itou/templates/apply/refusal_messages/prevent_objectives.txt
  itou/templates/apply/refusal_messages/training.txt
  itou/www/apply/forms.py
  itou/www/apply/urls.py
  itou/www/apply/views/process_views.py
  tests/www/apply/test_forms.py
  tests/www/apply/test_process.py
Labels: no-changelog

#3927 Linter les scripts du dossier scripts/
  Makefile
Labels: no-changelog

#3924 Arrêter de stocker les adresses des utilisateurs non-candidats [GEN-1553]
  itou/templates/dashboard/edit_user_info.html
  itou/www/dashboard/forms.py
  tests/www/dashboard/tests.py
Labels: 1-recette-jetable

#3926 Suppression des adresses des comptes non-candidat [GEN-1553]
  itou/users/migrations/0004_remove_non_job_seeker_address.py
Labels: no-changelog

#3896 Stabiliser test_populate_job_seekers
  tests/metabase/management/test_populate_metabase_emplois.py
Labels: no-changelog

#3897 Utiliser textContent plutôt que innerHTML
  itou/static/js/siae_evaluations_sample_selection.js
Labels: no-changelog

#3935 Parcours de candidature: suppression de la rétrocompatibilité avec les anciennes sessions
  itou/www/apply/views/submit_views.py
Labels: 1-recette-jetable, no-changelog

#3936 Github actions: simplification du message de la recette jetable
  .github/workflows/review-app-creation.yml
Labels: 1-recette-jetable, no-changelog

#3941 Suppression de la synchro automatique des notifications
  itou/communications/apps.py
Labels: no-changelog

#3945 Tableau de bord: suppression de la bannière Inclusion Connect de mai 2023
  itou/templates/dashboard/dashboard.html
Labels: no-changelog

#3929 [GEN-269] Permettre de partager le motif de refus de candidature au candidat
  itou/job_applications/migrations/0002_jobapplication_refusal_reason_shared_with_job_seeker.py
  itou/job_applications/models.py
  itou/templates/apply/email/refuse_body_for_job_seeker.txt
  itou/templates/apply/email/refuse_body_for_proxy.txt
  itou/templates/apply/includes/job_application_answers.html
  itou/templates/apply/process_refuse.html
  itou/www/apply/forms.py
  itou/www/apply/views/process_views.py
  tests/job_applications/tests.py
  tests/www/apply/test_process.py
Labels: 1-recette-jetable

#3950 Gestion d’un cas très particulier dans l’import SIAE
  itou/companies/management/commands/_import_siae/siae.py
Labels: no-changelog

#3948 tests: correction de tests pour mieux correspondre à leur utilisation réelle
  tests/www/approvals_views/__snapshots__/test_includes.ambr
  tests/www/approvals_views/test_includes.py
Labels: no-changelog

#3943 Matomo: correctifs de `buttons_form`
  itou/templates/apply/process_postpone.html
  itou/templates/apply/process_refuse.html
  itou/templates/apply/submit/application/resume.html
  itou/templates/companies/edit_job_description.html
  itou/templates/companies/edit_job_description_details.html
  itou/templates/companies/edit_job_description_preview.html
  itou/templates/companies/edit_siae.html
  itou/templates/companies/edit_siae_description.html
  itou/templates/companies/edit_siae_preview.html
  itou/templates/dashboard/includes/edit_job_seeker_info_form.html
  itou/templates/employee_record/add.html
  itou/templates/employee_record/includes/create_step_2.html
  itou/templates/utils/templatetags/buttons_form.html
  itou/utils/templatetags/buttons_form.py
  tests/utils/__snapshots__/test_templatetags.ambr
  tests/www/approvals_views/__snapshots__/test_suspend.ambr
  tests/www/employee_record_views/__snapshots__/test_add.ambr
  tests/www/employee_record_views/__snapshots__/test_create.ambr
  tests/www/signup/__snapshots__/test_job_seeker.ambr
Labels: 1-recette-jetable

#3955 Template: suppression de code inaccessible
  itou/templates/invitations_views/create.html
Labels: no-changelog

#3957 Notifier #mep-c1 lors d’une mise en prod [GEN-1528]
  .github/workflows/notify-slack.yml
Labels: no-changelog

#3960 :wrench: notify_slack: nouvelle version pour échapper les " (ainsi que les ' qui ne devraient plus poser soucis) :crossed_fingers:
  .github/workflows/notify-slack.yml
Labels: no-changelog

#3939 Ouverture des TBs DDETS/DREETS à la DGEFP
  itou/templates/dashboard/includes/stats.html
  itou/utils/apis/metabase.py
  itou/www/stats/urls.py
  itou/www/stats/views.py
Labels: no-changelog

#3954 changelog: Sprint 85
  CHANGELOG.md
Labels: no-changelog

#3930 GPS : ajout d'un feature flag
  config/settings/base.py
Labels: no-changelog

#3952 Générer le changelog automatiquement depuis GitHub [GEN-1526]
  .github/pull_request_template.md
  .github/workflows/mkchangelog.yml
  .github/workflows/require-labels.yml
  scripts/mkchangelog
Labels: no-changelog

#3956 Refonte UX/UI - Ajouts d'onglets sur l'accueil du tableau de bord
  itou/static/css/itou.css
  itou/static/img/dashboard/banner-statistiques-pilotage-bg.jpg
  itou/templates/dashboard/dashboard.html
  itou/templates/dashboard/includes/siae_employees_card.html
  itou/templates/dashboard/includes/stats.html
  itou/templates/layout/_header.html
  itou/templates/layout/base.html
  itou/utils/staticfiles.py
  tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
  tests/www/companies_views/__snapshots__/test_views.ambr
  tests/www/dashboard/__snapshots__/tests.ambr
Labels: 1-recette-jetable, modifié

#3898 Retirer les boutons appliquer dans les filtres
  itou/static/js/approvals_filters.js
  itou/static/js/job_applications_filters.js
  itou/templates/apply/list_for_job_seeker.html
  itou/templates/apply/list_for_prescriber.html
  itou/templates/apply/list_for_siae.html
  itou/templates/approvals/list.html
  tests/www/apply/__snapshots__/test_list.ambr
Labels: no-changelog

#3966 Correction d'un bug de mise en forme sur les cartes candidatures
  itou/templates/approvals/includes/job_description_creation.html
  itou/templates/employee_record/includes/_status.html
  itou/utils/templatetags/job_applications.py
  tests/utils/__snapshots__/tests.ambr
  tests/www/apply/__snapshots__/test_list.ambr
Labels: 1-recette-jetable, modifié

#3971 settings: add http.status_code key to request logs
  config/settings/base.py
Labels: no-changelog

#3965 [GEN-191] Affichage des boutons enregistrer en haut des formulaires d'admin
  itou/utils/admin.py
Labels: modifié

#3961 [GEN-233] Masquage de l’adresse email du prescripteur ou de l'employeur dans la page candidature pour le candidat
  itou/templates/apply/includes/job_application_sender_info.html
  tests/www/apply/test_process.py
Labels: modifié

#3978 Correction de la commande mkchangelog --publish
  scripts/mkchangelog
Labels: no-changelog

#3970 Retirer session_key des logs Datadog
  itou/utils/logging.py
Labels: no-changelog

#3975 Retirer les arguments par défaut de FullNameFormMixin
  itou/www/signup/forms.py
Labels: no-changelog

#3976 Profil utilisateur : Demander le prénom avant le nom, pour être cohérent avec le parcours d’inscription
  itou/templates/signup/job_seeker_signup.html
  tests/www/signup/__snapshots__/test_job_seeker.ambr
Labels: modifié

#3972 UX/UI : Ajouter une balise `<noscript>` sur le site
  itou/templates/layout/base.html
  itou/utils/staticfiles.py
Labels: pending, ajouté

#3949 UX/UI : Filtrer les employeurs et postes de manière plus dynamique
  itou/templates/search/includes/siaes_search_filters.html
  itou/templates/search/includes/siaes_search_filters_company.html
  itou/templates/search/includes/siaes_search_filters_departments.html
  itou/templates/search/includes/siaes_search_results.html
  itou/templates/search/includes/siaes_search_tabs.html
  itou/templates/search/includes/siaes_search_title.html
  itou/templates/search/includes/siaes_search_top.html
  itou/templates/search/siaes_search_results.html
  itou/www/search/views.py
  tests/conftest.py
  tests/utils/htmx/test.py
  tests/utils/test.py
  tests/www/search/tests.py
Labels: 1-recette-jetable, modifié

#3984 [GEN-1567] Privilégier les administrateurs de l’organisation lors des notifications de relance des demandes de Prolongation
  itou/approvals/notifications.py
  tests/approvals/test_notifications.py
Labels: modifié

#3991 Retirer les format_filters de employee_record/list.html
  itou/templates/employee_record/list.html
Labels: no-changelog

#3981 changelog: From 2024-04-22 to 2024-04-28
  CHANGELOG.md
Labels: no-changelog

#3994 [GEN-1586] Ajout d'une colonne SIRET à l’extraction CTA
  itou/scripts/sql/cta_export.sql
Labels: ajouté

#3992 [GEN-1625] Ajout d'un message d'alerte pour inviter à remplir en enquête sur la réattribution des candidatures d’un collaborateur
  itou/templates/prescribers/members.html
Labels: ajouté

#3996 Suppression de code inutilisé
  itou/www/apply/urls.py
  itou/www/apply/views/process_views.py
Labels: no-changelog

#3884 Remplacer le fil d'ariane par des boutons retour [GEN-237]
  itou/templates/apply/includes/job_application_info.html
  itou/templates/apply/includes/job_applications_export_button.html
  itou/templates/apply/list_for_prescriber.html
  itou/templates/apply/list_for_siae.html
  itou/templates/apply/list_of_available_exports.html
  itou/templates/apply/process_details.html
  itou/templates/apply/process_details_company.html
  itou/templates/approvals/detail.html
  itou/templates/approvals/includes/job_applications.html
  itou/templates/approvals/includes/job_description_creation.html
  itou/templates/approvals/includes/list_card.html
  itou/templates/approvals/list.html
  itou/templates/approvals/prolongation_requests/list.html
  itou/templates/approvals/prolongation_requests/show.html
  itou/templates/companies/card.html
  itou/templates/companies/includes/_card_jobdescription.html
  itou/templates/companies/includes/_card_siae.html
  itou/templates/companies/includes/_siae_jobdescription.html
  itou/templates/companies/job_description_card.html
  itou/templates/companies/job_description_list.html
  itou/templates/companies/members.html
  itou/templates/companies/show_financial_annexes.html
  itou/templates/dashboard/includes/prescriber_organisation_card.html
  itou/templates/dashboard/includes/siae_card.html
  itou/templates/employee_record/includes/list_item.html
  itou/templates/employee_record/list.html
  itou/templates/employee_record/summary.html
  itou/templates/invitations_views/create.html
  itou/templates/layout/previous_step.html
  itou/templates/prescribers/card.html
  itou/templates/prescribers/edit_organization.html
  itou/templates/prescribers/list_accredited_organizations.html
  itou/templates/prescribers/members.html
  itou/templates/search/prescribers_search_results.html
  itou/templates/search/siaes_search_results.html
  itou/utils/templatetags/previous_step.py
  itou/www/apply/views/list_views.py
  itou/www/approvals_views/views.py
  itou/www/companies_views/views.py
  itou/www/employee_record_views/views.py
  itou/www/prescribers_views/views.py
  itou/www/search/views.py
  tests/utils/test.py
  tests/utils/tests.py
  tests/www/apply/__snapshots__/test_list.ambr
  tests/www/apply/test_list.py
  tests/www/apply/test_process.py
  tests/www/approvals_views/test_detail.py
  tests/www/approvals_views/test_list.py
  tests/www/approvals_views/test_prolongation_requests.py
  tests/www/companies_views/__snapshots__/test_views.ambr
  tests/www/companies_views/test_job_description_views.py
  tests/www/companies_views/test_views.py
  tests/www/employee_record_views/test_add.py
  tests/www/employee_record_views/test_list.py
  tests/www/invitations_views/test_prescriber_organization.py
  tests/www/prescribers_views/test_edit.py
  tests/www/prescribers_views/test_list.py
  tests/www/prescribers_views/test_members.py
  tests/www/search/tests.py
Labels: 1-recette-jetable, modifié
