Repository gip-inclusion/les-emplois, pull requests merged in 2024-08, with the labels that each got.

#4488 Pilotage : Utilisation de `None` plutôt qu'une fausse valeur afin de corriger la synchro
  itou/metabase/tables/organizations.py
  tests/metabase/management/test_populate_metabase_emplois.py
Labels: no-changelog

#4493 Ajout de tracking matomo pour le tranfert de candidatures
  itou/templates/apply/process_external_transfer_resume.html
  itou/templates/companies/card.html
  itou/templates/companies/includes/_card_siae.html
  itou/templates/companies/job_description_card.html
Labels: no-changelog

#4492 GPS : ajout d'un événement Matomo
  itou/templates/gps/includes/memberships_results.html
  tests/gps/__snapshots__/test_views.ambr
Labels: no-changelog

#4498 Stats : Ouverture des stats CD à 2 nouveaux départements
  config/settings/base.py
Labels: no-changelog

#4500 changelog: From 2024-07-29 to 2024-08-04
  CHANGELOG.md
Labels: no-changelog

#4490 Candidature : ajout d'un select_related à la requête d'acceptation
  itou/www/apply/views/process_views.py
Labels: no-changelog

#4495 Tableau de bord : Retirer les bannières mobil'emploi [GEN-1789]
  itou/templates/dashboard/dashboard.html
  itou/www/dashboard/views.py
Labels: supprimé

#4502 openid_connect: Add FT users to their new workplace at every connection
  itou/openid_connect/inclusion_connect/views.py
  tests/openid_connect/inclusion_connect/tests.py
Labels: modifié

#4496 Candidature : Bon à savoir vide dans le parcours de dépôt de candidature EA [GEN-1873]
  itou/templates/apply/submit/application/resume.html
Labels: modifié

#4514 Suppression d'un moniteur de cron non enregistré
  itou/metabase/management/commands/populate_metabase_emplois.py
Labels: no-changelog

#4513 GPS: nettoyage
  itou/templates/users/includes/list_card.html
  itou/www/users_views/views.py
Labels: modifié

#4516 Fiches salarié : correctif sur la commune de naissance
  itou/www/employee_record_views/forms.py
  tests/www/employee_record_views/test_create.py
Labels: no-changelog

#4450 UX/UI : Privilégier l’ouverture d’onglet [ GEN-1872 ]
  itou/templates/apply/includes/accept_section.html
  itou/templates/apply/includes/job_seeker_info.html
  itou/templates/apply/includes/transfer_job_application.html
  itou/templates/apply/process_internal_transfer.html
  itou/templates/apply/submit/application/base.html
  itou/templates/companies/edit_siae_preview.html
  itou/templates/companies/includes/_company_info.html
Labels: modifié

#4520 Admin: Correction de la page des critères d'éligibilité et des diagnostics suite à l'ajout de la certification
  itou/eligibility/admin.py
Labels: modifié

#4517 docker: add a cache dir writable by docker user
  docker-compose.yml
  docker/dev/django/Dockerfile
Labels: no-changelog

#4527 Mettre à jour vers Django 5.0.8
  requirements/base.txt
  requirements/dev.txt
  requirements/test.txt
Labels: no-changelog

#4522 Candidature: correction d'une erreur d'acceptation du siae dans de rares conditions
  itou/www/apply/views/common.py
  tests/www/apply/test_forms.py
  tests/www/apply/test_process.py
Labels: modifié

#4528 UX/UI: Correction de l'affichage responsif des filtres départements et arrondissements
  itou/templates/search/includes/siaes_search_filters_departments.html
Labels: modifié

#4518 Fiches salarié : Utiliser l’objet Pays au lieu de sa PK
  itou/asp/forms.py
  itou/www/apply/forms.py
  itou/www/employee_record_views/forms.py
Labels: no-changelog

#4511 Empêcher de déplacer les données d’entreprise s’il y a un contrôle a posteriori
  itou/companies/management/commands/move_company_data.py
  tests/companies/test_management_commands.py
Labels: no-changelog

#4529 Candidature: Ne pas charger le diagnostic dans le contexte s'il n'est pas utilisé
  itou/www/apply/views/submit_views.py
Labels: no-changelog

#4521 Tests : Ne pas créer de diagnosique d'éligibilité par défaut pour les candidatures réalisées par le candidat
  tests/approvals/tests.py
  tests/employee_record/test_models.py
  tests/gps/test_management_commands.py
  tests/job_applications/factories.py
  tests/users/test_management_commands.py
  tests/www/apply/test_process.py
Labels: no-changelog

#4526 Candidature : Ne plus appeler `.full_clean()` à chaque `.save()`
  itou/job_applications/models.py
  itou/www/apply/views/process_views.py
  itou/www/approvals_views/views.py
  tests/approvals/tests.py
  tests/job_applications/test_transfer.py
  tests/job_applications/tests.py
Labels: no-changelog

#4536 Connexion: modifier les règles de connexion pour les agents FranceTravail
  itou/openid_connect/inclusion_connect/views.py
  tests/openid_connect/inclusion_connect/tests.py
Labels: modifié

#4530 API: Ajout de l'accès à l'api agences de FranceTravail
  itou/utils/apis/pole_emploi.py
  tests/utils/apis/test_pole_emploi_api.py
Labels: no-changelog

#4539 PASS IAE: Simplification de la detection de pass valides
  itou/approvals/models.py
Labels: no-changelog

#4541 changelog: From 2024-08-05 to 2024-08-11
  CHANGELOG.md
Labels: no-changelog

#4533 Tests : Retirer l’ignore du warning sur Blowfish
  pytest.ini
Labels: no-changelog

#4534 tests: Utiliser tous les context_processors de Django dans la 500 personnalisée
  itou/www/error.py
Labels: no-changelog

#4542 Corriger des typos dans le journal des modifications
  CHANGELOG.md
Labels: no-changelog

#3150 Règles plus restrictives pour la suppression de certain objets afin de ne pas créer d'incohérences de données
  itou/approvals/migrations/0004_alter_approval_created_by_and_more.py
  itou/approvals/models.py
  itou/common_apps/address/models.py
  itou/common_apps/organizations/models.py
  itou/companies/migrations/0006_alter_company_created_by_alter_company_insee_city_and_more.py
  itou/companies/models.py
  itou/eligibility/migrations/0005_alter_administrativecriteria_created_by_and_more.py
  itou/eligibility/models/common.py
  itou/eligibility/models/geiq.py
  itou/eligibility/models/iae.py
  itou/geiq/migrations/0002_alter_implementationassessment_reviewed_by_and_more.py
  itou/geiq/models.py
  itou/institutions/migrations/0006_alter_institution_insee_city_and_more.py
  itou/institutions/models.py
  itou/job_applications/migrations/0008_alter_jobapplication_approval_and_more.py
  itou/job_applications/models.py
  itou/prescribers/migrations/0005_alter_prescribermembership_updated_by_and_more.py
  itou/prescribers/models.py
  itou/siae_evaluations/migrations/0002_alter_evaluatedadministrativecriteria_administrative_criteria_and_more.py
  itou/siae_evaluations/models.py
  itou/users/migrations/0009_alter_user_created_by_alter_user_insee_city.py
  itou/users/models.py
  tests/job_applications/test_transfer.py
  tests/www/apply/test_process.py
  tests/www/approvals_views/test_prolongation_requests.py
Labels: modifié

#4550 Accessibilité: toujours inclure un texte pour les boutons copier-coller
  itou/templates/includes/copy_to_clipboard.html
  tests/gps/__snapshots__/test_views.ambr
Labels: modifié

#4553 templates: utilisation généralisé de l'include copy_to_clipboard.html
  itou/templates/apply/includes/job_application_sender_info.html
  itou/templates/apply/includes/job_seeker_info.html
  itou/templates/approvals/includes/list_card.html
  itou/templates/companies/includes/_company_info.html
  itou/templates/employee_record/includes/list_item.html
  itou/templates/includes/email_li.html
  itou/templates/includes/phone_li.html
  tests/www/companies_views/__snapshots__/test_card_views.ambr
  tests/www/geiq_views/__snapshots__/tests.ambr
Labels: 1-recette-jetable, no-changelog

#4446 Page d’accueil : modale nouveautés
  config/settings/base.py
  itou/communications/admin.py
  itou/communications/cache.py
  itou/communications/migrations/0002_announcementcampaign_announcementitem_and_more.py
  itou/communications/models.py
  itou/templates/layout/_news_modal.html
  itou/templates/layout/base.html
  itou/utils/context_processors.py
  tests/communications/__snapshots__/test_campaigns.ambr
  tests/communications/factories.py
  tests/communications/test_cache.py
  tests/communications/test_campaigns.py
  tests/communications/test_models.py
  tests/conftest.py
  tests/utils/tests.py
Labels: ajouté

#4551 Utiliser `--no-strip-extras` pour coller au fonctionnement de dependabot et réduire la diff/bruit dans ses PR
  Makefile
  requirements/base.txt
  requirements/dev.txt
  requirements/test.txt
Labels: no-changelog

#4558 Ajout d'un accent au mot Émetteur
  itou/job_applications/admin_forms.py
  itou/templates/apply/includes/job_application_sender_info.html
  tests/job_applications/test_admin.py
  tests/job_applications/tests.py
Labels: no-changelog

#4559 Toujours passer le bon type de PK aux factories
  tests/api/test_geiq.py
  tests/employee_record/test_transfer_employee_records.py
  tests/job_applications/factories.py
  tests/www/apply/test_list.py
Labels: no-changelog

#4565 changelog: From 2024-08-12 to 2024-08-18
  CHANGELOG.md
Labels: no-changelog

#4555 Script pour ajouter un utilisateur en tant qu'admin à une liste de SIREN tout en désactivant certaines de ses notifications
  itou/scripts/management/commands/add_admin_for_company_group.py
Labels: ajouté

#4566 Créer les FAST MACHINE avec la bonne version de python
  scripts/create-fast-machine.sh
Labels: no-changelog

#4576 tests: MàJ commentaires du assertNumQueries de test_approval_status_includes
  tests/www/approvals_views/test_detail.py
Labels: no-changelog

#4574 Retirer une requête de Approval.latest_approval
  itou/users/models.py
  tests/www/apply/test_process.py
  tests/www/approvals_views/test_detail.py
Labels: no-changelog

#4525 Utiliser le nom de la vue au lieu de l’URL pour définir la partie active du header
  itou/templates/layout/_header_nav_secondary_items.html
Labels: no-changelog

#4580 UX/UI : Optimisation des performances étranges sur les images d'illustration de la homepage
  itou/templates/search/siaes_search_home.html
Labels: modifié

#4579 docker: Changement mineur à l’entrypoint.sh
  docker/dev/django/entrypoint.sh
Labels: no-changelog

#4581 dependabot : Correction d'une erreur de syntaxe
  .github/dependabot.yml
Labels: no-changelog

#4586 UX/UI: Suppression de la mention "ex pôle emploi" pour France Travail
  itou/approvals/migrations/0001_initial.py
  itou/approvals/models.py
  itou/eligibility/data/administrative_criteria.json
  itou/templates/admin/approvals/includes/job_application_details.html
  itou/templates/apply/includes/job_seeker_info.html
  itou/templates/apply/includes/profile_infos.html
  itou/users/migrations/0001_initial.py
  itou/users/models.py
  itou/utils/validators.py
  itou/www/apply/forms.py
  itou/www/apply/views/common.py
  itou/www/employee_record_views/forms.py
  tests/www/apply/test_process.py
  tests/www/dashboard/test_edit_user_info.py
Labels: supprimé

#4590 Candidature : Correction de l'acception quand la ville de naissance n'est pas référencée pour la date de naissance renseignée
  itou/asp/forms.py
  itou/static/js/utils.js
  itou/templates/employee_record/create.html
Labels: modifié

#4532 [GEN-1835] Profil salarié: Accès à la Immersion Facilitée sur la page de salarié
  itou/templates/approvals/detail.html
  itou/utils/constants.py
  itou/utils/immersion_facile.py
  itou/www/approvals_views/views.py
  tests/utils/test_immersion_facile.py
  tests/www/approvals_views/__snapshots__/test_detail.ambr
  tests/www/approvals_views/test_detail.py
Labels: ajouté

#4573 [GEN-1927] Demandeur d’emploi: coordonnées importées des conseillers de France Travail
  itou/gps/excel.py
  itou/gps/management/commands/import_advisor_information.py
  itou/gps/migrations/0005_francetravailcontact.py
  itou/gps/models.py
  itou/templates/users/details.html
  itou/users/admin.py
  itou/www/users_views/views.py
  tests/gps/__snapshots__/test_views.ambr
  tests/gps/factories.py
  tests/gps/test_management_commands.py
  tests/gps/test_views.py
  tests/users/factories.py
Labels: ajouté

#4593 UX/UI : Harmonisation des “x résultats” au dessus d’une liste de résultats
  itou/templates/apply/includes/list_counter.html
  itou/templates/approvals/includes/list_counter.html
  itou/templates/employee_record/includes/list_counter.html
  itou/templates/search/includes/prescribers_search_summary.html
  itou/templates/search/includes/siaes_search_top.html
  tests/www/apply/test_process_external_transfer.py
Labels: modifié

#4594 UX/UI: Taille bouton "Modifier ces infos"
  itou/templates/dashboard/edit_user_info.html
  tests/www/dashboard/__snapshots__/test_edit_user_info.ambr
Labels: modifié

#4596 changelog: From 2024-08-19 to 2024-08-25
  CHANGELOG.md
Labels: no-changelog

#4595 Candidature: correction d'affichage dans des cas rares
  itou/templates/apply/includes/accept_section.html
  itou/templates/apply/includes/job_application_accept_form.html
  itou/www/apply/views/common.py
Labels: no-changelog

#4597 Candidatures : Indiquer la date minimale pour les champs début et fin de contrat
  itou/www/apply/forms.py
Labels: modifié

#4607 Tableau de bord : Indiquer aux collaborateurs France Travail de contacter le support si l’adresse de leur agence est incorrecte [GEN-1919]
  itou/templates/dashboard/dashboard.html
Labels: modifié

#4606 UX/UI : Affichage des messages de succès liés à l’authentification en toast [GEN-1916]
  itou/users/adapter.py
Labels: modifié

#4610 Tableau de bord - Organisation : N'afficher le sous-menu des annexes financières que si il est utilisable
  itou/templates/companies/job_description_list.html
  itou/templates/companies/members.html
  itou/www/companies_views/views.py
  tests/www/companies_views/test_job_description_views.py
Labels: modifié

#4588 Pilotage : Création de l'institution "Convergence France" et ouverture des TB446 et TB469 pour celle-ci
  itou/institutions/enums.py
  itou/institutions/migrations/0007_convergence_institution.py
  itou/templates/dashboard/includes/stats.html
  itou/utils/apis/metabase.py
  itou/www/dashboard/views.py
  itou/www/stats/urls.py
  itou/www/stats/utils.py
  itou/www/stats/views.py
Labels: ajouté

#4608 PASS IAE : Suppression de l’import des agréments Pôle Emploi [GEN-1974]
  itou/templates/approvals/pe_approval_search.html
  itou/templates/approvals/pe_approval_search_found.html
  itou/templates/approvals/pe_approval_search_user.html
  itou/templates/dashboard/includes/employer_employees_card.html
  itou/users/models.py
  itou/www/approvals_views/forms.py
  itou/www/approvals_views/urls.py
  itou/www/approvals_views/views.py
  tests/www/approvals_views/test_pe_approval.py
  tests/www/dashboard/test_dashboard.py
Labels: supprimé

#4611 Préférer les constantes de JobApplicationWorkflow au lieu de leurs valeurs
  itou/job_applications/models.py
Labels: no-changelog

#4613 GPS : Toujours afficher l’encart conseiller emploi France Travail
  itou/templates/users/details.html
  itou/www/users_views/views.py
  tests/gps/__snapshots__/test_views.ambr
  tests/gps/test_views.py
Labels: no-changelog

#4592 Pilotage : Ajouter des encarts pour les prochains webinaires
  itou/templates/stats/stats.html
  itou/www/stats/views.py
Labels: ajouté

#4615 Pilotage: déplacer la création d'institutions d'une migration à une fixture
  itou/fixtures/django/05_test_users.json
  itou/fixtures/django/06_confirmed_emails.json
  itou/fixtures/django/16_institutions.json
  itou/fixtures/django/17_institution_memberships.json
  itou/institutions/migrations/0007_convergence_institution.py
Labels: no-changelog

#4620 GEIQ: correctif du champs "Commune de naissance" à l'acceptation d'une candidature
  itou/asp/forms.py
  itou/www/apply/forms.py
  itou/www/apply/views/common.py
  itou/www/employee_record_views/forms.py
  tests/www/apply/test_forms.py
Labels: no-changelog
