Repository gip-inclusion/les-emplois, pull requests merged in 2024-10, with the labels that each got.

#4783 GEIQ : Masquer les diagnostics d’éligibilité employeurs aux prescripteurs [GEN-1975]
  itou/www/apply/views/submit_views.py
  tests/www/apply/test_submit.py
Labels: modifié

#4780 Expliquer le tri des GEIQEligibilityDiagnosis avec un commentaire
  itou/eligibility/models/geiq.py
Labels: no-changelog

#4782 Renommer la variable siae de la vue _accept en company
  itou/templates/apply/includes/accept_section.html
  itou/templates/apply/includes/job_application_accept_form.html
  itou/templates/apply/submit/hire_confirmation.html
  itou/www/apply/views/common.py
Labels: no-changelog

#4857 MàJ les commentaires de allauth dans requirements/base.in
  requirements/base.in
Labels: no-changelog

#4763 Vérifier l’existence d’une `apply_session` après ApplicationJobsView
  itou/www/apply/views/process_views.py
  itou/www/apply/views/submit_views.py
  tests/www/apply/test_geiq.py
  tests/www/apply/test_process_external_transfer.py
  tests/www/apply/test_submit.py
Labels: no-changelog

#4858 Retour arriére : Pilotage : Ouvrir le TB 440 à toutes les SIAE
  config/settings/base.py
  itou/templates/dashboard/includes/stats.html
  itou/www/dashboard/views.py
  itou/www/stats/utils.py
  itou/www/stats/views.py
  tests/www/stats/test_views.py
Labels: supprimé, pilotage

#4855 UX/UI: forcer la position .dropdown-menu sur les menu "mon espace" et "besoin d'aide"
  itou/templates/layout/_header.html
  itou/templates/layout/_header_authenticated.html
  itou/utils/staticfiles.py
  tests/www/__snapshots__/test_layout.ambr
Labels: no-changelog

#4859 Admin: vérification automatique de certaines règles de cohérence
  itou/utils/admin.py
  tests/job_applications/test_admin.py
Labels: modifié

#4862 admin: Autoriser `blank=True` pour les critères administratifs sélectionnés
  itou/eligibility/migrations/0007_geiqselectedadministrativecriteria_certification_period_and_more.py
  itou/eligibility/models/common.py
Labels: no-changelog

#4828 Connexion : Empêcher les utilisateurs de remplacer leur SSO une fois ils sont inscrit [GEN-2115]
  itou/openid_connect/france_connect/models.py
  itou/openid_connect/inclusion_connect/models.py
  itou/openid_connect/models.py
  itou/openid_connect/pe_connect/models.py
  tests/openid_connect/france_connect/tests.py
  tests/openid_connect/pe_connect/tests.py
Labels: modifié

#4742 Performances: Utilisation de Brevo à la place de Mailjet pour la gestion de campagnes mails
  clevercloud/cron.json
  config/settings/base.py
  config/settings/test.py
  itou/users/management/commands/new_users_to_brevo.py
  itou/users/management/commands/new_users_to_mailjet.py
  tests/users/test_management_commands.py
Labels: modifié

#4834 Employeur : ajouter un éditeur de texte markdown sur les grands champs de saisie
  config/settings/base.py
  itou/static/js/easymde_config.js
  itou/templates/companies/card.html
  itou/templates/companies/create_siae.html
  itou/templates/companies/edit_job_description_details.html
  itou/templates/companies/edit_siae_description.html
  itou/templates/companies/edit_siae_preview.html
  itou/templates/companies/includes/_job_description_details.html
  itou/templates/prescribers/card.html
  itou/templates/prescribers/edit_organization.html
  itou/utils/urls.py
  itou/utils/widgets.py
  itou/www/companies_views/forms.py
  itou/www/prescribers_views/forms.py
  requirements/base.in
  requirements/base.txt
  requirements/dev.txt
  requirements/test.txt
  tests/www/companies_views/test_card_views.py
  tests/www/companies_views/test_edit_company_views.py
  tests/www/companies_views/test_job_description_views.py
  tests/www/prescribers_views/test_edit.py
Labels: 1-recette-jetable, ajouté

#4874 Performance: réduction du nombre de requête nécessaire pour l'encart PASS IAE en cas de suspension active
  itou/approvals/models.py
  itou/templates/approvals/includes/box.html
  tests/approvals/tests.py
  tests/www/approvals_views/__snapshots__/test_suspend.ambr
Labels: no-changelog

#4864 Vie privée: suppression pour les orienteurs des nom/prénom des candidats auxquels ils ne sont pas censés avoir accès [GEN-2129]
  itou/www/apply/forms.py
  itou/www/apply/views/list_views.py
  tests/www/apply/__snapshots__/test_list_prescriptions.ambr
  tests/www/apply/test_list_prescriptions.py
Labels: 1-recette-jetable, modifié

#4863 Tech: fiabiliser la création de recette jetable
  .github/workflows/review-app-creation.yml
Labels: 1-recette-jetable, no-changelog

#4877 Performance: ajout d'index sur la date de naissance pour fluidifier le parcours de création d'utilisateur
  itou/users/migrations/0014_alter_jobseekerprofile_birthdate__add_index.py
  itou/users/models.py
Labels: no-changelog

#4876 tests: amélioration de `ProlongationFactory`
  tests/approvals/factories.py
  tests/metabase/management/test_populate_metabase_emplois.py
Labels: no-changelog

#4871 Amélioration des méthodes `has_data_changed()`
  itou/users/models.py
Labels: no-changelog

#4880 changelog: From 2024-09-30 to 2024-10-06
  CHANGELOG.md
Labels: no-changelog

#4878 Performance: utilisation d'une annotation pour éviter des requêtes en boucle
  itou/job_applications/models.py
  itou/templates/apply/includes/list_card_body_company.html
  itou/www/apply/views/list_views.py
  tests/www/apply/__snapshots__/test_list_for_siae.ambr
  tests/www/apply/__snapshots__/test_list_prescriptions.ambr
Labels: no-changelog

#4900 pro_connect: hide migation banner until the real switch
  itou/templates/account/login_generic.html
Labels: no-changelog

#4902 PASS IAE: suppression lors de l'annulation de la dernière candidature acceptée [GEN-2032]
  itou/approvals/models.py
  tests/approvals/tests.py
Labels: modifié

#4882 Candidature: Amélioration de la validation du NIR
  itou/users/models.py
  tests/www/dashboard/test_edit_user_info.py
Labels: modifié

#4903 Candidature: Correction de la sélection de commune quand le code insee a changé depuis la naissance du candidat
  itou/www/apply/forms.py
  tests/www/apply/test_forms.py
Labels: modifié

#4906 Admin: suppression du total de tous les objets sur la page de liste de certains objets
  itou/approvals/admin.py
  itou/employee_record/admin.py
  itou/users/admin.py
Labels: modifié

#4907 Tableau de bord: Suppression du bandeau GPS GEN-2146
  itou/templates/dashboard/dashboard.html
Labels: modifié

#4879 migration unittest -> pytest
  requirements/dev.txt
  requirements/test.in
  requirements/test.txt
  tests/api/siae_api/tests.py
  tests/job_applications/tests.py
  tests/openid_connect/france_connect/tests.py
  tests/prescribers/tests.py
  tests/rdv_insertion/tests.py
  tests/users/__snapshots__/test_management_commands.ambr
  tests/users/test_management_commands.py
  tests/utils/apis/test_entreprise_api.py
  tests/utils/apis/test_pole_emploi_api.py
  tests/utils/htmx/test.py
  tests/utils/htmx/tests.py
  tests/utils/perms/tests.py
  tests/utils/tests.py
  tests/www/announcements/test_views.py
  tests/www/apply/__snapshots__/test_process.ambr
  tests/www/apply/__snapshots__/test_submit.ambr
  tests/www/apply/test_edit.py
  tests/www/apply/test_forms.py
  tests/www/apply/test_process.py
  tests/www/apply/test_submit.py
  tests/www/approvals_views/__snapshots__/test_prolongation.ambr
  tests/www/approvals_views/__snapshots__/test_suspend.ambr
  tests/www/approvals_views/test_display.py
  tests/www/approvals_views/test_prolongation.py
  tests/www/approvals_views/test_suspend.py
  tests/www/autocomplete/tests.py
  tests/www/companies_views/__snapshots__/test_card_views.ambr
  tests/www/companies_views/__snapshots__/test_job_description_views.ambr
  tests/www/companies_views/test_card_views.py
  tests/www/companies_views/test_edit_company_views.py
  tests/www/companies_views/test_financial_annex_views.py
  tests/www/companies_views/test_forms.py
  tests/www/companies_views/test_job_description_views.py
  tests/www/dashboard/__snapshots__/test_edit_job_seeker_info.ambr
  tests/www/dashboard/__snapshots__/test_edit_user_info.ambr
  tests/www/dashboard/__snapshots__/test_edit_user_notifications.ambr
  tests/www/dashboard/test_edit_job_seeker_info.py
  tests/www/dashboard/test_edit_user_email.py
  tests/www/dashboard/test_edit_user_info.py
  tests/www/dashboard/test_edit_user_notifications.py
  tests/www/dashboard/test_switch_organization.py
  tests/www/eligibility_views/tests.py
  tests/www/employee_record_views/__snapshots__/test_create.ambr
  tests/www/employee_record_views/__snapshots__/test_list.ambr
  tests/www/employee_record_views/test_create.py
  tests/www/employee_record_views/test_disable.py
  tests/www/employee_record_views/test_list.py
  tests/www/employee_record_views/test_reactivate.py
  tests/www/employee_record_views/test_summary.py
  tests/www/home/tests.py
  tests/www/invitations_views/test_prescriber_organization.py
  tests/www/login/tests.py
  tests/www/siae_evaluations_views/__snapshots__/test_institutions_views.ambr
  tests/www/siae_evaluations_views/test_institutions_views.py
  tests/www/siae_evaluations_views/test_views.py
Labels: no-changelog

#4881 Admin - Fiches salarié : Corriger la supression
  itou/employee_record/admin.py
  tests/employee_record/test_admin.py
Labels: no-changelog

#4909 Enlever le bandeau “Nouveauté” concernant l’archivage des Candidatures sur la page des candidatures GEN-2153
  itou/templates/apply/list_for_siae.html
Labels: no-changelog

#4883 UX/UI: Correction du positionnement du bouton “Régulariser le n° de sécurité sociale”
  itou/templates/employee_record/includes/list_item.html
  tests/www/employee_record_views/__snapshots__/test_list.ambr
Labels: no-changelog

#4917 Contrôle a posteriori: amélioration de l'admin pour afficher l'état d'une auto-prescription au sein d'une entreprise contrôlée
  itou/siae_evaluations/admin.py
  tests/siae_evaluations/test_admin.py
Labels: modifié

#4915 changelog: From 2024-10-07 to 2024-10-13
  CHANGELOG.md
Labels: no-changelog

#4905 admin: amélioration de la recherche de PASS IAE
  itou/approvals/admin.py
  tests/approvals/test_admin.py
Labels: modifié

#4930 Admin: amélioration de la recherche des PASS IAE par numéro
  itou/approvals/admin.py
Labels: no-changelog

#4911 UX/UI: Ajouter un hover au choix de structure
  itou/utils/staticfiles.py
Labels: 1-recette-jetable, modifié

#4914 UX/UI: N'afficher les infos PASS que dans l'onglet "Informations générales"
  itou/templates/apply/process_base.html
  itou/templates/apply/process_details.html
  itou/templates/apply/process_details_company.html
  itou/templates/apply/submit/check_job_seeker_info_for_hire.html
  itou/templates/apply/submit/eligibility_for_hire.html
  itou/templates/job_seekers_views/details.html
  tests/www/apply/__snapshots__/test_process.ambr
  tests/www/job_seekers_views/__snapshots__/test_details.ambr
Labels: 1-recette-jetable, modifié

#4935 tests: migration de tests vers `assertSnapshotQueries`
  tests/api/employee_record_api/__snapshots__/tests.ambr
  tests/api/employee_record_api/tests.py
  tests/siae_evaluations/__snapshots__/test_models.ambr
  tests/siae_evaluations/test_models.py
  tests/users/__snapshots__/test_admin_views.ambr
  tests/users/test_admin_views.py
  tests/utils/test.py
  tests/www/apply/__snapshots__/test_list_for_siae.ambr
  tests/www/apply/__snapshots__/test_list_prescriptions.ambr
  tests/www/apply/__snapshots__/test_process.ambr
  tests/www/apply/test_process.py
  tests/www/approvals_views/__snapshots__/test_list.ambr
  tests/www/companies_views/__snapshots__/test_job_description_views.ambr
  tests/www/job_seekers_views/__snapshots__/test_list.ambr
  tests/www/search/__snapshots__/tests.ambr
  tests/www/search/tests.py
Labels: no-changelog

#4904 UX/UI : Passage de quelques font-weight-* à fw-*
  itou/static/js/formset_add_remove_row.js
Labels: no-changelog

#4933 Employeur : Correction de l'import EA/EATT quand d'autres fichiers sont présents
  itou/companies/management/commands/import_ea_eatt.py
  tests/companies/test_import_ea_eatt.py
Labels: no-changelog

#4934 Stabilité: Correction du fonctionnement des "copy to clipboard" apres htmx:load
  itou/utils/staticfiles.py
Labels: 1-recette-jetable, no-changelog, modifié

#4932 Candidature: uniformisation de l'affichage des noms de candidat et d'utilisateur dans les filtres de recherche
  itou/www/apply/forms.py
  tests/www/apply/test_list_prescriptions.py
Labels: modifié

#4937 Candidature: normalisation de l'affichage des noms et prénoms
  itou/templates/apply/email/diagoriente_prescriber_invite_body.txt
  itou/templates/apply/includes/job_seeker_info.html
  itou/templates/users/details.html
  tests/gps/__snapshots__/test_views.ambr
Labels: modifié

#4943 requirements: passage à Django 5.1
  itou/approvals/migrations/0001_initial.py
  itou/approvals/models.py
  itou/communications/migrations/0001_initial.py
  itou/communications/migrations/0002_announcementcampaign_announcementitem_and_more.py
  itou/communications/models.py
  itou/eligibility/migrations/0001_initial.py
  itou/eligibility/migrations/0002_remove_geiqadministrativecriteria_ac_level_annex_coherence_and_more.py
  itou/eligibility/models/geiq.py
  itou/geiq/migrations/0001_initial.py
  itou/geiq/models.py
  itou/job_applications/migrations/0001_initial.py
  itou/job_applications/migrations/0006_jobapplication_processed_coherence.py
  itou/job_applications/migrations/0009_jobapplication_archived_at.py
  itou/job_applications/models.py
  itou/prescribers/migrations/0001_initial.py
  itou/prescribers/migrations/0006_prescriberorganization_prevent_validated_authorization_if_other.py
  itou/prescribers/models.py
  itou/siae_evaluations/migrations/0001_initial.py
  itou/siae_evaluations/models.py
  itou/users/migrations/0001_initial.py
  itou/users/models.py
  requirements/base.in
  requirements/base.txt
  requirements/dev.txt
  requirements/test.txt
  tests/users/__snapshots__/test_admin_views.ambr
  tests/users/test_admin_views.py
  tests/www/apply/__snapshots__/test_list_for_siae.ambr
  tests/www/companies_views/__snapshots__/test_job_description_views.ambr
  tests/www/dashboard/__snapshots__/test_dashboard.ambr
  tests/www/itou_staff_views/__snapshots__/tests.ambr
  tests/www/siae_evaluations_views/__snapshots__/test_institutions_views.ambr
  tests/www/signup/__snapshots__/test_siae.ambr
Labels: no-changelog

#4953 Candidature: correction de l'affichage du diagnostic dans le parcours d'embauche
  itou/templates/apply/submit/hire_confirmation.html
  tests/www/apply/__snapshots__/test_submit.ambr
Labels: no-changelog

#4944 UX/UI: Modifier l’icone “sens interdit” dans la liste des collaborateurs
  itou/templates/includes/members.html
Labels: no-changelog

#4954 changelog: From 2024-10-14 to 2024-10-20
  CHANGELOG.md
Labels: no-changelog

#4949 tests: correction de test instable
  itou/www/apply/views/process_views.py
  itou/www/apply/views/submit_views.py
  itou/www/employees_views/views.py
Labels: no-changelog

#4950 Prescripteur : Ignorer les diagnostics d’éligibilité des auto-prescriptions [GEN-1657]
  itou/www/apply/views/submit_views.py
  tests/www/apply/test_submit.py
Labels: 1-recette-jetable, modifié

#4952 Tableau de bord: correction du message lié au délai de carence pour l'encart PASS IAE du candidat
  itou/job_applications/models.py
  itou/templates/dashboard/includes/job_seeker_approval_card.html
  itou/users/models.py
  tests/users/test_models.py
  tests/www/apply/__snapshots__/test_process.ambr
  tests/www/apply/__snapshots__/test_submit.ambr
Labels: modifié

#4948 UX/UI: Ajout d'un sondage Maze sur la page des candidatures [GEN-2162]
  itou/templates/apply/list_for_siae.html
Labels: no-changelog

#4788 Candidature : le bouton Annuler renvoie vers la fiche de poste ou l'entreprise
  itou/templates/apply/submit/application/resume.html
  itou/templates/apply/submit_step_check_job_seeker_nir.html
  itou/templates/apply/submit_step_job_seeker.html
  itou/templates/apply/submit_step_job_seeker_check_info.html
  itou/www/apply/views/submit_views.py
  tests/www/apply/test_submit.py
Labels: 1-recette-jetable, modifié

#4955 github: Possiblité de notifier seulement le pilotage
  .github/workflows/notify-slack.yml
Labels: no-changelog, pilotage

#4970 Mise à jour du wording "Fiches salarié"
  CHANGELOG.md
  itou/approvals/admin.py
  itou/templates/approvals/list.html
  itou/templates/dashboard/includes/employer_employees_card.html
  itou/templates/employee_record/list.html
  itou/utils/templatetags/nav.py
  tests/www/__snapshots__/test_layout.ambr
  tests/www/dashboard/test_dashboard.py
Labels: no-changelog

#4968 github: Possiblité de notifier seulement le pilotage (pour de vrai cette fois)
  .github/workflows/notify-slack.yml
Labels: no-changelog, pilotage

#4967 Fiches salarié : Alléger le texte d’introduction de la page “liste des fiches salarié” [GEN-1813]
  itou/templates/employee_record/includes/list_results.html
  itou/templates/employee_record/includes/list_status_help.html
  itou/templates/employee_record/list.html
Labels: modifié

#4980 Corriger les diags des tests/eligibility/test_iae
  tests/eligibility/test_iae.py
Labels: no-changelog

#4984 UX/UI: Fix outdated date for the GIP
  itou/templates/includes/gip_address.html
  itou/templates/static/accessibility.html
  itou/templates/static/legal/notice.html
  itou/templates/static/legal/privacy.html
Labels: no-changelog

#4981 Limitation du prénom à 30 caractères dans le sérialiseur à destination de l'ASP
  itou/employee_record/serializers.py
  tests/employee_record/test_serializers.py
Labels: modifié

#4975 Correction d'un message d'erreur
  itou/www/apply/forms.py
Labels: no-changelog

#4976 tests: découper test_selected_administrative_criteria_certified
  tests/eligibility/test_iae.py
Labels: no-changelog

#4979 Retirer l’argument save de SelectedAdministrativeCriteria.certify
  itou/eligibility/models/common.py
  tests/eligibility/test_iae.py
  tests/www/apply/test_templates.py
Labels: no-changelog

#4987 RDVI: Réalignement du contenu de la modale à gauche
  itou/templates/apply/includes/appointments.html
  tests/www/apply/__snapshots__/test_detail_rdv_insertion.ambr
Labels: no-changelog

#4986 Mise à jour de clever-deploy
  scripts/clever-deploy
Labels: no-changelog

#5006 Amélioration de la page d'édition des informations personelles pour les comptes ProConnectés
  itou/templates/dashboard/edit_user_info.html
  tests/www/dashboard/test_edit_user_info.py
Labels: no-changelog

#5008 template: Fix typo
  itou/templates/dashboard/edit_user_info.html
Labels: no-changelog

#4978 Déplacer CAN_BE_CERTIFIED_KINDS vers AdministrativeCriteriaKind
  itou/eligibility/enums.py
  itou/eligibility/models/common.py
  tests/eligibility/test_iae.py
  tests/www/apply/test_process.py
  tests/www/apply/test_submit.py
Labels: no-changelog

#5011 Admin: Permettre de libérer des comptes ProConnect pour bascule Employer <-> Prescripteur
  itou/users/admin.py
  tests/users/test_admin_views.py
Labels: modifié

#5014 Connexion: Correction du message d'erreur pour les comptes Inclusion Connect
  itou/www/login/forms.py
  tests/openid_connect/inclusion_connect/tests.py
  tests/www/login/tests.py
Labels: modifié

#5013 UX/UI: Remplacer message de confirmation de maj de la fiche structure par un toast
  itou/www/companies_views/views.py
  itou/www/prescribers_views/views.py
Labels: modifié

#5016 UX/UI: Retirer le bouton “Retour vers la liste des postes”
  itou/templates/companies/job_description_card.html
  tests/www/companies_views/test_job_description_views.py
Labels: modifié

#5022 Connexion: Bloquer l'accès à la connexion Inclusion Connect quand ProConnect est activé
  itou/openid_connect/inclusion_connect/views.py
  tests/openid_connect/inclusion_connect/tests.py
Labels: modifié

#5020 UX/UI: Corriger l'alignement du texte dans les modales imbriquées
  itou/static/css/itou.css
Labels: 1-recette-jetable, modifié
