Repository gip-inclusion/les-emplois, pull requests merged in 2024-03, with the labels that each got.

#3724 scripts: Correction pour `imports-asp.sh` suite à d1ce32902 et f7b6f4400
  scripts/imports-asp.sh
Labels: no-changelog

#3749 security.txt: vérification et mise à jour
  itou/templates/static/security/security.txt
Labels: no-changelog

#3750 Refonte UX/UI: Maj UI des cartes de postes ouverts au recrutement
  itou/templates/companies/includes/_card_jobdescription.html
  itou/templates/search/prescribers_search_results.html
  tests/www/search/tests.py
Labels: recette-jetable

#3752 Fix candidature card job list
  itou/companies/models.py
  itou/templates/approvals/includes/job_description_list.html
  tests/www/apply/__snapshots__/test_list.ambr
Labels: recette-jetable

#3745 Pilotage : Modifier un intitulé de TB privé des SIAE [GEN-8137]
  itou/templates/dashboard/includes/stats.html
  tests/www/dashboard/tests.py
Labels: no-changelog

#3748 Import GEIQ : Utiliser un argument plutôt qu'un chemin obligatoire
  itou/companies/management/commands/import_geiq.py
Labels: no-changelog

#3733 Ajout du statut du PASS IAE dans l'export des candidatures (employeurs et prescripteurs)
  itou/job_applications/export.py
  tests/job_applications/tests.py
Labels: recette-jetable

#3735 Retrait du NewDnsRedirectMiddleware
  config/settings/base.py
  itou/utils/new_dns/__init__.py
  itou/utils/new_dns/middleware.py
  tests/utils/new_dns/tests.py
Labels: no-changelog

#3699 Appairer des assert{Not,}Contains dans tests.www.companies_views
  tests/www/companies_views/test_job_description_views.py
Labels: no-changelog

#3713 Appairer les assert{Not,}Contains dans tests.www.dashboard
  tests/www/dashboard/tests.py
Labels: no-changelog

#3758 Améliorer le comportement responsif du placeholder select2 sur la recherche
  itou/static/css/itou.css
  itou/templates/search/includes/prescribers_search_form.html
  itou/templates/search/includes/siaes_search_form.html
  itou/www/search/forms.py
  tests/www/dashboard/__snapshots__/tests.ambr
Labels: recette-jetable

#3046 [ADRESSES] Proposer l'autocomplétion des adresses des candidats [GEN-3540]
  config/settings/base.py
  itou/static/js/address_autocomplete_fields.js
  itou/templates/dashboard/edit_job_seeker_info.html
  itou/templates/dashboard/edit_user_info.html
  itou/templates/dashboard/includes/edit_job_seeker_info_form.html
  itou/users/admin_forms.py
  itou/users/migrations/0044_user_address_filled_at.py
  itou/users/models.py
  itou/utils/mocks/address_format.py
  itou/utils/widgets.py
  itou/www/dashboard/forms.py
  tests/scripts/test_users_geolocation.py
  tests/www/dashboard/__snapshots__/tests.ambr
  tests/www/dashboard/tests.py
Labels: recette-jetable

#3751 Refonte UX/UI: Maj UI des cartes siae
  itou/templates/companies/includes/_card_siae.html
  itou/templates/companies/includes/_list_siae_actives_jobs.html
  itou/templates/companies/includes/_list_siae_actives_jobs_row.html
  tests/www/search/tests.py
Labels: recette-jetable

#3762 Sprint 82 : Journal des changements
  CHANGELOG.md
Labels: no-changelog

#3769 Suppression de commandes personnalisées liées au modèle `PoleEmploiApproval`
  itou/approvals/management/commands/check_approvals_date.py
  itou/approvals/management/commands/update_nir_from_pe_data.py
  itou/approvals/models.py
  itou/scripts/liste-agrements-22_03-fake.xlsx
  itou/scripts/management/commands/import_pe_approvals.py
  itou/scripts/management/commands/import_pe_approvals_siret_kind.py
  itou/scripts/management/commands/merge_pe_approvals.py
  itou/scripts/management/commands/send_pe_approvals_to_pe.py
  itou/scripts/management/commands/update_pe_approvals_from_asp_data.py
  tests/scripts/tests.py
Labels: no-changelog

#3771 Correction mineure de tests.companies_views
  tests/www/companies_views/test_views.py
Labels: no-changelog

#3801 Préparation Django 5 - mark_safe
  itou/utils/perms/middleware.py
  itou/www/approvals_views/forms.py
Labels: no-changelog

#3802 tests: correction d'un test
  tests/users/test_admin.py
Labels: no-changelog

#3779 Ajouter API_BAN_BASE_URL en dev
  .env.template
  CHANGELOG_breaking_changes.md
Labels: no-changelog

#3780 Forcer DEBUG=False dans settings.base
  config/settings/base.py
Labels: no-changelog

#3799 MàJ des dates de PASS IAE dans les fixtures [GEN-8242]
  itou/fixtures/django/21_approvals.json
Labels: no-changelog

#3805 Retirer pytest-timeout
  README.md
  pytest.ini
  requirements/base.txt
  requirements/dev.txt
  requirements/test.in
  requirements/test.txt
Labels: discussion

#3812 Fix échecs intermittents DRF rate-limits
  config/settings/base.py
  itou/utils/cache.py
  tests/www/companies_views/__snapshots__/test_views.ambr
  tests/www/companies_views/test_views.py
Labels: no-changelog

#3815 Retirer du CSS inutilisé pour htmx-indicator
  itou/static/css/itou.css
Labels: no-changelog

#3816 templates: suppression du type="button" d'une balise <a>
  itou/templates/layout/_header_nav_primary_items.html
  tests/www/__snapshots__/test_layout.ambr
Labels: no-changelog

#3818 Mise à jour du nom des recettes jetables
  .github/workflows/review-app-creation.yml
  .github/workflows/review-app-removal.yml
Labels: no-changelog

#3836 Proposition d'ajout au readme
  README.md
Labels: no-changelog

#3817 Migration à l'assertMessages natif de Django 5
  tests/approvals/test_admin.py
  tests/approvals/tests.py
  tests/employee_record/test_admin.py
  tests/job_applications/test_admin.py
  tests/openid_connect/inclusion_connect/tests.py
  tests/siae_evaluations/test_admin.py
  tests/users/test_admin_views.py
  tests/utils/test.py
  tests/utils/tests.py
  tests/www/apply/test_process.py
  tests/www/apply/test_submit.py
  tests/www/approvals_views/test_pe_approval.py
  tests/www/approvals_views/test_prolongation_requests.py
  tests/www/companies_views/test_job_description_views.py
  tests/www/employee_record_views/test_list.py
  tests/www/invitations_views/test_company_accept.py
  tests/www/invitations_views/test_prescriber_organization.py
  tests/www/login/tests.py
  tests/www/siae_evaluations_views/test_institutions_views.py
  tests/www/siae_evaluations_views/test_siaes_views.py
  tests/www/signup/test_prescriber.py
  tests/www/signup/test_siae.py
Labels: no-changelog

#3835 Refonte UX/UI: Maj du fonctionnement responsif des onglets
  itou/static/js/sliding_tabs.js
  itou/templates/companies/card.html
  itou/templates/companies/job_description_card.html
  itou/templates/companies/job_description_list.html
  itou/templates/companies/members.html
  itou/templates/companies/show_financial_annexes.html
  itou/templates/layout/base.html
  itou/utils/staticfiles.py
  tests/www/companies_views/__snapshots__/test_views.ambr
Labels: 1-recette-jetable

#3845 Filtre candidatures sur Mobile
  itou/utils/staticfiles.py
Labels: 1-recette-jetable

#3626 Makefile: ajout d'une cible fast_fix
  Makefile
Labels: no-changelog

#3831 changelog: Sprint 83
  CHANGELOG.md
Labels: no-changelog

#3852 Admin: amélioration du texte d'explication du champs "ID unique envoyé à l'ASP"
  itou/users/admin.py
  tests/users/test_admin_views.py
Labels: no-changelog

#3854 Liste de candidatures: correctif pour les prescripteurs et candidat
  itou/static/js/job_applications_filters.js
Labels: 1-recette-jetable
