Repository gip-inclusion/les-emplois, pull requests merged in 2025-02, with the labels that each got.

#5514 Candidature: le message de mise en attente par lot est maintenant optionnel
  itou/www/apply/forms.py
  tests/www/apply/__snapshots__/test_list_for_siae.ambr
  tests/www/apply/test_batch_views.py
Labels: modifié

#5519 Sentry: ignorer le logger `django_datadog_logger.middleware.request_log`
  config/sentry.py
Labels: no-changelog

#5513 Simplifier update_admin_role
  itou/common_apps/organizations/views.py
Labels: no-changelog

#5521 Réusinage de l’activation/désactivation du statut administrateur d’un membre d’une organisation
  itou/common_apps/organizations/models.py
  itou/common_apps/organizations/views.py
Labels: no-changelog

#5520 Tech: amélioration de la détection des étapes précédentes manquantes
  itou/www/apply/views/batch_views.py
  tests/www/apply/test_batch_views.py
Labels: no-changelog

#5498 Pilotage: Étendre commande extract_c2_users avec plus des données
  itou/users/management/commands/extract_c2_users.py
Labels: no-changelog

#5515 GPS: Créer et mettre à jour les groupes de suivi
  itou/gps/management/commands/init_follow_up_groups.py
  itou/gps/management/commands/sync_follow_up_groups_and_members.py
  itou/gps/management/commands/update_follow_up_groups_member_created_at.py
  tests/gps/test_management_commands.py
Labels: modifié

#5517 Admin: Permettre de modifier la date de début de suivi d'un membre de groupe GPS
  itou/gps/admin.py
  tests/gps/test_admin.py
Labels: modifié

#5518 changelog: From 2025-01-27 to 2025-02-02
  CHANGELOG.md
Labels: no-changelog

#5538 fixtures: Correction suite à un changement d'un modèle GPS
  itou/fixtures/django/27_follow_up_group_memberships.json
Labels: no-changelog

#5534 Renommer PrescriberWithOrg{Sent,}InvitationFactory
  tests/invitations/factories.py
  tests/invitations/tests.py
  tests/www/invitations_views/test_helpers.py
  tests/www/invitations_views/test_prescriber_organization.py
Labels: no-changelog

#5541 Technique: Amélioration du code de création de fiches salariées
  itou/www/employee_record_views/views.py
  tests/www/employee_record_views/__snapshots__/test_add.ambr
  tests/www/employee_record_views/test_add.py
Labels: tech

#5539 Tech: bascule des commandes de transfert de fiche salarié vers des logs
  itou/employee_record/common_management.py
  itou/employee_record/management/commands/transfer_employee_records.py
  itou/employee_record/management/commands/transfer_employee_records_updates.py
  tests/employee_record/__snapshots__/test_transfer_employee_records.ambr
  tests/employee_record/__snapshots__/test_transfer_employee_records_updates.ambr
  tests/employee_record/test_transfer_employee_records.py
  tests/employee_record/test_transfer_employee_records_updates.py
Labels: no-changelog

#5542 Tableau de bord: Retrait du bandeau pour inviter les candidats autonomes à un webinaire d'information
  itou/templates/dashboard/dashboard.html
Labels: supprimé

#5543 Tableau de bord: Retrait du bandeau promotionnel de GPS pour le Gard
  itou/templates/dashboard/dashboard.html
Labels: supprimé

#5547 Pilotage : Correction typo dans populate_metabase_matomo.py
  itou/metabase/management/commands/populate_metabase_matomo.py
  tests/metabase/management/__snapshots__/test_populate_metabase_matomo.ambr
Labels: no-changelog, bug

#5523 Tests : vérifier le contenu de la modale confirmant un candidat trouvé par son NIR ou son email
  itou/templates/job_seekers_views/step_search_job_seeker_by_email.html
  tests/gps/test_create_beneficiary.py
  tests/www/apply/test_submit.py
Labels: no-changelog

#5550 Tests : retrait des assertions dupliquées assertContains et assertRedirects
  tests/gps/test_create_beneficiary.py
  tests/www/apply/test_submit.py
  tests/www/apply/test_submit_from_job_seekers_list.py
Labels: no-changelog

#5552 UX/UI: Correction UI du spinner sur les switch
  itou/utils/staticfiles.py
Labels: 1-recette-jetable, modifié

#5522 Simplification de update_admin_role pour suivre deactivate_membership
  itou/common_apps/organizations/views.py
  itou/www/companies_views/views.py
  itou/www/institutions_views/views.py
  itou/www/prescribers_views/views.py
Labels: no-changelog

#5553 Performance: dénormalisation des tailles d'image dans la base de données - partie 1
  itou/communications/migrations/0004_announcementitem_image_height_and_more.py
  itou/communications/models.py
Labels: no-changelog

#5548 Tech: ajout d'une option pour alerter sur des fichiers ayant disparu de notre bucket
  itou/files/management/commands/sync_s3_files.py
  tests/files/tests.py
Labels: tech

#5556 Technique: Correction d'une regression apportée par #5541
  itou/www/employee_record_views/views.py
  tests/www/employee_record_views/test_add.py
Labels: no-changelog, bug

#5557 UX.UI: Formulation plus claire pour la liste des candidatures émises par une structure pour le compte d'un candidat [GEN-129]
  itou/templates/job_seekers_views/job_applications.html
  tests/www/job_seekers_views/__snapshots__/test_details.ambr
Labels: no-changelog

#5561 Performances : amélioration des requêtes pour la liste des candidats
  itou/www/job_seekers_views/views.py
  tests/www/job_seekers_views/__snapshots__/test_list.ambr
Labels: no-changelog

#5563 PASS IAE: réduction de la fréquence d'envoi
  clevercloud/cron.json
Labels: no-changelog

#5565 Tech: mise à jour de notre code pour rester compatible avec l'API ROME de FranceTravail
  itou/utils/apis/pole_emploi.py
  tests/jobs/management/test_sync_romes_and_appellations.py
  tests/utils/apis/test_pole_emploi_api.py
Labels: tech

#5568 changelog: From 2025-02-03 to 2025-02-09
  CHANGELOG.md
Labels: no-changelog

#5558 Employeur: Rendre le numéro de téléphone optionel dans le formulaire de création d'entreprise [GEN-737]
  itou/www/companies_views/forms.py
  tests/www/companies_views/test_edit_company_views.py
Labels: modifié

#5564 Tests: Améliorer les tests du menu de navigation
  tests/utils/test_templatetags.py
Labels: no-changelog

#5566 Tech: vérification des incohérences entre notre base de données et notre bucket une fois par jour
  clevercloud/cron.json
Labels: no-changelog

#5571 UX/UI: Supprimer lien vers webinaire dans introjsSwitchView
  itou/templates/apply/list_for_siae.html
Labels: modifié

#5569 Pilotage: Ajout du nom au extrait utilisateurs
  itou/users/management/commands/extract_c2_users.py
Labels: no-changelog, pilotage

#5560 Stabilité: Correction d'une redirection cassée après avoir annulé une embauche [GEN-2188]
  itou/www/apply/views/process_views.py
  tests/www/apply/test_process.py
Labels: modifié, bug

#5583 RGPD: Ne pas mettre les adresses géolocalisées par les management commands dans la sortie standard
  itou/companies/management/commands/update_companies_coords.py
  itou/users/management/commands/update_job_seeker_coords.py
  tests/companies/test_management_commands.py
  tests/users/test_management_commands.py
Labels: modifié

#5585 Retirer une fixture non utilisée de TestCreateEmployeeRecordStep1
  tests/www/employee_record_views/test_create.py
Labels: no-changelog

#5587 API: amélioration de notre réponse d'erreur
  config/settings/base.py
  itou/api/errors.py
  tests/api/test_error.py
Labels: tech

#5590 tests: Simplifier TestCreateEmployeeRecordStep3.test_fail_step_3
  tests/www/employee_record_views/test_create.py
Labels: no-changelog

#5380 A11Y: Amélioration de l'accessibilité des tooltip
  itou/templates/apply/includes/appointments.html
  itou/templates/apply/includes/buttons/rdv_insertion_invite.html
  itou/templates/apply/includes/job_seeker_info.html
  itou/templates/apply/includes/next_appointment.html
  itou/templates/apply/includes/transfer_job_application.html
  itou/templates/apply/list_of_available_exports.html
  itou/templates/apply/process_refuse.html
  itou/templates/approvals/details.html
  itou/templates/approvals/includes/box.html
  itou/templates/approvals/includes/list_card.html
  itou/templates/approvals/prolongation_requests/list.html
  itou/templates/approvals/prolongation_requests/show.html
  itou/templates/companies/edit_siae.html
  itou/templates/companies/includes/_company_info.html
  itou/templates/companies/job_description_list.html
  itou/templates/dashboard/includes/dashboard_title_content.html
  itou/templates/dashboard/includes/employer_job_applications_card.html
  itou/templates/includes/members.html
  itou/templates/job_seekers_views/includes/list_results.html
  tests/www/apply/__snapshots__/test_detail_rdv_insertion.ambr
  tests/www/apply/__snapshots__/test_list_for_siae.ambr
  tests/www/apply/__snapshots__/test_list_rdv_insertion.ambr
  tests/www/apply/__snapshots__/test_process.ambr
  tests/www/apply/test_submit_from_job_seekers_list.py
  tests/www/approvals_views/__snapshots__/test_approval_box.ambr
  tests/www/approvals_views/__snapshots__/test_detail.ambr
  tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
  tests/www/geiq_views/__snapshots__/tests.ambr
  tests/www/job_seekers_views/__snapshots__/test_details.ambr
  tests/www/job_seekers_views/__snapshots__/test_list.ambr
  tests/www/job_seekers_views/test_list.py
Labels: modifié

#5593 UX/UI: Un seul champ de saisie par ligne
  itou/templates/companies/edit_siae.html
Labels: modifié

#5594 Pilotage: Correction de crash sur les TdBs ETP quand un utilisateur est aussi membre des non-SIAEs
  itou/www/stats/views.py
Labels: no-changelog, pilotage, bug

#5600 docs: Retirer des références aux variables Mailjet pour le compte principal
  docs/environment.md
Labels: no-changelog

#5606 Admin: permettre de chercher par public_id
  itou/users/admin.py
  tests/users/test_admin.py
Labels: modifié

#5608 Correction d'un nom de test
  tests/prescribers/tests.py
Labels: no-changelog

#5611 Fiches Salarié : Correction du phrasé pour la première étape du tunnel de création
  itou/templates/employee_record/add.html
  tests/www/employee_record_views/__snapshots__/test_add.ambr
Labels: no-changelog

#5615 Tech: correction de configuration des logs `huey`
  config/settings/base.py
Labels: no-changelog

#5620 changelog: From 2025-02-10 to 2025-02-16
  CHANGELOG.md
Labels: no-changelog

#5260 Pilotage: Supprimer populate_metabase_flux_iae
  itou/companies/management/commands/_import_siae/utils.py
  itou/metabase/dataframes.py
  itou/metabase/db.py
  itou/metabase/management/commands/populate_metabase_emplois.py
  itou/metabase/management/commands/populate_metabase_fluxiae.py
  scripts/import-iae.sh
Labels: tech, pilotage

#5624 MàJ d’un setting pour django-allauth 65.4.0
  config/settings/base.py
Labels: no-changelog

#5570 Réutiliser JobSeekerProfileForm dans EditJobSeekerInfoForm [GEN-1380]
  itou/www/dashboard/forms.py
  tests/www/dashboard/__snapshots__/test_edit_job_seeker_info.ambr
  tests/www/dashboard/__snapshots__/test_edit_user_info.ambr
Labels: no-changelog

#5642 GPS: Changer des DatetimeField en DateField
  itou/gps/admin.py
  itou/gps/management/commands/sync_follow_up_groups_and_members.py
  itou/gps/migrations/0012_alter_followupgroupmembership_ended_at.py
  itou/gps/migrations/0013_alter_followupgroupmembership_started_at.py
  itou/gps/models.py
  tests/gps/factories.py
  tests/gps/test_admin.py
  tests/gps/test_models.py
  tests/gps/test_views.py
Labels: no-changelog

#5650 UX/UI: Suppression de la mise en avant du bouton "Postuler pour ce candidat"
  itou/templates/job_seekers_views/includes/list_results.html
  itou/templates/job_seekers_views/list.html
  tests/www/apply/test_submit_from_job_seekers_list.py
  tests/www/job_seekers_views/__snapshots__/test_list.ambr
  tests/www/job_seekers_views/test_list.py
Labels: modifié

#5652 [GEN-2208] Changement d’intitulé pour le filtre des candidatures archivées
  itou/templates/apply/includes/job_applications_filters/offcanvas_body.html
  tests/www/apply/__snapshots__/test_list_for_siae.ambr
  tests/www/apply/__snapshots__/test_list_prescriptions.ambr
Labels: modifié

#5656 Sécurité: amélioration de `get_safe_url`
  itou/utils/urls.py
  tests/utils/tests.py
Labels: tech

#5659 Tech: rétablissement de la fréquence d'envoi des PASS IAE à France Travail
  clevercloud/cron.json
Labels: tech

#5646 GPS: Correction du retrait d'un groupe
  itou/gps/admin.py
  itou/gps/migrations/0014_fill_memberships_ended_at.py
  itou/gps/models.py
  itou/www/gps/views.py
  tests/gps/__snapshots__/test_views.ambr
  tests/gps/test_admin.py
  tests/gps/test_models.py
  tests/gps/test_views.py
Labels: modifié

#5647 GPS: refactor des tests
  tests/gps/__snapshots__/test_views.ambr
  tests/gps/test_views.py
Labels: no-changelog

#5662 Fiches salarié: correction d'une faute dans le libellé d'un badge
  itou/templates/employee_record/includes/_status.html
Labels: no-changelog

#5602 Prescripteur: ajout de tri dans la liste des candidats [GEN-1844]
  itou/templates/common/tables/th_with_sort.html
  itou/templates/job_seekers_views/includes/list_results.html
  itou/templates/job_seekers_views/list.html
  itou/utils/staticfiles.py
  itou/www/job_seekers_views/enums.py
  itou/www/job_seekers_views/views.py
  tests/www/job_seekers_views/__snapshots__/test_list.ambr
  tests/www/job_seekers_views/test_enums.py
  tests/www/job_seekers_views/test_list.py
Labels: 1-recette-jetable, modifié

#5666 PASS IAE: correction du code empêchant l'envoi d'un PASS avant sa date de début
  itou/approvals/models.py
Labels: modifié, bug

#5667 Retirer des asserts inutiles dans pro_connect/tests.py
  tests/openid_connect/pro_connect/tests.py
Labels: no-changelog

#5668 Candidat: stabilisation du tri en cas d'égalité
  itou/www/job_seekers_views/enums.py
  itou/www/job_seekers_views/views.py
  tests/www/job_seekers_views/__snapshots__/test_list.ambr
  tests/www/job_seekers_views/test_list.py
Labels: 1-recette-jetable, modifié, bug

#5672 changelog: From 2025-02-17 to 2025-02-23
  CHANGELOG.md
Labels: no-changelog

#5669 Convertir les SiaeFinancialAnnex {start,end}_at en date
  itou/companies/management/commands/_import_siae/financial_annex.py
  itou/companies/management/commands/_import_siae/utils.py
  itou/companies/management/commands/_import_siae/vue_af.py
  itou/companies/migrations/0015_fix_financial_annexes_dates.py
  itou/companies/migrations/0016_alter_siaefinancialannex_end_at_and_more.py
  itou/companies/models.py
  tests/companies/factories.py
  tests/companies/test_import_siae_command.py
Labels: no-changelog, bug

#5685 GPS: Mise à jour du document Grist
  itou/gps/grist.py
Labels: no-changelog

#5686 Correction des fixtures des annexes financières
  itou/fixtures/django/12_siae_financial_annexes.json
Labels: 1-recette-jetable, no-changelog

#5671 Fiches salarié : Autoriser les employeur à séléctionner une annexe financière non valide [GEN-2245]
  itou/templates/employee_record/includes/create_step_4.html
  itou/www/employee_record_views/forms.py
  tests/www/employee_record_views/test_create.py
Labels: 1-recette-jetable, modifié

#5690 Recettes jetable : Limiter le nom à 63 caractères
  .github/workflows/review-app-creation.yml
  .github/workflows/review-app-removal.yml
Labels: no-changelog

#5657 Fiches salarié : retirer la mention champs obligatoire de l’étape de sélection des Annexes financières dans le parcours des fiches salarié [GEN-2213]
  itou/templates/employee_record/includes/create_step_4.html
Labels: supprimé

#5658 Tableau de bord (équipe support uniquement) : modifier le nom “comité technique d’animation” par “export des prescripteurs et employeurs” [GEN-2209]
  itou/templates/dashboard/includes/staff_export_card.html
Labels: no-changelog

#5701 Pilotage : Mise à jour des formulaire Tally pour les tableaux de bord ETP employeurs
  itou/utils/apis/metabase.py
Labels: no-changelog, pilotage

#5699 GPS: Ajout d'un bouton pour modifier le profil candidat
  itou/templates/gps/group_beneficiary.html
  itou/www/gps/views.py
  tests/gps/__snapshots__/test_views.ambr
  tests/gps/test_views.py
Labels: modifié

#5700 UX/UI: mise a jour du theme vers v2.7.3
  itou/utils/staticfiles.py
Labels: 1-recette-jetable, modifié

#5702 Alimenter les listes de contacts Brevo avec certains profils candidats [GEN-1400]
  clevercloud/cron.json
  itou/users/management/commands/send_users_to_brevo.py
  tests/users/test_management_commands.py
Labels: modifié

#5707 Fiche entreprise : Correctif de la phrase “Cet employeur accepte de recevoir des candidatures spontanées” pour les employeurs qui ont bloqué la réception de candidatures [GEN-2279]
  itou/templates/companies/card.html
  tests/www/companies_views/__snapshots__/test_card_views.ambr
Labels: modifié, bug
