Repository gip-inclusion/les-emplois, pull requests merged in 2025-08, with the labels that each got.

#6610 [API] Pole emploi : utilisation d'un client en gestionnaire de contexte
  itou/approvals/management/commands/send_approvals_to_pe.py
  itou/approvals/models.py
  itou/jobs/management/commands/sync_romes_and_appellations.py
  itou/users/management/commands/pe_certify_users.py
  itou/utils/apis/pole_emploi.py
  tests/jobs/management/test_sync_romes_and_appellations.py
  tests/utils/apis/test_pole_emploi_api.py
Labels: no-changelog

#6650 [API] Déplacement de `pole_emploi_api_client` vers son module
  itou/approvals/management/commands/send_approvals_to_pe.py
  itou/approvals/models.py
  itou/companies/management/commands/sync_ft_offers.py
  itou/jobs/management/commands/sync_romes_and_appellations.py
  itou/prescribers/management/commands/sync_ft_organizations.py
  itou/users/management/commands/pe_certify_users.py
  itou/utils/apis/__init__.py
  itou/utils/apis/pole_emploi.py
  tests/users/test_management_commands.py
Labels: no-changelog

#6651 GPS: Correction de l'affichage des informations personnelles des intervenants
  itou/templates/gps/group_memberships.html
  tests/gps/__snapshots__/test_views.ambr
Labels: modifié, bug

#6657 Tech: Ajout d'un fichier `__init__.py` manquant
  itou/utils/apis/__init__.py
Labels: no-changelog

#6659 Test: Correction d'un utilitaire pour le rendre prédictif
  tests/archive/__snapshots__/tests_management_command.ambr
  tests/archive/tests_management_command.py
Labels: no-changelog

#6646 Pilotage : Rendre le téléversement du flux IAE plus robuste
  clevercloud/cron.json
  config/settings/dev.py
  itou/metabase/management/commands/upload_data_to_pilotage.py
  tests/metabase/management/__snapshots__/test_upload_data_to_pilotage.ambr
  tests/metabase/management/test_upload_data_to_pilotage.py
Labels: no-changelog, pilotage

#6674 PASS IAE: Ne plus envoyer les PASS à FT entre minuit et 1h CET/CEST [GEN-2651]
  clevercloud/cron.json
Labels: no-changelog

#6677 Fiches de poste: Désactivation des fiches de poste non mises à jour par l'employeur uniquement si créées depuis les Emplois [GEN-2649]
  itou/companies/management/commands/deactivate_old_job_descriptions.py
  itou/companies/migrations/0007_auto_20250807_1719.py
  itou/companies/models.py
  tests/companies/test_management_commands.py
Labels: modifié, bug

#6678 Invitations: Ajout de liens vers la documentation sur la page d'invitation de collaborateurs [GEN-2597]
  itou/templates/includes/members_list.html
  tests/www/companies_views/__snapshots__/test_members_views.ambr
  tests/www/prescribers_views/__snapshots__/test_members.ambr
Labels: modifié

#6680 Candidat: Permettre de copier son ID candidat depuis le tableau de bord [GEN-2567]
  itou/templates/dashboard/includes/dashboard_title_content.html
  tests/www/dashboard/__snapshots__/test_dashboard.ambr
  tests/www/dashboard/test_dashboard.py
Labels: 1-recette-jetable, ajouté

#6709 Prescripteur: Ajout d'un bandeau d’alerte pour une enquête Maze
  itou/templates/dashboard/dashboard.html
Labels: ajouté

#6707 Interface: Placer le badge d'archivage après le badge du statut de candidature
  itou/utils/templatetags/badges.py
Labels: modifié

#6705 Vie privée : refactor des tests de la commande d'anonymisation des candidats [1/2]
  tests/archive/__snapshots__/tests_management_command.ambr
  tests/archive/tests_management_command.py
Labels: no-changelog

#6729 Tech: ajout du setting `PILOTAGE_SLACK_WEBHOOK_URL`
  config/settings/base.py
  itou/metabase/management/commands/populate_metabase_emplois.py
  itou/metabase/management/commands/populate_metabase_matomo.py
Labels: no-changelog

#6728 Tech: ajout d'une vérification de cohérence quotidienne
  clevercloud/cron.json
  config/settings/base.py
  itou/utils/admin.py
  itou/utils/management/commands/check_inconsistencies.py
  tests/utils/test_check_inconsistencies.py
Labels: no-changelog

#6723 Contrôle a posteriori : Mise à jour d'une mention relative aux justificatifs [GEN-2657]
  itou/templates/siae_evaluations/includes/criterion_infos.html
  tests/www/siae_evaluations_views/__snapshots__/test_siaes_views.ambr
  tests/www/siae_evaluations_views/test_siaes_views.py
Labels: modifié

#6733 Vie privée : retrait d'une mention RGPD incomprise causant beaucoup de demande au support [GEN-2678]
  itou/templates/account/email/email_jobseeker_created_by_third_party_body.txt
  itou/templates/account/email/email_jobseeker_created_by_third_party_for_gps_body.txt
  tests/users/__snapshots__/test_models.ambr
Labels: modifié

#6603 Admin : Enrichir les fiches salarié avec les détails de l’entreprise
  itou/employee_record/admin.py
  tests/employee_record/test_admin.py
Labels: modifié

#6653 Fiche de poste : N'afficher l'entrée dédiée aux candidatures spontanées que sur la première page de la liste
  itou/templates/companies/job_description_list.html
  tests/www/companies_views/test_job_description_views.py
Labels: no-changelog

#6753 FranceConnect: récupération du genre de l'utilisateur
  itou/openid_connect/france_connect/models.py
  tests/openid_connect/france_connect/tests.py
  tests/www/signup/test_job_seeker.py
Labels: modifié

#6754 tests: Définir la date de certification quand un critère est certifié
  tests/eligibility/factories.py
  tests/openid_connect/france_connect/tests.py
  tests/openid_connect/pe_connect/tests.py
  tests/siae_evaluations/test_models.py
  tests/www/apply/test_process.py
  tests/www/apply/test_templates.py
  tests/www/dashboard/test_edit_job_seeker_info.py
  tests/www/dashboard/test_edit_user_info.py
  tests/www/employee_record_views/test_create.py
  tests/www/job_seekers_views/test_create_or_update.py
  tests/www/siae_evaluations_views/test_institutions_views.py
  tests/www/siae_evaluations_views/test_siaes_views.py
Labels: no-changelog

#6758 Vie privée : Supprimer le modèle OriginalPoleEmploiApproval [251]
  itou/approvals/migrations/0004_delete_originalpoleemploiapproval.py
  itou/approvals/models.py
Labels: no-changelog
