Repository gip-inclusion/les-emplois, pull requests merged in 2025-05, with the labels that each got.

#6063 Interface: Inversion des blocs structure et orientation sur le dashboard
  itou/templates/dashboard/dashboard.html
  itou/templates/dashboard/includes/employer_prescription_card.html
Labels: 1-recette-jetable, modifié

#6072 Interface : harmonisation de la formulation en "numéro SIRET"
  itou/templates/static/legal/terms.html
  itou/www/companies_views/forms.py
  itou/www/signup/forms.py
  tests/www/companies_views/test_create_company_views.py
Labels: modifié

#6070 Correction d'une coquille sur la page de connexion candidat
  itou/templates/account/login_job_seeker.html
Labels: no-changelog

#6058 Eligibilité : Ajouter un badge pour indiquer les critères non certifiés [GEN-2008]
  itou/templates/apply/includes/certification_info_box.html
  itou/templates/apply/includes/selected_administrative_criteria_display.html
  tests/www/apply/test_templates.py
Labels: ajouté

#6044 Utiliser le SessionNamespace pour sécuriser l’édition des fiches de poste [GEN-2311]
  itou/templates/companies/edit_job_description_details.html
  itou/templates/companies/edit_job_description_preview.html
  itou/templates/companies/job_description_card.html
  itou/www/companies_views/urls.py
  itou/www/companies_views/views.py
  tests/www/apply/test_process_external_transfer.py
  tests/www/companies_views/test_job_description_views.py
Labels: modifié

#6075 Admin: Amélioration d'une description de champ [GEN-2325]
  itou/approvals/models.py
Labels: modifié

#6076 Inscription: Sécuriser l’inscription des OPCS pour éviter les offres frauduleuses [GEN-2373]
  itou/www/signup/views.py
  tests/www/signup/test_siae.py
Labels: modifié

#6068 Interface: ajout de la classe .stretched-link manquante sur les cartes de job_description
  itou/templates/companies/includes/_card_jobdescription.html
Labels: 1-recette-jetable, modifié

#6088 Candidature: Vérifier l'identité de l'utilisateur pour accéder à la page de fin de candidature
  itou/www/apply/views/submit_views.py
  tests/job_applications/factories.py
  tests/www/apply/test_submit.py
Labels: modifié

#6073 [Prescripteur] Ajout d'un message pour les admins des CD
  itou/templates/prescribers/list_accredited_organizations.html
Labels: 1-recette-jetable, ajouté

#6089 Contrôle a posteriori : Réusinage du badge d’état des candidatures pour les SIAE [GEN-2345]
  itou/siae_evaluations/models.py
  itou/siae_evaluations/templatetags/__init__.py
  itou/siae_evaluations/templatetags/siae_evaluations_siae_tags.py
  itou/templates/siae_evaluations/includes/job_seeker_infos_for_siae.html
Labels: no-changelog

#6092 RDV Insertion : Création d’un groupe pour un accès restreint à l’interface administateur
  itou/users/management/commands/sync_group_and_perms.py
  tests/users/__snapshots__/test_sync_group_and_perms.ambr
Labels: ajouté

#6093 Pilotage : Réparer le TB "Suivi des prescriptions des AHI" pour la DIHAL
  itou/utils/apis/metabase.py
  itou/www/stats/views.py
Labels: no-changelog, pilotage

#6098 Fiche de poste: correction d'un nom de test erronné
  tests/www/companies_views/__snapshots__/test_job_description_views.ambr
  tests/www/companies_views/test_job_description_views.py
Labels: no-changelog

#6069 Fiche de poste: Mise à jour de l'ordonnancement des fiches
  itou/companies/models.py
  itou/www/companies_views/views.py
  tests/www/companies_views/__snapshots__/test_job_description_views.ambr
  tests/www/companies_views/test_job_description_views.py
Labels: modifié

#6100 Admin : Rendre les champs utilisateurs éditables même lorsque son identité est certifiée
  itou/users/admin.py
  tests/users/test_admin.py
Labels: modifié, bug

#6103 Pilotage : Ajouter l’absence/présence de CV dans la table candidatures de Metabase [GEN-2272]
  itou/metabase/management/commands/populate_metabase_emplois.py
  itou/metabase/tables/job_applications.py
  tests/metabase/management/test_populate_metabase_emplois.py
Labels: ajouté

#6102 Candidature: Remplissage des CV des anciennes candidatures [GEN-2443]
  itou/job_applications/management/commands/fill_resume.py
  tests/job_applications/tests.py
Labels: modifié

#6097 Simplifier TestEvaluationCampaignManager.test_populate
  tests/siae_evaluations/test_models.py
Labels: no-changelog

#6107 Retirer la recette `make clean`
  Makefile
Labels: no-changelog

#6135 [API candidats] Correction d'un test
  tests/api/job_applications_api/test_search.py
Labels: no-changelog

#6134 Accessibilité: correction d'un `id` pour correspondre au `aria-labelledby`
  itou/templates/gps/join_group_from_name_and_email.html
  tests/gps/__snapshots__/test_views.ambr
Labels: no-changelog

#6137 Vie privée : ajout de EmployeeRecordTransitionLogFactory [GEN-2454]
  tests/employee_record/factories.py
Labels: no-changelog

#6127 Notifications : Utiliser les données Pilotage de l’inclusion pour identifier les candidats autonomes sans solutions
  itou/users/management/commands/send_users_to_brevo.py
  tests/users/test_management_commands.py
Labels: modifié

#6121 Nettoyage des URLs de gestion des fiches de poste
  itou/www/companies_views/urls.py
  itou/www/companies_views/views.py
  tests/www/companies_views/test_job_description_views.py
Labels: no-changelog

#6139 Éligibilité : Vérifier que le badge certifié n’était pas affiché aux employeurs après l’expiration du diag
  tests/www/apply/test_process.py
  tests/www/apply/test_templates.py
  tests/www/eligibility_views/utils.py
Labels: no-changelog

#6128 Interface : Petite amélioration de l’encart justificatif du contrôle a posteriori
  itou/templates/siae_evaluations/includes/criterion_infos.html
  tests/www/siae_evaluations_views/test_siaes_views.py
Labels: modifié

#6145 Prescripteur : dans la page d'édition de l'organisation, n'afficher l'alerte sur la visibilité des informations qu'aux prescripteurs habilités
  itou/templates/prescribers/edit_organization.html
  tests/www/prescribers_views/test_edit.py
Labels: no-changelog

#6124 changelog: From 2025-04-28 to 2025-05-04
  CHANGELOG.md
Labels: no-changelog

#6099 Accessibilité: Mise a jour du contenu de la page Accessibilité
  itou/templates/static/accessibility.html
  tests/www/test_static_views.py
Labels: no-changelog

#6129 Clarifier User.can_create_siae_antenna
  itou/users/models.py
Labels: no-changelog

#6158 Retirer les ignore_unknown_variable_template_error des tests siae_evaluations
  tests/www/siae_evaluations_views/test_institutions_views.py
  tests/www/siae_evaluations_views/test_siaes_views.py
Labels: no-changelog

#6161 Fin du bagotage pour prescribers_views.test_edit
  tests/www/prescribers_views/test_edit.py
Labels: no-changelog

#6160 Retrait d’un test en double dans tests/www/siae_evaluations_views/test_institutions_views.py
  tests/www/siae_evaluations_views/test_institutions_views.py
  tests/www/siae_evaluations_views/test_siaes_views.py
Labels: no-changelog

#6133 Vie privée : suppression du champ created_by dans les modèles AdministrativeCriteria [GEN-2453] (partie 1/2)
  itou/eligibility/admin.py
  itou/eligibility/data/administrative_criteria_geiq.json
  itou/eligibility/migrations/0012_remove_administrativecriteria_created_by_state_operation.py
  itou/eligibility/models/common.py
  tests/api/__snapshots__/test_geiq.ambr
  tests/users/test_admin.py
  tests/www/apply/__snapshots__/test_list_for_siae.ambr
  tests/www/apply/__snapshots__/test_list_prescriptions.ambr
  tests/www/itou_staff_views/__snapshots__/tests.ambr
  tests/www/siae_evaluations_views/__snapshots__/test_institutions_views.ambr
Labels: no-changelog

#6162 Vie privée : suppression du champ created_by dans les modèles AdministrativeCriteria [GEN-2453] (partie 2/2)
  itou/eligibility/migrations/0013_remove_administrative_criteria_created_by_database_operation.py
Labels: no-changelog

#6164 Fixtures : mise à jour de `test_users.json` pour ne pas avoir à remplir les info du candidat à chaque connexion
  itou/fixtures/django/05_test_users.json
Labels: no-changelog

#6173 Éligibilité : Correction de durées de certification de critères administratifs incorrects
  itou/eligibility/migrations/0014_selectedadministrativecriteria_empty_certification_period.py
Labels: modifié

#6170 Considérer les fixtures `.json` comme du texte et non comme des fichiers binaires
  itou/fixtures/django/.gitattributes
Labels: no-changelog

#6178 GEIQ: suppression de la fonction `sync_assessments`
  itou/geiq/sync.py
  tests/geiq/test_sync.py
Labels: no-changelog

#6065 Candidature: Passage a une session UUID
  itou/www/apply/urls.py
  itou/www/apply/views/process_views.py
  itou/www/apply/views/submit_views.py
  itou/www/job_seekers_views/urls.py
  itou/www/job_seekers_views/views.py
  tests/www/apply/__snapshots__/test_submit.ambr
  tests/www/apply/__snapshots__/test_submit_from_job_seekers_list.ambr
  tests/www/apply/test_geiq.py
  tests/www/apply/test_process_external_transfer.py
  tests/www/apply/test_submit.py
  tests/www/apply/test_submit_from_job_seekers_list.py
  tests/www/job_seekers_views/test_create_or_update.py
  tests/www/job_seekers_views/test_list.py
Labels: modifié

#6166 Vie privée : suppression du champ created_by dans les modèles AdministrativeCriteria [GEN-2453] (partie 3/2)
  itou/eligibility/migrations/0012_remove_administrativecriteria_created_by_state_operation.py
  itou/eligibility/migrations/0013_remove_administrative_criteria_created_by_database_operation.py
Labels: no-changelog

#6177 Éligibilité : Créer un nouveau diagnostic plutôt que modifier la date de fin lors de la mise à jour
  itou/eligibility/models/iae.py
  tests/eligibility/test_iae.py
Labels: modifié

#6147 [PASS IAE] Modification des dates de début de PASS IAE et de candidatures à partir d'un fichier Excel
  itou/approvals/management/commands/bulk_update_from_file.py
  tests/approvals/test_mng_cmd_bulk_update_from_file.py
Labels: no-changelog

#6181 Fiches salarié : correction d'un test bagottant
  tests/www/employee_record_views/test_list.py
Labels: no-changelog

#6183 Vie privée : suspension de la tâche
  clevercloud/cron.json
Labels: tech

#6186 GEIQ: suppression des permissions pour l'accès à l'admin des bilans d'exécution
  itou/users/management/commands/sync_group_and_perms.py
  tests/users/__snapshots__/test_sync_group_and_perms.ambr
Labels: no-changelog

#6188 Suppression d'un script à usage unique
  itou/approvals/management/commands/bulk_update_from_file.py
  tests/approvals/test_mng_cmd_bulk_update_from_file.py
Labels: no-changelog

#6210 Pilotage : Nettoyage de code à usage unique
  itou/www/stats/views.py
Labels: no-changelog

#6207 Fiches salarié : Ordre déterministe pour les objets sélectionnés lors du transfert
  itou/employee_record/management/commands/transfer_employee_records.py
  itou/employee_record/management/commands/transfer_employee_records_updates.py
  tests/employee_record/__snapshots__/test_transfer_employee_records.ambr
  tests/employee_record/test_transfer_employee_records.py
Labels: no-changelog

#6217 Reapply "suspend notify_archive_users task"
  clevercloud/cron.json
Labels: modifié

#6172 GPS: Ajout de logs plus précis
  itou/www/gps/forms.py
  itou/www/gps/utils.py
  itou/www/gps/views.py
  itou/www/job_seekers_views/views.py
  tests/gps/__snapshots__/test_views.ambr
  tests/gps/test_views.py
Labels: modifié

#6212 Interface: Intégrer les orientations et candidatures envoyées dans le menu latéral pour les employeurs [GEN-2257]
  itou/utils/templatetags/nav.py
  tests/www/__snapshots__/test_layout.ambr
Labels: ajouté

#6216 Fixtures : ajout du diagnostic d'éligibilité GEIQ à `dumpdata.sh`
  itou/fixtures/django/05_test_users.json
  itou/fixtures/django/06_confirmed_emails.json
  itou/fixtures/django/07_jobseeker_profile.json
  itou/fixtures/django/24_job_applications.json
  itou/fixtures/django/30_geiq_eligibility_diagnoses.json
  itou/fixtures/django/31_geiq_selected_administrative_criteria.json
  itou/fixtures/django/dumpdata.sh
Labels: 1-recette-jetable, no-changelog

#6222 Admin: Permettre aux membres du groupe itou-admin de modifier les nouveautés
  itou/users/management/commands/sync_group_and_perms.py
  tests/users/__snapshots__/test_sync_group_and_perms.ambr
Labels: modifié
