Repository gip-inclusion/les-emplois, pull requests merged in 2025-04, with the labels that each got.

#5837 Candidature: Correction du compteur de rendez-vous à venir
  itou/job_applications/models.py
  itou/templates/apply/includes/next_appointment.html
  itou/www/apply/views/list_views.py
  itou/www/apply/views/process_views.py
  tests/www/apply/__snapshots__/test_list_for_job_seeker.ambr
  tests/www/apply/__snapshots__/test_list_for_siae.ambr
  tests/www/apply/__snapshots__/test_process.ambr
  tests/www/apply/test_list_rdv_insertion.py
Labels: no-changelog, bug

#5858 Candidature: ajout d'une bannière pour inviter les employeurs à un entretien [GEN-2341]
  itou/templates/apply/list_for_siae.html
Labels: ajouté

#5859 Dev: ne pas demander l'OTP quand REQUIRE_OTP_FOR_STAFF est désactivé
  itou/utils/perms/middleware.py
  tests/companies/__snapshots__/test_admin.ambr
  tests/companies/test_admin.py
  tests/siae_evaluations/test_admin.py
  tests/users/__snapshots__/test_admin_views.ambr
  tests/www/itou_staff_views/__snapshots__/tests.ambr
  tests/www/login/tests.py
Labels: no-changelog

#5860 apis: Change data⋅inclusion themes
  itou/utils/apis/data_inclusion.py
  tests/utils/apis/test_data_inclusion_api.py
Labels: no-changelog

#5843 Rendre uv indispensable pour le développement
  .github/workflows/ci.yml
  CHANGELOG_breaking_changes.md
  Makefile
  README.md
  pyproject.toml
  requirements/dev.txt
  requirements/test.in
  requirements/test.txt
Labels: tech

#5863 Pilotage : Fusionner le TB traitement et résultats des candidatures recues par ma ou mes structures et déclarations d’embauche (394/185)
  itou/templates/dashboard/includes/stats.html
  itou/utils/apis/metabase.py
  itou/www/stats/urls.py
  itou/www/stats/views.py
  tests/www/dashboard/__snapshots__/test_dashboard_stats.ambr
Labels: no-changelog, pilotage

#5865 Maintenance: Ajout d'une bannière pour informer d'une future maintenance
  itou/templates/layout/base.html
Labels: no-changelog

#5866 Maintenance: retrait d'une bannière informant d'une maintenance
  itou/templates/layout/base.html
Labels: no-changelog

#5871 Nettoyage de code
  itou/utils/session.py
  itou/www/job_seekers_views/views.py
Labels: no-changelog

#5869 GPS: Suppression d'un formulaire tally pour inviter un partenaire
  itou/templates/gps/group_list.html
  tests/gps/__snapshots__/test_views.ambr
  tests/gps/test_views.py
Labels: no-changelog

#5867 Pilotage : Fusionner le TB auto-prescription et controle a posteriori
  itou/templates/dashboard/includes/stats.html
  itou/utils/apis/metabase.py
  itou/www/stats/urls.py
  itou/www/stats/views.py
  tests/www/dashboard/__snapshots__/test_dashboard_stats.ambr
Labels: no-changelog, pilotage

#5864 Candidature : Autoriser l'annulation quand la fiche salarié n'a pas été transmise
  itou/employee_record/models.py
  itou/job_applications/models.py
  tests/employee_record/factories.py
  tests/job_applications/tests.py
  tests/www/apply/__snapshots__/test_process.ambr
  tests/www/apply/test_process.py
Labels: modifié

#5875 GPS: Suppression de l'ancienne commande d'import de référents FT 1/2
  clevercloud/cron.json
  itou/gps/management/commands/import_advisor_information.py
  itou/gps/utils.py
  itou/users/admin.py
  itou/users/models.py
  tests/gps/factories.py
  tests/gps/test.py
  tests/gps/test_management_commands.py
  tests/users/factories.py
  tests/www/apply/test_submit.py
Labels: no-changelog

#5876 GPS: Suppression de l'ancienne commande d'import de référents FT 2/2
  itou/gps/migrations/0020_delete_francetravailcontact.py
  itou/gps/models.py
Labels: no-changelog

#5879 GPS: Ne pas créer de relations sur des utilisateurs non prescripteur ou employeur
  itou/gps/management/commands/sync_follow_up_groups_and_members.py
  itou/gps/models.py
  tests/gps/test_management_commands.py
  tests/gps/test_models.py
Labels: modifié, bug

#5877 Tableau de bord : Ajout d'un évènement matomo pour le lien des candidats sans solution
  itou/templates/dashboard/includes/prescriber_job_seekers_card.html
Labels: no-changelog

#5881 fixtures: ajout des DREETS & DDETS GEIQ pour les régions HDF/NA & NORM
  itou/fixtures/django/16_institutions.json
Labels: no-changelog

#5888 changelog: From 2025-03-31 to 2025-04-06
  CHANGELOG.md
Labels: no-changelog

#5891 Candidats : correction d'un test
  tests/www/job_seekers_views/__snapshots__/test_list.ambr
  tests/www/job_seekers_views/test_list.py
Labels: no-changelog

#5889 UX/UI: déplacement du contenu des pages d'erreur au bon endroit
  itou/templates/403.html
  itou/templates/404.html
  itou/templates/500.html
Labels: no-changelog

#5884 Migration de la CI & stack local en postgres 17
  .github/workflows/ci.yml
  .github/workflows/review-app-creation.yml
  CHANGELOG_breaking_changes.md
  docker-compose.yml
Labels: no-changelog

#5886 Tech: ajout d'un bouton de connexion rapide pour l'admin également
  itou/templates/includes/demo_accounts.html
  itou/utils/templatetags/demo_accounts.py
Labels: no-changelog

#5883 Pilotage : Suppression du TB 327 "Suivre le cofinancement de mon ACI"
  config/settings/base.py
  itou/templates/dashboard/includes/stats.html
  itou/utils/apis/metabase.py
  itou/www/dashboard/views.py
  itou/www/stats/urls.py
  itou/www/stats/utils.py
  itou/www/stats/views.py
  tests/www/dashboard/__snapshots__/test_dashboard_stats.ambr
  tests/www/dashboard/test_dashboard_stats.py
  tests/www/stats/test_utils.py
  tests/www/stats/test_views.py
Labels: supprimé, pilotage

#5748 Employeur : empêcher l'envoi de candidatures en cours dès que l'employeur ferme les offres
  itou/templates/apply/submit/application/jobs.html
  itou/www/apply/forms.py
  itou/www/apply/views/constants.py
  itou/www/apply/views/submit_views.py
  tests/www/apply/__snapshots__/test_submit.ambr
  tests/www/apply/test_submit.py
Labels: no-changelog

#5912 Retrait d’un auxiliaire de test de test_job_description_views.py
  tests/www/companies_views/test_job_description_views.py
Labels: no-changelog

#5913 Profil salarié : correction de la mention du PASS si celui-ci n'a pas démarré dans l'encart Immersion Facilitée
  itou/templates/employees/detail.html
  itou/www/employees_views/views.py
  tests/www/employees_views/__snapshots__/test_detail.ambr
  tests/www/employees_views/test_detail.py
Labels: modifié

#5914 Correction d'un test erratique
  itou/gps/management/commands/import_advisor_information.py
Labels: no-changelog

#5917 Amélioration du type d'un argument de management command
  itou/gps/management/commands/import_advisor_information.py
Labels: no-changelog

#5916 Simplifier test_empty_session_during_edit
  tests/www/companies_views/test_job_description_views.py
Labels: no-changelog

#5919 Data inclusion : séparation de deux thématiques
  itou/utils/apis/data_inclusion.py
  tests/utils/apis/test_data_inclusion_api.py
Labels: modifié, bug

#5920 Ajout du composant c-title aux templates account et announcements
  itou/templates/account/account_inactive.html
  itou/templates/account/account_type_selection.html
  itou/templates/account/email_confirm.html
  itou/templates/account/login_existing_user.html
  itou/templates/account/login_generic.html
  itou/templates/account/login_job_seeker.html
  itou/templates/account/logout.html
  itou/templates/account/password_change.html
  itou/templates/account/password_reset.html
  itou/templates/account/password_reset_done.html
  itou/templates/account/password_reset_from_key.html
  itou/templates/account/password_reset_from_key_done.html
  itou/templates/account/peamu_no_email.html
  itou/templates/account/verification_sent.html
  itou/templates/account/verify_otp.html
  itou/templates/announcements/news.html
  tests/www/signup/__snapshots__/test_password.ambr
Labels: modifié

#5925 Ajout du composant c-title aux templates geiq et job_seekers
  itou/templates/geiq/assessment_info_for_employer.html
  itou/templates/geiq/assessment_info_for_labor_inspector.html
  itou/templates/geiq/assessment_review.html
  itou/templates/geiq/employee_details.html
  itou/templates/geiq/geiq_list.html
  itou/templates/geiq/list_base.html
  itou/templates/job_seekers_views/check_job_seeker_info_for_hire.html
  itou/templates/job_seekers_views/create_or_update_job_seeker/step_base.html
  itou/templates/job_seekers_views/create_or_update_job_seeker/step_end.html
  itou/templates/job_seekers_views/details.html
  itou/templates/job_seekers_views/job_applications.html
  itou/templates/job_seekers_views/list.html
  itou/templates/job_seekers_views/step_check_job_seeker_nir.html
  itou/templates/job_seekers_views/submit_base_two_columns.html
  tests/www/apply/test_submit.py
  tests/www/geiq_views/__snapshots__/tests.ambr
  tests/www/job_seekers_views/__snapshots__/test_details.ambr
  tests/www/job_seekers_views/__snapshots__/test_list.ambr
Labels: 1-recette-jetable, modifié

#5926 Ajout du composant c-title aux templates gps, search et signup
  itou/templates/gps/group_details_base.html
  itou/templates/gps/group_edition.html
  itou/templates/gps/group_list.html
  itou/templates/gps/join_group.html
  itou/templates/gps/join_group_from_coworker.html
  itou/templates/gps/join_group_from_name_and_email.html
  itou/templates/gps/join_group_from_nir.html
  itou/templates/institutions/members.html
  itou/templates/logout/warning.html
  itou/templates/search/prescribers_search_results.html
  itou/templates/search/siaes_search_results.html
  itou/templates/signup/choose_user_kind.html
  itou/templates/signup/company_select.html
  itou/templates/signup/employer.html
  itou/templates/signup/facilitator_search.html
  itou/templates/signup/job_seeker_signup_base.html
  itou/templates/signup/prescriber_check_already_exists.html
  itou/templates/signup/prescriber_check_pe_email.html
  itou/templates/signup/prescriber_choose_kind.html
  itou/templates/signup/prescriber_choose_org.html
  itou/templates/signup/prescriber_confirm_authorization.html
  itou/templates/signup/prescriber_pole_emploi_safir_code.html
  itou/templates/signup/prescriber_pole_emploi_user.html
  itou/templates/signup/prescriber_request_invitation.html
  itou/templates/signup/prescriber_user.html
  itou/templates/stats/stats.html
  tests/gps/__snapshots__/test_views.ambr
Labels: modifié

#5929 tests: DRY TestApplicationView session setup
  tests/www/apply/test_submit.py
Labels: no-changelog

#5930 Pilotage : Correction du titre des pages des TB refondus
  itou/www/stats/views.py
Labels: no-changelog, pilotage

#5918 Déplacer TestEditJobDescriptionView.test_remove_location
  tests/www/companies_views/test_job_description_views.py
Labels: no-changelog

#5937 PASS IAE: Correction de l'affichage de la durée destante du PASS
  itou/approvals/models.py
  tests/approvals/tests.py
Labels: modifié, bug

#5936 [Candidature] Retrait du sondage sur RDVI
  itou/static/img/rdvi-integration.png
  itou/templates/apply/includes/buttons/rdv_insertion_promote.html
  itou/templates/apply/includes/list_card_body.html
  itou/templates/apply/includes/siae_hiring_actions.html
  itou/templates/rdv_insertion/discover.html
  itou/www/rdv_insertion/urls.py
  itou/www/rdv_insertion/views.py
  tests/www/apply/__snapshots__/test_list.ambr
  tests/www/apply/__snapshots__/test_list_for_siae.ambr
Labels: supprimé

#5939 Amélioration du code suite à #5937
  itou/approvals/models.py
  tests/approvals/tests.py
Labels: no-changelog

#5946 changelog: From 2025-04-07 to 2025-04-13
  CHANGELOG.md
Labels: no-changelog

#5944 utils: suppression de `UniqueConstraintWithErrorCode`
  itou/users/migrations/0001_initial.py
  itou/users/models.py
  itou/utils/models.py
Labels: no-changelog

#5878 Ajout d’un champ JobSeekerProfile.identity_certifications [GEN-1380]
  itou/approvals/models.py
  itou/eligibility/tasks.py
  itou/users/enums.py
  itou/users/management/commands/pe_certify_users.py
  itou/users/migrations/0026_identitycertification.py
  itou/users/models.py
  tests/approvals/test_notify_pole_emploi.py
  tests/eligibility/test_iae.py
  tests/eligibility/test_tasks.py
  tests/users/__snapshots__/test_management_commands.ambr
  tests/users/test_management_commands.py
  tests/users/test_models.py
Labels: no-changelog

#5933 Vérification systématique du type de session dans SessionNamespace
  itou/utils/session.py
  itou/www/apply/views/submit_views.py
  itou/www/gps/views.py
  itou/www/job_seekers_views/views.py
  itou/www/utils/wizard.py
  tests/gps/test_views.py
  tests/utils/test.py
  tests/utils/tests.py
  tests/www/apply/test_batch_views.py
  tests/www/apply/test_process.py
  tests/www/apply/test_submit.py
  tests/www/employee_record_views/test_add.py
  tests/www/job_seekers_views/test_create_or_update.py
  tests/www/job_seekers_views/test_list.py
Labels: tech

#5963 Préparation à la suppression d'un champ inutilisé
  itou/companies/admin.py
  itou/companies/migrations/0019_alter_companymembership_notifications.py
  itou/companies/models.py
Labels: no-changelog

#5967 Suite et fin de la suppression d'un champ inutilisé
  itou/companies/migrations/0021_remove_companymembership_notifications.py
Labels: no-changelog

#5969 admin: Ajouter les certificateur d’identité au profil demandeur d’emploi
  itou/users/admin.py
  itou/users/migrations/0026_identitycertification.py
  itou/users/models.py
  tests/users/test_admin.py
Labels: ajouté

#5970 Supression de for_snapshot=True non nécessaires dans des tests
  tests/www/apply/test_process_external_transfer.py
Labels: no-changelog

#5968 GEIQ: suppression de la 1ère version du bilan d'exécution
  config/urls.py
  itou/geiq/admin.py
  itou/templates/dashboard/dashboard.html
  itou/templates/dashboard/includes/employer_geiq_card.html
  itou/templates/dashboard/includes/labor_inspector_geiq_assessment_card.html
  itou/templates/geiq/assessment_info_for_employer.html
  itou/templates/geiq/assessment_info_for_labor_inspector.html
  itou/templates/geiq/assessment_review.html
  itou/templates/geiq/email/to_institution_assessment_submitted_body.txt
  itou/templates/geiq/email/to_institution_assessment_submitted_subject.txt
  itou/templates/geiq/employee_contract_list.html
  itou/templates/geiq/employee_details.html
  itou/templates/geiq/employee_exit_list.html
  itou/templates/geiq/employee_job_application_list.html
  itou/templates/geiq/employee_personal_information_list.html
  itou/templates/geiq/employee_support_list.html
  itou/templates/geiq/geiq_list.html
  itou/templates/geiq/includes/_experiment_info_alert.html
  itou/templates/geiq/includes/labor_inspector_assessment_state_badge.html
  itou/templates/geiq/includes/labor_inspector_assessment_state_badge_for_list.html
  itou/templates/geiq/includes/last_synced_at.html
  itou/templates/geiq/list_base.html
  itou/www/dashboard/views.py
  itou/www/geiq_views/__init__.py
  itou/www/geiq_views/forms.py
  itou/www/geiq_views/urls.py
  itou/www/geiq_views/views.py
  tests/geiq/test_admin.py
  tests/www/dashboard/test_dashboard.py
  tests/www/geiq_views/__init__.py
  tests/www/geiq_views/__snapshots__/tests.ambr
  tests/www/geiq_views/tests.py
Labels: supprimé

#5971 Candidature: Uniformisation du nom d'un paramètre GET
  itou/templates/apply/submit/application/base.html
  itou/templates/companies/card.html
  itou/templates/companies/includes/_card_jobdescription.html
  itou/templates/companies/includes/_card_siae.html
  itou/templates/companies/includes/_company_info.html
  itou/templates/companies/includes/_list_siae_actives_jobs_row.html
  itou/templates/companies/includes/_siae_jobdescription.html
  itou/templates/companies/job_description_card.html
  itou/templates/job_seekers_views/check_job_seeker_info_for_hire.html
  itou/templates/job_seekers_views/details.html
  itou/templates/job_seekers_views/includes/list_results.html
  itou/templates/job_seekers_views/job_applications.html
  itou/templates/search/includes/siaes_search_content.html
  itou/www/apply/views/submit_views.py
  itou/www/job_seekers_views/views.py
  itou/www/search/views.py
  tests/www/apply/test_process.py
  tests/www/apply/test_submit.py
  tests/www/apply/test_submit_from_job_seekers_list.py
  tests/www/companies_views/test_card_views.py
  tests/www/job_seekers_views/__snapshots__/test_details.ambr
  tests/www/job_seekers_views/__snapshots__/test_list.ambr
  tests/www/job_seekers_views/test_create_or_update.py
  tests/www/job_seekers_views/test_details.py
  tests/www/job_seekers_views/test_list.py
  tests/www/search/tests.py
Labels: modifié

#5981 Mini modifs sur ItouUserAdmin.get_readonly_fields
  itou/users/admin.py
Labels: no-changelog

#5982 Utiliser request.current_organization dans companies_views/views.py
  itou/www/companies_views/views.py
Labels: no-changelog

#5984 Simplifier les assertions de test_job_description_views
  tests/www/companies_views/test_job_description_views.py
Labels: no-changelog

#5986 Simplifier edit_job_description_details
  itou/www/companies_views/views.py
  tests/www/companies_views/test_job_description_views.py
Labels: no-changelog

#5991 PASS IAE: Ajouter des informations sur l'affichage d'un PASS IAE expiré [GEN-2392]
  itou/templates/approvals/includes/box.html
  tests/www/approvals_views/__snapshots__/test_approval_box.ambr
  tests/www/approvals_views/__snapshots__/test_detail.ambr
  tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
  tests/www/job_seekers_views/__snapshots__/test_details.ambr
Labels: modifié

#5993 Correction d'un test bagottant
  tests/www/apply/test_submit.py
Labels: no-changelog

#5980 Nettoyage de code de retrocompatibilité
  itou/www/apply/views/submit_views.py
  itou/www/job_seekers_views/views.py
  tests/www/apply/test_submit_from_job_seekers_list.py
  tests/www/search/tests.py
Labels: no-changelog

#5994 changelog: From 2025-04-14 to 2025-04-20
  CHANGELOG.md
Labels: no-changelog

#5977 Accessibilité: Amélioration de l'affichage des erreurs de formulaire
  itou/templates/django_bootstrap5/form_errors.html
  itou/templates/layout/base.html
  tests/gps/__snapshots__/test_views.ambr
  tests/www/apply/test_list_for_siae.py
  tests/www/apply/test_list_prescriptions.py
  tests/www/apply/test_process.py
  tests/www/apply/test_submit.py
  tests/www/dashboard/test_edit_user_info.py
  tests/www/employee_record_views/test_create.py
  tests/www/job_seekers_views/test_create_or_update.py
  tests/www/siae_evaluations_views/test_institutions_views.py
  tests/www/signup/__snapshots__/test_job_seeker.ambr
  tests/www/signup/test_job_seeker.py
Labels: modifié

#5935 Fiche de poste: ajout d'une data migration
  itou/companies/migrations/0023_fill_last_employer_update_at.py
Labels: no-changelog

#6015 Vie privée : Allonger la durée d'inactivité à 24 mois avant la notification des comptes candidats sans candidature inactifs
  itou/archive/management/commands/notify_archive_jobseekers.py
  tests/archive/tests_management_command.py
Labels: modifié

#6013 Ne pas bloquer la suppression d'un compte à cause d'un groupe de suivi GPS
  itou/gps/migrations/0023_alter_followupgroup_beneficiary_and_more.py
  itou/gps/models.py
Labels: no-changelog

#6016 Interface: Optimisation des formulaires de création et d'édition de fiches poste
  itou/templates/companies/edit_job_description.html
  itou/templates/companies/edit_job_description_details.html
Labels: modifié

#6020 Admin: utilisation de la permission `change_company` pour l'affichage du bouton de transfert d'entreprise
  itou/templates/admin/companies/change_company_form.html
  tests/companies/test_admin.py
Labels: no-changelog

#6008 Statistiques : Désactivation du NPS en démo
  itou/static/js/nps_popup.js
  itou/templates/apply/list_for_siae.html
  itou/templates/apply/list_prescriptions.html
  itou/templates/apply/submit/application/end.html
Labels: no-changelog

#6017 Tech: ajout d'un petit helper `check_date_order_constraint`
  itou/geiq/models.py
  itou/siae_evaluations/models.py
  itou/utils/models.py
Labels: no-changelog

#6022 GPS: Suppression du badge nouveau à côté du menu latéral pour le département du Gard
  itou/utils/templatetags/nav.py
Labels: modifié

#6023 Nettoyage de code dans le parcours de transfert de candidature
  itou/www/apply/views/process_views.py
Labels: no-changelog

#6030 Typos : Correctif de typos variées dans les commentaires du code
  itou/companies/management/commands/move_company_data.py
  itou/companies/models.py
Labels: no-changelog

#6028 [Prolongations] Affichage du _spinner_ sur la totalité du formulaire
  itou/www/approvals_views/forms.py
  tests/www/approvals_views/__snapshots__/test_prolongation.ambr
Labels: modifié

#6024 Interface: Optimisation des formulaires de création et d'édition de Salarié ASP
  itou/templates/employee_record/add.html
  itou/templates/employee_record/includes/create_step_1.html
  itou/templates/employee_record/includes/create_step_2.html
  itou/templates/employee_record/includes/create_step_3.html
  itou/templates/employee_record/includes/create_step_4.html
  itou/templates/employee_record/includes/create_step_5.html
  tests/www/employee_record_views/__snapshots__/test_add.ambr
  tests/www/employee_record_views/__snapshots__/test_create.ambr
Labels: modifié

#6033 Interface: Remonter le bandeau “Votre avis nous intéresse” au dessus du bandeau action de la liste de candidatures
  itou/templates/apply/list_for_siae.html
Labels: no-changelog

#5943 Admin : conserver le statut d'administrateur lors du transfert d'une SIAE à une autre, et supprimer les membres lors de la désactivation [GEN-2374]
  itou/companies/transfer.py
  tests/companies/test_admin.py
Labels: 1-recette-jetable, modifié

#6036 Interface: Harmonisation des longueurs de champs par type spécifique
  itou/templates/account/login_job_seeker.html
  itou/templates/apply/includes/job_application_accept_form.html
  itou/templates/approvals/includes/declaration_prescriber_email.html
  itou/templates/dashboard/edit_user_info.html
  itou/templates/dashboard/includes/edit_job_seeker_info_form.html
  itou/templates/job_seekers_views/create_or_update_job_seeker/step_1.html
  itou/templates/signup/job_seeker_signup.html
  itou/templates/signup/job_seeker_signup_credentials.html
  tests/www/signup/__snapshots__/test_job_seeker.ambr
Labels: no-changelog

#6040 changelog: From 2025-04-21 to 2025-04-27
  CHANGELOG.md
Labels: no-changelog

#6042 Performances: JobApplication: correction de la FK vers User pour le champ archived_by
  itou/job_applications/models.py
Labels: no-changelog

#6032 Retrait du code de compatibilité sur la vérification des session namespace
  itou/utils/session.py
  tests/utils/tests.py
  tests/www/apply/test_geiq.py
  tests/www/apply/test_process_external_transfer.py
  tests/www/job_seekers_views/test_create_or_update.py
  tests/www/job_seekers_views/test_list.py
Labels: no-changelog

#6038 Github : Définir les permissions pour les jobs
  .github/workflows/ci.yml
  .github/workflows/git.yml
  .github/workflows/mkchangelog.yml
  .github/workflows/notify-slack.yml
  .github/workflows/require-labels.yml
  .github/workflows/review-app-creation.yml
  .github/workflows/review-app-removal.yml
Labels: no-changelog

#6057 Éligibilité : Mieux indiquer le lien externe dans le bloc d’information sur la certification des critères
  itou/templates/apply/includes/certification_info_box.html
Labels: modifié

#6045 Changelog : Utiliser le token GitHub des actions
  .github/workflows/mkchangelog.yml
Labels: no-changelog

#6014 Réusinage: La carte de job description utilise le nouveau composant c-navinfo
  itou/templates/companies/card.html
  itou/templates/companies/job_description_card.html
  itou/templates/components/c-navinfo.html
  itou/utils/templatetags/components.py
  pyproject.toml
  tests/www/companies_views/__snapshots__/test_card_views.ambr
  tests/www/companies_views/test_card_views.py
Labels: no-changelog

#6066 [Admin] Permettre aux admins itou d'ajouter un calendrier
  itou/users/management/commands/sync_group_and_perms.py
  tests/users/__snapshots__/test_sync_group_and_perms.ambr
Labels: modifié
