Repository gip-inclusion/les-emplois, pull requests merged in 2025-10, with the labels that each got.

#6935 Fiche salarié: correction de l'utilitaire `employee_record`
  itou/employee_record/management/commands/employee_record.py
  itou/employee_record/models.py
  tests/employee_record/test_employee_record_command.py
Labels: no-changelog

#6938 Admin: ajout de la date de création des diagnostics dans la vue des candidats
  itou/users/admin.py
Labels: modifié

#6930 MinIO : utilisation de l'image officielle
  docker-compose.yml
Labels: no-changelog

#6940 Statistiques: Ne plus envoyer à Matomo les urls qui nous sont inconnues
  itou/templates/layout/base.html
  itou/utils/context_processors.py
  tests/utils/__snapshots__/tests.ambr
  tests/utils/tests.py
Labels: no-changelog

#6947 Candidatures : débagottage de tests
  tests/job_applications/tests.py
Labels: no-changelog

#6944 Tech: Amélioration d'un test
  tests/utils/tests.py
Labels: no-changelog

#6939 Pilotage: Ajout du sub ProConnect à la table des utilisateurs
  itou/metabase/tables/users.py
  tests/metabase/management/__snapshots__/test_populate_metabase_emplois.ambr
  tests/metabase/management/test_populate_metabase_emplois.py
Labels: modifié

#6961 Technique: Nettoyage des urls envoyées à matomo dans les pages de stats
  itou/common_apps/address/departments.py
  itou/www/stats/views.py
  tests/www/stats/test_views.py
Labels: no-changelog

#6963 Tech: nettoyage d'une migration de donnée
  itou/siae_evaluations/migrations/0003_evaluatedsiae_final_state.py
Labels: no-changelog

#6951 Accessibilité: Correction du dropdown .c-box--structure
  itou/templates/includes/structures/_structure_info.html
  tests/www/apply/__snapshots__/test_submit.ambr
  tests/www/apply/__snapshots__/test_submit_from_job_seekers_list.ambr
  tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
  tests/www/prescribers_views/test_overview.py
Labels: modifié

#6962 Pilotage : Mise à jour du TB auto-prescription pour les DDETS/DREETS/SIAE
  itou/utils/apis/metabase.py
  itou/www/stats/views.py
Labels: no-changelog, pilotage

#6968 Admin: ajout de la date de modification de la remarque support
  itou/utils/admin.py
  itou/utils/migrations/0002_pksupportremark_updated_at.py
  itou/utils/migrations/0003_uuidsupportremark_updated_at.py
  itou/utils/models.py
  tests/users/__snapshots__/test_admin_views.ambr
Labels: modifié
