Repository gip-inclusion/les-emplois, pull requests merged in 2025-03, with the labels that each got.

#5692 Performances: Ajout de docker-compose.override.yml au .gitignore
  .gitignore
Labels: no-changelog

#5705 Stabilité: Correction du script de suppression des buckets
  scripts/delete-bucket
Labels: no-changelog, bug

#5710 changelog: From 2025-02-24 to 2025-03-02
  CHANGELOG.md
Labels: no-changelog

#5721 GPS: Petit correctif UI
  itou/templates/gps/group_memberships.html
  tests/gps/__snapshots__/test_views.ambr
Labels: no-changelog

#5716 UX/UI: Ajustement UI du stepper et la progress bar
  itou/templates/apply/includes/geiq_eligibility_section.html
  itou/templates/apply/includes/job_application_external_transfer_progress.html
  itou/templates/apply/process_refuse.html
  itou/templates/apply/submit/application/base.html
  itou/templates/approvals/includes/progress_bar.html
  itou/templates/approvals/prolongation_requests/deny.html
  itou/templates/companies/edit_job_description.html
  itou/templates/companies/edit_job_description_details.html
  itou/templates/companies/edit_job_description_preview.html
  itou/templates/companies/edit_siae.html
  itou/templates/companies/edit_siae_description.html
  itou/templates/companies/edit_siae_preview.html
  itou/templates/employee_record/add.html
  itou/templates/job_seekers_views/create_or_update_job_seeker/step_base.html
  itou/templates/job_seekers_views/create_or_update_job_seeker/step_end.html
  itou/templates/siae_evaluations/institution_evaluated_siae_notify_step1.html
  itou/templates/siae_evaluations/institution_evaluated_siae_notify_step2.html
  itou/templates/siae_evaluations/institution_evaluated_siae_notify_step3.html
  tests/www/apply/__snapshots__/test_process_external_transfer.ambr
  tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
  tests/www/employee_record_views/__snapshots__/test_add.ambr
Labels: modifié

#5703 UX/UI: Changement UI de la modale de connexion aux comptes de démonstration
  itou/static/css/itou.css
  itou/static/img/demo_accounts/ai.svg
  itou/static/img/demo_accounts/de.svg
  itou/static/img/demo_accounts/ea.svg
  itou/static/img/demo_accounts/ei.svg
  itou/static/img/demo_accounts/etti.svg
  itou/static/img/demo_accounts/geiq.svg
  itou/static/img/demo_accounts/prescripteur_habilite.svg
  itou/static/img/demo_accounts/prescripteur_non_habilite.svg
  itou/static/img/demo_accounts/prescripteur_solo.svg
  itou/templates/includes/demo_accounts.html
  itou/utils/templatetags/demo_accounts.py
Labels: 1-recette-jetable, modifié

#5726 Candidature: Ajout d’un nouveau motif de refus “Refus automatique” [GEN-2298]
  itou/job_applications/enums.py
  itou/job_applications/migrations/0001_initial.py
Labels: modifié

#5730 GPS: Ajout d'urls de compatibilité
  itou/www/gps/urls.py
  tests/gps/test_views.py
Labels: modifié

#5732 Modifier la valeur de FORCE_PROCONNECT_LOGIN en tests
  config/settings/test.py
Labels: no-changelog

#5737 changelog: From 2025-03-03 to 2025-03-09
  CHANGELOG.md
Labels: no-changelog

#5733 github : Lancer `require-labels` quand une PR est mis dans la merge queue
  .github/workflows/require-labels.yml
Labels: no-changelog

#5734 Tech : Remplacer le check Django `check_verbose_name_lower` par un test
  itou/utils/apps.py
  itou/utils/checks.py
  tests/test_consistency.py
Labels: no-changelog

#5752 Correction mineure d'un aria-label
  itou/templates/job_seekers_views/list.html
  tests/www/job_seekers_views/__snapshots__/test_list.ambr
Labels: no-changelog

#5755 UX/UI: Fix invitations placeholder
  itou/static/js/formset_add_remove_row.js
  itou/templates/invitations_views/create.html
Labels: no-changelog

#5758 admin: Forcer la création manuelle de PASS IAE via la procédure prévue
  itou/approvals/admin.py
  tests/approvals/tests.py
Labels: no-changelog

#5753 Gabarits : passer systématiquement `force_valid` aux badges d'éligibilité
  itou/templates/apply/includes/eligibility_badge.html
  itou/templates/apply/submit/application/base.html
  itou/templates/apply/submit/hire_confirmation.html
  itou/templates/job_seekers_views/check_job_seeker_info_for_hire.html
  itou/templates/job_seekers_views/includes/list_results.html
  tests/www/job_seekers_views/__snapshots__/test_list.ambr
Labels: no-changelog

#5759 Admin: Limiter les modifications de PASS IAE
  itou/approvals/admin.py
  itou/approvals/admin_forms.py
  tests/approvals/tests.py
Labels: modifié

#5762 admin: correction du formulaire de modification d'un PASS IAE
  itou/approvals/admin_forms.py
Labels: no-changelog, bug

#5763 Admin: Correction de la page des PASS IAE
  tests/approvals/test_admin.py
Labels: modifié, bug

#5765 Simplifier User.is_handled_by_proxy
  itou/users/models.py
Labels: no-changelog

#5767 Fiche de poste: Correction d'une typo dans un template
  itou/templates/companies/job_description_list.html
Labels: no-changelog, bug

#5770 Admin: Correction du tableau de bord pour les non super utilisteurs
  itou/templates/dashboard/dashboard.html
  itou/www/dashboard/views.py
  tests/www/dashboard/__snapshots__/test_dashboard.ambr
  tests/www/dashboard/test_dashboard.py
Labels: modifié

#5775 changelog: From 2025-03-10 to 2025-03-16
  CHANGELOG.md
Labels: no-changelog

#5777 Nettoyage des LoginRequiredMixin restants
  itou/www/apply/views/process_views.py
  itou/www/gps/views.py
Labels: no-changelog

#5778 Désactiver le 2FA par défaut sur l'environnement de développement
  config/settings/dev.py
Labels: no-changelog

#5776 JS : utiliser le préfixe data-emplois- pour la synchronisation des checkboxes
  itou/static/js/htmx_dropdown_filter.js
  itou/templates/includes/btn_dropdown_filter/checkboxes.html
  itou/templates/job_seekers_views/includes/job_seekers_filters/single_checkbox.html
  tests/www/apply/test_list_for_job_seeker.py
  tests/www/apply/test_list_for_siae.py
  tests/www/apply/test_list_prescriptions.py
  tests/www/job_seekers_views/__snapshots__/test_list.ambr
  tests/www/job_seekers_views/test_list.py
Labels: no-changelog

#5795 Admin: Re-permettre aux membre du groupe itou-admin de créer un PASS depuis l'admin
  itou/users/management/commands/sync_group_and_perms.py
  tests/users/__snapshots__/test_sync_group_and_perms.ambr
Labels: no-changelog

#5798 Fiches salarié : Correction de l'URL du bouton "Créer une fiche salarié"
  itou/templates/employee_record/add.html
  itou/templates/employee_record/includes/list_header.html
  itou/templates/employee_record/includes/list_results.html
  itou/templates/employee_record/list.html
  itou/www/employee_record_views/views.py
  tests/www/employee_record_views/__snapshots__/test_add.ambr
  tests/www/employee_record_views/__snapshots__/test_list.ambr
  tests/www/employee_record_views/test_add.py
Labels: modifié, bug

#5800 Admin: Modification de l'icone indiquant l'appareil OTP utilisé
  itou/templates/itou_staff_views/otp_devices.html
  tests/www/itou_staff_views/__snapshots__/tests.ambr
Labels: no-changelog

#5796 UX/UI : Réduire la taille des badges dans le tableau des demandeurs d’emplois des prescripteurs
  itou/templates/apply/includes/eligibility_badge.html
  itou/templates/job_seekers_views/includes/list_results.html
  tests/www/job_seekers_views/__snapshots__/test_list.ambr
Labels: modifié

#5808 Correction d'une typo dans JobSeekerBaseView
  itou/www/job_seekers_views/views.py
Labels: no-changelog

#5811 changelog: From 2025-03-17 to 2025-03-23
  CHANGELOG.md
Labels: no-changelog

#5805 Prescripteur: Améliorer la liste des candidats affichés dans l'onglet "Tous les candidats de ma structure"
  itou/users/models.py
  itou/www/job_seekers_views/views.py
  tests/users/test_models.py
  tests/www/job_seekers_views/__snapshots__/test_list.ambr
  tests/www/job_seekers_views/test_create_or_update.py
  tests/www/job_seekers_views/test_list.py
Labels: modifié

#5812 Technique: Utilisation d'un utilisaire pour nettoyer le code
  itou/users/models.py
Labels: no-changelog

#5804 Candidature : ajouter `back_url` sur les boutons Postuler
  itou/templates/companies/card.html
  itou/templates/companies/includes/_card_siae.html
  itou/templates/companies/job_description_card.html
  itou/templates/dashboard/includes/dashboard_title_content.html
  itou/www/apply/views/submit_views.py
  tests/www/apply/test_submit.py
  tests/www/companies_views/__snapshots__/test_card_views.ambr
  tests/www/job_seekers_views/test_create_or_update.py
Labels: modifié

#5831 Correction d’une typo dans les settings de dev
  config/settings/dev.py
Labels: no-changelog

#5830 UX/UI: Suppression de l’IntroJS du traitement par lot
  itou/templates/apply/includes/list_tr.html
  itou/templates/apply/includes/siae_actions.html
  itou/templates/apply/list_for_siae.html
  tests/www/apply/__snapshots__/test_list_for_siae.ambr
  tests/www/apply/__snapshots__/test_process.ambr
  tests/www/dashboard/__snapshots__/test_dashboard.ambr
Labels: modifié

#5829 Ajout d'un setting temporaire pour changer le SECRET_KEY de Django
  config/settings/base.py
Labels: no-changelog

#5803 Tech: importer les librairies frequemment utilisées dans shell_plus
  config/settings/dev.py
Labels: tech

#5826 GPS: Mise en conformité de l'UI de la liste des intervenants
  itou/templates/gps/group_beneficiary.html
  itou/templates/gps/group_contribution.html
  itou/templates/gps/group_edition.html
  itou/templates/gps/group_memberships.html
  tests/gps/__snapshots__/test_views.ambr
Labels: no-changelog

#5833 Tableau de bord: Supprimer les sondages présentés aux employeurs et aux prescripteurs [GEN-2336]
  itou/templates/dashboard/dashboard.html
Labels: supprimé

#5835 UX/UI: Correction de wording de boutons de formulaires
  itou/templates/approvals/suspension_delete.html
  itou/templates/approvals/suspension_update.html
  itou/templates/approvals/suspension_update_enddate.html
  itou/templates/job_seekers_views/create_or_update_job_seeker/step_end.html
  tests/www/approvals_views/__snapshots__/test_suspend.ambr
Labels: 1-recette-jetable, modifié

#5838 Ajout d'un tracker sur l'affichage de la bannière Mon Récap
  itou/templates/includes/mon_recap_banner.html
Labels: no-changelog

#5841 Correction de contrôle d’accès aux fiches de poste
  itou/www/companies_views/views.py
  tests/www/companies_views/test_job_description_views.py
Labels: modifié

#5840 GEIQ: ajout de la méthode `get_compte_pdf` utilisant le nouvel endpoint `/rest/DownloadCompte`
  itou/utils/apis/geiq_label.py
  tests/utils/apis/test_geiq_label.py
Labels: no-changelog

#5845 UX/UI: correction UI des "cards" du dashboard candidats
  itou/templates/dashboard/dashboard.html
  itou/templates/dashboard/includes/job_seeker_approval_card.html
  itou/templates/dashboard/includes/job_seeker_job_applications_card.html
Labels: modifié

#5846 changelog: From 2025-03-24 to 2025-03-30
  CHANGELOG.md
Labels: no-changelog

#5848 settings: Remove SECRET_KEY_FALLBACKS
  config/settings/base.py
Labels: no-changelog

#5839 Outillage: ajout debugger pour les management command dans vscode
  .vscode/launch.json
Labels: no-changelog
