Repository gip-inclusion/les-emplois, pull requests merged in 2025-01, with the labels that each got.

#5325 CGU : Changement de l'adresse de contact du DPO
  itou/templates/static/legal/terms.html
Labels: modifié

#5313 Tech : Chainer les appels pour `.raise_for_status()` d'HTTPX
  itou/cities/management/commands/sync_cities.py
  itou/emails/admin.py
  itou/metabase/db.py
  itou/metabase/management/commands/populate_metabase_matomo.py
  itou/rdv_insertion/api.py
  itou/utils/apis/api_entreprise.py
  itou/utils/apis/api_particulier.py
  itou/utils/apis/data_inclusion.py
  itou/utils/apis/datadog.py
  itou/utils/apis/esd.py
  itou/utils/apis/geiq_label.py
  itou/utils/apis/geocoding.py
  itou/utils/apis/pole_emploi.py
  itou/utils/apis/sentry.py
  itou/utils/apis/updown.py
  itou/www/apply/views/process_views.py
Labels: no-changelog

#5326 Fiches salarié : Corriger définitivement la sérialisation des vieilles archives JSON
  itou/employee_record/admin.py
  itou/employee_record/migrations/0002_fix_archived_json_as_string.py
Labels: no-changelog

#5312 Demandeur d’emploi : Suppression du champ de l'aide ATA
  itou/api/employee_record_api/serializers.py
  itou/employee_record/serializers.py
  itou/fixtures/django/07_jobseeker_profile.json
  itou/users/admin.py
  itou/users/migrations/0018_remove_jobseekerprofile_ata_allocation_since.py
  itou/users/models.py
  itou/www/itou_staff_views/export_utils.py
  tests/api/__snapshots__/test_geiq.ambr
  tests/api/employee_record_api/__snapshots__/tests.ambr
  tests/users/__snapshots__/test_admin_views.ambr
  tests/www/apply/__snapshots__/test_list_for_siae.ambr
  tests/www/apply/__snapshots__/test_list_prescriptions.ambr
  tests/www/apply/__snapshots__/test_process.ambr
  tests/www/apply/__snapshots__/test_submit.ambr
  tests/www/approvals_views/__snapshots__/test_detail.ambr
  tests/www/dashboard/__snapshots__/test_edit_job_seeker_info.ambr
  tests/www/dashboard/__snapshots__/test_edit_user_info.ambr
  tests/www/employee_record_views/__snapshots__/test_list.ambr
  tests/www/employees_views/__snapshots__/test_detail.ambr
  tests/www/itou_staff_views/__snapshots__/tests.ambr
  tests/www/job_seekers_views/__snapshots__/test_details.ambr
Labels: supprimé

#5327 Admin : Donner accès aux candidatures en lecture seule à GPS
  itou/users/management/commands/sync_group_and_perms.py
  tests/users/__snapshots__/test_sync_group_and_perms.ambr
Labels: no-changelog

#5328 Tech : Suppression de la colonne du champ de l'aide ATA
  itou/users/migrations/0018_remove_jobseekerprofile_ata_allocation_since.py
  itou/users/migrations/0019_drop_jobseekerprofile_ata_allocation_since.py
Labels: no-changelog

#5314 Correctif de la mise à jour des scores de la recherche employeur
  itou/companies/management/commands/update_companies_job_app_score.py
  tests/companies/test_management_commands.py
Labels: modifié

#5340 UX/UI: mise a jour du theme vers v2.5.6
  itou/utils/staticfiles.py
Labels: 1-recette-jetable, modifié

#5342 Correctif du script de génération du journal des changements.
  scripts/mkchangelog
Labels: tech

#5344 UX/UI: Fin de la demande de retours prescripteurs habilités sur une refonte de leur espace [GEN-2334]
  itou/templates/dashboard/dashboard.html
Labels: supprimé

#5345 UX/UI: Retirer le texte d'aide du filtre archivé des candidatures [GEN-2028]
  itou/templates/apply/includes/job_applications_filters/offcanvas_body.html
  tests/www/apply/__snapshots__/test_list_for_siae.ambr
  tests/www/apply/__snapshots__/test_list_prescriptions.ambr
Labels: supprimé

#5347 changelog: From 2024-12-23 to 2024-12-29
  CHANGELOG.md
Labels: no-changelog

#5346 Ordonner les feuilles de style dans base.html
  itou/templates/layout/base.html
Labels: no-changelog

#5348 changelog: From 2024-12-30 to 2025-01-05
  CHANGELOG.md
Labels: no-changelog

#5350 Connexion; Ajout de plus de contexte d'erreur lors d'échec de connexion via France Travail pour les candidats
  itou/openid_connect/pe_connect/views.py
Labels: modifié

#5349 UX/UI: modification de la couleur du badge "Agrément expiré"
  itou/utils/templatetags/badges.py
  tests/utils/__snapshots__/tests.ambr
  tests/www/approvals_views/test_list.py
Labels: modifié

#5354 Notifications: Continuer à envoyer les notifications aux anciens collaborateurs
  itou/communications/dispatch/email.py
  tests/communications/test_dispatch.py
Labels: modifié

#5341 Simplification du tri des résultats de la recherche de fiches de poste
  itou/templates/search/includes/siaes_search_top.html
  itou/www/search/views.py
  tests/www/search/__snapshots__/tests.ambr
Labels: modifié

#5337 Éligibilité : Prise en compte du forçage de `dateFin` à null par l’API Particulier
  itou/eligibility/tasks.py
  itou/utils/apis/api_particulier.py
  itou/utils/mocks/api_particulier.py
  tests/eligibility/test_iae.py
  tests/eligibility/test_tasks.py
  tests/www/apply/test_process.py
Labels: modifié

#5352 Documenter les migrations techniques en cours
  migrations.md
Labels: no-changelog

#5358 Déplacement de code GPS
  itou/users/models.py
  itou/www/autocomplete/views.py
  tests/gps/test_views.py
Labels: no-changelog

#5362 Inscription: Nettoyage suite au déploiement des champs lieu et pays de naissance candidat
  itou/www/signup/forms.py
Labels: no-changelog

#5339 Éligibilité : Rattrapage de dates de fin incorrectes de l’API Particulier
  itou/eligibility/migrations/0009_fix_selectedadministrativecriteria_certification_period.py
Labels: modifié

#5361 UX/UI: Passer le "bon à savoir" en composant info
  itou/templates/employee_record/includes/create_step_1.html
  itou/templates/employee_record/includes/create_step_2.html
  tests/www/employee_record_views/__snapshots__/test_create.ambr
Labels: 1-recette-jetable, modifié

#5324 github: Pouvoir lancer `ci.yml` sur les PR ouvertes depuis un fork publique
  .github/workflows/ci.yml
Labels: no-changelog

#5364 candidature: correction de l'affichage d'une candidature geiq acceptée sans diagnostic
  itou/www/apply/views/process_views.py
  tests/www/apply/test_geiq.py
Labels: modifié, bug

#5369 Prescripteur: Mettre à jour le bandeau d’info des utilisateurs sans organisation [GEN-2366]
  itou/templates/dashboard/dashboard.html
Labels: modifié

#5370 Pilotage: Supprimer l’encart webinaires
  itou/www/stats/views.py
Labels: no-changelog

#5366 GPS: Ajout d'un bouton pour demander l'ajout d'un bénéficiaire
  itou/templates/gps/my_groups.html
  itou/www/gps/views.py
  tests/gps/test_views.py
Labels: 1-recette-jetable, ajouté

#5367 GPS: Créer le flux “Ajouter un intervenant existant”
  itou/templates/users/includes/gps_group.html
  itou/www/gps/views.py
  tests/gps/__snapshots__/test_views.ambr
  tests/gps/test_views.py
Labels: 1-recette-jetable, ajouté

#5280 Changer l’adresse de contact pour l’API des emplois
  config/settings/base.py
Labels: tech

#5382 Mise à jour de compte candidat : nettoyage des URLs et vues dépréciées
  itou/www/job_seekers_views/urls.py
  itou/www/job_seekers_views/views.py
  tests/www/apply/test_submit.py
Labels: no-changelog

#5381 Retirer la classe non utilisée js-period-date-input
  itou/www/employee_record_views/forms.py
  itou/www/job_seekers_views/forms.py
Labels: no-changelog

#5383 GPS: Ajout de liens dans l'admin
  itou/gps/admin.py
  itou/users/admin.py
  tests/gps/test_admin.py
  tests/users/__snapshots__/test_admin_views.ambr
Labels: modifié

#5365 GPS: Amélioration de l'autocomplete avec recherche plein texte
  itou/static/js/gps.js
  itou/users/migrations/0020_add_simple_unaccent_search_config.py
  itou/users/migrations/0021_user_full_name_search_vector.py
  itou/users/migrations/0022_user_full_name_search_idx.py
  itou/users/models.py
  itou/www/autocomplete/views.py
  tests/api/__snapshots__/test_geiq.ambr
  tests/api/employee_record_api/__snapshots__/tests.ambr
  tests/companies/__snapshots__/test_admin.ambr
  tests/gps/__snapshots__/test_views.ambr
  tests/gps/test_views.py
  tests/job_applications/__snapshots__/test_transfer.ambr
  tests/users/__snapshots__/test_admin_views.ambr
  tests/www/apply/__snapshots__/test_list_for_siae.ambr
  tests/www/apply/__snapshots__/test_list_prescriptions.ambr
  tests/www/apply/__snapshots__/test_process.ambr
  tests/www/apply/__snapshots__/test_submit.ambr
  tests/www/approvals_views/__snapshots__/test_detail.ambr
  tests/www/approvals_views/__snapshots__/test_list.ambr
  tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
  tests/www/approvals_views/__snapshots__/test_suspend.ambr
  tests/www/companies_views/__snapshots__/test_job_description_views.ambr
  tests/www/dashboard/__snapshots__/test_dashboard.ambr
  tests/www/dashboard/__snapshots__/test_edit_job_seeker_info.ambr
  tests/www/dashboard/__snapshots__/test_edit_user_info.ambr
  tests/www/dashboard/__snapshots__/test_edit_user_notifications.ambr
  tests/www/employee_record_views/__snapshots__/test_list.ambr
  tests/www/employees_views/__snapshots__/test_detail.ambr
  tests/www/itou_staff_views/__snapshots__/tests.ambr
  tests/www/job_seekers_views/__snapshots__/test_details.ambr
  tests/www/job_seekers_views/__snapshots__/test_list.ambr
  tests/www/siae_evaluations_views/__snapshots__/test_institutions_views.ambr
  tests/www/siae_evaluations_views/__snapshots__/test_siaes_views.ambr
  tests/www/signup/__snapshots__/test_siae.ambr
Labels: modifié

#5385 GPS: Corriger et améliorer le formulaire d'admin des participants
  itou/gps/admin.py
Labels: modifié, bug

#5388 UX/UI: Changer de input type pour les numéros de téléphone
  itou/www/approvals_views/forms.py
  itou/www/companies_views/forms.py
  itou/www/dashboard/forms.py
  itou/www/job_seekers_views/forms.py
  itou/www/prescribers_views/forms.py
  tests/www/prescribers_views/__snapshots__/test_edit.ambr
Labels: 1-recette-jetable, modifié

#5391 UX/UI: Correction des fiches de détail d’un prescripteur
  itou/templates/prescribers/card.html
Labels: modifié

#5392 Pilotage: Ajouter un bandeau sur les tableaux de bord en sursis
  itou/templates/stats/stats.html
  itou/utils/apis/metabase.py
  itou/www/stats/views.py
  tests/www/stats/test_views.py
Labels: ajouté

#5386 UX/UI: Amélioration du message affiché avant de retirer un collaborateur [GEN-1823]
  itou/templates/includes/deactivate_member.html
  itou/templates/includes/update_admin.html
Labels: 1-recette-jetable, modifié

#5407 Connexion: Rediriger les utilisateurs d'InclusionConnect vers ProConnect
  itou/templates/account/login_existing_user.html
  tests/www/login/__snapshots__/tests.ambr
Labels: modifié, bug

#5389 GPS : la création de bénéficiaire ne passe plus par les vues `apply`
  itou/www/gps/forms.py
  tests/gps/test_create_beneficiary.py
Labels: no-changelog, bug

#5408 apply: nettoyage du code GPS de création de bénéficiaire
  itou/www/apply/views/submit_views.py
Labels: no-changelog

#5406 tests: amélioration de l'utilitaire `update_page_with_htmx`
  tests/utils/htmx/test.py
  tests/utils/htmx/tests.py
Labels: no-changelog

#5403 GPS: Ajout de test sur l'admin
  tests/gps/test_admin.py
Labels: no-changelog

#5412 API: commentaire temporaire des scopes de l'API Rome en maintenance
  itou/utils/apis/pole_emploi.py
Labels: no-changelog

#5415 changelog: From 2025-01-13 to 2025-01-19
  CHANGELOG.md
Labels: no-changelog

#5410 GPS: utiliser le `tunnel` de la session et non un paramètre dans l'URL
  itou/www/job_seekers_views/views.py
  tests/gps/test_create_beneficiary.py
Labels: no-changelog

#5413 Recherche employeur : ne jamais afficher de bouton Postuler quand l'employeur a bloqué l'envoi de candidatures
  itou/templates/companies/includes/_card_siae.html
  tests/www/search/tests.py
Labels: modifié, bug

#5419 Corrections de "diagnostique" en "diagnostic"
  CHANGELOG.md
  itou/approvals/admin_views.py
  tests/approvals/tests.py
Labels: no-changelog

#5411 GPS: Amélioration de l'affichage des résultat de l'ajout de bénéficiaires
  itou/static/js/gps.js
  itou/www/autocomplete/views.py
  tests/gps/test_views.py
Labels: modifié

#5420 [IDOR] sécurisation des urls de fusion de membres [GEN-2400]
  itou/www/itou_staff_views/urls.py
  itou/www/itou_staff_views/views.py
  tests/www/itou_staff_views/tests.py
Labels: tech

#5432 Retrait de la constante inutilisée ITOU_EMAIL_PROLONGATION
  itou/utils/constants.py
Labels: no-changelog

#5395 Gabarit des PR : ajout d'une mention pour vérifier si l'étiquette Bug est nécessaire
  .github/pull_request_template.md
Labels: no-changelog

#5442 UX/UI: corrections UI des templates "eligibility"
  itou/templates/apply/includes/geiq/legislative_text_link.html
  itou/templates/apply/submit/application/eligibility.html
  itou/templates/apply/submit/application/geiq_eligibility.html
  itou/templates/approvals/prolongation_requests/deny.html
  tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
Labels: 1-recette-jetable, modifié

#5444 tech: typage manquants d'arguments des urls de `employee_record_views` [GEN-2416]
  itou/www/employee_record_views/urls.py
Labels: tech

#5445 GPS: Suppression de la fonctionnalité « Ajouter un bénéficiaire »
  itou/static/js/gps.js
  itou/templates/gps/join_group.html
  itou/templates/gps/my_groups.html
  itou/www/autocomplete/urls.py
  itou/www/autocomplete/views.py
  itou/www/gps/forms.py
  itou/www/gps/urls.py
  itou/www/gps/views.py
  tests/gps/test_create_beneficiary.py
  tests/gps/test_views.py
Labels: 1-recette-jetable, supprimé

#5434 Création de compte candidat : gestion des permissions
  itou/www/job_seekers_views/views.py
  tests/www/apply/test_submit.py
  tests/www/job_seekers_views/test_create_or_update.py
Labels: no-changelog

#5447 Admin: Ajout du référent FT sur la page de profil de demandeur d'emploi
  itou/gps/models.py
  itou/users/admin.py
Labels: modifié

#5449 Utiliser JobSeekerProfileFieldMixin pour JobSeekerPersonalDataForm
  itou/common_apps/nir/forms.py
  itou/www/apply/forms.py
  itou/www/apply/views/common.py
Labels: no-changelog

#5421 Demandeur d’emploi: Unifier les formulaires de gestion de données personnelles
  itou/asp/forms.py
  itou/templates/apply/includes/job_application_accept_form.html
  itou/users/forms.py
  itou/www/apply/forms.py
  itou/www/apply/views/common.py
  itou/www/dashboard/forms.py
  itou/www/employee_record_views/forms.py
  itou/www/employee_record_views/views.py
  itou/www/job_seekers_views/forms.py
  itou/www/signup/forms.py
  tests/www/apply/__snapshots__/test_process.ambr
  tests/www/apply/__snapshots__/test_submit.ambr
  tests/www/apply/test_forms.py
  tests/www/apply/test_process.py
  tests/www/apply/test_submit.py
  tests/www/dashboard/__snapshots__/test_edit_job_seeker_info.ambr
  tests/www/dashboard/__snapshots__/test_edit_user_info.ambr
  tests/www/job_seekers_views/test_forms.py
Labels: 1-recette-jetable, no-changelog

#5451 S’assurer que le candidat a un diagnostic valide avant d’essayer de certifier les critères d’éligibilité
  itou/www/apply/views/common.py
Labels: no-changelog, bug

#5454 Tech: ajout d'annotations de type sur 2 fonctions
  itou/utils/perms/institution.py
  itou/utils/perms/prescriber.py
Labels: no-changelog

#5453 Vérification du type d'utilisateur pouvant accéder aux vues
  itou/www/apply/views/process_views.py
  itou/www/apply/views/submit_views.py
  itou/www/approvals_views/views.py
  tests/www/apply/__snapshots__/test_submit.ambr
Labels: no-changelog, bug

#5458 Connexion: Petites améliorations de formulation et de mise en page
  itou/templates/pro_connect/includes/description.html
  itou/templates/signup/prescriber_user.html
Labels: modifié

#5456 Ajout d'une popup Tally sur la dashboard prescripteurs habilités et employeurs [GEN-2351]
  itou/templates/dashboard/dashboard.html
Labels: ajouté

#5460 GPS: Ne plus afficher le NIR sur le détail des bénéficiaires
  itou/templates/gps/user_details.html
  tests/gps/__snapshots__/test_views.ambr
Labels: modifié

#5450 Création de compte candidat: refactoriser la sortie du bloc
  itou/www/job_seekers_views/views.py
Labels: no-changelog

#5466 GPS: Correction d'un test
  tests/gps/__snapshots__/test_views.ambr
  tests/gps/test_views.py
Labels: no-changelog

#5465 GPS: Changement du nom d'une colonne
  itou/templates/gps/includes/memberships_results.html
  tests/gps/__snapshots__/test_views.ambr
Labels: modifié

#5467 GPS: Changement de l'ordre d'affichage des membres d'un groupe
  itou/www/gps/views.py
  tests/gps/test_views.py
Labels: modifié

#5464 Ajout d'un bandeau d'info pour inviter les candidats autonomes à un webinaire d'information [GEN-2409]
  itou/templates/dashboard/dashboard.html
Labels: ajouté

#5468 changelog: From 2025-01-20 to 2025-01-26
  CHANGELOG.md
Labels: no-changelog

#5480 Prescripteur : masquer le nom des candidats dans le filtre de la liste des candidats
  itou/www/job_seekers_views/forms.py
  itou/www/job_seekers_views/views.py
  tests/www/job_seekers_views/__snapshots__/test_list.ambr
  tests/www/job_seekers_views/test_list.py
Labels: modifié, bug

#5483 GPS: Ne pas masquer les informations de contact de l'utilisateur
  itou/templates/gps/includes/group_members.html
  tests/gps/__snapshots__/test_views.ambr
  tests/gps/test_views.py
Labels: modifié

#5452 UX/UI: Mise a jour du thème vers la v2.6.1
  itou/static/css/itou.css
  itou/templates/apply/includes/accept_section.html
  itou/templates/apply/includes/buttons/rdv_insertion_invite.html
  itou/utils/staticfiles.py
  tests/www/apply/__snapshots__/test_detail_rdv_insertion.ambr
  tests/www/apply/__snapshots__/test_list_rdv_insertion.ambr
Labels: 1-recette-jetable, modifié

#5485 Admin: Correction du formulaire des diagnostics d'éligibilité.
  itou/eligibility/admin_form.py
  tests/eligibility/test_admin.py
Labels: modifié

#5486 Admin: Ajout d'un message warning lors de la selection d'une organisation non habilité pour un diagnostic d'éligibilité.
  itou/eligibility/admin.py
  itou/eligibility/admin_form.py
  tests/eligibility/test_admin.py
Labels: modifié

#5487 Tech: utilisation de logs dans la commande `run_status_probes`
  itou/status/management/commands/run_status_probes.py
  tests/status/tests.py
Labels: tech

#5489 Technique: Ajout d'une contrainte en base de donnée sur la structure de l'autaur d'un diagnostic d'éligibilité IAE
  itou/eligibility/migrations/0010_add_eligibilitydiagnosis_author_kind_coherence.py
  itou/eligibility/migrations/0011_update_geiqeligibilitydiagnosis_author_kind_coherence.py
  itou/eligibility/models/geiq.py
  itou/eligibility/models/iae.py
  tests/companies/test_import_siae_command.py
  tests/eligibility/factories.py
  tests/eligibility/test_admin.py
  tests/eligibility/test_geiq.py
  tests/siae_evaluations/test_models.py
  tests/www/apply/test_process.py
  tests/www/employees_views/test_detail.py
Labels: modifié

#5492 Technique: Correction des données de fixtures de diagnostics d'éligibilité IAE suite à l'ajout de contrainte en base de donné
  itou/fixtures/django/20_eligibility_diagnoses.json
Labels: no-changelog

#5495 Tableau de bord: Ajout d'un bandeau promotionnel de GPS pour le Gard [GEN-2435]
  itou/templates/dashboard/dashboard.html
Labels: ajouté

#5496 suppression de la redirection temporaire approvals:redirect_to_employee vers employees:detail
  itou/www/approvals_views/urls.py
  itou/www/approvals_views/views.py
  tests/www/approvals_views/test_detail.py
Labels: modifié

#5455 Utiliser une socket UNIX pour se connecter à la base de données en dev
  .github/workflows/ci.yml
  .gitignore
  docker-compose.yml
  docs/environment.md
Labels: no-changelog

#5461 Tester l’embauche d’une auto-prescription d’une autre entreprise
  tests/www/apply/test_submit.py
Labels: no-changelog

#5503 Technique: Ajout d'un commentaire expliquant l'origine d'un setting
  itou/openid_connect/pro_connect/constants.py
Labels: no-changelog

#5448 Connexion: Suppression des migrations Inclusion Connect
  config/settings/base.py
  itou/openid_connect/inclusion_connect/__init__.py
  itou/openid_connect/inclusion_connect/apps.py
  itou/openid_connect/inclusion_connect/migrations/0001_initial.py
  itou/openid_connect/inclusion_connect/migrations/0002_delete_inclusionconnectstate.py
  itou/openid_connect/inclusion_connect/migrations/__init__.py
Labels: no-changelog

#5509 GPS: Ne pas ajouter les orienteurs aux groupes de suivi automatiquement
  itou/www/apply/views/submit_views.py
  tests/www/apply/test_submit.py
Labels: modifié, bug

#5494 Notifications : correction du contenu de l'email envoyé aux prescripteurs lors du refus d'une candidature
  itou/templates/apply/email/refuse_body_for_proxy.txt
  tests/job_applications/__snapshots__/tests.ambr
  tests/job_applications/tests.py
Labels: no-changelog, bug

#5504 UX/UI: Amélioration des champs de saisie de dates
  itou/static/js/duet_date_picker_widget.js
Labels: no-changelog

#5506 Candidature: Simplification du parcours de refus (expérimentation dans le Rhône) [GEN-1611]
  itou/templates/apply/email/refuse_body_for_job_seeker.txt
  itou/templates/apply/email/refuse_body_for_proxy.txt
  itou/templates/apply/includes/job_application_answers.html
  itou/www/apply/forms.py
  itou/www/apply/views/batch_views.py
  itou/www/apply/views/process_views.py
Labels: ajouté
