Repository gip-inclusion/les-emplois, pull requests merged in 2025-07, with the labels that each got.

#6443 Tech: Nettoyage des vielles migrations squashée
  itou/scripts/management/commands/clean_old_applied_migrations.py
  tests/scripts/test_clean_old_applied_migrations.py
Labels: no-changelog

#6454 Candidature: déplacement du bandeau invitant à un entretien utilisateur vers l'espace prescripteur [GEN-2579]
  itou/templates/apply/list_for_siae.html
  itou/templates/apply/list_prescriptions.html
Labels: modifié

#6449 Pilotage : Ouverture du TB "Suivi des bénéficiaires, taux d’encadrement et présence en emploi" aux SIAE
  itou/templates/dashboard/includes/stats/employer.html
  itou/utils/apis/metabase.py
  itou/www/stats/urls.py
  itou/www/stats/views.py
  tests/www/dashboard/__snapshots__/test_dashboard_stats.ambr
Labels: ajouté, pilotage

#6461 Tech: revert de #6443
  itou/scripts/management/commands/clean_old_applied_migrations.py
  tests/scripts/test_clean_old_applied_migrations.py
Labels: no-changelog

#6467 Candidature: Correction du formulaire de recherche de poste [GEN-2588]
  itou/www/search/views.py
Labels: modifié, bug

#6423 Interface: Corrections des écrans du contrôle a posteriori
  itou/templates/siae_evaluations/evaluated_siae_detail.html
  itou/templates/siae_evaluations/includes/criteria_form.html
  itou/templates/siae_evaluations/institution_evaluated_siae_list.html
  itou/templates/siae_evaluations/siae_select_criteria.html
  itou/templates/siae_evaluations/siae_upload_doc.html
Labels: 1-recette-jetable, modifié

#6471 Limiter l’accès au site à 30 requêtes par minute
  itou/utils/throttling.py
  itou/www/middleware.py
  tests/www/test_throttling.py
Labels: modifié

#6472 Candidature : ne pas afficher `None` si des informations concernant le candidat sont manquantes
  itou/templates/apply/includes/job_seeker_info.html
  tests/www/apply/test_details.py
Labels: modifié, bug

#6388 Admin : permettre la modification de la date de début des suspensions si la nouvelle date est avant la date de création
  itou/approvals/models.py
  itou/www/approvals_views/forms.py
  tests/approvals/test_admin.py
  tests/approvals/tests.py
Labels: 1-recette-jetable, modifié

#6477 Mettre à jour Pillow
  requirements/base.txt
  requirements/dev.txt
  requirements/test.txt
Labels: modifié

#6476 Tests : correction d'un test bagottant sur la modale de nouveauté
  tests/communications/test_campaigns.py
Labels: no-changelog

#6464 Tech : Rendre l'usage de `temporary_bucket` obligatoire
  config/settings/test.py
  tests/communications/test_admin.py
  tests/conftest.py
  tests/files/tests.py
  tests/www/announcements/test_views.py
  tests/www/apply/test_process_external_transfer.py
  tests/www/apply/test_submit.py
  tests/www/approvals_views/test_prolongation.py
  tests/www/approvals_views/test_prolongation_requests.py
  tests/www/geiq_assessments_views/test_views_for_geiq.py
  tests/www/siae_evaluations_views/test_siaes_views.py
  tests/www/siae_evaluations_views/test_views.py
Labels: no-changelog

#6473 Retirer l’environnement FAST-MACHINE
  config/settings/base.py
  itou/templates/account/email/email_confirmation_subject.txt
  itou/templates/account/email/password_reset_key_subject.txt
  itou/templates/layout/base_email_signature.txt
  itou/utils/emails.py
  itou/utils/enums.py
  scripts/create-fast-machine.sh
Labels: modifié

#6480 find_orphan_files : Découvrir les relations à `File`
  itou/files/management/commands/find_orphan_files.py
Labels: no-changelog

#6494 Pilotage : Ajouter un encart pour prévenir que nous menons une enquête sur les pratiques des SIAE lorsqu’elles préparent leur DG
  itou/templates/dashboard/dashboard_stats.html
  itou/www/stats/views.py
  tests/www/dashboard/__snapshots__/test_dashboard_stats.ambr
Labels: no-changelog, pilotage

#6488 [PASS] Suppression d'une commande à usage presque unique
  itou/approvals/management/commands/bulk_update_from_file.py
  tests/approvals/test_mng_cmd_bulk_update_from_file.py
Labels: no-changelog

#6500 Se désabonner des _webhooks_ Mailjet
  config/settings/base.py
  config/urls.py
  itou/external_data/admin.py
  itou/external_data/apps.py
  itou/external_data/models.py
  itou/external_data/signals.py
  tests/external_data/tests.py
  tests/www/test_anymail.py
Labels: no-changelog

#6475 Empêcher les migrations de base de données en parallèle
  itou/utils/db.py
  itou/utils/management/commands/migrate.py
Labels: no-changelog

#6505 Supprimer la table RejectedEmailEventData
  itou/external_data/migrations/0002_delete_rejectedemaileventdata.py
  itou/external_data/models.py
Labels: no-changelog

#6510 Tech : Correction pour les tests utilisant `temporary_bucket` échouant "aléatoirement" sur la CI
  tests/www/approvals_views/test_prolongation_requests.py
Labels: tech

#6498 Tech: Gérer les groupes GPS dans la fusion de comptes utilisateurs [GEN-2592]
  itou/www/itou_staff_views/merge_utils.py
  tests/www/itou_staff_views/tests.py
Labels: no-changelog

#6508 Employeur: Désactivation des fiches de poste non mises à jour depuis plus de 1 ans [GEN-2585]
  itou/companies/management/commands/deactivate_old_job_descriptions.py
  tests/companies/test_management_commands.py
Labels: modifié

#6518 Vérifier la génération des fichiers Excel de manière plus stricte
  tests/conftest.py
Labels: no-changelog

#6519 Interface: Annoncer le fonctionnement de la barre d’actions avec les "nouvelles" candidatures
  itou/templates/apply/includes/siae_batch_actions.html
  itou/templates/apply/list_for_siae.html
Labels: 1-recette-jetable, modifié

#6504 [Fichiers] Utiliser un wrapper dans geiq-assessments
  itou/www/geiq_assessments_views/views.py
Labels: no-changelog

#6486 [Fichiers] Ranger les fichiers GEIQ dans un « dossier » S3
  itou/www/geiq_assessments_views/views.py
  tests/www/geiq_assessments_views/test_views_for_geiq.py
Labels: tech

#6536 Fiches salarié: Suppression d'une recommandation inutile sans la création de fiche salarié ASP
  itou/templates/employee_record/includes/create_step_2.html
  tests/www/employee_record_views/__snapshots__/test_create.ambr
Labels: no-changelog

#6512 Tech: Ajout de propriétés sur les `File` pour construire les urls
  itou/approvals/admin.py
  itou/files/admin.py
  itou/files/models.py
  itou/job_applications/models.py
  itou/siae_evaluations/admin.py
  itou/www/approvals_views/views.py
  itou/www/geiq_assessments_views/views.py
  itou/www/siae_evaluations_views/views.py
  tests/files/tests.py
  tests/www/approvals_views/test_prolongation_requests.py
  tests/www/siae_evaluations_views/test_views.py
Labels: no-changelog

#6543 Admin : Passer les champs texte des candidatures en lecture seule
  itou/job_applications/admin.py
Labels: no-changelog

#6545 Vie privée : activer la notification des professionnels sans activité récente
  clevercloud/cron.json
Labels: ajouté

#6548 Vie privée : renommage des champs has_xxx en had_xxx
  itou/archive/management/commands/anonymize_jobseekers.py
  itou/archive/migrations/0008_rename_anonymizedapplication_has_been_transferred_and_more.py
  itou/archive/models.py
  tests/archive/__snapshots__/tests_management_command.ambr
Labels: no-changelog

#6123 Interface: Déplacer le lien vers la création d'une nouvelle structure dans la liste déroulante des structures du menu principal
  itou/templates/companies/create_siae.html
  itou/templates/dashboard/includes/employer_company_card.html
  itou/templates/layout/_structure_switcher_dropdown_menu.html
  itou/templates/layout/_structure_switcher_nav.html
  itou/templates/layout/_structure_switcher_offcanvas.html
  itou/utils/templatetags/structure_switcher.py
  itou/www/dashboard/views.py
  tests/www/__snapshots__/test_layout.ambr
  tests/www/dashboard/test_dashboard.py
  tests/www/test_layout.py
Labels: modifié

#6563 Tests : Correction des lundi pour les EA/EATT
  tests/companies/test_import_ea_eatt.py
Labels: no-changelog

#6550 Tech : Correction du contexte manquant pour les management commands
  itou/approvals/management/commands/prolongation_requests_chores.py
  itou/archive/management/commands/notify_inactive_jobseekers.py
  itou/archive/management/commands/notify_inactive_professionals.py
  itou/asp/management/commands/sync_communes.py
  itou/companies/management/commands/import_ea_eatt.py
  itou/companies/management/commands/import_geiq.py
  itou/companies/management/commands/import_siae.py
  itou/emails/management/commands/delete_old_emails.py
  itou/employee_record/management/commands/archive_employee_records.py
  itou/employee_record/management/commands/employee_record.py
  itou/employee_record/management/commands/resend_employee_records.py
  itou/employee_record/management/commands/unarchive_employee_records.py
  itou/metabase/management/commands/metabase_data.py
  itou/prescribers/management/commands/sync_ft_organizations.py
  itou/scripts/management/commands/add_admin_for_company_group.py
  itou/scripts/management/commands/create_asp_employee_records.py
  itou/siae_evaluations/management/commands/evaluation_campaign_notify.py
  itou/users/management/commands/sync_group_and_perms.py
  itou/utils/command.py
Labels: no-changelog, bug

#6571 GPS: Nettoyage automatique de l'ID unique utilisé lors des échanges avec FT si les informations du compte candidat changent
  itou/users/models.py
  tests/users/test_models.py
Labels: modifié

#6577 admin : Autoriser les membres du support à supprimer un candidat qui a des infos dans GPS
  itou/users/management/commands/sync_group_and_perms.py
  tests/users/__snapshots__/test_sync_group_and_perms.ambr
Labels: modifié

#6579 Vie privée : ajuster le nombre de professionnels notifiés par jour
  clevercloud/cron.json
  itou/archive/management/commands/notify_inactive_professionals.py
Labels: modifié

#6582 admin : Afficher la PK de la structure
  itou/utils/admin.py
Labels: no-changelog

#6584 admin : Retirer la permission « changer » de PERMS_DELETE
  itou/users/management/commands/sync_group_and_perms.py
  tests/users/__snapshots__/test_sync_group_and_perms.ambr
Labels: no-changelog

#6590 Candidature : Ajout de logs sur la modification des dates du contrat
  itou/www/apply/views/edit_views.py
  tests/www/apply/test_edit.py
Labels: no-changelog

#6591 PASS IAE : logger la création et modification de suspensions
  itou/www/approvals_views/views.py
  tests/www/approvals_views/test_suspend.py
Labels: no-changelog

#6604 Prescripteur : Supprimer le bandeau de prise de rendez-vous d'entretiens utilisateur
  itou/templates/apply/list_prescriptions.html
Labels: supprimé

#6608 Vie privée : rendre les snapshots plus lisibles dans les tests
  tests/archive/__snapshots__/tests_management_command.ambr
  tests/archive/tests_management_command.py
Labels: no-changelog

#6607 Candidature : Reformulation des critères d'éligibilité Mobilité et Langue française [GEN-2624]
  itou/eligibility/data/administrative_criteria.json
  itou/eligibility/data/administrative_criteria_geiq.json
  tests/metabase/management/test_populate_metabase_emplois.py
  tests/www/apply/__snapshots__/test_list_for_siae.ambr
  tests/www/apply/__snapshots__/test_list_prescriptions.ambr
  tests/www/apply/__snapshots__/test_submit.ambr
  tests/www/apply/__snapshots__/test_submit_from_job_seekers_list.ambr
  tests/www/eligibility_views/__snapshots__/test_views.ambr
Labels: 1-recette-jetable, modifié

#6615 Recherche employeur : Correctif temporaire permettant d'afficher le menus déroulants (distance, type de structure…) au-dessus du titre et des onglets
  itou/static/css/itou.css
  itou/templates/includes/btn_dropdown_filter/checkboxes.html
  itou/templates/includes/btn_dropdown_filter/radio.html
  itou/templates/search/includes/siaes_search_content.html
  itou/templates/search/includes/siaes_search_filters_departments.html
  itou/templates/search/prescribers_search_results.html
Labels: modifié

#6631 Nettoyage d'un test
  tests/www/stats/test_views.py
Labels: no-changelog

#6633 Admin : autofocus sur le champ de saisie du code OTP
  itou/www/login/forms.py
Labels: modifié

#6634 Tech : Suppression de `@timeit`
  itou/companies/management/commands/import_geiq.py
  itou/metabase/management/commands/populate_metabase_emplois.py
  itou/utils/python.py
  tests/metabase/management/test_populate_metabase_emplois.py
Labels: no-changelog

#6636 Pilotage : Ne plus créer les tables ne contenant pas les données des emplois
  itou/metabase/db.py
Labels: no-changelog

#6637 Invitations : vérifier que request.current_organization n'est pas None avant de l'utiliser
  itou/www/invitations_views/views.py
  tests/www/invitations_views/test_generic.py
Labels: no-changelog

#6632 Fiche entreprise, fiche de poste : Arrêter de servir les fiches des entreprises désactivées [GEN-2627]
  itou/www/companies_views/views.py
  tests/www/companies_views/__snapshots__/test_card_views.ambr
  tests/www/companies_views/__snapshots__/test_job_description_views.ambr
  tests/www/companies_views/test_card_views.py
Labels: modifié
