Repository gip-inclusion/les-emplois, pull requests merged in 2025-06, with the labels that each got.

#6071 Makefile : ignorer les changements dans `requirements/dev.txt` dans les appels récursifs à `make`
  Makefile
  README.md
Labels: no-changelog

#6238 Contrôle a posteriori : Correction d’une régression dans la validation du formulaire de sélection des critères administratifs [GEN-2457]
  itou/www/siae_evaluations_views/forms.py
  itou/www/siae_evaluations_views/views.py
  tests/www/eligibility_views/test_forms.py
  tests/www/siae_evaluations_views/test_forms.py
  tests/www/siae_evaluations_views/test_siaes_views.py
Labels: modifié

#6215 GPS: Autoriser un organisame de formation à accéder aux fonctionnalités avancées de GPS
  itou/prescribers/admin.py
  itou/prescribers/migrations/0013_prescriberorganization_is_gps_authorized.py
  itou/prescribers/models.py
  itou/www/gps/forms.py
  itou/www/gps/utils.py
  itou/www/gps/views.py
  tests/api/__snapshots__/test_geiq.ambr
  tests/api/employee_record_api/__snapshots__/tests.ambr
  tests/api/job_applications_api/__snapshots__/test_search.ambr
  tests/gps/__snapshots__/test_views.ambr
  tests/gps/test_views.py
  tests/www/apply/__snapshots__/test_list_for_job_seeker.ambr
  tests/www/apply/__snapshots__/test_list_for_siae.ambr
  tests/www/apply/__snapshots__/test_list_prescriptions.ambr
  tests/www/apply/__snapshots__/test_process.ambr
  tests/www/apply/__snapshots__/test_submit.ambr
  tests/www/approvals_views/__snapshots__/test_detail.ambr
  tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
  tests/www/companies_views/__snapshots__/test_job_description_views.ambr
  tests/www/dashboard/__snapshots__/test_edit_job_seeker_info.ambr
  tests/www/dashboard/__snapshots__/test_edit_user_notifications.ambr
  tests/www/employee_record_views/__snapshots__/test_list.ambr
  tests/www/employees_views/__snapshots__/test_detail.ambr
  tests/www/itou_staff_views/__snapshots__/tests.ambr
  tests/www/job_seekers_views/__snapshots__/test_details.ambr
  tests/www/job_seekers_views/__snapshots__/test_list.ambr
Labels: 1-recette-jetable, modifié

#6263 Interface : Suppression de la bannière temporaire pour prévenir que Zendesk était indisponible
  itou/templates/layout/base.html
Labels: supprimé

#6258 Tableau de bord : reformulation dans l'encart du PASS IAE expiré
  itou/templates/approvals/includes/box.html
  tests/www/dashboard/test_dashboard.py
Labels: no-changelog

#6278 Tech: suppression définitive du champs `is_head_office`
  itou/prescribers/migrations/0014_remove_prescriberorganization_is_head_office.py
  itou/prescribers/migrations/0015_drop_is_head_office_for_real.py
Labels: no-changelog

#6275 Nouveautés: correction de la sélection des évènements mis en avant dans la modale pour les candidats [GEN-2503]
  itou/communications/models.py
  itou/templates/layout/_news_modal.html
  itou/utils/context_processors.py
  tests/communications/__snapshots__/test_campaigns.ambr
  tests/communications/test_cache.py
  tests/communications/test_campaigns.py
Labels: modifié

#6245 Fiches Salarié : Ignorer les communes historiques de Mayotte
  itou/asp/migrations/0007_ignore_historic_mayotte_communes.py
Labels: modifié

#6261 Interface: Mise à jour des .list-data sur les pages GEIQ
  itou/templates/geiq_assessments_views/assessment_contracts_details.html
  itou/templates/geiq_assessments_views/assessment_details_for_institution.html
  tests/www/geiq_assessments_views/__snapshots__/test_views_for_institution.ambr
Labels: modifié

#6283 GPS: Suppression de la colonne is_referent en base de donnée
  itou/gps/migrations/0024_alter_followupgroupmembership_is_referent.py
  itou/gps/migrations/0025_remove_is_referent_column.py
Labels: no-changelog

#6288 Metabase: Correction d'une typo
  itou/metabase/tables/job_applications.py
Labels: no-changelog

#6262 Admin : Créer automatiquement les EmailAddress lorsque le support change l’email d’un utilisateur Django
  itou/users/admin.py
  tests/users/test_admin.py
Labels: modifié

#6315 Employeur: ajout d'un bandeau sur la page “Métier et recrutement” pour le questionnaire Maze [GEN-2475]
  itou/templates/companies/job_description_list.html
Labels: modifié

#6317 Vie privée : rendre la tâche de suppression des emails visible de Huey
  itou/archive/management/commands/notify_archive_users.py
  itou/archive/tasks.py
  itou/utils/brevo.py
  tests/archive/__snapshots__/tests_tasks.ambr
  tests/archive/tests_tasks.py
  tests/utils/__snapshots__/test_brevo.ambr
  tests/utils/test_brevo.py
Labels: no-changelog

#6313 Nouveautés: correction de l'affichage de la modale
  itou/static/js/demo_accounts.js
  itou/templates/layout/_news_modal.html
Labels: modifié, bug

#6306 fixtures: Corriger le format des ID France Travail
  itou/siae_evaluations/fixtures.py
Labels: no-changelog

#6308 UX/UI : Ajouter des icônes aux organisations dans le sélecteur de structure
  itou/templates/layout/_header_organization_dropdown_menu.html
Labels: no-changelog

#6311 Tech: Ajout d'un mode de maintenance
  config/settings/base.py
  itou/templates/static/maintenance.html
  itou/www/middleware.py
  tests/www/__snapshots__/test_maintenance.ambr
  tests/www/test_maintenance.py
Labels: modifié

#6324 Tech; Ajout d'un nombre maximum de fichiers à supprimer à la fois
  itou/files/management/commands/purge_files.py
Labels: no-changelog

#6310 Resserrer les select_for_update() pour mieux gérer la concurrence
  itou/approvals/models.py
  itou/eligibility/tasks.py
  itou/emails/tasks.py
  itou/geiq/sync.py
  itou/gps/management/commands/import_advisor_information.py
  itou/gps/management/commands/sync_follow_up_groups_and_members.py
  itou/job_applications/management/commands/reject_job_applications_after_delay.py
  itou/www/apply/views/batch_views.py
  itou/www/apply/views/process_views.py
  itou/www/geiq_assessments_views/views.py
  tests/www/siae_evaluations_views/__snapshots__/test_siaes_views.ambr
Labels: no-changelog, performance

#6331 Tech: suppression d'emails présents dans nos logs
  itou/utils/brevo.py
  itou/utils/logging.py
  tests/utils/__snapshots__/test_brevo.ambr
  tests/utils/test_brevo.py
Labels: no-changelog

#6342 Interface: Harmoniser les breakpoints des colonnes principales
  itou/templates/announcements/news.html
  itou/templates/employee_record/add.html
  itou/templates/siae_evaluations/siae_select_criteria.html
  itou/templates/siae_evaluations/siae_upload_doc.html
  tests/www/announcements/__snapshots__/test_views.ambr
  tests/www/employee_record_views/__snapshots__/test_add.ambr
Labels: no-changelog

#6362 Vie privée: correction de la surveillance d'une tâche planifiée
  itou/archive/management/commands/anonymize_users.py
Labels: no-changelog

#6361 Settings : définir `IMMERSION_FACILE_SITE_URL` par une variable d'environnement
  config/settings/base.py
  itou/utils/constants.py
  itou/utils/immersion_facile.py
  tests/utils/test_immersion_facile.py
  tests/www/employees_views/__snapshots__/test_detail.ambr
Labels: no-changelog

#6336 Tests: Remettre <genexpr> des origins dans les snapshots de requêtes
  tests/siae_evaluations/__snapshots__/test_models.ambr
  tests/utils/test.py
  tests/www/itou_staff_views/__snapshots__/tests.ambr
  tests/www/siae_evaluations_views/__snapshots__/test_institutions_views.ambr
  tests/www/siae_evaluations_views/__snapshots__/test_siaes_views.ambr
Labels: no-changelog

#6369 Tech: mise à jour des settings CSP en dev
  config/settings/dev.py
Labels: no-changelog

#6373 Vie privée : ajout d'un tri sur la date de notification des candidats à anonymiser
  itou/archive/management/commands/anonymize_users.py
Labels: modifié

#6305 Pilotage : Ajouter un encart sur le TB 488 pour les PLIE
  itou/www/stats/views.py
Labels: no-changelog, pilotage

#6380 Admin: ajout de champs manquant pour les candidatures
  itou/job_applications/admin.py
Labels: modifié

#6375 GEIQ: diverses améliorations d'affichage pour le bilan d'exécution
  itou/templates/geiq_assessments_views/assessment_contracts_details.html
Labels: modifié, bug

#6193 Zendesk: Suppression des pièces jointes de tickets clos [GEN-235]
  clevercloud/cron.json
  itou/scripts/management/commands/redact_zendesk_attachments.py
Labels: no-changelog

#6387 Tableau de bord: correction d'une typo [GEN-2554]
  itou/templates/dashboard/edit_user_info.html
Labels: no-changelog

#6379 Fiches Salarié : Améliorations pour l'utilitaire `employee_record` [GEN-2487]
  itou/employee_record/management/commands/employee_record.py
Labels: no-changelog

#6400 Renommer `switch{User,Structure}Dropdown`
  itou/templates/layout/_structure_switcher_nav.html
  itou/templates/layout/_structure_switcher_offcanvas.html
Labels: no-changelog

#6323 Tech: ajoute la possibilité de configurer un `statement_timeout`
  config/settings/base.py
Labels: tech

#6410 Admin: ajoute l'accès aux données analytiques [GEN-2388]
  itou/users/management/commands/sync_group_and_perms.py
  tests/users/__snapshots__/test_sync_group_and_perms.ambr
Labels: modifié

#6407 Fiches salarié : Retrait d’une vérification de cohérence de l’adresse
  itou/www/employee_record_views/forms.py
  tests/www/employee_record_views/test_create.py
Labels: modifié

#6414 Tech: Corrections de typos diverses dans des tests
  tests/www/apply/__snapshots__/test_list_for_siae.ambr
  tests/www/apply/test_batch_views.py
  tests/www/apply/test_list_for_siae.py
Labels: no-changelog

#6413 admin : Permettre les recherches de NIR contenant un A ou un B
  itou/approvals/admin.py
  itou/users/admin.py
  itou/users/utils.py
  tests/approvals/test_admin.py
Labels: modifié

#6409 Stabilité : correctif d'un test incomplet
  tests/www/apply/__snapshots__/test_list_for_siae.ambr
  tests/www/apply/test_list_for_siae.py
Labels: no-changelog

#6419 Fiches Salarié : Ne plus tronquer l'identifiant France Travail lors de l'envoi à l'Extranet IAE
  itou/employee_record/serializers.py
  tests/employee_record/__snapshots__/test_serializers.ambr
  tests/employee_record/test_serializers.py
Labels: modifié

#6327 Limiter le nombre d’actions par minute pour les utilisateurs authentifiés
  config/settings/base.py
  itou/templates/429.html
  itou/utils/throttling.py
  itou/www/middleware.py
  tests/www/test_throttling.py
Labels: tech

#6424 Vie privée : empêcher `job_seekers_views:details` d'afficher les informations des utilisateurs qui ne sont pas des candidats
  itou/www/job_seekers_views/views.py
  tests/www/job_seekers_views/__snapshots__/test_details.ambr
  tests/www/job_seekers_views/test_details.py
Labels: no-changelog

#6425 Tech: Nettoyage de code inutilisé depuis 2022
  itou/archive/admin.py
  itou/archive/management/commands/anonymize_users.py
  itou/archive/migrations/0007_remove_anonymizedapplication_hiring_without_approval.py
  itou/archive/models.py
  itou/fixtures/django/24_job_applications.json
  itou/job_applications/admin.py
  itou/job_applications/migrations/0019_remove_jobapplication_hiring_without_approval_faked.py
  itou/job_applications/models.py
  itou/templates/apply/process_base.html
  itou/www/apply/forms.py
  itou/www/apply/views/common.py
  itou/www/apply/views/process_views.py
  tests/api/__snapshots__/test_geiq.ambr
  tests/api/employee_record_api/__snapshots__/tests.ambr
  tests/api/job_applications_api/__snapshots__/test_search.ambr
  tests/archive/__snapshots__/tests_management_command.ambr
  tests/archive/tests_management_command.py
  tests/employee_record/__snapshots__/test_transfer_employee_records.ambr
  tests/employee_record/__snapshots__/test_transfer_employee_records_updates.ambr
  tests/employee_record/test_models.py
  tests/job_applications/__snapshots__/test_transfer.ambr
  tests/job_applications/factories.py
  tests/job_applications/tests.py
  tests/siae_evaluations/__snapshots__/test_models.ambr
  tests/users/__snapshots__/test_admin_views.ambr
  tests/www/apply/__snapshots__/test_list_for_job_seeker.ambr
  tests/www/apply/__snapshots__/test_list_for_siae.ambr
  tests/www/apply/__snapshots__/test_list_prescriptions.ambr
  tests/www/apply/__snapshots__/test_process.ambr
  tests/www/approvals_views/__snapshots__/test_detail.ambr
  tests/www/approvals_views/__snapshots__/test_suspend.ambr
  tests/www/employee_record_views/__snapshots__/test_add.ambr
  tests/www/employee_record_views/__snapshots__/test_list.ambr
  tests/www/employees_views/__snapshots__/test_detail.ambr
  tests/www/itou_staff_views/__snapshots__/tests.ambr
  tests/www/job_seekers_views/__snapshots__/test_details.ambr
  tests/www/search/__snapshots__/tests.ambr
  tests/www/siae_evaluations_views/__snapshots__/test_institutions_views.ambr
  tests/www/siae_evaluations_views/__snapshots__/test_siaes_views.ambr
Labels: no-changelog

#6426 Tests: détection des oublis de `csrf_token`
  tests/conftest.py
  tests/www/employee_record_views/__snapshots__/test_template.ambr
  tests/www/employee_record_views/test_template.py
Labels: no-changelog

#6377 Vie privée : ajout de champs dans l'admin
  itou/archive/admin.py
Labels: modifié

#6436 Utiliser le mode strict de JavaScript
  itou/static/js/address_autocomplete_fields.js
  itou/static/js/admin.js
  itou/static/js/demo_accounts.js
  itou/static/js/easymde_config.js
  itou/static/js/formset_add_remove_row.js
  itou/static/js/gps.js
  itou/static/js/hijack_hide.js
  itou/static/js/matomo.js
  itou/static/js/modal_control.js
  itou/static/js/notifications_center.js
  itou/static/js/nps_popup.js
  itou/static/js/prevent_multiple_submit.js
  itou/static/js/utils.js
Labels: no-changelog

#6438 Retirer un {{ block.super }} doublon dans la confirmation d’embauche
  itou/templates/apply/submit/hire_confirmation.html
Labels: no-changelog

#6437 Fusionner prevent_multiple_submit dans utils.js
  itou/static/js/prevent_multiple_submit.js
  itou/static/js/utils.js
  itou/templates/layout/base.html
Labels: no-changelog

#6442 Tech: Nettoyage des logger dans les managments commands
  itou/approvals/management/commands/bulk_update_from_file.py
  itou/archive/management/commands/anonymize_jobseekers.py
  itou/archive/management/commands/anonymize_professionals.py
  itou/archive/management/commands/notify_inactive_jobseekers.py
  itou/cities/management/commands/resolve_insee_cities.py
  itou/companies/management/commands/_import_siae/siae.py
  itou/companies/management/commands/update_companies_coords.py
  itou/scripts/management/commands/geolocate_jobseeker_addresses.py
  itou/status/management/commands/run_status_probes.py
  itou/users/management/commands/pe_certify_users.py
  itou/users/management/commands/send_users_to_brevo.py
  itou/users/management/commands/update_job_seeker_coords.py
Labels: no-changelog
