Repository gip-inclusion/les-emplois, pull requests merged in 2025-09, with the labels that each got.

#6759 Éligibilité : Ne pas certifier les critères au sein de la requête web
  config/settings/base.py
  itou/eligibility/models/common.py
  tests/eligibility/test_iae.py
  tests/utils/apis/test_api_particulier.py
Labels: no-changelog

#6734 Admin : Permettre aux membres du groupe itou-admin-readonly de télécharger les exports CTA [GEN-2666]
  itou/users/management/commands/sync_group_and_perms.py
  tests/users/__snapshots__/test_sync_group_and_perms.ambr
  tests/users/test_sync_group_and_perms.py
Labels: modifié

#6766 Renommer EligibilityDiagnosis.certify_criteria en schedule_certification
  itou/eligibility/models/common.py
  itou/eligibility/models/geiq.py
  itou/eligibility/models/iae.py
  itou/www/apply/views/common.py
Labels: no-changelog

#6767 archive: Tester l’anonymisation d’un prescripteur en deux étapes
  tests/archive/tests_management_command.py
Labels: no-changelog

#6783 Employeur : Ne pas recommander de contacter un admin inactif à l’inscription
  itou/www/signup/views.py
  tests/www/signup/__snapshots__/test_siae.ambr
  tests/www/signup/test_siae.py
Labels: no-changelog

#6775 Vie privée : suppression de la fiche salariée lors de l'archivage du candidat
  itou/archive/management/commands/anonymize_jobseekers.py
  tests/archive/tests_management_command.py
Labels: modifié

#6789 Tech: Mise à jour de Django en 5.2.6
  requirements/base.txt
  requirements/dev.txt
  requirements/test.txt
Labels: no-changelog

#6800 Candidature: Empêcher la déclaration d'embauche en double en cas de double-clic
  itou/templates/apply/includes/accept_section.html
Labels: modifié

#6812 Prescripteur: Suppression d'un bandeau d’alerte pour une enquête Maze
  itou/templates/dashboard/dashboard.html
Labels: supprimé

#6810 Tech: améliorations barre de navigation
  itou/utils/templatetags/nav.py
  tests/www/geiq_assessments_views/__snapshots__/test_views_for_geiq.ambr
Labels: no-changelog

#6803 Candidatures: Permettre le transfert d'une candidature vers une autre structure depuis les actions par lot
  itou/templates/apply/includes/siae_batch_actions.html
  itou/templates/apply/includes/siae_batch_actions_modals.html
  itou/www/apply/views/list_views.py
  tests/www/apply/__snapshots__/test_list_for_siae.ambr
  tests/www/apply/test_list_for_siae.py
Labels: 1-recette-jetable, modifié

#6863 API Pole Emploi : Simplification
  itou/utils/apis/pole_emploi.py
  tests/utils/apis/test_pole_emploi_api.py
Labels: no-changelog

#6864 Renommer API_ESD["AUTH_BASE_URL{,_PARTENAIRE}"]
  config/settings/base.py
  itou/utils/apis/esd.py
  itou/utils/apis/pole_emploi.py
  tests/approvals/test_notify_pole_emploi.py
  tests/companies/test_sync_ft_offers.py
  tests/external_data/tests.py
  tests/job_applications/tests.py
  tests/jobs/management/test_sync_romes_and_appellations.py
  tests/openid_connect/pe_connect/tests.py
  tests/users/test_management_commands.py
Labels: no-changelog

#6862 Tech: ajout de nouveau test de cohérence pour les dates de prolongation
  itou/approvals/admin.py
  tests/approvals/test_admin.py
Labels: no-changelog

#6865 GPS: Correction du header du fichier importé
  itou/gps/management/commands/import_advisor_information.py
  tests/gps/test_management_commands.py
Labels: no-changelog

#6873 Admin: passage de l'admin des fichiers en lecture seule
  itou/files/admin.py
Labels: modifié

#6867 apis.pole_emploi: Réusinage et organisation des mocks
  itou/utils/apis/pole_emploi.py
  itou/utils/mocks/pole_emploi.py
  tests/utils/apis/test_pole_emploi_api.py
Labels: no-changelog

#6893 Tech : Réparer la création des applications de recette
  .github/workflows/review-app-creation.yml
Labels: no-changelog

#6902 [Metabase] Changement de l'id des TBs metabase etp (SIAE & DREETS/DDETS)
  itou/utils/apis/metabase.py
Labels: no-changelog, pilotage

#6914 change id to get new facilitation embauche dashboard
  itou/utils/apis/metabase.py
Labels: no-changelog, pilotage
